### ISSUE TITLE
Git Extensions v3.5.4.12724 Portable upgrade from v3.1.1 first startup error dialog

### ISSUE THREAD

**Issue by klorinczi** [gitextensions/gitextensions#10024]
### Environment

- GitExtensions version: v3.5.4.12724 
- GIT version: 
- OS version: Windows 7 Pro
- .NET version: 

![2022-06-02 12_52_01-Git Extensions startup error](https://user-images.githubusercontent.com/11757244/171614697-7590eb27-4d6b-433e-bc7b-efd5105a138f.jpg)

### Issue description

Copied Git Extensions v3.5.4.12724 Portable to Git Extensions v3.1.1.6049 directory to upgrade, but I got this error dialog after starting it.

### Steps to reproduce

- copy Git Extensions v3.5.4.12724 Portable files to Git Extensions v3.1.1.6049 directory to upgrade it
- get error dialog after starting it

### Did this work in previous version of GitExtensions?

v3.1.1

**Comment by RussKie** [comment]
Sorry, this is not a supported use case. You can't just copy files from one version over another and expect it to work.

**Comment by pmiossec** [comment]
> Well, portable apps are used to work just by overwriting the old version...

If you mix old binaries with new binaries, you could have this case of unexpected behavior sometimes due to dynamic dll loading...

You are welcome to contribute to the project if you want to ensure that all the version released are compatible with all the previous version.
That is definitely something that we can ensure. Don't forget that GitExtensions is an opensource project and that contributors are doing it on their free time.

The update workflow of a portable app should better be:
1. Unzip new version.
2. Copy only the settings from the previous version:
   *  `GitExtensions.settings` file
   * `Recent` folder
 3. If it's working, great (and that will be nearly 100% of the times)! If not, do it again without coping the settings.
