### ISSUE TITLE
Context menu do not work on Windows 10 Library

### ISSUE THREAD

**Issue by Netislander** [gitextensions/gitextensions#10176]
### Environment

- GitExtensions version 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- GIT version: 2.36.1.windows.1
- OS version: Microsoft Windows NT 10.0.19044.0
- .NET version: .NET Framework 4.8.4515.0

### Issue description

When opening a folder through Windows Explorer Library, the context menus do not appear.  Any other way it works fine.  Reinstalling does not work.  The first pic shows the issue when opening through a library and the second shows it working when accessing the folder directly.  Notice the address bar difference between the two.
![image](https://user-images.githubusercontent.com/38320206/187915224-273c3927-b350-4905-902a-53aba5f11773.png)
![image](https://user-images.githubusercontent.com/38320206/187915414-e54fc452-c6cb-4d48-84b5-8d6cdbf4ec63.png)

### Steps to reproduce

1. Open windows explorer and right click on Libraries.
2. Select New > Library
![image](https://user-images.githubusercontent.com/38320206/187916328-b43ebe60-e9d8-4089-9ba2-11c2b16d120b.png)
4. Name the library
5. Right-click library and select properties.
6. Click the add button and Select a development folder.
![image](https://user-images.githubusercontent.com/38320206/187916283-99d8829f-0c22-48dd-a089-392d37077137.png)
8. Open that folder through the Library and right click to bring up the context menu

### Did this work in previous version of GitExtensions?

Do not know.

**Comment by pmiossec** [comment]
I have made a little test because I didn't know this "Libraries" feature of Win10.
And, for me, it's not that the Context menu is not working with Libraries because you have it when you click on any folder **but that when you right click on nothing i.e the empty space, GitExtensions menu items are not displayed in the context menu**. 

Because you don't have VSCode and VS also...

So there is clearly a different behavior from Win 10 in a Library than in a normal folder. So the problem is more on Win 10 side.

After that, why do you have the Git Bash/UI ones is a good question and I imagine that it's because that are not registered on the same type of objects.

I don't really think that GitExtensions has something to fix here...

Workaround: right click on the folder in the treeview and you will have it. Or go one level up and click on the folder.
