### ISSUE TITLE
Git Extensions sets core.editor to its own program without asking the user

### ISSUE THREAD

**Issue by kostix** [gitextensions/gitextensions#1018]
I have installed Git Extensions 2.32 onto a Windows XP SP3 32-bit machine and found out that simply running `git commit` (from cmd.exe) in a repository suddenly spawns some unexpected test editor.

As it turned out, this is a text editor provided by Git Extensions:

C:>git config --get-all core.editor
"C:/Program Files/GitExtensions/GitExtensions.exe" fileeditor

Note that I do not have core.editor set at all (on either condiguration level) and instead relying on the EDITOR environment variable being set to "gvim.exe" (as thisway to set the preferred editor is used by a number of other tools, like command-line subversion client).

I do not remember Git Extensions asked me about this commit editor setting during the setup phase nor did I change anything relevant in its settings dialog (I only messed with the language and PuTTY location).

So it looks like either Git Extensions unconditionally hijacks this setting unconditionally (I doubt this) or relies or somewhat naive heuristics ("the user does not have core.editor set so we're free to set it to whatever we wish").
I think the proper way to go would be to ask the user on install or, if heuristics are used, to at least look at the environment and do nothing if either VISUAL or EDITOR is set.

**Comment by lcnittl** [comment]
Stumbling across this very old issue...

Is it intentional that `core.editor` is set in `global` config if it is already supplied in `system`?
After removing that setting from the `global` config, whenever settings are applied in the GUI, it is re-added.

Is there a way to make it aware of `system` settings?

**Comment by RussKie** [comment]
@lcnittl please open a new issue and provide as much information as possible. Thanks

**Comment by vbjay** [comment]
Just set global to what you desire.  Think about it. That is really a per
user config. You can manage the setting in gitextensions settings. We
really only have per user global, per repo distributed, per repo local git
config. Yes. System is available from running git config. Because it is
developed against windows and system would have possible uac needs and or
prevention from multiple user instances writing settings in all users app
data area.
