### ISSUE TITLE
Right-click dropdown menu remains open forever; neither click outside nor Esc key close it

### ISSUE THREAD

**Issue by php4fan** [gitextensions/gitextensions#10236]
### Environment

- GitExtensions version: 2.51.05
- GIT version: irrelevant 
- OS version: Manjaro Linux
- .NET version: no idea

### Issue description

see below

### Steps to reproduce

- Open a repository
- Right click on a commit
- Try to close the context menu that just opened

EXPECTED:
This is very basic UI design; when you open a right-click menu, clicking anywhere outside it should close it. Hitting the Esc key should close it. Not every time you right-click on something to open a context menu, will you end up clicking on one of the items it contains.

OBSERVED:
it is very difficult to close the menu. Clicking outside won't close it. The esc key won't close it. It will stick around even as you click on other commits. Absolutely ridiculous.

**Comment by RussKie** [comment]
This would _likely_ be some kind of issue with the version of the Mono Windows Forms you may have installed. When I ran Git Extensions on Linux (which was years ago) it was something like 5.12 or 5.14, and I don't recall having any kind of issues like the one you're describing. Since no one in the core team is running on Linux, there's literally no support we can provide. You're welcome to try to debug the issue, or to raise the issue in https://github.com/mono/mono/labels/area-BCL%3A%20System.Windows.Forms.
