### ISSUE TITLE
Enable Interactive Rebase and Autosquash when selecting rebase with advanced options

### ISSUE THREAD

**Issue by dlidstrom** [gitextensions/gitextensions#10230]
### Feature description

I find that the only reason I do advanced rebase is because I want to do interactive rebase with autosquash. Would it make sense to enable these options by default?

### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.33.0.windows.2
- Microsoft Windows NT 10.0.19044.0
- .NET Framework 4.8.4515.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
The autosquash checkbox state follow the git setting "rebase.autosquash"

In v4.0, this setting will be exposed in the settings (See #10123 ).
Until that, you have to set it with command line:

` git config --global rebase.autosquash true`

**Comment by dlidstrom** [comment]
Hi Philippe, that is good. However the ui is a bit inconsistent. While the checkbox autosquash is now enabled, the Interactive Rebase checkbox is not enabled. Perhaps it should be to make the ui consistent.

**Comment by pmiossec** [comment]
>However the ui is a bit inconsistent.

Let me disagree ;)

> While the checkbox autosquash is now enabled, the Interactive Rebase checkbox is not enabled. Perhaps it should be to make the ui consistent.

When we open the form, we can't know that you want to do an "Interactive rebase" or not.
So we can't force the user to do an "Interactive rebase".

And the "autosquash" checkbox is disabled to tell you that this settings make no sense if you don't select "Interactive rebase".
We could have hide the checkbox because you don't need this setting but it makes the UX of the UI strange because you will have either a hole or the following checkbox will move.

Maybe you can propose something better?

**Comment by dlidstrom** [comment]
It can't be known with 100% certainty, but given that I've configured autosquash by default it is a good indicator that I would like to perform an interactive rebase when I choose to do an advanced rebase. But of course this is just my idea of usability and it may not apply to anyone else. Besides, with autosquash enabled by default I can achieve what I want by going directly to interactive rebase as that now does exactly what I want.

**Comment by pmiossec** [comment]
> It can't be known with 100% certainty, but given that I've configured autosquash by default it is a good indicator that I would like to perform an interactive rebase when I choose to do an advanced rebase. But of course this is just my idea of usability and it may not apply to anyone else.

Autosquash is a sub option **WHEN** you do an interactive rebase. It doesn't mean that you always want to do an interactive rebase. It's not a setting that must drive an **action** you want to do...

For example, when I use this screen, it's nearly exclusively to do a "rebase onto" (the 2nd line of options), never an interactive rebase and do you know why? Because of 👇 

>Besides, with autosquash enabled by default I can achieve what I want by going directly to interactive rebase as that now does exactly what I want.

So everything good? 😄

**Comment by dlidstrom** [comment]
Yes I am happy :-) Thanks for the discussion! Closing now since everything works as by-design.
