### ISSUE TITLE
Color theme does not apply to the entirety of the window

### ISSUE THREAD

**Issue by prostolyubo** [gitextensions/gitextensions#10312]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.20.0.windows.1 (minimum: 2.25.0, please update!)
- Microsoft Windows NT 10.0.19042.0
- .NET 6.0.10
- DPI 144dpi (150% scaling)

### Issue description

Hi!
After applying any of the shipped color themes, I see it applied only in some elements.
![image](https://user-images.githubusercontent.com/45892416/199251112-ac345c3d-a018-437f-be3b-1844a8f4b679.png)

### Steps to reproduce

1. Install Git Extensions
2. Select a dark theme
3. Restart Git Extensions
4. Open Git Extensions browser/settings/etc
5. Notice dark theme is not applied to most of things

**Comment by pmiossec** [comment]
For others ending up here: as dark theme are not available in v4 of the application, you should switch back to a bright or default theme in the settings:

![image](https://user-images.githubusercontent.com/460196/200822884-f1d4b6bd-3213-4e14-8201-88fd1174583e.png)

**Comment by dmex** [comment]
@gerhardol 

> .NET 6 does not support remoting and multiple AppDomain required for those hooks

The main problem is these hooks are located in `GitExtensions.dll` instead of the executable and are trying to hook functions at runtime while they're in-use.

Recent versions of .NET (5/6/7 etc...) are not using the Windows loader to initialize the CLR and instead use a generic apphost executable to load the runtime. If you dump the symbols for `GitExtensions.exe` you'll find it doesn't contain any of your project code like previous versions and just contains Microsoft code from `\corehost\apphost\standalone\apphost.exe`

When you compile .NET projects your `project.exe` is now just the `apphost.exe` copied from the `C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Host.win-x64\6.0.14\runtimes\win-x64\native\` directory and renamed `GitExtensions.exe`

So fixing theme support can be done by moving the hooks into the host executable. Custom runtime hosts are documented here:
https://learn.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting

Custom hosts are simple to implement and don't require much effort. There's an official sample project here:
https://github.com/dotnet/samples/tree/main/core/hosting/src

Everything is located in this file:
https://github.com/dotnet/samples/blob/main/core/hosting/src/NativeHost/nativehost.cpp

32bit headers:
`C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Host.win-x86\6.0.14\runtimes\win-x86\native`

64bit headers:
`C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Host.win-x64\6.0.14\runtimes\win-x64\native\` 

The above directory contains the headers and libs needed to compile your own host:
![image](https://user-images.githubusercontent.com/1306177/225097742-48e63c7a-4be6-4fa5-9f09-563fffbe3a1c.png)

Step 1)  Copy the sample code from the above links and the headers/libs from the above directory.
Step 2)  Use detours to hook the functions needed for theming.
Step 3) Call load_hostfxr() from the documentation ([initialize-and-start-the-net-runtime](https://learn.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting#step-2---initialize-and-start-the-net-runtime))

The headers/libraries from step 1 are used here:
https://github.com/dotnet/samples/blob/b120cce50e1a38b362e543a44e0f9d42baec8fe6/core/hosting/src/NativeHost/nativehost.cpp#L74-L80

Step 4) The `config_path` for `get_dotnet_load_assembly` is the `GitExtensions.runtimeconfig.json` file in the same directory as `GitExtensions.exe`:

![image](https://user-images.githubusercontent.com/1306177/225099852-ddd2d04c-a514-47d3-a6bf-702d5ddfe959.png)

Pass the file name here:
https://github.com/dotnet/samples/blob/main/core/hosting/src/NativeHost/nativehost.cpp#L83-L89

Step 5) The assembly filename you need to pass is `GitExtensions.dll` and the method can either be `GitExtensions.Program.Main` or some other method.

Here's a minimal example of what the custom host needs for theme support:

```c
static HRESULT (WINAPI* DefaultDrawThemeBackground)(
    _In_ HTHEME Theme,
    _In_ HDC Hdc,
    _In_ INT PartId,
    _In_ INT StateId,
    _In_ LPCRECT Rect,
    _In_ LPCRECT ClipRect
    ) = NULL;

static HRESULT (WINAPI* ManagedDrawThemeBackground)(
    _In_ HTHEME Theme,
    _In_ HDC Hdc,
    _In_ INT PartId,
    _In_ INT StateId,
    _In_ LPCRECT Rect,
    _In_ LPCRECT ClipRect
    ) = NULL;

__declspec(dllexport) VOID GitExtensionsAddHooks(PVOID Function1, PVOID Function2) // Called from C#
{
    InterlockedExchangePointer(&ManagedDrawThemeBackground, Function1);
    InterlockedExchangePointer(&ManagedFunction2, Function2);
}

HRESULT HookDrawThemeBackground(
    _In_ HTHEME Theme,
    _In_ HDC Hdc,
    _In_ INT PartId,
    _In_ INT StateId,
    _In_ LPCRECT Rect,
    _In_ LPCRECT ClipRect
    )
{
    if (GitExtensionsDrawThemeBackground) // managed callback
    {
        return GitExtensionsDrawThemeBackground(Theme, Hdc, PartId, StateId, Rect, ClipRect)
    }

    return DefaultDrawThemeBackground(Theme, Hdc, PartId, StateId, Rect, ClipRect); // native default callback
}

VOID InitializeThemeHooks(VOID)
{
   HMODULE uxthemebaseaddress = LoadLibraryW(L"UxTheme.dll")

   DefaultDrawThemeBackground = GetProcAddress(uxthemebaseaddress, "DrawThemeBackground");

   DetourUpdateThread(GetCurrentThread());
   DetourTransactionBegin();
   DetourAttach((PVOID)&DefaultDrawThemeBackground, (PVOID)HookDrawThemeBackground)
   DetourTransactionCommit()
}

VOID InitializeRuntime(VOID)
{
   typedef void (CORECLR_DELEGATE_CALLTYPE *main_entry_point_fn)();

   load_hostfxr();

   get_dotnet_load_assembly("gitextensions.DLL", "GitExtensions.runtimeconfig.json");

   main_entry_point_fn callmain = load_assembly_and_get_function_pointer("GitExtensions.Program.Main");
   callmain()
}

int __cdecl wmain(int argc, wchar_t *argv[])
{
   InitializeThemeHooks();
   InitializeRuntime();
}
```

Then from C# something like:

```cs
[LibraryImport("GitExtensions.exe")]
public static partial void GitExtensionsAddHooks(IntPtr Function1, IntPtr Function2); // We exported this using __declspec(dllexport)

private static uint DrawThemeBackgroundManaged(...)
{
    return 0; // hresult
}

private static void SetupThemeCallback()
{
  GitExtensionsAddHooks(Marshal.GetFunctionPointerForDelegate(DrawThemeBackgroundManaged), ...);
}
```

If you setup the hooks before loading the runtime then there's no issues. You can export functions/types from the host executable using `__declspec(dllexport)` then import/call them from C# like any other native function or the host can call into manged methods using load_assembly_and_get_function_pointer.

For example:

```c
VOID InitializeRuntime(VOID)
{
   typedef void (CORECLR_DELEGATE_CALLTYPE *cache_theme_callback_fn)(void* Function);

   cache_theme_callback_fn cache_theme_function = load_assembly_and_get_function_pointer("GitExtensions.Program.CacheThemeCallback");
   cache_theme_function(DefaultDrawThemeBackground); // Call the managed method to cache the pointer

   main_entry_point_fn callmain = load_assembly_and_get_function_pointer("GitExtensions.Program.Main");
   callmain(); // Call the managed entrypoint
}


```

```cs
static Action ThemeHookCallback = null;

private static void CacheThemeCallback(IntPtr Function)
{
 ThemeHookCallback = Marshal.GetDelegateForFunctionPointer(Function);
}
```

A custom host is the only way you'll be able to use fix the theme hooks so hope this helps. I would also rename `GitExtensions.exe` to something like `GitExtensions_default.exe` or something and if there's any errors while loading the custom host then just call `CreateProcess("GitExtensions_default.exe")` so users can still use the application and update it.

**Comment by RussKie** [comment]
Thank you @dmex, looks like you know quite a bit (and significantly more than anyone on the core team) about this. Do you think you could create some POC for us?

**Comment by NickPolyder** [comment]
Hello, I know that this might be a longshot and please guide me to the correct place if this is not the place to put the idea.

But I have seen a library called [Harmony](https://github.com/pardeike/Harmony) that is used to mod games which sounds kind of what the EasyHook is doing.

Kind Regards.

**Comment by TMDevel89** [comment]
@dmex or anyone else
Can you explain the procedure to me in more detail?

> @gerhardol
> 
> > .NET 6 does not support remoting and multiple AppDomain required for those hooks
> 
> The main problem is these hooks are located in `GitExtensions.dll` instead of the executable and are trying to hook functions at runtime while they're in-use.
> 
> Recent versions of .NET (5/6/7 etc...) are not using the Windows loader to initialize the CLR and instead use a generic apphost executable to load the runtime. If you dump the symbols for `GitExtensions.exe` you'll find it doesn't contain any of your project code like previous versions and just contains Microsoft code from `\corehost\apphost\standalone\apphost.exe`
> 
> When you compile .NET projects your `project.exe` is now just the `apphost.exe` copied from the `C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Host.win-x64\6.0.14\runtimes\win-x64\native\` directory and renamed `GitExtensions.exe`
> 
> So fixing theme support can be done by moving the hooks into the host executable. Custom runtime hosts are documented here: https://learn.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting
> 
> Custom hosts are simple to implement and don't require much effort. There's an official sample project here: https://github.com/dotnet/samples/tree/main/core/hosting/src
> 
> Everything is located in this file: https://github.com/dotnet/samples/blob/main/core/hosting/src/NativeHost/nativehost.cpp
> 
> 32bit headers: `C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Host.win-x86\6.0.14\runtimes\win-x86\native`
> 
> 64bit headers: `C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Host.win-x64\6.0.14\runtimes\win-x64\native\`
> 
> The above directory contains the headers and libs needed to compile your own host: ![image](https://user-images.githubusercontent.com/1306177/225097742-48e63c7a-4be6-4fa5-9f09-563fffbe3a1c.png)
> 
> Step 1) Copy the sample code from the above links and the headers/libs from the above directory. Step 2) Use detours to hook the functions needed for theming. Step 3) Call load_hostfxr() from the documentation ([initialize-and-start-the-net-runtime](https://learn.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting#step-2---initialize-and-start-the-net-runtime))
> 
> The headers/libraries from step 1 are used here: https://github.com/dotnet/samples/blob/b120cce50e1a38b362e543a44e0f9d42baec8fe6/core/hosting/src/NativeHost/nativehost.cpp#L74-L80
> 
> Step 4) The `config_path` for `get_dotnet_load_assembly` is the `GitExtensions.runtimeconfig.json` file in the same directory as `GitExtensions.exe`:
> 
> ![image](https://user-images.githubusercontent.com/1306177/225099852-ddd2d04c-a514-47d3-a6bf-702d5ddfe959.png)
> 
> Pass the file name here: https://github.com/dotnet/samples/blob/main/core/hosting/src/NativeHost/nativehost.cpp#L83-L89
> 
> Step 5) The assembly filename you need to pass is `GitExtensions.dll` and the method can either be `GitExtensions.Program.Main` or some other method.
> 
> Here's a minimal example of what the custom host needs for theme support:
> 
> ```c
> static HRESULT (WINAPI* DefaultDrawThemeBackground)(
>     _In_ HTHEME Theme,
>     _In_ HDC Hdc,
>     _In_ INT PartId,
>     _In_ INT StateId,
>     _In_ LPCRECT Rect,
>     _In_ LPCRECT ClipRect
>     ) = NULL;
> 
> static HRESULT (WINAPI* ManagedDrawThemeBackground)(
>     _In_ HTHEME Theme,
>     _In_ HDC Hdc,
>     _In_ INT PartId,
>     _In_ INT StateId,
>     _In_ LPCRECT Rect,
>     _In_ LPCRECT ClipRect
>     ) = NULL;
> 
> __declspec(dllexport) VOID GitExtensionsAddHooks(PVOID Function1, PVOID Function2) // Called from C#
> {
>     InterlockedExchangePointer(&ManagedDrawThemeBackground, Function1);
>     InterlockedExchangePointer(&ManagedFunction2, Function2);
> }
> 
> HRESULT HookDrawThemeBackground(
>     _In_ HTHEME Theme,
>     _In_ HDC Hdc,
>     _In_ INT PartId,
>     _In_ INT StateId,
>     _In_ LPCRECT Rect,
>     _In_ LPCRECT ClipRect
>     )
> {
>     if (GitExtensionsDrawThemeBackground) // managed callback
>     {
>         return GitExtensionsDrawThemeBackground(Theme, Hdc, PartId, StateId, Rect, ClipRect)
>     }
> 
>     return DefaultDrawThemeBackground(Theme, Hdc, PartId, StateId, Rect, ClipRect); // native default callback
> }
> 
> VOID InitializeThemeHooks(VOID)
> {
>    HMODULE uxthemebaseaddress = LoadLibraryW(L"UxTheme.dll")
> 
>    DefaultDrawThemeBackground = GetProcAddress(uxthemebaseaddress, "DrawThemeBackground");
> 
>    DetourUpdateThread(GetCurrentThread());
>    DetourTransactionBegin();
>    DetourAttach((PVOID)&DefaultDrawThemeBackground, (PVOID)HookDrawThemeBackground)
>    DetourTransactionCommit()
> }
> 
> VOID InitializeRuntime(VOID)
> {
>    typedef void (CORECLR_DELEGATE_CALLTYPE *main_entry_point_fn)();
> 
>    load_hostfxr();
> 
>    get_dotnet_load_assembly("gitextensions.DLL", "GitExtensions.runtimeconfig.json");
> 
>    main_entry_point_fn callmain = load_assembly_and_get_function_pointer("GitExtensions.Program.Main");
>    callmain()
> }
> 
> int __cdecl wmain(int argc, wchar_t *argv[])
> {
>    InitializeThemeHooks();
>    InitializeRuntime();
> }
> ```
> 
> Then from C# something like:
> 
> ```cs
> [LibraryImport("GitExtensions.exe")]
> public static partial void GitExtensionsAddHooks(IntPtr Function1, IntPtr Function2); // We exported this using __declspec(dllexport)
> 
> private static uint DrawThemeBackgroundManaged(...)
> {
>     return 0; // hresult
> }
> 
> private static void SetupThemeCallback()
> {
>   GitExtensionsAddHooks(Marshal.GetFunctionPointerForDelegate(DrawThemeBackgroundManaged), ...);
> }
> ```
> 
> If you setup the hooks before loading the runtime then there's no issues. You can export functions/types from the host executable using `__declspec(dllexport)` then import/call them from C# like any other native function or the host can call into manged methods using load_assembly_and_get_function_pointer.
> 
> For example:
> 
> ```c
> VOID InitializeRuntime(VOID)
> {
>    typedef void (CORECLR_DELEGATE_CALLTYPE *cache_theme_callback_fn)(void* Function);
> 
>    cache_theme_callback_fn cache_theme_function = load_assembly_and_get_function_pointer("GitExtensions.Program.CacheThemeCallback");
>    cache_theme_function(DefaultDrawThemeBackground); // Call the managed method to cache the pointer
> 
>    main_entry_point_fn callmain = load_assembly_and_get_function_pointer("GitExtensions.Program.Main");
>    callmain(); // Call the managed entrypoint
> }
> ```
> 
> ```cs
> static Action ThemeHookCallback = null;
> 
> private static void CacheThemeCallback(IntPtr Function)
> {
>  ThemeHookCallback = Marshal.GetDelegateForFunctionPointer(Function);
> }
> ```
> 
> A custom host is the only way you'll be able to use fix the theme hooks so hope this helps. I would also rename `GitExtensions.exe` to something like `GitExtensions_default.exe` or something and if there's any errors while loading the custom host then just call `CreateProcess("GitExtensions_default.exe")` so users can still use the application and update it.

**Comment by gmcelhanon** [comment]
I did some poking around (on @dmex's profile) and found some code in a project that he works on that looks like it's handling the theming and is clearly the basis for his comments above. I don't really understand it, but it is a potentially useful reference example and so I thought I'd at least provide the link.

https://github.com/winsiderss/systeminformer/blob/e517d760ac32743d5f0e7bbf6865d3557160e701/SystemInformer/delayhook.c#L1483
