### ISSUE TITLE
I can't start Git Extensions even after installing the .NET 6.0.10 Runtime

### ISSUE THREAD

**Issue by marbel82** [gitextensions/gitextensions#10337]
### Environment

- GitExtensions version: GitExtensions-4.0.0-cba315df5.msi
- GIT version: 2.36.0.windows.1
- OS version: Windows 10.0.19044 x64
- .NET version:  

`dotnet --info`

Zestaw .NET SDK (odzwierciedlenie dowolnego pliku global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Środowisko uruchomieniowe:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300\

global.json file:
  Not found

Host:
  Version:      6.0.10
  Architecture: x64
  Commit:       5a400c212a

.NET SDKs installed:
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  6.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

### Issue description

I try to install GitExtensions from `GitExtensions-4.0.0-cba315df5.msi` file (earlier, I had to uninstall the previous version 3.5.4 manually).

When I ran GitExtensions after installation, I got this message:
_EDIT_
![image](https://user-images.githubusercontent.com/31281571/200133476-8c867173-efb4-4f51-b260-a66c3f8b9afd.png)

I cliked Yes, and the following website opened:
_EDIT_
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-6.0.10-windows-x64-installer?cid=getdotnetcore

The file started to download:
dotnet-runtime-6.0.10-win-x64.exe

The installation was successful, but GitExtensions still show me the message that I need to install .NET.

_EDIT:_ Go to my [comment](https://github.com/gitextensions/gitextensions/issues/10337#issuecomment-1304598892) below and see that second message box (after install runtime) was different.

### Steps to reproduce

Uninstall  .NET runtimes as me in comment below.

I paste `dotnet --info` in Environment section.

**Comment by vbjay** [comment]
Try x86 and x64 of desktop runtime

.NET Desktop Runtime 6.0.10

The .NET Desktop Runtime enables you to run existing Windows desktop
applications. This release includes the .NET Runtime; you don't need to
install it separately.
Downloads for .NET 6.0 Desktop Runtime (v6.0.10)
OSInstallersBinaries
Windows Arm64
<https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.10-windows-arm64-installer>
 | x64
<https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.10-windows-x64-installer>
 | x86
<https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.10-windows-x86-installer>
 | winget instructions
<https://learn.microsoft.com/dotnet/core/install/windows?WT.mc_id=dotnet-35129-website#install-with-windows-package-manager-winget>

**Comment by pmiossec** [comment]
Follow this link ( https://dotnet.microsoft.com/en-us/download/dotnet/6.0 ) and install the ".NET **Desktop** Runtime 6.0.10".

In fact you have a version (6.0.5) previous than the minimum required (6.0.9).
You have the version  6.0.10 of the runtime but it is not enough because the desktop runtime is required...

**Comment by marbel82** [comment]
It looks like it's Microsoft's fault.

I manually download `windowsdesktop-runtime-6.0.9-win-x64.exe` from

https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.9-windows-x64-installer

----
Now dotnet --info shows that I have WindowsDesktop.App 6.0.9
```
 Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
----
Everything works fine now.

**Comment by marbel82** [comment]
I reproduce my issue. I think I made a mistake earlier.

Now.

I uninstall:
- Microsoft.NETCore.App 6.0.10
- Microsoft.WindowsDesktop.App 6.0.9

Git Extensions shows me this message:
![image](https://user-images.githubusercontent.com/31281571/200133476-8c867173-efb4-4f51-b260-a66c3f8b9afd.png)

I click Yes, page opend in browser:
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-6.0.10-windows-x64-installer?cid=getdotnetcore
File downloaded:
`dotnet-runtime-6.0.10-win-x64 (4).exe`

Now it is correct, I install only Runtime, not Desktop Runtime.

And now when I start Git Extensions I got:
![image](https://user-images.githubusercontent.com/31281571/200133654-977b8ab8-b5f3-4acd-8823-24f3407bd245.png)
And next:
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.10-windows-x64-installer?cid=getdotnetcore

`windowsdesktop-runtime-6.0.10-win-x64 (4).exe`

Install....

Yupiiii  Git Extensions  WORKING

----
**I think Git Extensions should show the second message the first time.**

**Comment by vbjay** [comment]
Completely agree. Installing just the desktop runtime will install both.

**Comment by gerhardol** [comment]
The message and link is provided by the DotnetRuntimeBootstrapper.
The component is not in direct control by GE.
I have asked if there is a way to customize the message and link.

https://github.com/Tyrrrz/DotnetRuntimeBootstrapper/discussions/36

Pointing other issues here.

**Comment by Tyrrrz** [comment]
> The message and link is provided by the DotnetRuntimeBootstrapper. The component is not in direct control by GE. I have asked if there is a way to customize the message and link.
> 
> [Tyrrrz/DotnetRuntimeBootstrapper#36](https://github.com/Tyrrrz/DotnetRuntimeBootstrapper/discussions/36)
> 
> Pointing other issues here.

This is not correct. The message above is the default message provided by the default .NET apphost.

**Comment by RussKie** [comment]
I've tried v4 on a workstation without any .NET installed. An attempt to run the app results in the following popup for me:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/4403806/200204923-74dd6f76-20af-411e-b6c5-36ab7beaaa70.png">

It gets installed, and then I can run the app:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/4403806/200205162-a17e25ce-baec-4227-b5d2-d1b8dc26fb53.png">

**Comment by asmwarrior** [comment]
> I reproduce my issue. I think I made a mistake earlier.
> 
> Now.
> 
> I uninstall:
> 
>     * Microsoft.NETCore.App 6.0.10
> 
>     * Microsoft.WindowsDesktop.App 6.0.9
> 
> 
> Git Extensions shows me this message: ![image](https://user-images.githubusercontent.com/31281571/200133476-8c867173-efb4-4f51-b260-a66c3f8b9afd.png)
> 
> I click Yes, page opend in browser: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-6.0.10-windows-x64-installer?cid=getdotnetcore File downloaded: `dotnet-runtime-6.0.10-win-x64 (4).exe`
> 
> Now it is correct, I install only Runtime, not Desktop Runtime.
> 
> And now when I start Git Extensions I got: ![image](https://user-images.githubusercontent.com/31281571/200133654-977b8ab8-b5f3-4acd-8823-24f3407bd245.png) And next: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.10-windows-x64-installer?cid=getdotnetcore
> 
> `windowsdesktop-runtime-6.0.10-win-x64 (4).exe`
> 
> Install....
> 
> Yupiiii Git Extensions WORKING
> 
> **I think Git Extensions should show the second message the first time.**

I have exact same issue. Just find the solution here, thanks.

When the web site opened, it will pop up the file `dotnet-runtime-6.0.10-win-x64 (4).exe` for the downloading, not the desktop version. People has to download the desktop version manually.

**Comment by RussKie** [comment]
I have also run another experiment installing an older version of .NET SDK (6.0.7). It is important to note that SDK is required to build apps, and the Runtime is required for those users who don't build .NET apps. I kind of expect .NET developers to be at least aware of this difference.

 Attempting to run the app, which demands a high version of .NET runtime than installed on the user's workstations, results in the following popups:

* prompt to update .NET Core App workload  - this is .NET host's doing, and it does look confusing. It refers to "SDK, yet it takes to the "Runtime" download page. /cc: @vitek-karas @elinor-fung - this kind of looks related to https://github.com/dotnet/runtime/pull/70059.
<img width="400" alt="image" src="https://user-images.githubusercontent.com/4403806/200207745-f09bc92b-627b-45cd-9f36-591e4c29d6c9.png">

Clicking on the link takes you to the **.NET Runtime** download page:
<img width="810" alt="image" src="https://user-images.githubusercontent.com/4403806/200208224-2fd0e5e8-58d8-408d-ba9e-ab24df5b33d9.png">

But there's still **Windows Desktop Runtime** missing, and that's the second popup that takes you to the appropriate download page.

I am not sure what w can do here. The message looks a bit confusing, and that's probably something the .NET team should address in the host. At the same time .NET developers should be aware of "SDK" vs "Runtime" differences, and, more importantly, should keep their .NET SDK up to date because almost every servicing release of .NET 6 contained security fixes:
<img width="220" alt="image" src="https://user-images.githubusercontent.com/4403806/200209346-dbc1c81c-b60d-40b4-aed3-6154112402f8.png">

**Comment by bjarnesvanberg** [comment]
I had the same problem. Thanks to the comments here I was able to solve it by installing both of the following:

- dotnet-runtime-6.0.10-win-x64.exe
- windowsdesktop-runtime-6.0.10-win-x64.exe

Perhaps the the gitExtensions program should be more precise in the guidelines for installing whatever is needed. Maybe just tell the user up front that two seperate files are needed?

Cheers
-B

**Comment by vitek-karas** [comment]
@RussKie 
> The message looks a bit confusing, and that's probably something the .NET team should address in the host. 

Could you please suggest what parts of the message are confusing (this is tricky area to get right, so I'm looking for specific feedback).

The surprising thing here is that the app has specific dependency on version `6.0.9` - in the original issue the machine as `6.0.5` installed. Normally SDK should not put a patch version into the framework dependency, it should simply state `6.0.0` in the runtimeconfig. And unless the app has a hard dependency on some functionality only available in a given patch version, there's no need to use the patch specific version.

Overall the problem is that SDK currently puts the lower level framework first (in runtimeconfig.json), so the hosts sees that first and if it's missing it fails - so that's why it produces the missing `Microsoft.NETCore.App` message - and the related URL points to that download.
If there are two frameworks listed in runtimeconfig.json with any of them missing, it's impossible for the host to determine which is lower level and which is higher level. It would be ideal if it reported the higher level framework missing first, as the installer at least for our framework automatically includes the lower level dependency.

**Comment by vbjay** [comment]
Key point. If you had installed windowsdesktop-runtime-6.0.10-win-x64.exe. It wouid have fixed up everything. It includes the base runtume. If we can get it to suggest the desktop runtime no matter what, it will install all that is needed.

**Comment by RussKie** [comment]
> Could you please suggest what parts of the message are confusing (this is tricky area to get right, so I'm looking for specific feedback).

What I found confusing (and I suppose what others found too) is:
- if I don't have .NET installed - I get the correct and clear message (https://github.com/gitextensions/gitextensions/issues/10337#issuecomment-1304952389);
- if I do have .NET SDK installed which is lower of what's required - the prompt is confusing:
    * it doesn't refer to Windows Desktop but mentions NETCoreApp instead, and
    * it mentions "Framework" but then opens a link to download Runtime;
    * once you install NETCoreApp runtime, then you get a prompt to download Windows Desktop runtime...

Ideally (I'm not sure how easy it is) the prompt would be the same as in the first instance - "Windows Desktop runtime is missing. Download?"

> The surprising thing here is that the app has specific dependency on version `6.0.9` - in the original issue the machine as `6.0.5` installed. Normally SDK should not put a patch version into the framework dependency, it should simply state `6.0.0` in the runtimeconfig. And unless the app has a hard dependency on some functionality only available in a given patch version, there's no need to use the patch specific version.

Thank you for mentioning this. However, Windows Forms had bug fixes pretty much in [every servicing release](https://github.com/dotnet/winforms/milestones?direction=asc&sort=title&state=closed), and we (kind of) need to target the latest.

> Overall the problem is that SDK currently puts the lower level framework first (in runtimeconfig.json), so the hosts sees that first and if it's missing it fails - so that's why it produces the missing `Microsoft.NETCore.App` message - and the related URL points to that download.
> If there are two frameworks listed in runtimeconfig.json with any of them missing, it's impossible for the host to determine which is lower level and which is higher level. It would be ideal if it reported the higher level framework missing first, as the installer at least for our framework automatically includes the lower level dependency.

Are you referring to this?
```
// GitExtensions.runtimeconfig.json
{
  "runtimeOptions": {
    "tfm": "net6.0",
    "frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "6.0.9"
      },
      {
        "name": "Microsoft.WindowsDesktop.App",
        "version": "6.0.9"
      }
    ]
  }
}
```

Would it be acceptable to remove NETCoreApp framework reference? I tried it locally and it appears to have worked - i.e., it gave me the prompt to install Windows Desktop "framework" (which is confusing, see above).
```diff
    {
      "runtimeOptions": {
        "tfm": "net6.0",
        "frameworks": [
-         {
-           "name": "Microsoft.NETCore.App",
-           "version": "6.0.9"
-         },
          {
            "name": "Microsoft.WindowsDesktop.App",
            "version": "6.0.9"
          }
        ]
      }
    }
```

**Comment by vbjay** [comment]
That should work. Just make sure you tweak the update dotnet version script
in the scripts folder to fix the right parts.

**Comment by RussKie** [comment]
I think, if we go down this path,  we'll be doing this when packaging
installers.

**Comment by vbjay** [comment]
If you just bootstrap the desktop runtime it will install all that is needed.

**Comment by vitek-karas** [comment]
> Would it be acceptable to remove NETCoreApp framework reference?

Yes, that should work just fine and it will fix the UX problems in this case.
