### ISSUE TITLE
"Delete obsolete branches" plugin stop working in version 4

### ISSUE THREAD

**Issue by GraySerg** [gitextensions/gitextensions#10347]
"Delete obsolete branches" plugin stop working in version 4

**Comment by VincentAshbySmith** [comment]
I can also confirm this plugin no longer works. It no longer highlights obsolete branches, that have been merged into the main branch. i.e. local feature branches

**Comment by pmiossec** [comment]
A first very quick investigation shows that `Validates.NotNull(_refreshCancellation);` prevent the execution of the code because `_refreshCancellation` is null in
https://github.com/gitextensions/gitextensions/blob/master/Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs#L281
introduced in 06049c0496b1245483b3b17b26c31996a38caff5

@drewnoakes If you are still around, can you review again?

@RussKie Side note: Can we remove tag `v3.5-RC1` which is very miss leading in investigating the issue because it doesn't belong to v3.5 branch but more on what will become the v4 so I that the commit found was also in v3.5 whereas it has been introduced only in v4.

**Comment by RussKie** [comment]
> Side note: Can we remove tag `v3.5-RC1` which is very miss leading in investigating the issue because it doesn't belong to v3.5 branch but more on what will become the v4 so I that the commit found was also in v3.5 whereas it has been introduced only in v4.

done

**Comment by crossan007** [comment]
I'm also experiencing this - the "search branches" operation doesn't seem to return anything
![image](https://user-images.githubusercontent.com/11679900/200588356-61c3969f-f265-4e2a-b4f5-a2270bc3e4ab.png)

**Comment by crossan007** [comment]
Possibly a duplicate of #9293

**Comment by mik0001** [comment]
> "Delete obsolete branches" plugin stop working in version 4

I also can confirm this - I hope that will be solved very soon.

**Comment by drewnoakes** [comment]
Fixed in #10396.
