### ISSUE TITLE
Building On Mac

### ISSUE THREAD

**Issue by mbostwick** [gitextensions/gitextensions#10371]
### Environment

- GitExtensions version:
latest from main
- GIT version: 
N/A
- OS version:
Mac  APPle Silcon 
- .NET version: 
Dotnet AMD 6 Installed

### Issue description

Did a git pull and tried to build the ui and ran into an issue trying to build this on mac. 

https://learn.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1100

### Steps to reproduce

1. git pull
2. dotnet build

### Did this work in previous version of GitExtensions?

Nope.

### Diagnostics

  Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90, 5): [NETSDK1100] To build a project targeting Windows on this operating system, set the EnableWindowsTargeting property to true.

**Comment by mbostwick** [comment]
I guess the question for this, is if PR's are welcome, and if you would want to move to  https://learn.microsoft.com/en-us/dotnet/maui/?view=net-maui-6.0 ?

**Comment by gerhardol** [comment]
MAUI is discussed in https://github.com/gitextensions/gitextensions/discussions/10305
There are some discussion on building for Windows/ARM that is relevant too
https://github.com/gitextensions/gitextensions/discussions/10288

PRs are welcome, but to convert to MAUI is a very big task and the planned work should be anchored with the core team.

I suggest this issue is solved and further discussions is done in #10305
