### ISSUE TITLE
ExternalOperationException from denied branch rename is swallowed

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#10375]
### Environment

- Git Extensions 33.33.33
- Build 0bd62f609cb1df6348acfc6098f0a7ac6b57dcf4
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.10
- DPI 96dpi (no scaling)

### Issue description

Errors from renaming a branch are only visible in the Git Command Log:

```
Exception:
 GitExtUtils.ExternalOperationException: error: 'refs/heads/release/4.0' exists; cannot create 'refs/heads/release/4.0/debug'
fatal: Branch rename failed
 ---> System.Exception: error: 'refs/heads/release/4.0' exists; cannot create 'refs/heads/release/4.0/debug'
fatal: Branch rename failed
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at GitCommands.GitModule.RenameBranch(String name, String newName)
   at GitUI.CommandsDialogs.FormRenameBranch.OkClick(Object sender, EventArgs e)
Standard err:
 error: 'refs/heads/release/4.0' exists; cannot create 'refs/heads/release/4.0/debug'
fatal: Branch rename failed
```

### Steps to reproduce

- create / checkout a branch like 'release/4.0'
- create a branch 'release/4.0_debug'
- rename it to 'release/4.0/debug'

### Did this work in previous version of GitExtensions?

I doubt it

**Comment by vbjay** [comment]
Probably a windows file name issue. Look inside the .git folder and especially the refs folder. I bet git is treating 4.0 as a flle extension. 

https://git-scm.com/docs/git-pack-refs

Run that and see if it fixes it.

**Comment by pmiossec** [comment]
> Probably a windows file name issue. Look inside the .git folder and especially the refs folder. I bet git is treating 4.0 as a flle extension.

Not sure to 100% understand what you are saying @vbjay but to be clearer the reason for me is because git treat '/' separator in a branch as sub-folders in the 'refs' folder.
So if the name is already taken by a branch file ( here I imagine that the branch `4.0` already exists. You already have a branch with this name, @mstv, right?) git can't create a folder with the same name to create inside the 'debug' file.

It's a limitation of how git handle branch as files before packing them. That's the file system that prevent git to create it.
But I think @mstv already knows it and this usecase was to highlight that GitExtensions swallow the error. Am I right?

**Comment by vbjay** [comment]
You got it @pmiossec can't have a file ...4.0 and a folder ...4.0/blaa.

**Comment by mstv** [comment]
> this usecase was to highlight that GitExtensions swallow the error. Am I right?

Exactly. I hate error hiding.
