### ISSUE TITLE
The merging tool and comparison tool of SVN cannot be directly selected in the settings

### ISSUE THREAD

**Issue by Senfee-Cheng** [gitextensions/gitextensions#10386]
### Environment

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version: 

### Issue description

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.34.1.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4200.0
- DPI 144dpi (150% scaling)

**I want to set the SVN merge tool and difference comparison tool directly, but the original SVN tool cannot be selected in Git Extensions Exe, I must copy them and change their names so that I can recognize this. exe**

![图片](https://user-images.githubusercontent.com/20067002/201466502-56b86562-d38c-4188-af89-5b7f0ba72b47.png)
![图片](https://user-images.githubusercontent.com/20067002/201466517-7f83a3ff-c948-49e4-a434-997595ffa1f2.png)
![图片](https://user-images.githubusercontent.com/20067002/201466522-1f09f274-be9b-4824-abfa-1e4c95064b89.png)
![图片](https://user-images.githubusercontent.com/20067002/201466533-e6560a4e-5cea-46e1-becd-9a2080d46569.png)
![图片](https://user-images.githubusercontent.com/20067002/201466543-8ee32227-fb53-4b69-8938-b930ea390e0c.png)
![图片](https://user-images.githubusercontent.com/20067002/201466549-41e082a6-d628-4d12-a36c-4eeb3b6df743.png)

### Steps to reproduce

If your computer has SVN, you can't directly select the merge tool and comparison tool that comes with SVN.

If you copy them and change their names. So that you can choose

I was thinking, why should I limit the name of "*. exe" when selecting? Who can ensure that the name must exist?

### Did this work in previous version of GitExtensions?

It seems that there is always a problem, because I have SVN, and I don't want to download other tools

**Comment by vbjay** [comment]
We ssuggest known paths but you can moist certainly select a different path.  Alosn with choosing a different tool.  I use p4merge myself.  

![image](https://user-images.githubusercontent.com/3629489/201473870-6b5a08c6-2567-4122-a82e-1c35fd3b817d.png)
![image](https://user-images.githubusercontent.com/3629489/201473899-dbd04378-e0ed-42ab-b644-34323ebf9a5f.png)

**Comment by vbjay** [comment]
Not to mention those are different tools.  SVN tools deal with svn repo info and I am sure are not compatible with git repos.

**Comment by gerhardol** [comment]
The difftool in TortoiseSVN should work, what I know TortoiseGit is just a fork including the difftool. I cannot see if there is a need for specific changes though. The executables are renamed.

If a diff or mergetool can be used in Git, it should be usable in Git Extensions. There is some funky special handling for mergetools, but the standard Git commandline is available too. tools can be added from the command line or in the GE GUI. 
Git has knowledge about arguments for some tools, can be seen with `git mergetool --tool-help`. GE has a similar support. also with search paths for a number of tools, so you do not have to figure out the agruments. For Tortoise* the TortoiseGit tool path is selected, expected to be the common tool. The TortoiseSvn path can be added manually.

So this is an enhancement request to add TortoiseSvn paths. This is not planned, it would confuse more users than it helps.

Sidenote: Some other tools known by Git could be added to GE too, there are some additions since the last cleanup a few years ago. Maybe there are interest in codecompare, deltawalker, diffuse, examdiff, guiffy (tkdiff and xxdiff outdated?). But it should be done by someone that use the tools.

Internal note: GE has hardcoded implementation to filter out non-GUI tools like `vimdiff` in the dropdown with all difftools. Git now lists this in the listing, like ` p4merge          Use HelixCore P4Merge (requires a graphical session)` so it should be possible to get this infor from the command.
