### ISSUE TITLE
Check For Dotnet Core & Dotnet Windows On Install

### ISSUE THREAD

**Issue by mbostwick** [gitextensions/gitextensions#10450]
### Feature description

It would make the install proccess better if the MSI checked for dotnet+ donet-for-windows being installed, and had an optional step to install. 

This seems like a small and easy feature that would make it easier to install and use the tool. 
https://learn.microsoft.com/en-us/answers/questions/913327/correct-approach-to-check-for-net-6-installation.html

### Environment

- GitExtensions version:
version 4+, ad lower versions didn't need a new installer 
- GIT version: 
any supported
- OS version: 
windows
- .NET version: 
whatever versions are supported

**Comment by vbjay** [comment]
We have a portable and installed version to consider. If app itself is bootstrapped then even if someone messes with installed net then the bootstrapping will handle both MSI and portable versions.

**Comment by mbostwick** [comment]
I don't understand where your coming from, the portable version would be its own thing. 

However, I want to share some context, I routed the issue because I decided to do an update, and thought I had screwed up because the error message said you need to install dotnet 6, so I installed dotnet 6, then I ran it again, and found I needed to install dotnet 6 for windows. I thought maybe the detection was broken, or I need to force a reboot, turns out the target detection just required both to be installed, which if you think about it is silly because the desktop runtime includes the core dotnet 6 runtime it may be I should have just **known** to install the desktop runtime, but I'm not sure .. However, since your adding a new dependency, and you can't auto upgrade the 3.5 versions, not having the dotnet install proccess as part of the UAC timing is a bit of a pain, as some places get all kinds of cranky about installing things (hence why portable versions of packages have been more and more popular), and you end up having to close and open the app 4 or 5 times to get the update going.

That may be fine if your a long time user or a power user, but to be honest the dotnet 6 update has been a major bummer for me, I've had to deal with shell permission issues with the updated git extensions, the fact that git extensions wont actually support any targets beyond what was in 3.5 (i.e. no mac support), and now the installer is a bit confusing, combined with the rise of the ever improving tooling offered by vscode and jetbrains.. I've closed it was wont fix but I feel like with this problem git extensions is no longer a recommend tool for people new getting started ..

**Comment by RussKie** [comment]
Thank you for the effort. However, this issue has been discussed in https://github.com/gitextensions/gitextensions/issues/10337 and has been fixed in https://github.com/gitextensions/gitextensions/pull/10355.
We do use DotnetRuntimeBootstrapper, which is responsible for downloading and installing required .NET runtime, if it's missing, however, it appears we failed to correctly bootstrapper the bootstrapper -> https://github.com/gitextensions/gitextensions/issues/10425.

**Comment by vbjay** [comment]
Mac support: our readme clearly points out where our cross platform support is and isn't. 

Bootstrap: Yes we goofed it. We got some help from the bootstrap developer to spot the issue. We also learned that requiring just desktop runtime will do it instead of marking both runtime and desktop runtime.  On your side reading the error message closer would have pointed out the fact you were being asked to install two different things. 

Where I'm coming from. Same exe runs if installed or portable. If we bootstrap the exe we gain both making sure they have the needed requirements installed. The extra benefit is that if someone cleans house and uninstalls the desktop runtime and makes it not runnable, the next time they run GE they would be asked again. If the bootstrap worked it would have been a simple ok click and install what it downloads.
