### ISSUE TITLE
MSIX installer?

### ISSUE THREAD

**Issue by Brouilles** [gitextensions/gitextensions#10463]
### Feature description

I saw a post about the potential use of MSIX (cf. https://github.com/gitextensions/gitextensions/issues/2456). Any news on it? Always planned or not really?

Don't know how the current update system works. But an advantage of MSIX is to have binary difference, so smaller updates.

### Environment

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version:

**Comment by vbjay** [comment]
See https://github.com/gitextensions/gitextensions/issues/2456#issuecomment-497947178

**Comment by vbjay** [comment]
I can see the core team making it pull request only.  Wix is pretty much official how you make MSIs. MSIX would need to be tested hard and validated it actually gets our deliverables out to the end user.

**Comment by pmiossec** [comment]
> But an advantage of MSIX is to have binary difference, so smaller updates.

My point of view: In fact, nowadays, we don't really care about packages size when the download happened once every months. This is absolutely not enough as added value to wish to change the solution we use for something else.

If you tell us that it's a lot easier to generate and maintain. Why not!

I don't think I'm wrong if I say that no one in the core team likes to work on setup things.
So that raise the question of who will do it.
If someone is happy to work on that and port everything that has been done in the current setup, I'm pretty sure the team will be happy to switch to it.

We are looking for someone who could tell us a clear list of advantages that could bring this solution and that could lead the work to achieve parity over what we already have in the current solution.

**Comment by Brouilles** [comment]
Not a complet awnser. But here a use case. Why Affinity Designer 2 switch to MSIX.

https://forum.affinity.serif.com/index.php?/topic/171826-why-are-we-using-msix-for-windows-installers/

**Comment by vbjay** [comment]
> MSIX apps are sandboxed to prevent this.

That would mean we would definitely need to vet nothing breaks. 

> MSI requires admin privileges to install. MSIX installs per-user, but files are deduplicated so that disk space isn't wasted.

Again validate file path changes and such don't harm functionality. 

> ...meaning an uninstall always leaves you in a clean state.

What if I want my settings to remain? I'm reinstalling or installing a new version that can't update.

**Comment by RussKie** [comment]
IIRC we've looked into options, and if my memory serves me well MSIX was a no go. MSIX doesn't (or didn't) support Win32 apps. It neither supports system-wide installations nor Explorer extensions registrations. Whilst some user may have desire to have per-user install, they can achieve this by other means - e.g., use the portable version.
If you really require the app distributed in a form of a MSIX you're welcome to champion the work and send a PR.

> Why Affinity Designer 2 switch to MSIX.
> 
> https://forum.affinity.serif.com/index.php?/topic/171826-why-are-we-using-msix-for-windows-installers/

This worked for them. It doesn't necessarily work for us.
