### ISSUE TITLE
Crash when searching in Diff View if multiple Diff Sections are shown

### ISSUE THREAD

**Issue by plego97** [gitextensions/gitextensions#10469]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.11
- DPI 144dpi (150% scaling)

### Issue description

When searching in the Diff view of a commit, the program crashes.
The Problem seems to be happening when the `Diff` view shows multiple `Diff`s, for example:
<img width="257" alt="image" src="https://user-images.githubusercontent.com/7893117/204496572-ca711ca0-ef57-480b-95ce-6b797d20b8bc.png">

### Steps to reproduce

* Select a commit 
* Go to `Diff` Tab
* Verify that multiple `Diff`-Sections are shown
* Press `Ctrl+F` or `Right-Click -> Find`
* type in any text
* Click on `Find next`

**Comment by RussKie** [comment]
Can't repro. What am I doing wrong?
![image](https://user-images.githubusercontent.com/4403806/204522373-99d3b0b0-77b8-4508-8b3c-2d3ced51718f.png)

**Comment by plego97** [comment]
I cloned the gitextentions repository to find a commit where it happens for me 

the first merge I found was:  `45f02913c484d1b113dfdadab29321f0c9030f3c`

I recorded a video to show what happends:

![Animation](https://user-images.githubusercontent.com/7893117/204529901-ec2bc7bb-d683-48a8-b114-042c024b5015.gif)

**Comment by mstv** [comment]
Thank you for the repro, @plego97!

**Comment by mstv** [comment]
`FindNextAsync()` has not skipped the "     - No changes -" item.

![grafik](https://user-images.githubusercontent.com/36601201/204600660-68e4b070-ee49-43be-a3f0-aadd16321ae8.png)

**Comment by mstv** [comment]
After setting `SelectedIndex` (regardless of with / without `_enableSelectedIndexChangeEvent = false`), both the `SelectedItem` and `FileStatusListView.Items[0]` point to the "no changes" item of the **second** group.
And indeed this item has the `Index` 0.
Is it added first somehow, @gerhardol?

![grafik](https://user-images.githubusercontent.com/36601201/204679518-061ceeea-e73b-4d9d-8fa4-cebd93e2397a.png)

**Comment by mstv** [comment]
> Is it added first somehow, @gerhardol?

No, it is not. The items are in the expected order before calling `FileStatusListView.Items.AddRange(list.ToArray())`.
`list` contains all items of all groups. Every item has `Index` `-1`.  `FileStatusListView.Items` is empty.
`ListView.AddRange()` assigns `1, 2, 3, 4, 5, 6, 0` as `Index`.
I could not find another property which indicates the visible order other than `Bounds.Y` / `Position.Y` and `ListViewItem.FindNearestItem()`.
This behavior of `ListView` is very counter-intuitive and would significantly complicate the implementation.

I propose to
- add an explicit iteration limit (= number of items) as a safety net in order to just avoid the hang (The search might be broken if items have been reordered.)
- skip `StatusOnly` and `RangeDiff`items when searching diffs (9e3fdc79c44b5f5ec15e2088e57566b433fed19c) regardless of this issue anyway
- pursue the switch to `TreeView`

Thoughts?

**Comment by mstv** [comment]
As feared, `Bounds` cannot be accessed for collapsed items and `Position.Y` is `0`.
It does *not* work better if the `group.CollapsedState` is set after the `ListView.AddRange()` call.

**Comment by gerhardol** [comment]
> skip StatusOnly and RangeDiffitems when searching diffs (https://github.com/gitextensions/gitextensions/commit/9e3fdc79c44b5f5ec15e2088e57566b433fed19c) regardless of this issue anyway

Seem fine

**Comment by RussKie** [comment]
> As feared, `Bounds` cannot be accessed for collapsed items and `Position.Y` is `0`.

Could you please point me where we access `Bounds`?

**Comment by mstv** [comment]
> Could you please point me where we access `Bounds`?

We don't and do not want to do this.

We need to iterate the items in order. And ListView boycots this. I was just searching how to find out the visible order of the items. `Bounds.Y` was one of the very few candidates.
But let's go for TreeView instead - in follow-up PRs.
