### ISSUE TITLE
Unable to run git commands from Git Extensions

### ISSUE THREAD

**Issue by Vincent-Pe** [gitextensions/gitextensions#10514]
### Environment

- GitExtensions version: 4.0.0.15569
- GIT version: 2.39.0
- OS version: Windows 11 22H2 (22621.819)
- .NET version: 6.0.11

### Issue description

This is a new Git Extensions install on a new computer.
I have some cloned repositories but whenever i try to do a fetch or pull from Git Extensions it fails.
Pull:
![image](https://user-images.githubusercontent.com/120427368/207181245-973f0d59-5c61-476c-96c6-06b24bb37286.png)

Fetch:
![image](https://user-images.githubusercontent.com/120427368/207181349-70007b75-f9aa-480c-bff8-1f33305a1112.png)

Git complains about the --jobs=0 option.
If I run the same command in Git Bash, it has the same error, but if I remove the --jobs=0 option, it works fine in Git Bash

I can't find a way to control that option from Git Extensions

### Steps to reproduce

Clone any repository
Perform a Fetch or Pull from Git Extensions

### Did this work in previous version of GitExtensions?

I don't have the problem on another computer running Git Extensions 3.5.3.12551 and Git 2.33.0

**Comment by gerhardol** [comment]
Seem to be a failed check in Git 2.39
Doc specifies that 0 is OK
https://git-scm.com/docs/git-config#Documentation/git-config.txt-fetchparallel
Downgrade Git, wait for a Git update.
Maybe change this in GE too.

**Comment by AdrianJSClark** [comment]
Seems this change was a specific decision made here: https://github.com/git/git/commit/51243f9f0f6a932ea579fd6f8014b348f8c2a523

Quoting from that commit message:
> When a "jobs = 0" is passed let's BUG() out rather than fall back on online_cpus(). [...] The preceding commit has an overview of the API callers that passed "jobs = 0". There were only two of them (actually three, but they resolved to these two config parsing codepaths).

Seems that when they did their analysis of this change the path where someone passed `--jobs=0` on the command line wasn't considered fully or it isn't properly handled in the `fetch` code. I'm not fluent enough in C to do any deeper analysis.

Perhaps if Git Extensions doesn't have a specific value to set here it should just skip adding this parameter and trust the config values?

**Comment by AdrianJSClark** [comment]
The other option for a fix might be to choose the number that would be chosen by Git. When the config settings are `0` the value used is the value returned by the `online_cpus()` method. On Windows that method calls [`GetSystemInfo`](https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getsysteminfo) and if the value of `dwNumberOfProcessors` is greater than zero that is returned, otherwise `1` is used.

I'd suggest that the default value used by Git Extensions for this setting should be [`Environment.ProcessorCount`](https://learn.microsoft.com/en-us/dotnet/api/system.environment.processorcount?view=net-7.0) or `1` (whichever is larger).

What do we think?

**Comment by AdrianJSClark** [comment]
I note that the feature doesn't apply this parameter if the setting is configured already. So that's OK.

It is also a work-around if you are reading this and just want things to work. Configure `fetch.parallel` for your repository or globally (to zero to get the defaults) and this parameter is never added.

To configure globally run: `git config --global fetch.parallel 0`

**Comment by gerhardol** [comment]
Not being able to test right now, but I interpret the functionality as if removing `--jobs=0`, parallel fetch will require the user to specifically enable parallel fetch, which would disable the functionality for all.
The argument could be ignored just for >= 2.39, which should be the same.
This should be changed in Git, breaking the documented behavior should require stronger motivation...

**Comment by gerhardol** [comment]
PR to set options to git (-c) instead, so same behavior.
