### ISSUE TITLE
Git Extensions 4.0.1.15887 -- a UI issue masquerading as an inability of GitEx to 'see' file changes in a repository

### ISSUE THREAD

**Issue by kismert1** [gitextensions/gitextensions#10632]
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.39.0.windows.2
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.13
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

    Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

### Issue description

I might be bonkers, but I swear that Git Extensions 4.0.10 seems to have intermittent problems seeing file changes in one of my repos.
### What It Feels Like
Let's say I have a file `modFoo` that I have modified.
 1) I start GitEx, pick my repo, and click Commit. `modFoo` isn't in the list.
 2) If I move `modFoo` to another directory and refresh, it shows as deleted in GitEx.
 3) But when I move it back, it again doesn't show in the commit list after a refresh.
 4) I exit and reopen GitEx: 
   * Now `modFoo` shows up in Commit changes.
   * But, the diff GitEx shows is not the same as a diff I get in Notepad++ between the Git version, and the file in the IDE.
   * The GitEx diff is wrong - time to panic! :cold_sweat:
### What Is Really Happening
But, after some experimentation, I came up a different explanation:
 * Step 1: I accidentally stage `modFoo` while fooling with the vertical divider. 
 * After Step 2, `modFoo` shows up as both deleted _and_ staged.
 * After Step 3, I make changes to `modFoo`.
 * After Step 4, the same file is now in two places: the Commit list has the current version, _and_ Staging has the older.
### The Problem
The problem is the same file can appear in two different states at the same time: it can both be in the Commit list, and also exist (as an earlier revision) in Staging.
Needless to say, this Git-style 'quantum superposition' is unexpected and confusing.
### A Solution?
Suggestion: Could you highlight any file that is both in the Commit list and Staged? Maybe show a tool-tip on hover? You might already show a  pop-up message on Commit, but I wasn't brave enough to try that on production code.

### Steps to reproduce

 1) Start GitEx, pick a repo, then 'accidentally' stage `modFoo`. The file is now not in the Commit list.
 2) Move `modFoo` to another directory and refresh the Commit list. It shows as deleted.
 3) Move `modFoo` back in place. Refresh again, and it again drops from the Commit list.
 4) Make some changes to `modFoo`
 5) Exit and reopen GitEx, click Commit
   * The old version of `modFoo` is still staged
   * The new version shows up in the Commit list

### Diagnostics

[CommandLog_20130111.txt](https://github.com/gitextensions/gitextensions/files/10397235/CommandLog_20130111.txt)

**Comment by pmiossec** [comment]
If I understand well what you thought was a bug in GitExtensions is in fact a normal behavior of GitExtensions and Git.

My feeling is that you are still not used to the fact that Git is a "[stupid **CONTENT** tracker](https://git-scm.com/docs/git)"
In fact git is managing content (of files) and not files in itself.
And the staging area in Git has been especially created to be able to commit a particular content of a file different than the content of the same file in the working directory. As a consequence, this feature could be used to commit only part of the file changes. Changes that you Git in command line and GitExtensions display as diff.

So what you see in the staging area is the content that you put at a given moment. And what you see in the "working directory changes" are the differences with what has already been staged.

>The problem is the same file can appear in two different states at the same time

So that's a perfectly normal use case and that's in fact the exact goal of the staging area (or also called 'index') to be a "place" where you put only the changes that you want to commit. Your are choosing carefully and staging the changes/contents that you would like to see in the commit you will create.
And, depending of your workflow, it could be very frequent to see the same file in the "working directory changed files" **AND** the "Staging area" if you used the "chunk of file staging" feature or if you modify again a file after having staged it.

>Suggestion: Could you highlight any file that is both in the Commit list and Staged? 

For me that's a so common use case that we get used to it and  it is not really needed. It will need to a lot of difficult logic in GitExtensions to make this list comparison that we will have to maintain...
Most of the times it's not a problem and you see it quickly except if you have a lot of changed files (which is maybe more the problem because with git you should create commit often)

**Comment by mstv** [comment]
Staging selected lines is a killer feature to me.

![StageSelectedLines](https://user-images.githubusercontent.com/36601201/212181123-3ec69c73-cd18-4450-814b-1925b39745d2.gif)

**Comment by RussKie** [comment]
This how git is supposed to work and this is by design.

**Comment by kismert1** [comment]
@pmiossec 
Thanks for your thoughtful response. It has improved my understanding of how Git works.
