### ISSUE TITLE
Ampersands (&) appear in a lot of translations

### ISSUE THREAD

**Issue by DirkieDurky** [gitextensions/gitextensions#10780]
### Environment

- GitExtensions version: 
Git Extensions 4.0.2.16100
Build 25100ec1f7c8da8f798613da74826038af81a50e
- GIT version: 
Git 2.39.1.windows.1
- OS version: 
Microsoft Windows NT 10.0.22621.0
- .NET version: 
.NET 6.0.14

### Issue description

A lot of ampersands appear in the translations. I use Git Extensions in English and found them when hovering the File Explorer icon or the Git Bash icon in the tooltips. It says: "File E&xplorer" and "Git &bash". I also checked the french translations where they also appear in a lot of places.
Are those characters somehow supposed to be there, or can I remove them?

### Steps to reproduce

Hover over the File Explorer icon in the taskbar at the top of Git Extensions

### Did this work in previous version of GitExtensions?

Unknown

**Comment by pmiossec** [comment]
> It says: "File E&xplorer" and "Git &bash".

I would say that for these 2 examples it's because the tooltip use the same string than the global menu items ones where the '&' is useful to be able to use them as keyboard shortcuts (when you access the menu with the 'alt' key)

![image](https://user-images.githubusercontent.com/460196/222186051-40d5ba2b-ecfa-4bdf-82b1-90a239ffb3ba.png)

![image](https://user-images.githubusercontent.com/460196/222185777-b3eefc2d-7da4-411b-96df-6cce474d7cb5.png)

Without knowing the code, so I don't guarantee it's possible, I would say that the perfect fix would be to remove these '&'s when used as tooltips...

**Comment by RussKie** [comment]
That's a known 'feature' of Windows Forms AFAIK. There's an issue somewhere
in https://github.com/dotnet/winforms to that effect.

IIRC the fix is to use double ampersand.

**Comment by mstv** [comment]
> IIRC the fix is to use double ampersand.

**Only** if the text is used for a **tooltip only** and if you want a "&" character.

In case of the two mentioned toolbar buttons, it is a mistake in the designer file (refer to #10781).
So it would be safe to remove them in the translation file - if tooltips were translated... (There's an open issue.)

For labels of buttons, menu items, etc. please keep the `&amp;` and try to put it in front of the same character, e.g. "Softwar&e" --> "Logici&el". These mnemonics should be unique per form / menu.

**Comment by mstv** [comment]
Obviously, tooltips *are* translated if they are set using `ToolTipText` property.
