### ISSUE TITLE
Recent repositories: characters near the end of directory paths are narrowly spaced

### ISSUE THREAD

**Issue by shirayuki** [gitextensions/gitextensions#10812]
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.13
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

In Recent repositories, characters near the end of directory paths are narrowly spaced.
![image](https://user-images.githubusercontent.com/18039/226538184-2e6c672c-dbde-46ad-8941-63ac0616ca6e.png)

### Steps to reproduce

Start Git Extensions without parameters.

**Comment by RussKie** [comment]
That's probably something to do with your font.

**Comment by mstv** [comment]
@shirayuki has seen more special font effects: #10382

**Comment by RussKie** [comment]
This is likely something to do with your Windows settings - e.g., Windows in different languages uses different default fonts, different font metrics, and in some situations, it can use raster fonts instead of vector fonts. We have no control over this.

I do believe you can change the fonts the app uses in the Settings. If this is not sufficient for some reason, you're welcome to propose a fix.
