### ISSUE TITLE
Disable Automatically "Show untracked files" in Commit Window

### ISSUE THREAD

**Issue by jwei** [gitextensions/gitextensions#10901]
### Feature description

By default it always "Show untracked files" when we open the commit window. Looks like even if you uncheck the option, next time when you open the window, the option is enabled automatically.

Can we have the capability to enable or disable this option by default?

### Environment

- GitExtensions version: 4.0.2.16100
- GIT version: 2.4.0.windows.1
- OS version: Windows 11
- .NET version: 4.8

**Comment by vbjay** [comment]
Untracked files are new files to be added. You want to see those. If specific paths are desired to not be shown, use git ignore feature. Rrat is what rrat is for.

**Comment by vbjay** [comment]
We don't remember that setting on purpose. Most people want to see what has changed or to be added, ignoring ignored and skip-worktree and assume-unchanged by default. We then allow you to adjust your view if you want.

**Comment by RussKie** [comment]
> By default it always "Show untracked files" when we open the commit window. Looks like even if you uncheck the option, next time when you open the window, the option is enabled automatically.
> 
> Can we have the capability to enable or disable this option by default?

Could you please help us understand why it would be desirable?

**Comment by jwei** [comment]
@vbjay  @RussKie  Thank you guys so much for the quick response. Really appreciate it!!

Our use case is, for development purpose, sometimes the devs may randomly put some files in some directories. Since we have a big project to maintain, there are lots of those files. 
Those files would never need to be committed. So every time when we click "Commit" button, a lot of untracked files were displayed in the "Unstaged" window. The default sort logic is that those untracked files would appear on top which just make the diff files invisible. So we need to uncheck the option of "Show untracked files" every time when we open the commit window.

The reason why we do not use git ignore is that, the files are indeed random, rather than in the same directory. Besides, there are quite some files. 

Thanks for the contribution on this project BTW :)

**Comment by vbjay** [comment]
I would suggest requiring the following. 

- Having a trunk branch like develop
- All work to be done on feature, bug,...branches
- Let them commit their work
- Allow rewrite of history in these branches but not develop
- Devs must create pull requests to merge into develop
- Do code reviews in pr
- They can fix their commits and rebase till they don't have issues
- MERGE pr

They will learn through rewriting history and pr reviews to start being more careful about what is committed instead of blindly committing all files. 


Also you can write commit hooks or scripts in repos to help them not change or reset common auto touched files. I wrote a book in a website project that prevents users from checking in a project.xml file where the element pointing to local db file that is tracked in gur lfs exists in folder path and the change would not mean xml file would never point to a non existent file. You delete current db file and export another dbpac file you must include project and dbpac files. So look for opportunities like that. 

Also look at skip-worktree if files are committed but should not be committed again unless specific reasons.

**Comment by RussKie** [comment]
> Thanks for the contribution on this project BTW :)

You're most welcome. 



> Our use case is, for development purpose, sometimes the devs may randomly put some files in some directories. Since we have a big project to maintain, there are lots of those files. Those files would never need to be committed. So every time when we click "Commit" button, a lot of untracked files were displayed in the "Unstaged" window. The default sort logic is that those untracked files would appear on top which just make the diff files invisible. So we need to uncheck the option of "Show untracked files" every time when we open the commit window.
> 
> The reason why we do not use git ignore is that, the files are indeed random, rather than in the same directory. Besides, there are quite some files.

I am afraid that sounds something very specific to your use case and, frankly, it something that it's better be fixed with teaching the devs the git best practices and etiquette (e.g., something along the lines of what @vbjay suggested above).
The app is used by quite a few users, and allowing to persist this setting _will_ cause quite a bit of mayhem; so we can't do that.

**Comment by jwei** [comment]
Sorry for the late updates. I appreciate your advice @vbjay and @RussKie. The key is to follow Git best practices, like utilizing Git ignore and do PRs. I totally agree that this should be pushed through all devs.

Thanks for all the work and comments!!

**Comment by ezradreisbach** [comment]
Open Tools -> Git Bash, then:
git config status.showUntrackedFiles no

This will set the git configuration and Git Extensions will read it and uncheck the "Show untracked files" just like OP wants.
That's how I want to use it too and I'm not going to stop no matter how many people say it's not "best".

**Comment by vbjay** [comment]
> Open Tools -> Git Bash, then:
> git config status.showUntrackedFiles no
> 
> This will set the git configuration and Git Extensions will read it and uncheck the "Show untracked files" just like OP wants.
> That's how I want to use it too and I'm not going to stop no matter how many people say it's not "best".

You do you.  Understand you will run into the situation of omg I forgot a file and never  committed it. You might want to rethink your view.

**Comment by mstv** [comment]
> git config status.showUntrackedFiles no
>
> This will set the git configuration and Git Extensions will read it and uncheck the "Show untracked files" just like OP wants.

What are you complaining about, @ezradreisbach? That _is(!)_ how the Commit dialog works.
(The virtual commit "Working directory" ignores this setting - because it does not have such a context menu as FormCommit.)

This is a volunteer project. If something is missing, you could discuss a feature and file a PR...

**Comment by ezradreisbach** [comment]
It's just a way for the originator of this thread to get what he wants. 
And I'm getting what I want too. Many thanks to the volunteers.

**Comment by mstv** [comment]
Then, thank you for the hint, @ezradreisbach!
