### ISSUE TITLE
Blank window area in repo browser

### ISSUE THREAD

**Issue by asherber** [gitextensions/gitextensions#10959]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.40.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.16
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

I upgraded from 4.0 to 4.1 this morning, and now I've got a new blank area on the right side of the repo browser:

![Screenshot_1](https://github.com/gitextensions/gitextensions/assets/5248041/d30e94cf-2c7d-48a6-86fe-ad5fd12baa01)

### Steps to reproduce

Open the repository browser.

### Did this work in previous version of GitExtensions?

Yes, worked in all previous versions.

**Comment by asherber** [comment]
Yes!

**Comment by gerhardol** [comment]
This occasionally occurs and I believe it has so for many years. I do not know the trigger.

**Comment by asherber** [comment]
Okay -- I assumed it was related to the new version because I've never seen it before. Thanks for the response.

**Comment by RussKie** [comment]
Added a known issue in https://github.com/gitextensions/gitextensions/discussions/10958.

**Comment by RussKie** [comment]
I'm going to keep this open for tracking and reference purposes.

**Comment by RussKie** [comment]
I guess the issue is related to this method:
https://github.com/gitextensions/gitextensions/blob/351084d4284b6773ee3c6713412b8f056c67da37/GitUI/CommandsDialogs/FormBrowse.cs#L2754-L2762

Few things come to mind - either the setting (`AppSettings.CommitInfoPosition`) isn't being parsed correctly, or the method isn't being called correctly.

**Comment by drewnoakes** [comment]
I hit this after updating just now to 4.1.

Attaching my settings file in case it's helpful.

[GitExtensions.settings.txt](https://github.com/gitextensions/gitextensions/files/11483782/GitExtensions.settings.txt)

I see no mention of `CommitInfoPosition` in the file.

**Comment by sjh37** [comment]
I too have the same issue
![image](https://github.com/gitextensions/gitextensions/assets/4190514/7b4104c6-4f45-4257-a571-f61a3854de47)

However, selecting this fixed it
![image](https://github.com/gitextensions/gitextensions/assets/4190514/b7be3ca1-79b8-49ed-a0e0-25e6f1854822)

**Comment by mstv** [comment]
I should have chosen a more detailed handling for the yet missing value instead of `_splitter.Panel2Collapsed = settings.GetBool(Panel2CollapsedSettingsKey, defaultValue: false);` in https://github.com/gitextensions/gitextensions/pull/10718/files#diff-3b5b9342dafabeb00290f170ec931fcdf433f9685397df5358df4c4fab936a0f
