### ISSUE TITLE
Amend Commit and Push - Force With Lease option

### ISSUE THREAD

**Issue by MgSam** [gitextensions/gitextensions#11050]
### Feature description

When making a Commit, the window contains an Amend button. This is convenient, but the issue is that whenever you actually make an Amend Commit, and hit Commit and Push you will **always** be prompted by Git Extensions that the commit was rejected and then offered the option to force-with-lease, etc instead.

I suggest there could be Force With Lease checkbox next to Amend Commit, and it automatically gets pre-selected when Amend Commit is selected. This checkbox both fixes the workflow issue with Amend Commit, and also simplifies the workflow in the case where you do really know ahead of time that you want to force-with-lease the commit you're sending up.

Thanks!

### Environment

- Git Extensions 3.4.0.9608
- Build a4f5744118651776ec26d570b462e5ba8fc18afc
- Git 2.30.0.windows.2
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4614.0
- DPI 192dpi (200% scaling)

**Comment by mstv** [comment]
![image](https://github.com/gitextensions/gitextensions/assets/36601201/9cf2de5b-3095-415a-9204-6925241df834)

**Comment by vbjay** [comment]
The task dialog gives a wait you are about to something potentially destructive. The whole point was to have something say not a normal push. If you check a checkbox that says force with lease then push that is your signoff you expect it to do so. The task dialog gave this info when needed and if a normal push failed because you can amend a local only  commit and then push just fine without it. I say at the least don't default to checked and opt in to the with lease. There still needs to be human intention to force with release.
