### ISSUE TITLE
Rebase dialog shows skipped commits as "pick"

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#11179]
### Environment

- GitExtensions version: 4.1

### Issue description

![image](https://github.com/gitextensions/gitextensions/assets/36601201/29a8ff36-46a9-4e0a-a0c3-9f02a5395573)

### Steps to reproduce

- interactively rebase a branch with conflicts
- drop first commits (or skip them by deleting the lines)
![image](https://github.com/gitextensions/gitextensions/assets/36601201/56100f1c-65e4-4138-9308-11f9ed8aa01d)

### Did this work in previous version of GitExtensions?

I guess no

**Comment by gerhardol** [comment]
The status for commits is incorrect also if you reorders the commits.
This changed when @pmiossec partly fixed this status handling some years ago. I believe the status is taken from the status before manually changes or so.
Have not investigated myself.

**Comment by pmiossec** [comment]
The data from this grid is taken from internal git files created during a rebase and yes, all the information are not available (or I didn't find it because there is no documentation about that and it is plain retro-engineering).

I remember that the action are kept in memory to be as accurate as possible but if you close the dialog and open it again, because the information is not available, the action is lost and the default one 'pick' is displayed. This edge case could be handled but it is more complex to do that why I have decided to not do it at the time I worked on it.

For your case, maybe the line marked as deleted could be handled by maybe reading the edited user file ourselves and handling the status. But for removed lines, it will be much more tricky...

**Comment by mstv** [comment]
Thank you for the explanation. This helps to interpret the displayed information.
I guess it would have been better to read the user-edited file. Though I would not spend much effort here.
One can use the new `Edit todo` feature in order to get an update of the remaining steps - with the drawback that applied commits are removed from the list. Since they are visible as commits (in another GE instance), this is not an issue.
I would agree to close this as not planned.

**Comment by pmiossec** [comment]
> I guess it would have been better to read the user-edited file. Though I would not spend much effort here.

I had a quick look yesterday and I'm pretty sure a recent version of Git changed the content because indeed the content displayed is completely broken and that was not the case before.
it seems that the file read has the same content than when you present it to the user and not what he has changed like it was the case before.

So I think it should be fixed but it will be a little more complicated because we will have to aggregate the content of 3 files now...
