### ISSUE TITLE
Searching on hash doesn't seem to work

### ISSUE THREAD

**Issue by iNineTailedFoxx** [gitextensions/gitextensions#11377]
### Environment

- Git Extensions 4.2.0.17591
- Build bf814d4f1c6f178eacef38d592b700f9f2519dcb
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.25
- Portable: False

### Issue description

When you select a commit with the right mouse button you have the option to copy the commit hash:
![image](https://github.com/gitextensions/gitextensions/assets/151656303/644cb865-922d-4cd1-a91a-4d66e80cac5f)

When you then try to search with this hash in the search box, you don't get any results:
Paste hash in search field (with options shown)
![image](https://github.com/gitextensions/gitextensions/assets/151656303/0e9dd357-225f-486d-8c48-b1522f914aab)

No results after searching:
![image](https://github.com/gitextensions/gitextensions/assets/151656303/3cc05a46-2a62-4d96-a3cb-9c9b10867e0f)

### Steps to reproduce

- Copy hash from a random commit
- Paste hash in in filter textbox
- Option "Commit message" should be enough
- Search

### Did this work in previous version of GitExtensions?

Yes, before version 4 this works. 
In the lastest 3.xxx version this does work.
- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET Framework 4.8.9181.0

**Comment by pmiossec** [comment]
This behavior has been removed because that's not an efficient way to search a commit (which is unique).
The best way to do it is to use the "Go to commit..." feature (shortcut  `ctrl+shift+g`).

![image](https://github.com/gitextensions/gitextensions/assets/460196/b4121340-a34d-413b-8030-22aace60a8a2)

**Comment by iNineTailedFoxx** [comment]
Thanks for the reply, I did not know that this option existed.

To bad that this behavior has been removed though cause now if youn need one extra step: You now need to open this 'Go to commit' popup (with shortcut) then paste the hash, then you can search instead of directly pasting the hash and go search right away.
Another difference is in the result, with the old way the result will just show only the commit you were searching for. With the new way everything will still be visable but the selected row is the commit you searched for. Not necessarily wrong, but different.

**Comment by pmiossec** [comment]
> To bad that this behavior has been removed though cause now if youn need one extra step: You now need to open this 'Go to commit' popup (with shortcut) then paste the hash, then you can search instead of directly pasting the hash and go search right away.

On the contrary, I find it more efficient because the hash is pasted automatically from the clipboard so it's just a matter of  quickly do `ctrl+shift+g` + `Enter` and with an immediate result. Whereas, for the filter, there is no shortcut, and you have to check the filter settings or (sometimes) restart a search if the settings are not good and the search is slower, especially on bigger repo (and you have to unfilter so you pay the slowness twice).

And also you need overall less steps because you don't have to unfilter 🤣 

>With the new way everything will still be visable but the selected row is the commit you searched for.

For me it's an advantage because when you filter, sometimes you want to see the commits before or after and so you have to unfilter and in this case the filter is more painful (extra steps! 😉 ).

I think it's definitely a better experience. You will get used to it 👼
