### ISSUE TITLE
File history stop working after upgrade to version 4.2

### ISSUE THREAD

**Issue by GraySerg** [gitextensions/gitextensions#11440]
### Environment

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version: 

### Issue description

Doesn't filter changes by file, shows all changes.

### Steps to reproduce

Call File History from context menu

### Did this work in previous version of GitExtensions?

Yes 4.0

**Comment by pmiossec** [comment]
You should more explicit and maybe provide screenshots.

>Call File History from context menu

context menu from inside GE? or from File explorer?

Example of file path? White spaces on it (or other strange character)?

**Comment by GraySerg** [comment]
Doesn't matter, from every menu. No whitespace or strange character, and in version 4.0 works fine

**Comment by GraySerg** [comment]
![ScreenShot](https://github.com/gitextensions/gitextensions/assets/12149591/fc263788-7b84-47be-b763-340c9f1594d8)
For example, no changes in UserSettings.cs

**Comment by vbjay** [comment]
Press f12.  Run the file history menu. Find the git log call in the command log window and right click entry and copy details to this issue.

**Comment by snuup** [comment]
I second that file history is not working since sometime 2023. The file difference view always shows the full file for every file in the changeset. Opening the external diff tool does not work.

**Comment by snuup** [comment]
I went back versions and found that all versions 4 have broken file history. With Verison 3.5.4 it works, a completely different view opens for file history. In versions 4 the same window opens again, with all changesets shown, not filtered to those having changes of that single file. Does File History really work for anyone using versions 4+ ?

**Comment by mstv** [comment]
Which tab have you selected?

Could you clone a public repo, describe the steps and provide screenshots?

**Comment by snuup** [comment]
Expected File History as in 3.5.4:

![image](https://github.com/gitextensions/gitextensions/assets/61933552/b68fdc74-e2f5-4f21-b233-ad254e8fa04b)

we can see the differences for that single file per changeset.



File History as since version 4:

![image](https://github.com/gitextensions/gitextensions/assets/61933552/9ebcada1-681f-47a9-8abd-9e4e56af2c62)

Pretty useless since there is no comparison between previous and next version, open with external diff tool (f3) does not work.

For the screenshot I used https://github.com/siege-media/contrast-ratio but it really behaves like this in every repo.

**Comment by mstv** [comment]
Until this will be fixed by #11275, you could switch to the (preferred) alternative:

![image](https://github.com/gitextensions/gitextensions/assets/36601201/80e3a606-9bc2-4d71-b6fc-73c8a16d5a9b)

If you do not like it, describe what is missing, please!

**Comment by RussKie** [comment]
@GraySerg here you're looking at the Diff tab:
![image](https://github.com/gitextensions/gitextensions/assets/4403806/b865b03e-599e-43a9-993e-f2511de231d4)

...and here you're looking at the blame instead of the diff
![image](https://github.com/gitextensions/gitextensions/assets/4403806/39fa3d00-a89e-4249-878c-009cd2a65d4f)

**Comment by snuup** [comment]
Thank you for both replies, each of them solved it!
