### ISSUE TITLE
Git *word* coloring

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#11634]
### Environment

- vNext with #11590 (and #11628)
- Build 27a3b1e4eee462accae311e882443aeaf75e7110
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.2
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

1. Git seems to be a pretty aggressive / hyperactive in matching rather unrelated lines. It feels like character matching instead of "word coloring" as the name promises. Can this be controlled using an option?
2. Multiple lines seem to be merged into one.
3. Leading and trailing whitespace of the change gets lost.

### Steps to reproduce

1. select commit 784a672ec304c5f534d7b26a389627c63f57086e
![image](https://github.com/gitextensions/gitextensions/assets/36601201/a96fe920-d819-41f1-8e53-bbac3c764909) ![image](https://github.com/gitextensions/gitextensions/assets/36601201/a6569a87-f22a-4f60-8d78-735b02956fa3)

---

2. & 3. select commit ac6487fd05262fc38490cd18b0eabe6bfd321edc

![image](https://github.com/gitextensions/gitextensions/assets/36601201/623edaaa-2359-4ab9-9632-4b8bd99f12ac)

![image](https://github.com/gitextensions/gitextensions/assets/36601201/3d0b3114-91d6-4421-a3a8-977020bc498c)

**Comment by gerhardol** [comment]
git word diff is very useful in some situations. But it has it flaws. That is a reason I do not want to promote it "too much" with a toolbar button right now.
I spent more than a week trying to recreate the major omission: patch format. But there were too many issues when the patch format would be incorrect. The missing indentation on line 345 is an obvious error.
The documentation must describe that this is a Git limitation.
(I will start with the documentation when there are no more requests for tests.)

Git is by default setting git word diff to full words. I set the diff to be minimal, to see details in line by line diff, this where the benefit in my opinion is the best. Bigger diffs will be worse by diff.
This can be configured by the user, another default could be selected too.

GitUI\Editor\Diff\DiffHighlightService.cs
```c#
        if (string.IsNullOrEmpty(module.GetEffectiveSetting("diff.wordRegex")))
        {
            // https://git-scm.com/docs/git-diff#Documentation/git-diff.txt-diffwordRegex
            // Set to "minimal" diff unless configured.
            commandConfiguration.Add(new GitConfigItem("diff.wordRegex", "."), command);
        }
```

Maybe delta/difftastic etc is better?
Will try to look at this when the current PRs are merged.

So I suggest that this issue is closed, maybe after there are documentation and issues are directed here.

**Comment by mstv** [comment]
Thank you for the clarification.
This diff becomes clearer with:
`git config --global diff.wordRegex "[a-z0-9_]+"`

Though the git output is sub-optimal / wrong:

![image](https://github.com/gitextensions/gitextensions/assets/36601201/cdd8f810-c743-4b56-8a55-9e6b60ca0693)   ![image](https://github.com/gitextensions/gitextensions/assets/36601201/15da3f4d-272a-4360-98eb-4698207f9c8b)

**Comment by gerhardol** [comment]
The defaults could be changed. I choose to override the Git default as it shows the minimal diffs in most cases, it is a contrast to the GE diff coloring (showing the largest diff section).
