### ISSUE TITLE
Add `--tags` option on git push branches

### ISSUE THREAD

**Issue by godcong** [gitextensions/gitextensions#11974]
### Feature description

Now push branches and tags are completely separate.
This makes it necessary to do 2 operations for each push.

I would like to add an option to turn on `--tags`. This can be turned on before each push or by default.
You can upload changes to branches and new tags in a single push.

![Image](https://github.com/user-attachments/assets/43f077d9-3620-4d15-9fe2-4986aa0b408d)
![Image](https://github.com/user-attachments/assets/17a8a83a-9def-46a0-be72-d33c414f5801)

### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.45.1.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 8.0.10
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

**Comment by vbjay** [comment]
git push --tags is a separate operation to git push since pushing tags should be a conscious choice to avoid accidentally pushing the wrong one. 

So that reasoning is mirrored in the UI.

**Comment by godcong** [comment]
![Image](https://github.com/user-attachments/assets/4411dd8f-4413-49f2-81a6-2c7ed27e29ce)

Would it be possible to add an option like goland?

**Comment by RussKie** [comment]
> Now push branches and tags are completely separate. This makes it necessary to do 2 operations for each push.
> 

It's been like this forever, because essentially these are two different operations. Unlike creation of new branches, creation of new tags isn't something developers do often, so it doesn't make much sense to combine these two operations.
It sounds that your workflow could be different from what a typical developer use, but with that it doesn't make much sense to bake that into the app to cater for a niche use-case. 

That said, if you need to always push tags alongside branches (how does that work for existing tags anyway?) then you could author a script which will be run at push. See under Settings > Scripts.
