### ISSUE TITLE
"No branch is selected, cannot push" due to bracket(s) in branch name

### ISSUE THREAD

**Issue by JeremiaAu** [gitextensions/gitextensions#11997]
### Environment

**Installed**
- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.46.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 8.0.10
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.33
    Microsoft.WindowsDesktop.App 8.0.10
```

**Portable Canary Build**
- Git Extensions 5.1.0.17945-dhrirvrx
- Build 5e31f51ff2a1c9f5b725ffdda2df5264f01a3fb9 (Dirty)
- Git 2.46.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 8.0.10
- DPI 96dpi (no scaling)
- Portable: True
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.33
    Microsoft.WindowsDesktop.App 8.0.10
```

### Issue description

When trying to commit and push changes, the following error occurs:
![Image](https://github.com/user-attachments/assets/5e21edac-b93c-4efc-8f76-8b42959a863c)

It is possible to push the commit by selecting a branch in the window, that pops up after the error message.
Similar to this other issue, HEAD is preselected : https://github.com/gitextensions/gitextensions/issues/11970
The thing both of our issues have in common is, that they both contain brackets in the branch name
I also have HEAD preselected when pressing the push button.

The problem only occured after I updated to version 5 of gitextensions.
I have also tried using the Canary build, as you can see in the environment section, but the issue persists.

### Steps to reproduce

1. create a new branch named "()". "(" or ")" is also possible
2. create a empty commit for that branch (not strictly necessary)
3. try to push that new branch to remote
![Image](https://github.com/user-attachments/assets/1f6f8159-01e8-4214-bd74-40c6d120671f)

### Did this work in previous version of GitExtensions?

Yes, it works with the latest version 4:

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.46.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 6.0.33
- DPI 96dpi (no scaling)
- Portable: True
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.33
    Microsoft.WindowsDesktop.App 8.0.10
```

### Diagnostics

Command Log when using version 5.0.0.17897:

> git ls-files -z --unmerged
> git --no-optional-locks for-each-ref --format="%(objectname) %(refname)" refs/heads/ refs/remotes/
> git remote

**Comment by KevinSlocumMFin** [comment]
I'm experiencing the same issue as described here and in #11970  (I'm guessing they are the same thing).
My branch name also contains parenthesis.
The branch name is like: **(abc)/123_abcdefg**
![Image](https://github.com/user-attachments/assets/5ced385b-29a8-4000-a812-c09c411887ec)
![Image](https://github.com/user-attachments/assets/bb939f23-32d1-47f9-b40e-e39143b52aa8)

I can then select the branch from the drop down and push:
![Image](https://github.com/user-attachments/assets/bce27240-3f89-4b7c-ae4e-43611ebf3908)



In contrast, a branch named the same way (including using a folder) except with curly braces instead of parenthesis works fine: **{abc}/123_abcdefg**
This will push to the associated origin branch without prompting.

I believe this behavior for branches with parenthesis just started with the most recent update.
