### ISSUE TITLE
No colors in diffs

### ISSUE THREAD

**Issue by mscdex** [gitextensions/gitextensions#1274]
I am using GitExtensions 2.41 on Ubuntu 12.04 with Mono 2.10.8.1 (Mono JIT compiler version 2.10.8.1 (Debian 2.10.8.1-1ubuntu2.2) and I do not get colored output in at least diffs, however the +/- markers do show up in the diffs.

I have even tried changing the diff colors in the settings from the defaults to something else, but still I get the same result.

Any ideas?

**Comment by UncleVasya** [comment]
I looked at ScintillaNET's code and it uses a lot of Windows native APIs. So it has same problem as ICSharpCode.TextEdit: it is incompatible with Linux.

Therefore if we want to have color diffs on Linux we have to:
a) edit ICSharpCode.TextEdit code to be compatible with Linux;
b) edit ScintillaNET code to be compatible with Linux;

Sadly, both options are a whole lot of work.

There are some another editor components, but all of them either forks of ICSharp (like DigitalRune TextEditor) or use win32 APIs too (like Alsing SyntaxBox).

**Comment by UncleVasya** [comment]
Turns out ICSharpCode.TextEdit doesn't need a lot of changes to work on Linux:
http://community.sharpdevelop.net/forums/t/11709.aspx

Applying them gave me colorful diffs on Ubuntu:

![01](https://cloud.githubusercontent.com/assets/1286157/10247610/e8a0cf7a-6922-11e5-9a03-d91afa0b2394.PNG)


Testing stability and if is ok, will make PR.

**Comment by kobygold** [comment]
Hi UncleVasya!
I was looking for that a long time!
How can I get those diff colors as well?

Thanks,
Koby

**Comment by kobygold** [comment]
Hi understood that there is not yet official version with this fix (and many other fixes).
I understood that in order to have the latest fixes I can build the project myself, but I have no idea how to do that...
I downloaded the sources but the mono build fails...
Can anyone share the compiled project with this fix...?

**Comment by UncleVasya** [comment]
@kobygold 
Here is a version that I compiled for myself few months ago: https://github.com/UncleVasya/gitextensions/releases/tag/v2.49a.Linux.v2

Didn't work on GitExt since then :(

**Comment by kobygold** [comment]
Thanks UncleVasya!
It works perfectly!
Thank you very much!
You are my favorite uncle ;-)
