### ISSUE TITLE
Auto-detect changes to unstaged files and refresh commit dialog

### ISSUE THREAD

**Issue by mmoayyed** [gitextensions/gitextensions#1439]
Add the option to automatically detect changes to the working directory files and refresh the commit dialog.

**Comment by RussKie** [comment]
@gerhardol is this something we want to do?

**Comment by gerhardol** [comment]
I say No.
Tested this for the "Unstaged" in Browse, but found no good way to handle this.

This is for changes done outside of GE. FileSystemWatcher can be used to detect changes, but you need to filter .gitignore changes separately. Then run git-status, which is an heavy command. If you are building at the same time, the this can take a lot of resources if there is no smart limitation. When you have a status, you need to find if the status affect the display or not, if it does then preserve the context (scroll position etc), it is very annoying otherwise.

However, the Refresh button should be updated to indicate that the information may be dirty, similar to Browse. I have plan to to use GitStatusMonitor for this also in Browse, then FormCommit can follow.
