### ISSUE TITLE
Scripts not asking for confirmation even if configured to do so

### ISSUE THREAD

**Issue by lucianm** [gitextensions/gitextensions#1608]
Hi,

I configured some scripts to be visibe on the user menu bar or on the revision grid context menu, and ask for confirmation, they are not bound to any event. They don't. Are they only supposed to do so when automatically executed on some event, so is this a bug, or a feature?

Ciao, Lucian

**Comment by drauch** [comment]
This is still an issue ... are there any plans for implementing?

**Comment by Radrik5** [comment]
No. Maybe some sunny day a person who really needs this will come with a pull request.

**Comment by vahanesac** [comment]
Any updates?

**Comment by RussKie** [comment]
It appears the confirmation is only displayed for event scripts
https://github.com/gitextensions/gitextensions/blob/master/GitUI/Script/ScriptManager.cs#L57-L61

This has been like this since the beginning - https://github.com/gitextensions/gitextensions/commit/85304256426e7c385ffcad52b43978720412b341#diff-4569427765567d1f044c82f0e6c83472R43

I suppose we can apply the same behavior to non-event scripts.

**Comment by RussKie** [comment]
Do you want to give https://ci.appveyor.com/api/buildjobs/fowb6obcatvfhi3y/artifacts/GitExtensions-2.50.02.1334-Mono.zip a try to see whether the issue is fixed?

**Comment by vahanesac** [comment]
Hi,

Sorry for the delayed response. I was on a vacation. Yes, I am getting a
confirmation now.
Thanks for fixing this.

Thanks,
Chetan
