### ISSUE TITLE
Tabbed view of multiple repo's / submodules

### ISSUE THREAD

**Issue by phileo** [gitextensions/gitextensions#1734]
This is a nice to have for swapping between different repos without having to close/open new repo.
http://blog.bitbucket.org/2013/03/19/introducing-sourcetree-git-client-microsoft-windows/

But, I think it's more than just nice to have, it's almost a must have when trying to swap between different submodule views of a parent git project.

**Comment by tomalec** [comment]
Is there any chance for tabbed view to happen, or at least to make favorite/recent repos pane visible while working with one?

Currently, to work with multiple repos at a time I need to open many windows (what is very disturbing). 

In my opinion, dropdown with non-grouped recent repositories, or even worse flow to `Repository -> Close (go to Dashboard) -> Click on repo` does not fit in case if you switch repo every few mins.

**Comment by Rushor** [comment]
any news on this?

**Comment by KindDragon** [comment]
No

**Comment by vbjay** [comment]
Opening multiple windows with taskbar button grouping is what you need to
do.

**Comment by chris-kruining** [comment]
Is this still a thing? I would love some 'simple/effortless' multi-repo management tools :D

**Comment by ideaalab** [comment]
5 years after the initial request there is no work done on this?

**Comment by vbjay** [comment]
You're welcome to do the work.
https://www.lollydaskal.com/leadership/story-everybody-somebody-anybody-nobody/

**Comment by Piedone** [comment]
This could possibly be part of the now much improved left pane (also see https://github.com/gitextensions/gitextensions/issues/7048)?

The repository registry feature and the tabbed repository navigation of TortoiseHg is a good example I think, I'd love to see something similar in Git Extensions:
![image](https://user-images.githubusercontent.com/1976647/64478332-44787780-d1a7-11e9-8ad0-2a971b40a964.png)

Note that you have a repository list on the left, with the ability to put them into folders (and then subfolders even). The little arrow to the left of repository names means that those repos have subrepos, similar to submodules of git. When you open a repository it'll appear as a tab in the middle of the window. Still, you can open TortoiseHg in multiple instances (windows) as well if you prefer that.

**Comment by francoas** [comment]
I know people that moved from GitExtensions to Fork just for the possibility to see multiple repositories in tabs

**Comment by ideaalab** [comment]
> I know people that moved from GitExtensions to Fork just for the possibility to see multiple repositories in tabs

Tempting :)

**Comment by vbjay** [comment]
Duplicating controls in tabs would be a bad idea. You can open new
instances of GE by double clicking a sub module in the file tree. You can
also just right click a changed submodule in commit window and bring up a
commit window for that submodule.

**Comment by RussKie** [comment]
I use Fork on a Mac.
It is a good app, but there are many features that I miss in it. And I don't like tabs, I find them confusing. I also found Fork a  memory hog.

But everyone is different, and if some users find Fork better - I'm happy for them.

**Comment by francoas** [comment]
> I use Fork on a Mac.
> It is a good app, but there are many features that I miss in it. And I don't like tabs, I find them confusing. I also found Fork a memory hog.
> 
> But everyone is different, and if some users find Fork better - I'm happy for them.

That was not a promotion of fork. I prefer GE too. What I wanted to point out is a feature that is missing in GE and that is appreciated by others. So it’s a reason to implement it.

**Comment by Piedone** [comment]
Would anybody interested in contributing this if we sponsor it? We at [Lombiq](https://lombiq.com/) started to use Git Extensions a lot more now that we move everything over from Bitbucket/hg to GitHub/git and would love to see this feature (along the lines of what TortoiseHg Workbench does as I've mentioned above).

We're a .NET shop so we could do it too I guess but I don't think we'd be able to find the time in the foreseeable future.

**Comment by gerhardol** [comment]
Tabbing is supposedly a little difficult with WinForms.
There are ideas to move to WPF or something like Avalonia (also for multiplatform), see #6239 #4972 
So it may not be simple

A very partial lightweight alternative is to improve the Windows taskbar functionality. The behavior is a little broken in 3.3, fixed in #7941.

**Comment by RussKie** [comment]
(I'm responding personally and speaking just for myself here.)

@Piedone thank you for using the app, and for the offer. 

I'm not sure what you're willing to fund is feasible without a significant effort. To sponsor this work you'd be looking at sponsoring months of full-time dev work of at least one senior level engineer. So this could be prohibitively expensive depending on a location of the engineer.

There have been architectural decisions (or lack of) in the past that led to a number of hard coupling. To undo them it would require to re-arch the core logic. It would involve breaking up `GitModule` and make it injectable, as well as separate the UI layer from the DAL.
Whilst it may not be a total re-write, it would be a ground-breaking change...

If these changes are not done with caution, they could easily break the app, and cause pain to many users. So these changes are either need to be done by someone from the core team, or by someone actively working with the core team. And the core team will need to have sufficient bandwidth to work with that developer as well. (This actually is a big one. We're all volunteers here, and everyone donates as much time as they can).

I think it is possible to reach the target state gradually by making smaller changes.
You and/or your engineers are welcome to get involved with the project, study the code we have, and start suggestions how it can be changed and improved for us to get to the desired target state. Obviously pull-requests are very welcome.

Personally this specific feature is not on my radar, I used other git UI clients (e.g. Fork) and found myself lost with multiple tabs, and preferred to have multiple instances of the app, especially working in a multi-monitor setup. Obviously YMMV, but it is worth questioning whether multi-tab experience is really needed.

**Comment by Piedone** [comment]
I see, that's quite unfortunate.

**Comment by Piedone** [comment]
Thanks for the explanation @RussKie. How about we simplify the approach and split it into two like following, would this be any better?

### Add a repository registry control

Optionally visible e.g. on the left sidebar where I'd prefer it (another option would be under the recent repo list when launching the app).

Would do the same as in TortoiseHg Workbench: it's a quick launch list for your repositories so you can find them easily even if a) you haven't used them in a while (as opposed to what the recent repository list currently does) and b) the logical repository structure is not necessarily the same as the folder structure on the file system (so just browsing in Explorer or else is slower).

Even without tabs this would allow you to quickly open repos and alternate between them.

E.g. I have repos for several projects spread across multiple drives, some of them on a slower with more storage, some of them on a faster one with less storage. I can keep all repos I need to work on in the next year in this registry as it'll still be not too long but most repos (due to using, then discarding a lot of temporary ones for example) would simply roll out the recent repositories list.

### Wrap the whole UI into tabs

I have no idea whether this would be less difficult in the current technical situation, just throwing the idea in here.

In this case, you'd have tabs at the top of the window (think Chrome tabs in the window title bar) and the whole existing UI would be duplicated in each tab. I'd guess ideally this can be done in a way that doesn't need a complete UI rewrite (even going as far as having a separate launcher exe for this UI that would host multiple current GE processes but this is probably hackish).

This is only really good if you have some kind of repository registry, so you can open repos without launching a new instance of the app and having to browse for the repo you want to open.


So, brainstorming here. I've hijacked the tabbed view topic a bit though. I'd actually consider a repo registry more important as it makes finding repos a lot quicker (I used this in TortoiseHg all the time). This would possibly also make tabs unnecessary since you're not really looking at two repos at the same time anyway, and now you'd have a quick way to switch between them.

**Comment by Piedone** [comment]
Wait, now I've found the Favorite Repositories feature :D. This just might be what I'm looking for but I didn't notice it yet. Way to RTFM I guess.

**Comment by gerhardol** [comment]
> Optionally visible e.g. on the left sidebar where I'd prefer it (another option would be under the recent repo list when launching the app).

See the "Configure this menu"
![image](https://user-images.githubusercontent.com/6248932/79124682-260dd680-7d9d-11ea-9708-c875d1d713f6.png)

![image](https://user-images.githubusercontent.com/6248932/79124734-43db3b80-7d9d-11ea-81ea-76da5ac4a6e8.png)

**Comment by Piedone** [comment]
Yeah, so I completely missed the favorite repos feature. I knew about the recent repo list configuration but that didn't quite fix my problem.

So I guess there is nothing to do on the repo registry front, thank you!

**Comment by RussKie** [comment]
You can also group repos in categories in the dashboard with the right click.

Closing as tabs are unattainable, but the desired can be achieved through the use of the existing functionality.

**Comment by TadGhostal66** [comment]
It's been a while since doing WinForms, but I used to do this for tabs
1.  Create a new frame or any container control
2. Cut controls from window, paste into container control
3. Put the tab control on the form, then wire up setting the moving the container control's parent to the current active tab every time a tab is clicked.

This way you are reusing the same controls.  Of course, on that same tab event, you need to update any control values.  If you make the tab's repo a property of the tab itself, you can just make all the controls act on the parent's (container control) parent (tab itself) repo - or something similar

If I didn't have to work for a living I might attempt it
