### ISSUE TITLE
Add "Remove Shell Extensions" in Settings Menu

### ISSUE THREAD

**Issue by meilon** [gitextensions/gitextensions#1821]
I really like GitExtensions and I use it at work, too. But since 2.44 the Shell Extensions seem to have changed and when I right click on a network share with a bigger latency it takes some time before the context menu appears.

I unregistered the shell extensions by hand and the context menu lag has gone.

Could you please add a button to manually enable and disable the Shell Extension from within the settings menu? I only code very rarely and therefore I need the Shell Extensions enabled only when I'm in a coding session.

For those who don't know how to do this manually (do this in an elevated cmd):

    cd c:\Program Files (x86)\GitExtensions or where you installed GitExtensions
    regsvr32 /u GitExtensionsShellEx32.dll
    regsvr32 /u GitExtensionsShellEx64.dll if you have 64bit Windows

**Comment by dylanh724** [comment]
"Please just uncheck it in installer" so instead of adding a simple add/remove feature, you want us to reinstall the entire thing? I can surely speak for most people by saying that upon installing, it sounded like a good idea at the time ... after seeing it take up 4 slots in my context menu, it's really not.

**Comment by ghanique** [comment]
Of all the features that could be developed a feature for making it simple
to remove the shell extensions for people that change their mind to me
sounds like the least important one, for one because there are plenty of
workarounds available. A few come to mind that might work (I did not test
them and take no responsibility if you do you're responsible for making
backups, etc):
* Remove the key
HKEY_CLASSES_ROOT\*\shellex\ContextMenuHandlers\GitExtensions2
* Unregister some dll (regsvr32)
* Use a tool like http://www.nirsoft.net/utils/shexview.html

Nevertheless, if you think most people would love being able to add or
remove the shell extensions from the settings menu, by all means implement
that feature yourself and create a pull request! That's one of the fun
things of an open source project :-)

**Comment by dylanh724** [comment]
The entire reason you had to say "I did not test them and take no responsibility, etc" is good enough reason to add it as a feature since it's simple enough. It's one of those features that's a given and should already be there to begin with. There's an option to change my default shell, which can be done in a similar method, so why not this?

If I have time, I will change it myself, but to the familiar it would take seconds rather than me who would have to get used to the code before adding it. /shrug

**Comment by JerryGoyal** [comment]
for latest version use this to remove:
cd C:\Program Files (x86)\Git\git-cheetah
regsvr32 /u git_shell_ext64.dll

**Comment by evan-king** [comment]
For the shell extensions to be a usable feature, we need convenient GUI access to 3 settings for the entries: enabled, disabled, OR placed in a submenu.  Controlling them all as a group and/or allowing the submenu for all or none only -  instead of offering the full range of choices per entry -  is acceptable, but sloppy.

Failing to provide the UI to apply any settings at all isn't merely sloppy, it's incomplete.

**Comment by heroselohim** [comment]
Yes, It worked on Windows 8, lastest Git. The DLLs were inside Program Files (x86)\Git\git-cheetah

Right click is faster now :D :+1:

**Comment by KindDragon** [comment]
@heroselohim git-cheetah not GitExt shell extension.

**Comment by estufa8** [comment]
looks like registering the dll again with regsvr32 git_shell_ext[64].dll (without /u) leaves it well. Now it opens fast and has Git Items.

**Comment by linquize** [comment]
It might be useful if there is an option not to show GitExt menu on network drive.

**Comment by KindDragon** [comment]
@estufa8 it is git-cheetah dll. GitExtensions use GitExtensionsShellEx32.dll and GitExtensionsShellEx64.dll

**Comment by fievelmousekewitz** [comment]
Thanks for this! Right clicking in a network share was taking 15-20 seconds with the Extensions enabled.

**Comment by distinctdan** [comment]
So, was the plan to ever add an option to disable the context menu extension? I'm on the most recent version of git extensions, but my context menu freezes explorer for a solid minute when I right click. I'd rather not go messing around with dll's if at all possible.

**Comment by distinctdan** [comment]
I ended up downloading Auto Runs to disable my context menu items

**Comment by dfkt** [comment]
This drove me insane as well. Nothing worked for me on Win8.1, except removing it from the registry:
```

Windows Registry Editor Version 5.00

[-HKEY_CLASSES_ROOT\Directory\background\shell\git_gui]

[-HKEY_CLASSES_ROOT\Directory\background\shell\git_shell]

[-HKEY_CLASSES_ROOT\Directory\Shell\git_gui]

[-HKEY_CLASSES_ROOT\Directory\Shell\git_shell]

[-HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Directory\background\shell\git_gui]

[-HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Directory\background\shell\git_shell]

[-HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Directory\shell\git_gui]

[-HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Directory\shell\git_shell]
```

**Comment by KindDragon** [comment]
Just don't install it

**Comment by KindDragon** [comment]
@dfkt It's not our shell extensions

**Comment by reach4thelasers** [comment]
This is really annoying.  The benefit that comes from using Git Extension is cancelled-out by the fact that around 200 times per day I need to wait 10 seconds for my right-click menu to appear.  Most of the time I don't event want to use it.  Making a new folder now takes 10 seconds etc.  Sort this out!  for now its being uninstalled.

**Comment by dylanh724** [comment]
"Just don't install it in Git for Windows" <closed>
**Way to represent the community.** Agree w/ @reach4thelasers .

**Comment by KindDragon** [comment]
I'm sorry if it looked rough to you, but this is Git Extensions issue tracker not "Git for Windows".
We have shell extensions too, but you report Git shell extension issue to our issue tracker. I closed this issue only because of this.

If you have issues with "Git for Windows" please report to their issue tracker https://github.com/git-for-windows/git/issues

**Comment by janfrederik** [comment]
I don't see why this issue is closed. The issue is still there and annoying.
Some people commenting here were confused and are actually users of "Git for Windows". However, the issue was brought up for GitExtensions and still applies.
So please re-open.

**Comment by mstv** [comment]
This discussion has become too long and confusing.
Could you open a new issue, please?

**Comment by janfrederik** [comment]
> This discussion has become too long and confusing.
> Could you open a new issue, please?

Done: #7982
