### ISSUE TITLE
Create Bundles

### ISSUE THREAD

**Issue by yoyodyn** [gitextensions/gitextensions#1826]
Would like to be able to create and import from bundles using the GUI.

**Comment by GintasS** [comment]
Abandoning this because of age.

**Comment by IMSMarian** [comment]
Still an important missing feature to date in my opinion.

> * User selects 2 commits.  Context menu has create bundle option, which creates bundle between the two commits.
> * User selects 1 commit.  Context menu again but the create bundle creates a bundle between current branch HEAD and the selected commit.

I especially like these implementation ideas.

**Comment by pmiossec** [comment]
> Still an important missing feature to date in my opinion.

Personally, I have never encountered someone using it and I used it only once.
So I think that should be implemented by someone using and understanding it well ( you?!? ) because looking at the documentation ( https://git-scm.com/docs/git-bundle#_specifying_references ) and testing it quickly, it's not that trivial and for me, the 2 use cases below are not working...
I don't think in the GE team, there is someone that want/need to tackle that. So contribution is really welcome.

> 
> > * User selects 2 commits.  Context menu has create bundle option, which creates bundle between the two commits.
> > * User selects 1 commit.  Context menu again but the create bundle creates a bundle between current branch HEAD and the selected commit.
> 
> I especially like these implementation ideas.

The tricky rule is "A revision name or a range whose right-hand-side cannot be resolved to a reference is not accepted"

It's the kind of feature that is tricky to implement if you want to provide the whole possibilities provided by the feature.
I don't think it will be easy to bundle more than one branch (with range support).

Due to the tricky rule, IMHO, the "easy" to support cases (from revision grid selection and contextual menu) will be more:
* if current selected commit is tip of currently checked out branch, bundle the whole checked out branch
* otherwise, bundle the commits range from selected commit to currently checked out branch (after check that the selected commit belong to the branch)

More complex use cases would require a full featured "Bundle form" (that could be pre-filled from revision grid selections) but depending on the bundle feature options we want to support (range, multiple branches, `--all` history, `--branches`, `--tags`,... ) it could be rather complex to do...

As a workaround, depending on your use case, maybe you could use "Scripts" feature:

![image](https://github.com/gitextensions/gitextensions/assets/460196/682db554-dea5-47fb-bcb1-6ff2293d41f8)

with:

* whole current branch bundle: `bundle create {UserInput} {cBranch}`
* commits range current branch bundle: `bundle create {UserInput} {sHash}..{cBranch}`

**Comment by IMSMarian** [comment]
I wish I was the right one to implement it... but sadly I'm not.
Maybe it is indeed a rare case. I use it on a regular basis though, since many of the computers I only access remotely (-> no thumb drive possible) and they have no direct internet access (-> no origin connection possible).
Therefore creating a simple bundle, transfering it to the computer and fetching from the bundle is the go to method for me.

Since bundles can be added as remote, the only missing functionality is creating one.
I would have expected such a button to be right next to the other commands:
![image](https://github.com/gitextensions/gitextensions/assets/143480657/921a986e-ddfc-4262-a1d0-8f187aa74581)

While git having numerous options for creating bundles, I think that the main functionality would be as follows:
-User clicks "Create Bundle"
-User is either asked for branch or probably even easier: current branch is assumed to be the desired one for the bundle
-User is asked how many commits shall be included in the bundle
-"bundle" file is saved to repository folder as if the user used the command "bundle create bundle -{AmountCommits} {CurrentBranch}"

I haven't messed with scripts yet, that might be a very good workaround though, thanks a lot!
Is there a possibility to have a pop up when using a script explicitely asking for a special input like the "amount of commits", which shall be included? And is there a keyword for the current branch (like cBranch for choosing one)?

**Comment by RussKie** [comment]
Scripts is probably your only option.

**Comment by pmiossec** [comment]
> Edit: I just read cBranch is supposed to select the current branch. Why am I being asked to select a branch when executing this script then?

You are talking about the scripts I provided?
That's because {UserInput} is used so that the user could select the bundle file name.

But you could hard code it with `bundle create my.bundle {sHash}..{cBranch}`
or even use the branch name as the target file like : `bundle create {cBranch}.bundle {sHash}..{cBranch}`

>User is asked how many commits shall be included in the bundle
I think selecting a commit is more user friendly but indeed, more error-prone.
But if you still want to ask the number of commits to take, it will be something like:
`bundle create {cBranch}.bundle {cBranch}~{UserInput}..{cBranch}`

**Comment by IMSMarian** [comment]
I was referring to a pop up when using {cBranch}, but noticed, that it only shows, when another branch is at the same commit as the current one:

![image](https://github.com/gitextensions/gitextensions/assets/143480657/839fddf7-2d75-44ad-bb35-399a7fb28ff3)

That confused me, since I was expecting cBranch to refer to the currently checked out branch without being asked to select another branch, just because it is at the same commit. Not sure if that is expected behavior.

Thanks again for the scripts though! That implements exactly what I was looking for.

**Comment by pmiossec** [comment]
>That confused me, since I was expecting cBranch to refer to the currently checked out branch without being asked to select another branch, just because it is at the same commit. Not sure if that is expected behavior.

I was not expecting the current behavior also (but I checked the source code and it is the expected behavior).
And I find the documentation a little misleading on that also. I will do a PR to discuss about and improve it (but don't expect it for soon in as it won't land in the release to come...)

As a consequence of this behavior, maybe you want to replace {cBranch} by {cLocalBranch} (to exclude remotes)

**Comment by maraf** [comment]
@IMSMarian I have created a plugin years ago https://github.com/maraf/GitExtensions.BundleBackuper
