### ISSUE TITLE
BeyondCompare command line arguments are incorrect

### ISSUE THREAD

**Issue by pvginkel** [gitextensions/gitextensions#1844]
The default command line arguments for BeyondCompare are incorrect. 3-way merge works OK, but with 2-way merge BeyondCompare thinks you're doing a 3-way merge with the merge output being the base.

The correct command line argument is:

```
"C:/Program Files (x86)/Beyond Compare 3/bcomp.exe" "$LOCAL" "$REMOTE" "$BASE" "/mergeoutput=$MERGED"
```

**Comment by phillijw** [comment]
BC3 works fine if $BASE is an empty string. The problem is that we are prompted for 2-way merge and I have no idea what it's choosing to use at that point. It probably shouldn't use the diff settings since that would require an output file. Here are the two scenarios I know of and this should work with BC3 I believe:

- 2-way merge: `"bcomp.exe" "C:\notes\test.txt.LOCAL" "C:\notes\test.txt.REMOTE" "" "C:\notes\test.txt"`
- 3-way merge: `"bcomp.exe" "C:\notes\test.txt.LOCAL" "C:\notes\test.txt.REMOTE" "C:\notes\test.txt.BASE" "C:\notes\test.txt"`
