### ISSUE TITLE
Commit dialog, remember "show untracked" option

### ISSUE THREAD

**Issue by cryham** [gitextensions/gitextensions#1872]
The option "Show untracked files", in commit dialog, under "Working dir changes"

![untracked](https://f.cloud.github.com/assets/720641/566916/d5d6ae92-c6a3-11e2-8ef5-b94cc87cd610.png)

is not remembered after window close.

I changed in code to have it always disabled, but proper way would be to save the option somewhere and mark the checkbox based on it.

I usually have many untracked files, and don't want them to be commited by accident nor do I want to uncheck this every time.

**Comment by mlutescu** [comment]
This feature would be wonderful.  It's really annoying to have to disable 'show untracked files' at each commit.

**Comment by Radrik5** [comment]
Why don't you want to add them to gitignore?

**Comment by aperomsik** [comment]
Too much hassle. In some projects, files to ignore can be transient and numerous. Obviously somebody added support for showuntrackedfiles to .git/config for a reason.

**Comment by Radrik5** [comment]
The reason is specified in the `git config` help:
> status.showUntrackedFiles
By default, git-status(1) and git-commit(1) show files which are not currently tracked by Git. Directories which contain only untracked files, are shown with the directory name only. **Showing untracked files means that Git needs to lstat() all the files in the whole repository, which might be slow on some systems. So, this variable controls how the commands displays the untracked files.** Possible values are:
no - Show no untracked files.
normal - Show untracked files and directories.
all - Show also individual files in untracked directories.

**Comment by cryham** [comment]
LoL. Soon will be 3 years since I issued this (luckily I don't use gitextensions).
Isn't this just 5 lines of code to add it? Or what's the reason here..

**Comment by mlutescu** [comment]
Damn.  In fact just one line of code would make this.

**Comment by asmwarrior** [comment]
What's the status of this bug, I see someone has fixes, but why are they not arrived in the official masters. Every time I open the dialog, I need to uncheck the "Show unchecked files", that's really annoying. Are there any workarounds? Thanks.

**Comment by mlutescu** [comment]
I saw my fix for this that I did 1 year ago was merged yestarday.   I wonder if it still works.   Let's see if it will enter in the next release

**Comment by asmwarrior** [comment]
@mlutescu 
I just download the [11.7 MB GitExtensions-2.50.02-Mono.zip](https://github.com/gitextensions/gitextensions/releases/download/v2.50.02/GitExtensions-2.50.02-Mono.zip), but I see this feature is still not implemented, but when I see the #3151 , you contribution is already merged last year. 

So, my question is: can you guys confirm this feature is enabled? Thanks.

**Comment by asmwarrior** [comment]
Oh, my god, it looks like the option are different between the "git gui" and the "gitextensions".
With gitextensions, I have to use such setting in the config file.

```
[status]
	showuntrackedfiles = no
```
Then, it works fine.

**Comment by asmwarrior** [comment]
So, I think this issue can be closed as fixed.

**Comment by RussKie** [comment]
The fact that it requires a manual config editing means that the request hasn't been fulfilled.

**Comment by RussKie** [comment]
The fact that it requires a manual config editing means that the request hasn't been fulfilled.
But the fact that the request after so many years is still open means that it isn't such a big issue...

**Comment by asmwarrior** [comment]
Yes, the "Git Gui" tool can automatically change the config file, but I was using the command `git config status.showuntrackedfiles no` to change this option.

**Comment by RussKie** [comment]
It looks like the fix, which was added to address the issue, was not
technically correct since it used a different from git gui setting
(inconsistency), nor it handled the setting the value (incomplete).

Going forward, I think, we should read both `status.showuntrackedfiles` and
`gui.displayuntracked` to determine the current setting, and set `gui.
displayuntracked` upon user selection.
Pull requests are welcome

**Comment by mlutescu** [comment]
My fix does not persist the settings chosen from UI (as asked by the initial requester)  but provides a way to set up the defaults that works best for you.   Now you have to  just run `git config status.showUntrackedFiles no` in a project, or `git config --global status.showUntrackedFiles no`  to change the default globally.

While change setting is done by use of CLI and not directly from GUI,  I think it solves the primary problem that motivated the initial requester:  that in projects with many untracked files, you have to disable showing them each time you make a commit.   

It didn't occur to me that we should strive for consistency with _git gui._   What value would bring this compatibility?   I expect nobody to use both _git gui_ and _gitextensions_ (as the second is so much better then the first).  But I see value in keeping compatibility with  _git status_ CLI tool, which I see as more fundamental and I suspect is anyway familiar to most _git_ users.  But I see no good reason to duplicate setting for _git_ CLI with one specific to the _gui_

As for persisting the value in '.git/config',  I think this would need a deeper change that might appear at first.  In my opinion, this would call for a generic mechanism in _gitextension_ to manage and persist options in '.git/config', and I would strive to use it for _all_  options (by example, use it also for 'show ignored files').  Because it wouldn't be nice to have persistence for one option and not for another, would it?  

Such mechanism would need more thinking:  there is allways the question, in which config to save?  The global one, or per project?   What properties to use: the ones of _git_, the ones of _git gui_, or some only for _gitextensions_?   So in my opinion, this should be decided by the primary drivers of the project.   I didn't want to take such decisions by myself, but needed a fast workaround for what was annoying me; which the fix provided.

**Comment by GintasS** [comment]
Abandoning this because of age, also the PR was closed.
