### ISSUE TITLE
Support Meld as a mergetool

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#1975]
It's not immediately clear if Meld is supported as a merge tool. I really like Meld!

Searching doesn't turn up any documentation on this. I've opened a [question on Stack Overflow](http://stackoverflow.com/q/17743085/24874) as well.

**Comment by twhitmorenz** [comment]
'git mergetool' with 'meld' selected invokes Meld with parameters:  
  /path/to/Meld.exe  $BASE $MERGED $REMOTE

aka. Mergetool command = </path/to/Meld.exe> \"$BASE\" \"$MERGED\" \"$REMOTE\"

I assume since Git invokes it this way (no use of $LOCAL as distinct from $MERGED) this is the best way Meld can currently be used. I have tested these parameters both in Git command-line and in GitExtensions and can confirm they work.

(I have an interest in having this working, since had been struggling to find the correct config for a week -- with other configs, merge results were being saved to $LOCAL but not saved to the actual repository file.)

Cheers guys!
