### ISSUE TITLE
Missing commit button

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#2066]
After change of repository the commit button disappeared. It happens randomly.
![2013-10-10 21_54_52-gitextensions libgit2sharp - git extensions -_ debug _-](https://f.cloud.github.com/assets/1003909/1317942/1413b720-32b2-11e3-8b13-77b26246fa86.png)

**Comment by RussKie** [comment]
Is this still a problem?

**Comment by TamaHobbit** [comment]
I installed GitExtensions 2.51.01 and the button was back, but without the number of modified files in brackets, so the button was called "Commit" instead of "Commit (2)". This behaviour persists after installing GitExtensionsMod 2.52 again. 

It's unclear what's going on here; is there a way for me to test if lg2s threw an exception on my repository?
