### ISSUE TITLE
Revision graph can get "curly"

### ISSUE THREAD

**Issue by kasal** [gitextensions/gitextensions#2214]
The revision graph can get too "curly" because the algorithm tries to save space (presses everything to the left) too eagerly, like the light blue path below.

![curly_gitext](https://f.cloud.github.com/assets/1481596/1939391/7939d91c-7f61-11e3-9615-6ad21e41c4a2.png)

**Comment by drewnoakes** [comment]
This still happens, though it doesn't look as bas since the curves became smoother:

![image](https://user-images.githubusercontent.com/350947/40946830-887e4db6-6857-11e8-8e77-bd2459459e65.png)

I've wondered about trying to straighten them out. Not familiar enough with the layout algorithm to know that's involved.
