### ISSUE TITLE
amend should show files of amended commit

### ISSUE THREAD

**Issue by AlexanderJ** [gitextensions/gitextensions#2260]
Just like git gui, git extensions should not only show the commit message of the amended commit, but also the affected files (patches). Right now I can only add additional changes when amending, but cannot unstage anything from the last commit. I always have to use git gui for that.

**Comment by 011V32** [comment]
Any updates for this feature?

**Comment by jimbo1qaz** [comment]
Any progress on this issue? This is my favorite feature of Git Cola.

**Comment by gerhardol** [comment]
The feature is up for grabs. If someone is interested assign yourself by writing a comment in the issue.

**Comment by zlolik** [comment]
Old discussion at #565

**Comment by RussKie** [comment]
A number of other git UI clients have the feature.
If anyone is willing to offer an algorithm which will help to develop the feature, it will certainly speed up the process here.

**Comment by Cyrillev91** [comment]
Hi,
here is an algorithm:
when Amend is checked:
Load and display the last commit (message and modified files)

When commit buton is activated, run git cmd:
 $ git reset --soft HEAD^
 $ git add file / git restore --staged file / ...
 $ git commit -m "new message"

**Comment by johndog** [comment]
This issue can encompass/replace #565 if the solution addresses both the file list and the description.  The amend description is currently already supported, but only if the description field is currently blank.  If it isn't blank it's currently a bad experience.

**Comment by johndog** [comment]
> Hi,
> here is an algorithm:
> when Amend is checked:
> Load and display the last commit (message and modified files)
> See also _load_last_commit_ function here (error_popup) : https://github.com/prati0100/git-gui/blob/master/lib/commit.tcl
> 
> When commit buton is activated, run git cmd:
> $ git reset --soft HEAD^
> $ git add file / git restore --staged file / ...
> $ git commit -m "new message"

If you add a "save current description text in history" as the first step when 'amend' is checked, then we'll have something to restore if the user _unchecks_ amend again without clicking commit.

More generally, does this algorithm actually solve the problem?  In order to make staging work, don't you have to "git reset --soft HEAD^" _before_ you click commit?  So that you can move things in and out of the index...  But that means a more comprehensive step to preserve initial state, so that it can be restored when the user unchecks amend again...  in fact, the state hast to be _merged_ with the former state in case the user made edits.  Either that, or the file list and index have to be simulated, which would likely require a completely alternate implementation of the UI.

**Comment by pmiossec** [comment]
> Either that, or the file list and index have to be simulated, which would likely require a completely alternate implementation of the UI.

For me that algorithm could not be used and indeed, we should not touch the history until the commit is created.
So yes, the git command run should be different and display implementation reworked that makes the work more difficult...

**Comment by gerhardol** [comment]
See also #565, some suggestions there too.

**Comment by johndog** [comment]
Actually, I suppose using a soft reset wouldn't require too scaffolding much since it just moves HEAD (and doesn't move or simulate an index), so doing it would be quite elegant.  However, moving HEAD even temporarily for this scenario is probably disqualifying.  

I think then we just need to somehow _simulate_ moving HEAD.  This may actually be as simple as changing the index file/hunk presentation from "git diff --cached" to "git diff --cached HEAD~1", whenever the 'amend' box is checked.  It would also have to switch from using "git status --porcelain" to "git diff --cached --name-only HEAD~1" to populate the listing.  That might be all that's needed.  Since hunks will be applied to the index either way for staging/unstaging, that logic likely needn't change.

So then it becomes...

**Non-intrusive algorithm**

When user checks **amend**:

- stash the current commit message in progress
- populate the commit message box with HEAD's commit message
- enable "amendMode", indicating that the index presentation should use `git diff --cached HEAD~1 [--name-only]` commands instead of the normal commands

When user UNchecks **amend**:

- restore the commit message box with the stashed message in progress
- clear "amendMode"

When user clicks Commit with amend checked:
- commit with --amend
- Restore former message in progress

**Comment by gerhardol** [comment]
I rather have a button with "Reset current HEAD" that is enabled when checking amend to avoid messing around with messages and contents. Sometimes I want to see what I am amending, sometimes the complete commit.

**Comment by Cyrillev91** [comment]
Hi,
Ok I understand that moving HEAD even temporarily for this scenario is disqualifying. Indeed it is not a good idea

**New algorithm:**

When user checks **amend**:
   - stash the current commit message in progress
   - populate the commit message box with HEAD's commit message
   - populate the staged box with HEAD's staged

When user **change stage area**:
   - add new file or add modified file : run `git add <file>` + display file in _staged box_
   - remove file or remove modified file : run `git restore --source=HEAD^ --staged <file>` + remove file in _staged box_ and display it in _unstaged box_

When user clicks **Commit with amend checked**:
   - run : `git commit --amend -m "<message>`
   - uncheck amend
   - reset commit message box 

  
note : If user UNchecks **amend** (before clicks Commit with amend checked)
   - populate  the _staged box_ and _unstaged box_ like `git status` command

**Comment by RussKie** [comment]
There are two distinct points in the discussion:
1. Dealing with the message, and
2. Showing the content of amended commit.

The first point is orthogonal to the OP, and should be discussed separately. We should stay on topic, which is the second point.

As a user I'd like to see the content I'm amending. I've seen this functionality implemented in Fork app. It was awhile since I used it last time, so I'm vague on behavioural specifics.

First of all we need to document all scenarios that are possible during amend, and work through all of them one-by-one. This way we won't miss anything or regress in some important scenario.

Thinking out loud here. 
1. Amend is always the previous commit, so when the checkbox is ticked we can load the content of HEAD~1 in to the staged area. 
2. If the checkbox is unchecked - refresh the view, and show only the current status.

Both 1 and 2 should be easy.

Other scenarios become trickier, how do we handle the following scenarios?

  3. A use decides to unstage a file/hunk from the "amended" set. Then unchecks "amend" button.
  4. A use stages a hunk to a file "being amended".  Then unchecks "amend" button.

**Comment by johndog** [comment]
> There are two distinct points in the discussion:
> 
> 1. Dealing with the message, and
> 2. Showing the content of amended commit.
> 
> The first point is orthogonal to the OP, and should be discussed separately. We should stay on topic, which is the second point.

I disagree, the topic has changed.  Once #565 was closed in favor this one, this issue is now carrying the torch for both points.  If we can either reopen #565, or we can use this (#2260) to represent holistic handling of the amend scenario.

**Comment by nyanpasu64** [comment]
Git Cola handles checking the Amend checkbox as if you had `git reset --soft HEAD~` for the duration of the checkbox. It used to have bugs when staging, unstaging, and reverting changes, but to my knowledge they've been fixed by now. It's a useful feature, and the experience is intuitive most of the time...

> A use decides to unstage a file/hunk from the "amended" set. Then unchecks "amend" button.

Unfortunately Cola's behavior is anything but intuitive when I check Amend, then unstage changes committed to HEAD. This actually stages a partial revert of HEAD, and adds unstaged changes corresponding to part of HEAD. This becomes visible when you uncheck Amend.

With Git Extensions's current staging UI, it's impossible to unstage changes already committed in HEAD, which reduces the potential for confusion but makes the tool less useful. I still think Cola's behavior is useful, and I don't know if it could be changed while preserving the tool's capabilities. Maybe I'm biased because I've already adopted "unstaging HEAD" into my workflow, and it's actually a net negative for user experience. I don't know.

> A use stages a hunk to a file "being amended". Then unchecks "amend" button.

I don't think this is confusing. When "amend" is checked, the diff shows `HEAD~..index`, and when you uncheck "amend", it instead shows `HEAD..index`, showing staged changes but not changes from the previous commit.

**Comment by RussKie** [comment]
Is anyone willing to do a PoC of the amend behaviour?

**Comment by mstv** [comment]
Should I statically reserve space for the button?

![grafik](https://user-images.githubusercontent.com/36601201/206566405-ef032aa9-f791-4071-992c-23ea89e72f07.png)

Or would you accept a standard FlowLayout?

![Amend - Reset soft](https://user-images.githubusercontent.com/36601201/206568719-b3151107-5088-42be-9aee-9b9321a793f5.gif)

Is the button label `Reset soft` clear enough? Add a tooltip?
Color the button background red?

**Comment by mstv** [comment]
I have just extended the current v4:

![grafik](https://user-images.githubusercontent.com/36601201/206573074-6343411e-04df-4a54-8275-f1dfd4bc02d3.png)

Indenting the dependent controls is worth consideration.

Checking the `Amend commit` checkbox is mandatory - at least its handling of the commit message.
I think in combination with the checkbox, a confirmation popup does not need to be added.

**Comment by mstv** [comment]
With indent and red backcolor:

![grafik](https://user-images.githubusercontent.com/36601201/206920683-d8073dfe-bdea-4fc1-a9e8-128b3d4880f7.png)

@RussKie, @gerhardol and @interesteds, open decisions (refer to previous comments):

/1/ Should the `Amend commit` checkbox need to be ticked before `Reset soft` is enabled?

/2a/ Is the wording `Reset soft` clear enough?
/2b/ Add tooltip?

/3a/ Should I statically reserve space for the button as requested by @RussKie in the PR for "Reset author" (https://github.com/gitextensions/gitextensions/pull/9778#discussion_r776879958)?
        Perhaps always visible but disabled?
/3b/ Or would you accept a standard FlowLayout?

**Comment by gerhardol** [comment]
Yes to all including 3a, but 3b is OK for me.

Indenting improves understanding.

There is an acknowledgable confirmation for amend, I believe there should be one here too. Amend can be reverted by not committing, this is 'final' (in this form).

**Comment by RussKie** [comment]
I do find the panel with the buttons getting very busy, and that is affecting the user experience. I haven't given much consideration to the UI layout and positioning of the dialog's elements. Yet. Let's get a "good enough" version out, and then iterate over the UI (similar to https://github.com/gitextensions/gitextensions/pull/10233).

> /2a/ Is the wording `Reset soft` clear enough?
> /2b/ Add tooltip?

I suggest following the branch reset dialog in terms of wording and colouring. A tooltip should be sufficient in my view for the longer text
![image](https://user-images.githubusercontent.com/4403806/206932387-1af1d015-d42f-4f57-88f9-dbb2cbc0dad0.png)

**Comment by RussKie** [comment]
> With indent and red backcolor:
> 
> ![grafik](https://user-images.githubusercontent.com/36601201/206920683-d8073dfe-bdea-4fc1-a9e8-128b3d4880f7.png)

Why is "commit and push" button red? The red colour is used to indicate dangerous (i.e., destructive) operations.

**Comment by gerhardol** [comment]
> > With indent and red backcolor:

> Why is "commit and push" button red? The red colour is used to indicate dangerous (i.e., destructive) operations.

![image](https://user-images.githubusercontent.com/6248932/206933558-727ddde0-58c6-4770-a66f-dac1b5f5f6dd.png)

**Comment by RussKie** [comment]
> > Why is "commit and push" button red? The red colour is used to indicate dangerous (i.e., destructive) operations.
> 
> ![image](https://user-images.githubusercontent.com/6248932/206933558-727ddde0-58c6-4770-a66f-dac1b5f5f6dd.png)

Right, thank you. This isn't obvious though for an average Joe developer (i.e., me :)). How would you feel if we were to show a different text on the button - e.g., "Commit & force push". This way it's obvious and the red colour could be justified then.

At the same time, isn't it the current behaviour to push and, if the push is rejected, to show a dialog with push options? Are we not using the same behaviour here?

**Comment by RussKie** [comment]
"Commit & force push"
>
> clearer, doable, affects translation, not changed by this PR though
>
We aren't servicing this change, so changed translations aren't an issue.
