### ISSUE TITLE
Sparse checkouts?

### ISSUE THREAD

**Issue by mmoayyed** [gitextensions/gitextensions#2289]
Is there a way to execute and configure git sparse checkouts? if not, is it possible to implement this feature? 

Thanks. 

P.S: Excellent tool, btw.

**Comment by hypersw** [comment]
Sparse support requires:
* ON/OFF toggle for a repo.
* Editor for the sparse inclusion file (same format as gitignore file).
* A command to apply the new sparse inclusion file to the existing working copy.

Stuff which is nice but not critical to have:
* Visual selection of the sparse filter which presents the full tree from the index (skipping the sparse filter yet) and allows to incl/excl nodes. Note that this can't be just checkboxes because, unlike SVN, the filter capabilities are quite limited.
* If not selection, then at least a preview. With complex filters, it's often not very easy to predict what happens (e.g. a filter to take only these subfolders plus root folder files has its caveats).
* Some context commands in Shell context menus to exclude/include certain folder.

**Comment by hypersw** [comment]
How good is _git sparse_?

With SVN, it's very OK and we used it quite widely. Used to be stable back then already.

With Hg, there's a prototype implementation which is more or less OK for R/O access (we use it on continuous integration servers for speed), but totally messes up things with R/W.

With Git, I've observed the filter being violated for certain working copy folders, especially after merge, i.e. the working looked as if it let thru more foders than allowed by the filter. Not sure if it's a stable repro though. Also it's non-fatal unless it messes up with actual commits (like it does with Hg).

So is it really read for use?
