### ISSUE TITLE
Git status spawns a ton of git instances

### ISSUE THREAD

**Issue by nickmayer** [gitextensions/gitextensions#230]
If the option to show repository status in browse dialog is checked, and you have a large repository that takes a while to show the status, you can end up with many "git status" processes running. The widget should throttle itself so it won't make a new request until the previous one has returned.

**Comment by JKniep** [comment]
I still experience this problem in 2.48.05. This happens especially after restarting the computer. If open a repo, approximately each second a new git process is spawned. In the end there are more than 30 individual processes, and each one seems to be active. When the repository has been read (after some minutes because there are no resources left), the commits are shown and the processes are killed one after the other. I can create a video of the situation if this helps. However, sometimes the repo opens in less than a second (when it has already been cached?). The same problem (slow and many processes) occurs when fetching or updating the submodules, but I can easily bypass this by typing the corresponding commands in the bash (where only one git process is used). I'm using a i7 notebook with 16GB RAM.

**Comment by vbjay** [comment]
Do the video and use
http://unix.stackexchange.com/questions/163145/how-to-get-whole-command-line-from-a-process
to
look at an active git process and look at the command line args

**Comment by JKniep** [comment]
Thanks for looking into this problem. One of the git-processes runs "git.exe" diff  -- "external/openssl", which is a subrepo (but not the one I’m currently in). I am in a single subrepo, and git seems to diff all subrepos of our superrepo. But there are even more processes than we have subrepos in our superrepo. Each of the “diff-processes” seems to have a child process that does “git status –porcelain”. Can I please send you the video by mail so not everybody can see it?
