### ISSUE TITLE
Add "git reflog" as a  UI element

### ISSUE THREAD

**Issue by scottpetrovic** [gitextensions/gitextensions#2303]
GIT reflog is a great tool to be able to see all commits that are stored in your repository. There is no way to see this in the UI right now. It would be nice to have a GUI option to show all of your most recent commits, even if they aren't in a branch.

**Comment by webmaster33** [comment]
+1

**Comment by vbjay** [comment]
You can start a bash terminal and run that.

**Comment by vbjay** [comment]
There is this option 
![image](https://cloud.githubusercontent.com/assets/3629489/6996704/fc7071fa-db64-11e4-8e7c-0feae230fe7f.png)

**Comment by msakuta** [comment]
I wrote a Tcl/Tk script to view and revert to reflog items and registered it to Git Extensions' scripts with ShowInUserMenuBar event. Since Git and Git Extensions come with Tcl/Tk interpreter, it's very handy to have such a little helper tool without invoking C# compiler. In fact, it's surprisingly useful when managing complex merges, although it's almost the first Tcl/Tk script I've ever written.

It only shows reflog of current branch, but it wouldn't be hard to modify it to show reflog for HEAD. I've only tested it works in Windows.

It would be nice to have similar functionality in standard Git Extensions, but it's likely for advanced users.

https://gist.github.com/msakuta/d141ca6a50b4b658034f

![image](https://cloud.githubusercontent.com/assets/2798715/7203766/10832640-e558-11e4-947e-a593f3fae469.png)


![image](https://cloud.githubusercontent.com/assets/2798715/7203695/71e2b9d8-e557-11e4-94c5-eb98109b62a0.png)

![image](https://cloud.githubusercontent.com/assets/2798715/7203722/a23618f0-e557-11e4-8b95-2db84f55d647.png)

**Comment by Radrik5** [comment]
What do you think about showing all the commits from the reflogs in the revision graph (with reflog labels simirar to branches and tags)? There can be a special option for it in the View menu.

Then you can select an appropriate commit and reset the current branch to it.

You can try it now by using "--reflog" in the Branches filter; but without reflog labels.

**Comment by Radrik5** [comment]
I suggest something like this:
![image](https://cloud.githubusercontent.com/assets/9339459/7395831/4da322b8-eea5-11e4-8429-c77af9cf7294.png)

We can easily draw all the commits from reflogs by adding `--reflog` to the `git log` command line. It works perfectly well.

But I cannot find a good way to get all the reflog references (like branch and tags references). `git log --walk-reflogs --format="%H %gD"` works well for one branch but returns very strange results for `--all` or `--branches` options. I use Git 1.9.5 on Windows.

**Comment by daflame76** [comment]
+1
I am also looking for this for the same reason.
Rebase sometimes doesn't go as planned.

**Comment by jbialobr** [comment]
Done in #3242.
