### ISSUE TITLE
Add support for gitconfig "include.path"

### ISSUE THREAD

**Issue by joephayes** [gitextensions/gitextensions#2431]
Git Extensions should respect gitconfig include.path settings

**Comment by johndog** [comment]
I have most of my settings in a .gitconfig.common file, which I include from my global .gitconfig file with:

```
[include]
	path = .gitconfig.common
```

I can then link .gitconfig.common to a file in a repo so that I can check in the majority of my settings and share them between machines.

Git Extensions doesn't read the settings in .gitconfig.common, so it doesn't present them in the GUI.  More importantly, it doesn't respect the chosen settings, such as which merge tool to invoke from the UI during conflicts.

**Comment by GintasS** [comment]
Abandoning this because of age.
