### ISSUE TITLE
No display of current changes in the toolbar

### ISSUE THREAD

**Issue by CharlesB2** [gitextensions/gitextensions#2447]
Since upgrade to 2.48, I don't see anymore the number of changes in the "commit" button.
Option "Show repo status in browse dialog" is set to true in the settings. 

Is it a bug, or is there something wrong in my setup?

--- GitExtensions2.48, Git 1.9.4.msysgit.1, Microsoft Windows NT 6.1.7601 Service Pack 1

**Comment by webmaster33** [comment]
I had the same issue, several git.exe was hung.
I had 2 Git Extensions window opened. When I closed both, the git.exe processes were also closed.

Good to know why the Commit button was not updated.

**Comment by Radrik5** [comment]
Git 2.5 is released! Now we can implement the version check and remove the IsRunningGitProcess call as suggested in https://github.com/gitextensions/gitextensions/commit/8b47b8c76ec1#commitcomment-8289795.

**Comment by ismyrnow** [comment]
I've noticed that since using Atom (text editor from GitHub), which has git support built in, GitExtensions hasn't been updating the status count consistently.

Based on the discussion so far, it sounds like it is due to the git process which Atom leaves running. As soon as I close that process, the status number updates.

Is it possible that GitExtensions is trying to use the existing process, but unable to for some reason? It doesn't seem to be a hung process, as Atom uses it normally. I also didn't find any issues in the Atom issue tracker related to this.

**Comment by Radrik5** [comment]
Git Extensions just periodically checks if any git process is running. And if it finds one, it doesn't run `git status` in order to avoid potential index corruption (when two processes modify index file).

**Comment by lijunle** [comment]
I got a similar problem. When any editor (Atom, VSCode, VS) integrated with git running, git extension spawns tons of git processes. :sob:

**Comment by ismyrnow** [comment]
Would more information be helpful for fixing this issue? GitExtensions seems to get my git status when I open the commit dialog, but not before, so long as I'm running a git-integrated editor or IDE.

**Comment by gerhardol** [comment]
The frequency that GE calls git-status is decreased in 2.51 (#4327 #4328) so this should be less of a problem now. There are still possible improvements (for instance issue #4256 #4230). I have done test shots to improve those, but am stuck on that they cannot be tested so they will not be accepted anyway.

Still suggesting that this issue is closed.
