### ISSUE TITLE
Blame opens wrong file

### ISSUE THREAD

**Issue by brandf** [gitextensions/gitextensions#2452]
--- GitExtensions2.48, Git 1.9.4.msysgit.1, Microsoft Windows NT 6.2.9200.0

I have two files in a directory:
MenuViewHost.js
MainMenuViewHost.js

When I right click on MenuViewHost.js and choose Blame it opens MainMenuViewHost.js instead of MenuViewHost.js.

The title says "FileHistory - [omitted path]MenuViewHost.js ([omitted path]MainMenuViewHost.js) - [omitted path]".  So it knows something is wonky, but it's hard to imagine this is a feature.

**Comment by alistairmgreen** [comment]
I have just hit a similar problem, and I think it's caused by similarity of *content.*

* I have two files - let's call them A and B.
* The content of B is identical to one of the previous revisions of A.
* When I open up the history or blame view of B, it shows me the history and current contents of A.
* At the command line, 'git log' and 'git blame' give me the correct information.

Unfortunately, this is in my employer's private repository so I can't share it with you. The history was quite convoluted:
* A was created first and went through several revisions.
* A was renamed to B.
* In the next commit, somebody copied B back to A by mistake. At this point, both files existed and they were identical.
* All subsequent work was done on A.

**Comment by vbjay** [comment]
Look at the follow renames setting.

**Comment by alistairmgreen** [comment]
Yes, "follow renames" is turned on (this appears to be the default). However, it is behaving in a surprising way.

I have created an [example repository which reproduces the issue.](https://github.com/alistairmgreen/git-extensions-history-wrong-file)

It appears that the rename detection in Git Extensions is more eager than the detection performed by `git log --follow`.

At the command line, Git looks backwards in time and shows the history of the file specified (noting that `exampleb.txt` is descended from the first version of `examplea.txt`).

However, Git Extensions looks both forwards and backwards in time. When I open the history dialog for `exampleb.txt`, the first thing it shows is a "rename" of `exampleb.txt` to `examplea.txt` with some new content inserted. At first glance the history of B looks exactly like the history of A, even though the files are now different.

This means that Git Extensions is showing *the most recent content descended from the content of the file that I clicked on.* Unfortunately, that version is *newer* than the one that I clicked on and the result is a bit confusing.

**Comment by loop-evgeny** [comment]
I ran into the same issue and luckily found https://github.com/gitextensions/gitextensions/issues/3044#issuecomment-160180832 which explained the problem. "Follow renames in file history (experimental)" was checked under options (I'm pretty sure I never enabled it). "Follow exact renames and copies only" was unchecked and checking it fixed the problem in my case.

This is extremely user-confusing behaviour and I would have never figured it out without that comment!

1) There is no way this should be the default.
2) If it is enabled, the File History dialog itself should make it clear what's happening: "You asked for file X, but I'm showing you the history for file Y, because you have Follow renames in file history enabled and I think X was renamed to Y. Click here to disable that setting".

**Comment by RussKie** [comment]
> 1. There is no way this should be the default.

Agree, experimental features must be opt-in. You're welcome to send a PR in flipping it off.

**Comment by GintasS** [comment]
Since no one has send a PR, I think we should close this one.
