### ISSUE TITLE
Option to disable detached head dialogs

### ISSUE THREAD

**Issue by m35** [gitextensions/gitextensions#2460]
Please add an option to disable the dialog asking to checkout/create a branch when in detached head state.

**Comment by KindDragon** [comment]
> Indeed, that is the reason for the existing dialog. And the reason to have the option to disable the dialog is because you're not a git novice, thus well aware of the implications of detached head state and don't need the incessant reminder.

But why you want to commit in detached head state?

**Comment by vbjay** [comment]
Exactly. I would want to know.

**Comment by ghanique** [comment]
I can think of one scenario where you'd be changing the commits during an
interactive rebase... Since that can be tricky I try to avoid it and in the
scenarios where I can't I'm ok with clicking the "yes, I want to commit in
a headless state"-button.

What is somewhat dangerous, in that scenario, is that it also suggests to
pull​ or merge or something similar. But since I'm not doing that scenario
casually anyway I'm not inclined to push the wrong button.

**Comment by KindDragon** [comment]
> I can think of one scenario where you'd be changing the commits during an
> interactive rebase... Since that can be tricky I try to avoid it and in the
> scenarios where I can't I'm ok with clicking the "yes, I want to commit in
> a headless state"-button.

We just need to disable this dialog when repository in `interactive rebase` state, it's bug.
