### ISSUE TITLE
Interactive Rebase Doesn't Open Git Extensions Editor Window

### ISSUE THREAD

**Issue by nathanpjones** [gitextensions/gitextensions#2600]
I'm using version 2.48.03 and I'm having a problem where the internal editing window doesn't show when I trigger an interactive rebase.

When this happens, the status window looks like it's waiting for `git.exe` to finish. My only choice is to abort the command.

However, when I go to abort the merge, it gives the following error.

```
rm: cannot unlink `c:/ProjectXXX/.git/rebase-merge/.git-rebase-todo.swp': Permission denied
rm: cannot remove directory `c:/ProjectXXX/.git/rebase-merge': Directory not empty
```

Using [Process Explorer](http://technet.microsoft.com/en-us/sysinternals/bb896653.aspx), it looks like `vim.exe` has the files open.

For this reason, it looks like there's some bug that's causing the default editor to open instead of the internal editing window.

**Workaround**

The workaround is simple. Just set the editor to be something else, notepad, Notepad++ ([see this SO post](http://stackoverflow.com/a/2486342/856595)), etc.

**Comment by ShahzadSoomro** [comment]
+1

**Comment by kris-sum** [comment]
+1 
I've also experienced this, and in my instance vim was using 100% of a cpu core. Vim works normally when executed seperately.

**Comment by apobekiaris** [comment]
+1

**Comment by KindDragon** [comment]
Can you try latest version?

**Comment by Quberik** [comment]
+1

**Comment by patricktokeeffe** [comment]
Still a problem with 2.48.05... and to be fair, the problem is Vim, not GitExtensions. Vim does not create a window, therefore the user cannot interact with it. 

I solved it by changing the 'editor' setting from blank to `"C:/Program Files/GitExtension/GitExtensions.exe" fileeditor`.

**Comment by patricktokeeffe** [comment]
This exact problem has been seen as far back as #358. Since it's very explicitly the fault of `vim.exe`, couldn't the built-in editor be made default, vim-be-damned?

**Comment by ghanique** [comment]
I've had this two times before. When this happens double clicking a file to
open a diff in a diff viewer doesn't work either.
The only way I could resolve it was by uninstalling Git Extensions and Git
and then re-installing it.
The funny thing is that when you open a shell (any shell) and do git config
--list everything points to your favorite editor and nothing points to vim.

**Comment by jbialobr** [comment]
With the 2.9.0.windows.1 msysgit vim does not hang up anymore, but it prints a warning that the process is not a terminal. After the recent ConEmu integration with GitExt vim runs and works correctly when ConEmu is set to be an output dialog for git commands (set to true by default). Since this is a minor issue know I remove the 2.49 milestone. 
If git was to set its editor as the default one at install time, it should be able to unset itself at uninstalling - there are many people that try GitExt and unistall it as it doesn't meet their expectations.
Maybe it should ask the user before preforming rebase if it should set the default editor otherwise the vim editor will be used because no editor is set.
