### ISSUE TITLE
"viewdiff" improvements - Diff range and external diff app

### ISSUE THREAD

**Issue by vitalybe** [gitextensions/gitextensions#2661]
I am lacking the following abilities in "viewdiff" mode:
1. Launch external diff viewer
2. Launch with range parameters, e.g: `gitex viewdiff origin/master..HEAD`

**Comment by ablam** [comment]
Hi vitalybe,
You can add in options/scripts section following entry: 
Command:git
Arguments: difftool -d -g {sHash} {cHash}
-g means that guitool from config file will be used instead of tool
-d means that entire dirs will be compared
Script will compare active commit to the selected one - works fine for me with beyond compare

**Comment by vitalybe** [comment]
@ablam Nice! `-d` is exactly what I was looking for. I guess with that, I don't really need the original request.

**Comment by gerhardol** [comment]
Directories can be compared from GE since 3.2 or so
