### ISSUE TITLE
Add ability to reveal certain commit from command line

### ISSUE THREAD

**Issue by mnaoumov** [gitextensions/gitextensions#2675]
It would be handy to be able to execute the following command from the command line

```
gitex reveal my-commit-hash
```

and have GitExtensions opened on the current repository on a desired commit

**Comment by ghanique** [comment]
Why?

**Comment by mnaoumov** [comment]
@ghanique One of the most common scenarios where I want such thing is when I am searching for something from console

    git log --grep "very old bug"

Then I found a commit and would like to take a look deeply into it. If commit is small enough, maybe

    git log -1 -p my-commit-hash

would be enough, but in case if the commit is very large, I think looking into it with GitExtensions would be much more pleasant.

The workaround I am using so far:
*. Copy the desired commit hash into clipboard
* Open GitExtensions
* Press Ctrl+Shift+G
* Press Enter (you don't need to type the commit hash as it is being automatically populated from clipboard)

**Comment by mouseas** [comment]
Seconded.

My use case would be seeing what's changed on a branch since it was branched off *master*. I currently select a branch's head and its branch point off *master*. It's something I have to do a lot. Currently I have to scroll through several pages of commits to find the branch point, select it, then scroll back to the branch's latest commit and ctrl-click it. Being able to pull up a window with these two commits' diff would save me a lot of time and frustration.

**Comment by tyoung87** [comment]
I agree that this would be useful. Perhaps for the situation that mouseas suggested, it might be useful to make `gitex viewdiff` be able to take in parameters, maybe along the lines of `gitex viewdiff <branch-name-or-tag-name-or-commit-hash> <branch-name-or-tag-name-or-commit-hash>`, then it could open the git extensions diff view with the two points specified selected (and potentially selected in the same order as listed).

**Comment by jbialobr** [comment]
Since 2.50 it can be done by `gitext browse -commit=sha1`
