### ISSUE TITLE
Intermittent error "cannot access a disposed object" on launch

### ISSUE THREAD

**Issue by jimbo1qaz** [gitextensions/gitextensions#2692]
It's very strange. It only happens occasionally, then afterwards, I try reproducing by running several times, and nothing happens.

**Comment by jimbo1qaz** [comment]
No progress? It just happened again, after pushing and entering pageant password, then retry and works.

**Comment by KindDragon** [comment]
Sorry, we cannot reproduce.

**Comment by cblupodev** [comment]
Same problem here. Don't know how to reproduce. Been happening intermittently for months
![General tab](http://i.imgur.com/IRxOb0R.png)
![Exception tab](http://i.imgur.com/yCgkAYw.png)

**Comment by EbenZhang** [comment]
I believe the exception of the `FormUpdate` is because the background thread (Which checks update in the background) tries to call `InvokeSync`, but the form was just disposed after `InvokeSync` checked the `IsDisposed`. The execution sequence might be something like below:

* Background thread calls `InvokeSync`
* `InvokeSync` checks the `IsDisposed`, which is `false`
* UI thread disposes the `FormUpdate`
* `InvokeSync` continues to perform the action against the already disposed form.

To fix it I suggest remove the `using (var updateForm = new FormUpdates(Module.AppVersion))` from `GitUI\CommandsDialogs\FormBrowse.cs` and dispose the form in `FormUpdates`'s done method.
