### ISSUE TITLE
connecting to unknown ssh-server: can't add fingerprint to known hosts

### ISSUE THREAD

**Issue by apuch** [gitextensions/gitextensions#2704]
Trying to clone from an unknown host by ssh fails with an error message saying something like "unknown host. Are you sure?"and the options yes or no. Saying yes..

Expected behavior: process continuous, successfully clone.

Observed behavior: a cmd windows opens, saying failed to connect. Closing this window brings up the same error message. Only chance to " break out" is selecting no and process fails.

Work around: open bash console by menu bar, type "putty/plink.exe <server name>", accept fingerprint and then close.

Seen on several win7 installations using msysgit/putty/.. From gitextensions installation.

**Comment by ghanique** [comment]
You could try to connect to the sender using putty manually as if you
wanted a shell. That allows you to store the fingerprint. The next time you
use Git extensions it won't ask you to store the fingerprint because it
already has been stored.

**Comment by apuch** [comment]
That's basically the workaround I've described. Sure, it is not a show stopper but still a bug in my eyes.

**Comment by ghanique** [comment]
Yes, it's a workaround, and probably a bug, too. But since there is a
finite number of servers and workstations to me the problem is not all that
bad.

That's basically the workaround I've described. Sure, it is not a show
stopper but still a bug in my eyes.

—
Reply to this email directly or view it on GitHub
<https://github.com/gitextensions/gitextensions/issues/2704#issuecomment-80716335>
.

**Comment by laurin1** [comment]
I've got one right now that even that workaround does not work. No idea how to fix it.

**Comment by vbjay** [comment]
More than likely Keith, you are not connecting to a server that allows ssh.

**Comment by pravic** [comment]
Same happened (2.50.02). It looks like GitEx was trying to do something, but failing.

First, it detects unknown host and asks to add his fingerprint: http://c2n.me/3NE101u.png
Since GUI dialog popped, there is no chance to agree to plink's question via console.
After pressing "OK", GitEx spawns a new plink process, but with empty command line: `"C:\Windows\System32\cmd.exe" /k ""path\to\plink.exe" """`

It seems, if new plink will be spawned with the proper command line (like `plink.exe git@github.com`), there will be a chance to add such host as known. 

And I definitely remember, that ssh host registration has worked in earlier GitEx versions.

**Comment by laurin1** [comment]
`More than likely Keith, you are not connecting to a server that allows ssh.`

I fixed it, but that was not it (gitlab.com) and all of my other machines could connect just fine. 

The issues was for some reason, my home was being set to /home/keithdavis and not c:\Users\keithdavis. I never did figure out why, as the Git settings in GE indicated HOME was set correctly. I think what fixed it was re-selecting the same folder for HOME (but not 100% sure).

**Comment by RussKie** [comment]
How did you find that you home was set to /home/keithdavis?

On 12/09/2017 2:22 AM, "Keith Davis" <notifications@github.com> wrote:

More than likely Keith, you are not connecting to a server that allows ssh.

I fixed it, but that was not it (gitlab.com) and all of my other machines
could connect just fine.

The issues was for some reason, my home was being set to /home/keithdavis
and not c:\Users\keithdavis. I never did figure out why, as the Git
settings in GE indicated HOME was set correctly. I think what fixed it was
re-selecting the same folder for HOME (but not 100% sure).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/gitextensions/gitextensions/issues/2704#issuecomment-328582052>,
or mute the thread

**Comment by laurin1** [comment]
I was testing / trying to fix it manually, using 

**plink -v** (connection string)

**Comment by GintasS** [comment]
Abandoning this because of age.

**Comment by pravic** [comment]
Since it hasn't been fixed what's the point of closing this?

**Comment by RussKie** [comment]
Since no one had any inclination or desire to fix it in years, it isn't
worth keeping the issue open.

If you feel passionate about it - please send a PR with a fix.
