### ISSUE TITLE
Add option to open submodule from diff lists

### ISSUE THREAD

**Issue by glen-nicol** [gitextensions/gitextensions#2706]
Some of the repositories I work with have a lot of submodules that are fairly active. Navigating those changes is fairly frustrating because currently all that the diff shows is the commit reference change and what files changed in that commit. There is also no direct way to open that submodule from the list of changes to get more information. It would be great if double clicking a submodule in a diff list would open a new browse window for that submodule with the referenced commit selected so that all the information can quickly be found (commit, tree, and diff). Adding this as an option seems adequate. 

I am willing to do the work on this one.

**Comment by ghanique** [comment]
+1 Yes, my team runs into this "issue" as well. You double click it hoping
that it will open the submodule in a new window (just like the file tab),
but instead it gives some information that doesn't really help. So you go
to the File Tree tab, look up the same module and double click that one.
Since we both work on the superproject as well as on the submodule we have
to do that quite a lot. So being able to right click the submodule in the
diff view would make a huge difference.

It would be even better if the superproject's diff view would also show
what changed in the submodule so that you don't have to open the submodule
every time :-). But that would be significantly harder to implement. Being
able to open the submodule from the diff would also be a significant
improvement.

**Comment by glen-nicol** [comment]
I agree that showing the diff information in the same window would be helpful. But, at the same time I think it makes sense to provide the ability to open the submodule from that list even if that information is displayed. Avoiding the need to hunt through the source tree as you described for more information that isn't imperative to a diff summary.

**Comment by jbialobr** [comment]
Implemented by #2740

**Comment by maliayas** [comment]
New implementation is pretty nice. I'd like to add a detail to improve it further:

Newly opened GitExtensions window jumps to the related commit in the submodule. How about if it jumped to (selected them) the 2 commits (from commit and to commit) so that we can directly see the total changes in that submodule by the commit in the super-repo?

**Comment by jbialobr** [comment]
I like that idea. Please, raise it as a new feature request.

**Comment by maliayas** [comment]
Done! Thanks.
