### ISSUE TITLE
"Pop Selected" button in the Stash dialog

### ISSUE THREAD

**Issue by Radrik5** [gitextensions/gitextensions#2708]
Deleting a stash is usually used right after applying the stash. It whould be nice if you could do it in one click. I suggest adding the "Pop Selected" button to the Stash dialog.

![image](https://cloud.githubusercontent.com/assets/9339459/6663898/0bae0bde-cbdc-11e4-8a20-5b6cde8a8cc8.png)

The button will run the 'git stash pop' command.

**Comment by KindDragon** [comment]
We already have this option on main window toolbar "Stash pop"

**Comment by Radrik5** [comment]
Yes, but it works only with the most recently created stash: stash@{0}.
The Stash dialog shows all the stashes and with the "Pop Selected" button you can pop any of them.

**Comment by Azendale** [comment]
@RussKie Can we get an explanation of why this issue was closed? I appreciate the explanations that there is a way to do a stash pop in Git Extensions main window (from the toolbar), but I think it's still valid to want a button for it on this page. Was closing this an oversight, or more "it's not a bug, it's a feature"? (If the latter, could you explain why you think that?)

I can think of two reasons that it's still valid to want a Pop button for this view:
1. It's one of the two main/expected workflows for this view, the other being a stash push. This view can be confusing to someone coming from CLI git, who may assume that the Apply button is a pop (with "friendlier" terminology than the git commands), instead of realizing it is aligned to the git stash apply command. This can lead to them getting the stashed changes in their tree with apply and still thinking they need to apply the stash a second time (instead of going for the Drop button) because they still see it in the list.
2. It allows pop to be operated on a specific stash item, not just the top one.

I would say that when a stash item is selected, the default action/button should be the new Pop button. Apply and Drop are more the advanced use cases.

**Comment by gerhardol** [comment]
You can git-stash-pop from the side panel for any stash and for those visible in the grid.
A contribution that modernizes ti stash form is welcome (would be needed to add more info there).

There are a lot of suggestions open, these must be cleaned up to  find the relevant ones.
Issues like this will only be done if someone is interested enough anyway.

**Comment by RussKie** [comment]
> Can we get an explanation of why this issue was closed?

The suggestion was opened in Mar 2015, which was 6 years before the issue was closed after it didn't spark any further interest from the users. As @gerhardol said our backlog is already large enough to keep random open issues around. If this issue is something that you feel passioned about - we're happy to consider a pull-request with a fix.
