### ISSUE TITLE
Ability to create a shallow clone  (git clone --depth option)

### ISSUE THREAD

**Issue by Radrik5** [gitextensions/gitextensions#2709]
Since shallow clones are fully functional (you can pull and push from them), it would be nice to have an ability to create them from Git Extensions. We have a huge repository with binary-only files (500 MB) and we are not usually interested in the history, so shallow clones will be often used with that repository.

What do you think is better way to implement this feature: add new check box with edit box for the number of commits or hide the advanced options under "Show options" link like in "Rebase" dialog?

**Comment by hypersw** [comment]
Feels like we could use this too with our repo, if we migrate it from HG.

From the product point of view, would it do if I add a checkbox to the Clone dialog, like, "Do not fetch full history", which would do smth like ``--depth 1 --no-single-branch`` ?

*(my experiments show that without ``no-single-branch`` it's nearly impossible to fetch other branches later, because the repo structure gets inconsistent on fetch and starts crashing on fake file access errors — might be a bug in shallow clones support, or something; with all branches it seemingly works OK)*

If OK from the feature point of view, then I'd get into making a pull request.

**Comment by sharwell** [comment]
I propose to add it below **Initialize all submodules** in the clone dialog.

* A check box, unchecked by default, which reads **Limit clone depth**.
* To the right of a check box, a number control which is only enabled when **Limit clone depth** is checked. The default value in this box is **1**.

**Comment by hypersw** [comment]
Technically, that's it.  An engineering UI, but I'm not sure if it's the most user-friendly way. The label isn't explaining much for novice git users, while "Do not download full history" does. _(The exact command line option should be explicitly stated there in a tooltip anyway, I believe)_

Pls give some ideas on whether smb would change the depth level from the default any often. I'm totally not sure. And additional controls would complicate the UI visually, not to mention the additional line spacing to house an editbox when compared to a mere checkbox.

**Comment by KindDragon** [comment]
> An engineering UI, but I'm not sure if it's the most user-friendly way. The label isn't explaining much for novice git users, while "Do not download full history" does. (The exact command line option should be explicitly stated there in a tooltip anyway, I believe)

I basically agree, but I do not like checkbox with negative text

**Comment by hypersw** [comment]
"Download full history", and checked by default?
