### ISSUE TITLE
Detect hashes in commit messages and convert them to hyper links

### ISSUE THREAD

**Issue by mnaoumov** [gitextensions/gitextensions#2714]
The most common useful scenario is message like

```
(cherry picked from commit 2cb1c1379f6303d4b81a0130d7f7a76b0993568b)
```

It would be great if you can click on the hash and navigate straight to the commit

**Comment by jbialobr** [comment]
You can configure [revision links](https://git-extensions-documentation.readthedocs.org/en/latest/settings.html#revision-links) for that. In-place replacement  is not implemented.

**Comment by vbjay** [comment]
See #1875

**Comment by mnaoumov** [comment]
@vbjay , yeah, that's a bit different. Instead of putting links to the header, I suggested and then implemented conversion hashes to hyperlink in-place in commit message

**Comment by pravic** [comment]
> You can configure revision links for that. In-place replacement is not implemented.

How? Because setting url to "gitext://gotocommit/{0}" doesn't work.

**Comment by jbialobr** [comment]
It works for me.
![2017-03-03 22_03_03](https://cloud.githubusercontent.com/assets/1003909/23568928/414677d8-005d-11e7-8aa4-d20e694f1579.png)

**Comment by pravic** [comment]
Well, `gitext://gotocommit` works only with full hashes while View/Go to commit works with short ones perfectly. 

When I clicking on link with short hash (I tried hashes with 8, 16 and 20 characters), the focus just goes away and nothing.

**Comment by Radrik5** [comment]
I confirm that `gitext://gotocommit` doesn't work with short hashes. But even if it worked, it would still be less convenient than having these links 'in place'.

At first I was thinking about extending Revision links so that links to GitHub issues also worked 'in place'. But hashes are different: they can be confused with large issue numbers. For example, this is a real issue number from our bug tracker: 964526146. Search pattern `[a-f\d]{8,40}` successfully matches it and Git Extensions creates Go to commit link that simple doesn't work. Hashes should be validated against commit objects that exist in the repository. And such links will be useful for all users, not just for those who know about Revision links.
