### ISSUE TITLE
Make Setup project compilable straight from Visual Studio

### ISSUE THREAD

**Issue by mnaoumov** [gitextensions/gitextensions#2745]
Discussing #2729 I found the following problems
1. Setup project relies on the existence of bin\Release folders that don't contain the desired files if you build in Debug configuration. So at least configuration project should not be compiling in Debug configuration

Setup projects relies on the existence of external installers. The system cannot find the file '..\Bin\KDiff3-64bit-Setup_0.9.98-2.exe' and those are downloaded by **DownloadExternals.cmd** which should be added as a prebuild step to the Setup project

**Comment by sharwell** [comment]
@RussKie I investigated several options related to this, but primarily looked at the following as potentially stable options:

1. Using existing NuGet packages
2. Using Git Large File Support
3. Using custom NuGet packages

## Approaches

### Existing NuGet packages

NuGet allows the placement of custom a **NuGet.Config** in the repository to control the sources of NuGet packages. Of particular interested is Chocolatey, which exposes its packages via a NuGet-compatible feed.

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <!-- Get the required installers from the Chocolatey feed -->
    <add key="Chocolatey" value="https://chocolatey.org/api/v2/" />
  </packageSources>
</configuration>
```

With this in place, I modified **Setup/packages.config** as follows, which triggered NuGet restore to download [git.install 2.13.2](https://chocolatey.org/packages/git.install/2.13.2) to the solution's **packages** directory:

```diff
 ﻿<?xml version="1.0" encoding="utf-8"?>
 <packages>
   <package id="7-Zip.CommandLine" version="9.20.0" />
+  <package id="git.install" version="2.13.2" />
   <package id="WiX" version="3.11.0" />
 </packages>
```

This worked exactly the way I intended. In fact, I probably would have stopped here if it wasn't for one big problem: I couldn't find an existing KDiff3 package which bundles the installer itself inside the package. The [KDiff3 0.9.97](https://chocolatey.org/packages/kdiff3/0.9.97) package is just a script that, when executes, downloads and runs the installer from SourceForge.

### Git Large File Support

Enabling Git Large File Support is quite easy on GitHub. However, it comes with both space and bandwidth limits. If the only issue was space, I'd probably just cover the cost, but I don't like the unpredictability of a bandwidth limitation. It's possible that the issue could be side-stepped by hosting a mirror of the repository on Visual Studio Online, per [Announcing Git-LFS on all VSO Git repos](https://blogs.msdn.microsoft.com/devops/2015/10/01/announcing-git-lfs-on-all-vso-git-repos/), but it sounds like that approach would require every user to manually configure remotes and/or repository hooks in strange ways. Relevant post from someone who had an experience similar to me:

:link: [GitHub’s Large File Storage is no panacea for Open Source — quite the opposite](https://medium.com/@megastep/github-s-large-file-storage-is-no-panacea-for-open-source-quite-the-opposite-12c0e16a9a91)

### Roll-your-own NuGet packages

For this option, you place the required binaries in the **tools** directory of a NuGet package and upload it. You might call it **GitExtensions.SetupFiles**, and possibly even mark it as unlisted. The downside of this approach is it requires 

## Recommendation

The only viable option from these three appears to be the third option, which could really take two forms:

1. Package both setup installers in GitExtensions.SetupFiles, and upload a new package whenever either installer is updated.
1. Use the Git installer from Chocolatey (option 1 way above), and only package the KDiff3 installer in GitExtensions.SetupFiles.

The second form allows any user to update the Git installer dependency (since the required package is regularly updated by Chocolatey), e.g. to address [this recent issue](http://blog.recurity-labs.com/2017-08-10/scm-vulns).

**Comment by RussKie** [comment]
Good stuff!
If we ditch KDiff for P4Merge we can use chocolatey - https://chocolatey.org/packages/P4Merge
😄

**Comment by KindDragon** [comment]
@RussKie  https://chocolatey.org/packages/kdiff3 😄

**Comment by sharwell** [comment]
@KindDragon my comment above explains why that won't work.

**Comment by RussKie** [comment]
@KindDragon cmon, it's time for a change! 😏 

https://www.youtube.com/watch?v=n4RjJKxsamQ

**Comment by vbjay** [comment]
Lol.

**Comment by gerhardol** [comment]
The dependencies were mostly corrected in #4270. Setup is not built by default but can be built explicitly in Visual Studio.
The hardcoded dependencies to Release were mostly addressed. However, I see some problems building Debug now. If this is enough, this issue can be closed.

The external packages are removed in #4515.
However, if something similar is used later, LFS is the was to go.

**Comment by RussKie** [comment]
> I see some problems building Debug now

Could you please elaborate?

**Comment by gerhardol** [comment]
> >  I see some problems building Debug now
> Could you please elaborate?

In #4270, I changed from hardcoded references to Release to use the currently active release (including Debug). I had problems building though yesterday in Debug. Fine today. I suggest this issue is closed.

**Comment by RussKie** [comment]
I am compiling it as we speak in debug mode for #4747.
No issues after all nugets are restored
