### ISSUE TITLE
No plugins - crash

### ISSUE THREAD

**Issue by vzabavnov** [gitextensions/gitextensions#2807]
During installation uncheck all plug-ins (no plugin will be installed).
Run the application and exception DirectoryNotFoundException raised. Creating empty folder "PLUGINS" - solve the problem

**Comment by lggomez** [comment]
The plugins folder should be created without files by changing its directory entry in the wix file Product.wxs:

```xml
<Directory Id="PluginsDir" Name="Plugins" />
```

to

```xml
<Directory Id="PluginsDir" Name="Plugins">
	<Component Id="PluginsDir" 
		Guid="1BAE9E9A-B836-4168-A7C3-7FC359AD1BD4" KeyPath="no" 
		NeverOverwrite="no" Permanent="no" Transitive="no"> 
		<CreateFolder />
	</Component> 
</Directory>
```

I couldn't test it since I keep getting the same error every time I try to build the installer, even if I set up the bin\Release folder

C:\DEV\GITHUB\gitextensions\Setup\Product.wxs(244): error LGHT0103: The system cannot find the file '..\GitExtensions\bin\Release\Newtonsoft.Json.dll'. [C:\DEV\GITHUB\gitextensions\Setup\Setup.wixproj]

**Comment by jbialobr** [comment]
GitExt now checks whether the Plugins dir exists.
