### ISSUE TITLE
Release Notes Generator

### ISSUE THREAD

**Issue by LaughingJohn** [gitextensions/gitextensions#2831]
I use this for producing documentation and have a couple of issues/suggestions.
1. I always remove the commit hash from the format (i.e. remove "%h@"). If I then click generate it works, but none of the copy buttons are enabled.
2. It would be nice if it would remember the last format, or there was a way to save it/reset to default.
3. It would be handy if the From/To field could have a dropdown of tags. We use these to denote releases. I realise that other users may do this differently so maybe have some options..

Thanks!

**Comment by feinstaub** [comment]
Hi, glad to hear you find the Release Notes Generator plugin useful. I'm the original author.

1. Sounds like a bug.
2. Should be possible. Maybe the GitExt plugin host supports reading and writing of custom settings (I didn't look at the source recently so I don't know). Otherwise one had to do it "manually".
3. Having tag names in a dropdown list also was a desired feature back then (same use case: make diffs between two releases). At this time, there was no straighforward way of getting a list of tags from the GitExt host to the plugin. Maybe now, this is easier possible.

Sadly, I don't use plugin anymore personally. So I won't make any changes to it. On the plus side, the code is not that difficult, so maybe you will have a look and make some changes. Your suggestions seem all reasonable, so I would be the last to decline a pull request. :-)

**Comment by sharwell** [comment]
> It would be nice if it would remember the last format, or there was a way to save it/reset to default.

:+1:

**Comment by vbjay** [comment]
Release notes should use commit search ui like other dialogs.

**Comment by jupsoleil** [comment]
It would be nice if it would remember the last format, or there was a way to save it/reset to default.

👍
