### ISSUE TITLE
Filter by commit id doesn't work

### ISSUE THREAD

**Issue by EbenZhang** [gitextensions/gitextensions#2854]
The `filter by commit id` stopped working due to changes made in pull request #2841.

@Radrik5

**Comment by Radrik5** [comment]
@EbenZhang, please take a look at #2840. Do you really prefer using quick filter instead of "Go to commit" or "Branches" filter to find a commit?

**Comment by Radrik5** [comment]
This bug is actually more serious. Quick filter doesn't work at all. File History doesn't use `--follow`, `--parents`, etc. options. All of them are treated as file names because they go after `--`. The problem is in simple concatenation of thee filter strings that can contain `-- filename`. So, after the first `--` everything is treated as file names. The code that generates the third filter (FormFileHistory) is very different in release/2.48 and master. So I prepared different fixes for the branches. In release/2.48 I reverted fix for #2700. In master I made a good fix that should cover all the case.
