### ISSUE TITLE
'Reset any branch to here' feature

### ISSUE THREAD

**Issue by mdonatas** [gitextensions/gitextensions#2876]
Hey, I've been wondering if anyone would be interested in such a feature I use it for over a year now in custom builds and still like it :)

Most common scenario is as shown in the screenshot. You rebase your Feature branch on top of lets say master and want to push to master just the first two commits. I then reset local master to this selected commit and push master. There are other usecases but this is the most common for me.

![reset-branch-to-here](https://cloud.githubusercontent.com/assets/483659/8721743/36935f6c-2bc6-11e5-9b46-a87dc0640827.png)

**Comment by ghanique** [comment]
+1!

I wouldn't use it for the same reason as you do, but every now and then I
find myself checking out another branch, reseting it to some other location
and then re-checkout the branch I was working on, every now then then by
shooting myself in the foot. Alternatively I sometimes edit the ref in the
.git directory.

I wouldn't replace "Reset CURRENT branch to here", though. I would like to
have two options: "Reset CURRENT branch to here" and "Reset branch to
here". Perhaps "Reset branch to here" should be in the menu section that
contains "Checkout revision" and "Revert commit".

**Comment by vbjay** [comment]
The issue with doing this is rewrite of history.  When you create 3 commits
on a branch and push to a remote, those 3 commits should be considered
stuck.  If you reset to commit 2 and then commit two more and push to the
remote, it won't let you unless you force push.  It overwrites the
history.  Sometimes you have to rewrite.  However in this case it is too
easy to go to far back.

**Comment by ghanique** [comment]
I'm afraid I don't get your point.

The main reason why I would use it is because I forgot to create a branch
for a few commits. So I create a new branch for the feature and want to
reset develop back a few commits.

Another reason would be because it makes it easier to clean up the remote
if other people created a mess (because they failed to rebase for example).

**Comment by vbjay** [comment]
It is great for that.  However, try this process.  Create two branches.
B1,B2  b1=5 commits.  b2 points to  b1-c4.  You have pushed both branches
to a remote.  That means that you can add commits to both branches that
extend after c4 but c5 and below are set in stone.

Now do your reset to c2 and add a commit.  You have now rewritten history.
If you push this then you will have to force push and whichever branch has
that change will lose old(c3-c5)  there will be a new c-3.

https://www.kernel.org/pub/software/scm/git/docs/user-manual.html#problems-With-rewriting-history

**Comment by Radrik5** [comment]
@vbjay, doesn't "Reset current branch to here" have the same issue with rewriting history?

**Comment by vbjay** [comment]
Yes.  Both need to be adjusted.  There should be a warning on both that say
there is a chance of rewriting history.  If the person acknowledges the
warning then allow the action.  The warning needs to only show when going
 past a commit that has been pushed.  Easy to check because the tracking
branch points to a specific commit.  You can compare the current and the
tracking commit and determine if that commit has been pushed.

**Comment by Radrik5** [comment]
And there should be no warning if there is no tracking branch for the given branch, right?
Should GitExt show the warning if the tracking branch is another local branch (`branch.<name>.remote` is `.`)?

**Comment by vbjay** [comment]
We have code that detects which branches contain a specific commit. The
check should check if one of the remote branches contains it. If any remote
contains the commit then it has been pushed.

**Comment by Radrik5** [comment]
Personally I don't need the warning because I understand what rewriting history is and I can see which commits will be overwritten (the tracking branch contains them). So, I'd like to have the warning configurable (like warning after amend).

**Comment by vbjay** [comment]
Sure. I thought that was understood. The default should be to warn and you
can turn it off if you want to.

**Comment by ghanique** [comment]
@Jay,

Thx for your suggestion. There are already workarounds to fixing things.
They'd just be much faster if you could "reset any branch to here". Take
the scenario where I committed on the master branch where I should have
created a feature branch:
* I could create a feature branch, reset master to origin/master and then
check out my feature branch again. (This updates my working copy twice,
which could be annoying if there were uncommitted changes. In that case I'd
have to stash them first and at the end pop them - two more actions).
* I could also copy the SHA1 of origin/master, edit .git/refs/heads/master,
paste that SHA1 and save it. (Now my working copy remains untouched, but I
do have to walk a directory tree to find the branch I want to reset.

Or, if we'd implement "reset any branch to here"

* reset master to origin master while the feature branch remains checked
out.

The last one is very simple, fast and unintrusive.
Putting it in the block that contains "Checkout revision" also clearly
separates it from "reset current branch to here", both in distance and in
function.

**Comment by vbjay** [comment]
You can actually  create a new branch by right clicking on any commit and
create your branch from there. You can also under the create  new branch
dialog select a different commit to create from. I an not saying you can't
reset. I am just saying after a push there should be a warning.

**Comment by mirkogeffken** [comment]
+1 Like it for the same/similar enough workflow as @ghanique. Not particular about how implemented, but I like the @mdonatas implementation.

**Comment by diaconesq** [comment]
+1 I find myself using (the command-line version of this) almost daily. @mdonatas Is your patch available anywhere? 

Another suggestion (SmartGit/Hg does it this way): I'd like to be able to drag/drop the branch label in the UI to reset it to a new location. (Smart Git lets you do this but asks what you want to do: reset or rebase).

**Comment by KindDragon** [comment]
Maybe it should be named something like `checkout and reset`. In order to make clear that this function will checkout the other branch

**Comment by ghanique** [comment]
I don't always want to check out a branch I'd want to move. I just want to
move it.

**Comment by vbjay** [comment]
I for one think it is a bad idea. You need to understand the ramifications
this would cause. Yes. There are times doing this would aid in getting
things done. I frankly think forcing the user to check out a branch and
then reset it to any other commit us the better action.

**Comment by Avalancs** [comment]
I mostly want to move temporary branches around, so not pushing them, just to not lose commits until I'm satisfied with a rebase/merge/etc. 

> git branch -f
Is the last command I'm still using from the terminal because everything else is available from the UI now. I'd love to see it as a right click option "Move a branch here" with a popup window similar to the "checkout branch..." menu.

**Comment by vbjay** [comment]
The problem and why this is not such a hot idea is the fact that the other
branch has to be checked out and then reset to the new commit. Which would
mean your working directory could be overwritten in the checkout part.

**Comment by Avalancs** [comment]
No, the command git branch -f <branch> <to where> doesn't do any checkouts, it just moves the label. Of course you cannot do it on the currently checked out branch, but any other branch is okay.

It doesn't check whether this will cause commits to be unreachable, so that will need to be done for a correct implementation. But I'd gladly use it even without the check, since I know what I'm doing when I need it.

**Comment by wolfen351** [comment]
Would be great if there was even an option to push it up after moving it.. 🥇

**Comment by johndog** [comment]
Frequent rebase and the use of small, interdependent topic branches necessitates moving branches around a lot, and having to check them out to do so is an expensive and unnecessary burden.  Like @Avalancs, I've been using C/L commands to repoint other branches to circumvent checkout, and that has significantly improved my workflow over checkout+reset.  Since I started doing this I've yearned for GitEx to support this: it's faster and easier to avoid mistakes if moves like this can be done visually.  

I **love** @diaconesq's idea of dragging a branch onto a commit and having it prompt for rebase/reset.  It's like the new Branches pane is tailor made for this.  Any warnings/confirmation can be handled in the resulting prompt.  

I'm generally comfortable leaving "force-push" as the sole red-flag operation for the dangers of rewritten history.  Careful use of force-push offers some protection for all the cases.  A fully featured git server will let you lock down branches to force-push, so that an authoritative history can be maintained as a matter of policy in branches that are shared by convention, offering an additional level of protection.  

There are a lot of ways of creating new commits with rewritten history in them (rebase, cherry-pick, commit -amend, squash-merge).  Reset is not actually one of them, because all it can do is point to an existing commit.  For reset, the foul was either already committed (wokka wokka) before the reset occurred, or it will be perpetrated when the rewritten branch get force-pushed.  Doing the warning on reset seems out of place to me, but it's not a big deal if a confirmation prompt presents anyway.

**Comment by RussKie** [comment]
I do that a lot too actually, and I like the idea of offering such functionality in the app.
Any takers?

**Comment by gerhardol** [comment]
I suggest "Reset branch to here..." with same dialog as "Checkout branch".
Possibly with "Force push" option if the branch is tracked

**Comment by gerhardol** [comment]
A coworker bumped this request

**Comment by pmiossec** [comment]
I also find this feature quite interesting.

A quick rebase of the @mdonatas code if someone wants to finish the feature: https://github.com/pmiossec/gitextensions/tree/reset_branch_to

**Comment by gerhardol** [comment]
> A quick rebase of the @mdonatas code if someone wants to finish the feature

Thanks for resurrecting

A quick tryout. I have 750 local branches and the rev grid context menu requires about 10s to open, then it is almost impossible to select in the list. This need to be changed to something similar to the delete branch form where the branch is enumerated and selected in the form.
Also I want to keep the current reset (soft/hard) form, so this would be yet another menu item (and form).

**Comment by mstv** [comment]
> This need to be changed to something similar to the delete branch form where the branch is enumerated and selected in the form.
Also I want to keep the current reset (soft/hard) form, so this would be yet another menu item (and form).

Yes, this is my feeling, too. I prefer to keep `Reset current branch to here...` and add another `Reset another(?) branch to here...` with a new / recycled dialog.
Perhaps it is time to open a PR for this, e.g. for others to contribute if you are too busy ATM.

It works well with my clone of the GE repo, e.g.:
`git.exe push ./ "303f3f4023cdbf72f0c3290f603871e320cd0ed8":"refs/heads/x" -f`
But unfortunately, it does not work on a different machine.
I always get the following error both with git 2.21 and 2.26.0.1:
```
Invalid remote name "./": invalid remote name: "./"
error: failed to push some refs to './'
```
Though that's exactly the remote name which should make this feature do the trick. 🤔 🤷‍♂️
