### ISSUE TITLE
Adding known host does not work for non standard ports

### ISSUE THREAD

**Issue by pvginkel** [gitextensions/gitextensions#2882]
I'm using Gerrit which has SSH running on the non standard port 29418. Automatically adding a known host doesn't work in that instance. The command box that opens clearly connects to the default SSH port; not the non-standard one. Since they are using different SSH certificates, the wrong host is added. Instead plink should be run as `plink -P 29418 host`.

**Comment by CookiePLMonster** [comment]
Oddly enough, a PR from 2014 claims to have that fixed - but it's still an issue in 2017.

**Comment by RussKie** [comment]
Which PR are referring to?
This bug is still open and it is still up for grabs.
You are welcome to volunteer and submit a fix

**Comment by CookiePLMonster** [comment]
Oh well, looks like the thing I found only concerns Test Connection and not pulling/pushing?

See #47 and cf807d40ee36483d5ee9bdf92bb37ceb83620767

**Comment by CookiePLMonster** [comment]
OK, so looks like this is actually **implemented and working**! My issue lied elsewhere - paths to plink/pageant I set in Settings -> SSH were **not** in line with those stored in registry `HKCU\Software\GitExtensions` and therefore Test Connection used a different plink.exe than Pull does.

![image](https://user-images.githubusercontent.com/7947461/30591234-3d0e76ac-9d42-11e7-8626-8afda5f15282.png)

![image](https://user-images.githubusercontent.com/7947461/30591248-4955a91c-9d42-11e7-86c3-a9ca20954c45.png)

**Comment by RussKie** [comment]
Good stuff!
So which one does the "Test Connection" use?

**Comment by CookiePLMonster** [comment]
UI for Test Connection relies on the one from registry (so if gitssh reg entry doesn't point to plink.exe, Test Connection button is gone), however when launched the option uses plink from Settings. _Pull/Fetch_ and _Update remote branch info_ always use plink from registry.

So if both paths point to valid plink (which is easy since they point to GitExt's plink by default and users might have changed the option in Settings to point to a separate plink) incosistencies like this can occur.

I'm currently working on noting down a reliable repro path for desyncing those without messing with registry keys manually and I'll redirect this discussion there.

**Comment by CookiePLMonster** [comment]
Created #4011 - let's move the discussion here.

Long story short - this seems to be fixed provided paths to plink are correct - I'm now able to pull from SSH over port `2322` with no problems.

**Comment by GintasS** [comment]
Discussion was moved to #4011, need to close this.
