### ISSUE TITLE
Please release a new version bundled with git 2.8

### ISSUE THREAD

**Issue by forki** [gitextensions/gitextensions#2925]
Git 2.5 is finally available on Windows. https://git-scm.com/download/win

**Comment by MichaelKetting** [comment]
/second/

**Comment by piotr-cz** [comment]
Will GitExtensions work properly if I update msysgit 1.9.x to Git 2.5 by myself?

**Comment by bart112233** [comment]
I was try this - GitExtensions start freezing on some operations

**Comment by piotr-cz** [comment]
This is important for me, because I've installed msysgit separately using [chocolatey](https://chocolatey.org), and then GitExtensions on top of it.

I'm using chocolatey upgrade command with the `--noop` switch, so I check available package upgrades before running real upgrade, but if anybody runs
`chocolatey upgrade all`, it will install Git 2.5 in place of mysgit and GitExtensions will probably break, as @bart112233 mentioned.

**Comment by MichaelKetting** [comment]
It definitely breaks Git Extensions when Git for Windows 2.5 is installed.

**Comment by narcotics726** [comment]
+1, it threw an Invalid Path Exception with Git for Windows 2.5 installed

**Comment by Troop666** [comment]
Git 2.5 for Windows works fine. At first i've got exception, but than i reconfigure Git Extensions.

**Comment by remcoros** [comment]
Been using Git 2.5 this week, so far so good. As @Troop666 says, update the path to the Git executable.

**Comment by MichaelKetting** [comment]
Yes, that works. Funny bit, the dialog already offered the correct path but I still needed to updat ethe settings.

**Comment by narcotics726** [comment]
Strange, every time I open the gitex's configuration window, it always throw an exception

**Comment by hypersw** [comment]
Which exception? Might be that your %PATH% contains quotes, for example (or any other symbols which .NET Path parser does not like). See #2924 for example.

**Comment by narcotics726** [comment]
@hypersw Well, I reinstall Git 2.5 while keeping the GitEx's setting dialog opened, and set the config path to Git 2.5. Now it's totally ok and no more invalid path exception. Strange still, but...just let it go.

And, thanks for your information. I checked the %PATH%, there's nothing about git's path and no quotes in them. So maybe my problem is just another one.

**Comment by linquize** [comment]
Git for Windows 2.5.3 comes with `git-flow`. Therefore, the users no longer need to install extra git-flow scripts or binaries in order to use git flow plugin! That's cool!

**Comment by Wirone** [comment]
I've upgraded Git to 2.6.3 and everything works fine, I didn't even have to set path to Git, previous configuration worked "out-of-the-box". No problems so far, after some basic operations. And there's `git-flow` bundled and working, nice :-)

**Comment by vbjay** [comment]
Git work tree has issues.

**Comment by Wirone** [comment]
@vbjay I didn't notice any issues with work tree. But I've installed 2.**6**.3, not 2.**5**.3 mentioned earlier by @linquize and others. Could you post more details? I could check it.

**Comment by mscrivo** [comment]
I don't think it's necessary to bundle git any more.  Git for Windows gets updated so frequently now, there would be no point.  Most developers can handle installing git on their own, and would prefer to use something like chocolatey instead.  I vote to remove the bundled git entirely.

**Comment by vbjay** [comment]
Why not try to detect git like we do already and if it can't be found ask
them if they would like to be directed to the git download page.  If so,
launch that page to download the current version.

**Comment by hypersw** [comment]
* GitExt should have some means to get git installed automatically. It's not a nice experience if you cannot use the app out of the box because it's missing a key dependency without which it's useless.
* GitExt should ideally check if there're newer versions of git out there and suggest installing them.
* For average-sized repo, I believe there's no much difference in any of those often-updated versions of git.

**Comment by KindDragon** [comment]
> GitExt should have some means to get git installed automatically. It's not a nice experience if you cannot use the app out of the box because it's missing a key dependency without which it's useless.

:+1: 
> GitExt should ideally check if there're newer versions of git out there and suggest installing them.

A large number of git versions break something in GitExt, we should only update to supported Git version

**Comment by mscrivo** [comment]
@KindDragon really?  The git team is pretty good with compatibility .. I've used every version that's come out since 1.9.5, and I haven't noticed any issues with GitExt.

Also, TortoiseGit manages to get along fine without including a version of git in the installer.   To me, it just seems messy to include it.

**Comment by KindDragon** [comment]
> @KindDragon really? The git team is pretty good with compatibility .. I've used every version that's come out since 1.9.5, and I haven't noticed any issues with GitExt.

We expect certain Git command output, so if they change something GitExt can start work differently. Also, they often change Git file location (they already do that couple times) that we read.

**Comment by jbialobr** [comment]
Done in e411f700092a76d38c0f676f5c51db78fc2c0178

**Comment by forki** [comment]
where is the download?

**Comment by KindDragon** [comment]
No release yet https://github.com/gitextensions/gitextensions/milestone/16

**Comment by forki** [comment]
Is one planned?

**Comment by KindDragon** [comment]
When fix all bugs: https://github.com/gitextensions/gitextensions/milestone/16
