### ISSUE TITLE
FSCK

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#2967]
Right after doing a fresh clone.
![image](https://cloud.githubusercontent.com/assets/3629489/10212990/3970a9b0-67d5-11e5-801c-258747062bdf.png)

**Comment by Radrik5** [comment]
This tree object belongs to GitCommands folder in only one commit a35d4cd854f69bdfea355480eac2a327cd7ac433. The commit was pushed 5 years ago and present in the repo since release 1.95. The only way to fix the tree object is to rewrite it, rewrite commit that introduced it, and all the commits above. In total 6977 commits will change SHA hashes.

I don't think it should be fixed taking into account that Git correctly works with such trees and that after the fix the repository will be rewritten. Everyone will need to clone it from scratch and recreate their pull requests.

See this discussion for more details: http://git.661346.n2.nabble.com/Tree-with-leading-0-modes-in-1-7-0-3-td4806618.html

**Comment by vbjay** [comment]
Cool. Thanks. I wasn't sure. More of a FYI and was wondering if it needed
fixing. Appreciate the info.
