### ISSUE TITLE
Stash window

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#2971]
When a stash is selected in the stash window, make the commit hash that the stash references a link that closes the dialog and selects that commit in the revision grid.  Or have a link or button that does the same action somewhere else in the window.

**Comment by Radrik5** [comment]
I guess stash commits appeared in the revision grid accidentally (simple because Git Extensions displays all the git references and stash is implemented via refs/stash reference and its reflog). So, Git Extensions shows only the most recent stash commit (stash or stash@{0}), other stash commits are not visible.

Also, the two or three stash commits (optional commit with untracked files, commit with index state, and merge commit with working directory changes) look scary for newcomers. From my point of view it's implementation details and these commits should be hidden from the user.

Maybe we can improve the stash dialog itself? What do you need a stash commit for?

**Comment by vbjay** [comment]
You aren't getting it. They are very useful. I use them on occasion. What I
want is a way to go to the commit that is linked to the stash ( the one
right before the stash) so that I can see the history around the stash.
