### ISSUE TITLE
/bin/sh^M: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by ArsenShnurkov** [gitextensions/gitextensions#3013]
https://github.com/gitextensions/gitextensions/blob/4237558f77d2227234e590904eec30d7e37a53c5/GitExtensions/copy_plugins.sh#L1

gives an error

    /usr/lib64/mono/4.5/Microsoft.Common.targets: Error: Command '/var/calculate/remote/distfiles/egit-src/gitextensions.git/GitExtensions/copy_plugins.sh /var/calculate/remote/distfiles/egit-src/gitextensions.git/ Debug' exited with code: 126. (GitExtensions.Mono)

/var/calculate/remote/distfiles/egit-src/gitextensions.git/GitExtensions/copy_plugins.sh: /bin/sh^M: bad interpreter: No such file or directory

**Comment by ArsenShnurkov** [comment]
this is the problem with local git configuration (line endings)

**Comment by JerryLumpkins** [comment]
I noticed that with the new alpha version of gitExtensions (2.4.9a1) you
are not supplying the gitextensions.sh file.

That file was deployed previously with earlier versions (2.4x - 2.4.8.05)
with the bad end of line characters.
Since you aren't supplying it, I think you are considering it a client-side
configuration issue, but it was part of the distributed files previously.

It's an easy fix, but I guess it isn't needed if you aren't supplying that
file.



On Thu, Nov 5, 2015 at 10:11 AM, ArsenShnurkov <notifications@github.com>
wrote:

> this is the problem with local git configuration (line endings)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gitextensions/gitextensions/issues/3013#issuecomment-154087999>
> .
>



-- 
Life is not a dress rehearsal.

**Comment by linquize** [comment]
shell script must use `\n` as EOL, not `\r\n`
