### ISSUE TITLE
Duplicate icon when application is pinned to taskbar

### ISSUE THREAD

**Issue by disklosr** [gitextensions/gitextensions#3021]
When you pin this app to Windows 7 taskbar and you open it, it opens in another taskbar icon.

![](http://i.imgur.com/mPdq1D5.png)

**Comment by tkrokli** [comment]
GitExtensions.exe [2.48.05] -- confirmed. Windows 10.0 Home, Build 10240. At first I thought that this happened because Microsoft released Windows 10, because I was in a transition between Windows 10 Tech Preview and converting a Windows 7 license to Windows 10. Unfortunately, I can't remember or verify if this started happening before or after I ditched Tech Preview and reinstalled Windows 7 Home x64 and chose to accept Microsoft's free upgrade to Win10.

**Comment by vbjay** [comment]
It happens on 7 and 10.

**Comment by ghanique** [comment]
Has been happening for a long time. I always ignored it. (I don't use the
pinning feature in Windows).

**Comment by disklosr** [comment]
If this can help, the atom.io project had the same issue on windows 10 and it has now been fixed. An issue has been created in said project and I believe consulting it will help.

**Comment by tkrokli** [comment]
Atom issue: [**Pinning Atom to the Windows taskbar duplicates the icon**](https://github.com/atom/atom/issues/7374) https://github.com/atom/atom/issues/7374
commit: [**Fix incorrect indentation on setAppUserModelId**](https://github.com/atom/atom/commit/47f973db3801ab13ccd8530632b944cf1865dddc)
diff from https://github.com/atom/atom/blob/master/src/browser/main.coffee :
```diff
   setupCompileCache()
   return if handleStartupEventWithSquirrel()
 
-    # NB: This prevents Win10 from showing dupe items in the taskbar
-    app.setAppUserModelId('com.squirrel.atom.atom')
+  # NB: This prevents Win10 from showing dupe items in the taskbar
+  app.setAppUserModelId('com.squirrel.atom.atom')
 
   args = parseCommandLine()
```
(would be nice if someone who knows the GitExt source could comment on if this is relatable or not.)

**Comment by disklosr** [comment]
Only change I see there is indentation

**Comment by tkrokli** [comment]
I know, but according to  @paulcbetts this was the solution for Atom in this case. Not sure how much it depended on other commits and PRs to be merged, but according to the comment line, the code line `app.setAppUserModelId('com.squirrel.atom.atom')` is supposedly the fix.

**Comment by disklosr** [comment]
They're not using squirrel.

**Comment by vbjay** [comment]
Doesn't matter.
app.setAppUserModelId is the important part. We would use our own
namespace.

**Comment by tkrokli** [comment]
@vbjay : Thanks for commenting and confirming that information. :+1:

**Comment by EbenZhang** [comment]
The appid has already been set in `FormBrowse.cs` -> `BrowserLoad`. 

 `TaskbarManager.Instance.ApplicationId = "GitExtensions"`

Maybe it's not enough or not correct.

**Comment by EbenZhang** [comment]
[TaskbarTweaker](http://rammichael.com/7-taskbar-tweaker) shows the that AppUserModelId of the pinned application is the full path of the exe, while in the application we set the applicationid = "GitExtensions" when running, that's why two icons on the task bar..

Moving the `TaskbarManager.Instance.ApplicationId = "GitExtensions"` to the beginning doesn't help (as MSDN says the call must be performed before any UI stuff).
Calling the `SetCurrentProcessExplicitAppUserModelID` doesn't help either.
Removing the `TaskbarManager.Instance.ApplicationId = "GitExtensions"` fixes the icon problem but on the other hand disables the TaskBar features (e.g. jump list).

Hope there would be some mechanism to tell windows the app id when being pinned, or it might just be a bug of windows. It only happens on one of my Windows 10 64 bits PC, while works on my Windows7 64 bits , Windows8 64 bits, and another Windows 10 64bits PC.

**Comment by tkrokli** [comment]
Thanks for the update. I am at least glad that the issue has been looked at as closely as this. :+1:

**Comment by EbenZhang** [comment]
I find when pinning the application, the system will create a shortcut in appdata/roaming/microsoft/internet explore/taskbar/user pinned, but for some reason on the faulty PC the appid is not set for the shortcut(can view the appid using the win7appid utility), while on the good PC it's GitExtensions.

Still uncertain why the system doesnt fill the appid sometimes. Will need more investigation, and probably consult with Microsoft. We could, in the worst case, workaround it by setting the appid for the shortcuts ourselves.

**Comment by tkrokli** [comment]
Nice. Thanks for the thorough information. :+1:

**Comment by EbenZhang** [comment]
After reinstalled the application, the problem disappeared, although the shortcut still doesn't have the appid. It seems the shortcut is not the cause of the problem. Hope someone else can investigate it further since I am not able to reproduce it now.

FYI: Windows 10 has a known issue fixed in the TH2 (see atom/electron#1954)

**Comment by tkrokli** [comment]
At 2015-11-23, 02:03 CET, EbenZhang commented:
> FYI: Windows 10 has a known issue fixed in the TH2 (see atom/electron#1954)

Confirmed. After upgrading to TH2, Version 1511 (OS Build 10586.14) pinning works again. :+1:

**Comment by nathanpjones** [comment]
This is still a problem for me in the latest Win 10 build, but seems to work if I pin a certain way.

1. First unpin any existing icon from the system tray.
2. Run the app and open up any repository. You'll probably see the taskbar icon disappear and a new one appear to take its place.
3. Pin the current taskbar icon.

**Comment by tkrokli** [comment]
Sounds like an icon caching issue in Windows, but I don't know for certain if that is the case for you.

**Comment by nathanpjones** [comment]
I tried it the usual way many times with the duplicate icon result. Also, I didn't mention but the recents list only worked with the "fixed" icon.

From what @EbenZhang mentioned above about missing appid my guess would be that Windows 10 is deducing a different one for the initial app instance than the instances that have a repo loaded.

**Comment by vbjay** [comment]
Noticed that starting multiple instances group together under one icon.

**Comment by vbjay** [comment]
That is what  noticed too.  Something about loading a repo does it.

**Comment by RussKie** [comment]
Please re-open if it is still a problem with 2.50

**Comment by eric-wieser** [comment]
Still a problem for me on 2.50

**Comment by tkrokli** [comment]
Confirmed. It happens with my version 2.50.02 on Windows 10 1703 (OS Build 15063.608). I had forgotten about this for some time because I had stopped pinning it to my taskbar for quite some time ... until now.

**Comment by RussKie** [comment]
It is happening on w10 but not on w8 for me

**Comment by wolfen351** [comment]
I can confirm this occurs on W10 Version 10.0.16299.248 - If you pin it without opening it, or pin it before opening a repository you end up with 2 icons. However if you pin it after opening a repo, it works correctly. 

It doesn't seem to affect the app opening in any way though, so it's a good workaround..

**Comment by GintasS** [comment]
I can't reproduce this on Windows 10. Might be fixed.
