### ISSUE TITLE
.gitignore and .gitattributes shows in pending changes to be committed

### ISSUE THREAD

**Issue by MishalValiyakath** [gitextensions/gitextensions#3077]
Version 2.48.05 

Sometimes .gitignore and .gitattributes shows in uncommited changes even though there are no changes. So we cannot checkout another branch until we reset or commit them , but the reset is not at all working on these files and keep on hanging in staging area. Anyone has faced this and resolution for this ?

**Comment by TamaHobbit** [comment]
If you open a terminal and do git status, are they there? Because if so, this is not a GitExtensions issue, and should be asked on a general git forum. Quite probably this is a line-endings issue. Unless you are able to switch branches in gitbash but not in GitExtensions, this issue should be closed
