### ISSUE TITLE
 repository error, please help to use git Extensions App for Microsoft 

### ISSUE THREAD

**Issue by samehgeorge89** [gitextensions/gitextensions#3160]
I received the following error during using my gitextension app.

Host key verification failed.
fatal: Could not read from remote repository.

please help 

regards,
Sameh

**Comment by hypersw** [comment]
Are you using OpenSSH? Have you connected to the same host with OpenSSH on this machine before?

**Comment by samehgeorge89** [comment]
first of all thank you so much for your reply and ask for helping me much much appreciated.

No I just downloaded the git extension it self and tried a plugin for oUAth token it worked and git the repos names but did not cloned. just give me the error.

would you please help me if I need to download a program like u mentioned or if there is any commands needs to request with to the git hub repository.



Host key verification failed.
fatal: Could not read from remote repository.

regards,
Sameh

**Comment by hypersw** [comment]
These things are built-in with git.
This might be from these reasons:

1. You have already connected to that server from this machine, the server identity has been remembered, but has since changed. Now the new identity does not match the old one.

2. The server is not yet known, and `git`/`openssh` is trying to ask you interactively whether it's allowed to use this server, but the release version of GitExtensions cannot support interactivity in `git` console windows yet.

3. Smth else. I haven't tried oAuth.

For 2, there's a [beta version](https://github.com/JetBrains/gitextensions/releases/tag/2016-03-14) which fixes interactivity. Though I'm very unsure if this is the issue in your case, but it might be easier to just try and see. Or wait for smb more knowledgable of git and oauth to help.

**Comment by samehgeorge89** [comment]
thanks so much for your help much much appreciated. I will try that. \


regards,
Sameh
