### ISSUE TITLE
Force push button no longer work after the ConEmu integration

### ISSUE THREAD

**Issue by EbenZhang** [gitextensions/gitextensions#3173]
Steps:

- Rewrite history of a branch
- Push the branch to remote repo
- GitExtensions will popup a rejection dialog
- Press the Force Push button
- The dialog closes immediately and nothing happened

**Comment by EbenZhang** [comment]
@hypersw where is the source code of the `ConEmuWinforms`? Checked your `conemu-inside` repo, but seems not the one used in GitExtensions, or the code in your repo is not up to date?

**Comment by hypersw** [comment]
For historical reasons, it's in the `winforms` branch.
I think it should be merged as soon as I write appropriate `readme`s.

**Comment by EbenZhang** [comment]
Your repo Has master branch only.

**Comment by hypersw** [comment]
https://github.com/maximus5/conemu-inside/tree/winforms

**Comment by phillijw** [comment]
Has conemu stuff even been merged into 2.49? I'm not seeing it

**Comment by pmiossec** [comment]
@hypersw Can you give some love to that? 

The problem, in my opinion, is due to the fact that the retry with the force push is done in the `ConsoleProcessExitedEventSink` event. So that prevent the `ConEmuStartInfo` instance to be disposed BEFORE running the force push one :(

We've got the error:

    System.InvalidOperationException: Cannot start a new console process because another console emulator session has failed to close in due time.

I think that there is 2 other problems more or less linked:
- I think that `_terminal` should be disposed
- Orphan processes `ConEmuC64.exe` are stacking, the one of the original push that failed. See the image...
![gitextensions_forcepush](https://cloud.githubusercontent.com/assets/460196/16850161/2474faaa-49fe-11e6-80a3-feddd5b662b2.png)

@hypersw Another thing not directly linked. You put `CommandLineBuilder` internal in ConEmu that prevent `ConEmu.Control.WinForms` to be updated to the last version. Could you find a solution for that?

**Comment by pmiossec** [comment]
@hypersw Sorry to insist but this bug is IMHO the last real bug blocking the release and preventing to use GitExtension. That was introduced by #3152 and sorry to bother you but you said you will have a look at it! ( https://github.com/gitextensions/gitextensions/pull/3152#issuecomment-210904039 )

**Comment by pmiossec** [comment]
Hey @hypersw, that's me again. Did you have a look at this problem? A little fix will be much appreciated!

**Comment by vbjay** [comment]
https://github.com/Maximus5/conemu-inside/commit/857eb7c45f0ded41eab214faa36d13fe7c9960d2#commitcomment-18371522 Is an issue when upgrading the nuget package.
