### ISSUE TITLE
Git Extensions fails to install on Windows 7

### ISSUE THREAD

**Issue by xyduan2000** [gitextensions/gitextensions#3175]
I tried to install Git Extension 2.48.05 and the intaller gave me the following errors even though I logged in under an Admin account,

The installer has insufficient privileges to access
this directory :C:\Users\usdadua\Documents\
...\Addins. The installation cannot continue. Log
on as administrator or contact your system
administrator.

**Comment by KindDragon** [comment]
Try disable VS addins in installer

**Comment by guban** [comment]
The problem could be caused by Windows User Account Control (UAC).
UAC can cause silent "insufficient privileges" failures when access filesystem if the installer is not run "as administrator" (even if you are logged on under an Administrator account!).

First, go to "Control Panel/User Account Control Settings" and report how UAC is configured in your case.
Second, try to reproduce the problem with UAC completely disabled. Chances are that installation will succeed.
Third, with UAC back to is original setting, try running the GitExtensions installer as administrator (even though you work under Administrator account, running as administrator could make a difference). When running as administrator, you might get UAC prompts during the installation. Please report whether you get some.

If UAC is indeed the cause, the problem could be solved by forcing the installer to be run "as administrator".
