### ISSUE TITLE
Add Build server integration for TFS-Build 2015

### ISSUE THREAD

**Issue by DanielTheCoder** [gitextensions/gitextensions#3177]
Microsoft introduced a [new build service ](https://msdn.microsoft.com/en-us/library/vs/alm/build/overview)with TFS 2015 which is also used with VSTS (Visual Studio Team Services). The existing TFS-integration only supports XAML build system which was previously used.
For the new introduced build system there is a new [rest based api](https://www.visualstudio.com/integrate/api/build/builds), similar to teamcity's api which can be used to gather the required build status information (can be used to fetch new build and xaml builds).

To support pre TFS 2015 installation I would suggest to leave the existing plugin as is and introduce a new plug-in for TFS 2015 and upwards.

**Comment by kine** [comment]
I have developed what is needed to see the TFS 2015 builds in the client. I extended the existing tfs 2013 plugin (as TfsInterop.Vs2015), because the REST api does not filter XAML builds correctly (using TFS 2015 Update 2) based on the date (returning all - which is too slow having few years of builds in the system). Thus I am reading XAML builds in old way and new builds through REST. But it depends on pull-request #2916, which was not pulled yet.

**Comment by DanielTheCoder** [comment]
Nice. When writing this issue, I was expecting that we don't need vs or tfs client sdk installed. Eg: Using vscode and gitextensions together ....
I can definitely think of scenarios were xaml and tfs2015 build definitions are used in one project. I'm not sure how both scenarios can be supported in an optical way.

**Comment by pmiossec** [comment]
>Thus I am reading XAML builds in old way **and new builds through REST**

@kine Good news. Could we see some code?

**Comment by kine** [comment]
See the pull request for code. As I wrote, I have used API libraries and not bare REST.

**Comment by kine** [comment]
Just want to add, that it should work with the Team Foundation Service as well with small changes (old XAML builds will need to be disabled and the authentication will need to be changed).
