### ISSUE TITLE
There is no base revision for (filename).  Fall back to 2-way merge?  Responses are swapped

### ISSUE THREAD

**Issue by aweintraut** [gitextensions/gitextensions#3184]
Performing a merge, received the above message.  If I select "Yes", I get the 3-way merge.  If I select "No" I get the 2-way merge.

**Comment by vbjay** [comment]
Check your settings for the diff and merge tool.  Make sure the values are
being passed correctly.   Which tool are you using?

**Comment by aweintraut** [comment]
![image](https://cloud.githubusercontent.com/assets/13574789/14691697/af1ece5e-0720-11e6-88a6-dbced67d4e3f.png)

**Comment by jbialobr** [comment]
I think the root cause is described in #1844

**Comment by phillijw** [comment]
I made a note on #1844. Basically we should not be using the diff tool command for the 2-way merge. If you can't specify an output file, it doesn't really do us any good. It would be nice to have another option to specify the command for a 2-way merge instead since we could actually set it up with an output file
