### ISSUE TITLE
Staging files with new line warning show empty window

### ISSUE THREAD

**Issue by KindDragon** [gitextensions/gitextensions#3189]
Staging files with new line warning show empty window after ConEmu merging

![gitextensions](https://files.gitter.im/gitextensions/gitextensions/r8Ft/________-2016-04-22-00.48.21.png)

**Comment by phillijw** [comment]
It doesn't appear the conemu feature has been merged to 2.49 yet

**Comment by KindDragon** [comment]
2.49 would be released from master

**Comment by jbialobr** [comment]
@hypersw FormStatus is shown [here](https://github.com/gitextensions/gitextensions/blob/fb696e47837ad2711c28b23d3a770cee2c986f24/GitUI/CommandsDialogs/FormCommit.cs#L1307) and [when output message is passed to the form](https://github.com/gitextensions/gitextensions/blob/fb696e47837ad2711c28b23d3a770cee2c986f24/GitUI/CommandsDialogs/FormCommit.cs#L1303) `_terminal.RunningSession` is null because no command was executed. If the RunningSession is null, the output message is not appended.
