### ISSUE TITLE
Performance issue with diff for stash of untracked files

### ISSUE THREAD

**Issue by Do-do-new** [gitextensions/gitextensions#3203]
Diff on stash from untracked files shows all files in the repo in diff ListView.
This is correspondent with the behavior of git diff --name-only in the console (still should check why).
However in, let's say bash, you will press 'f'', 'p' and 'q' and will be okay, but here we update ListView.

In big projects (thousands of tracked files) it looks like the program just hangs (though it is actually just loading ListView).

This calls at least for an indicator that diff is being loaded. 

Way to reproduce (screenshots will be from the source of gitextensions, there it is relatively quick, but it is a problem for bigger projects):
touch A
git stash save -u

Then we can see:

![image](https://cloud.githubusercontent.com/assets/16781381/15269697/af0b76d4-1a07-11e6-95f4-93a12367df84.png)
...
![image](https://cloud.githubusercontent.com/assets/16781381/15269699/bdb4cda2-1a07-11e6-9717-46760f1fdfb0.png)

Or the same if we select exact "parent":
![image](https://cloud.githubusercontent.com/assets/16781381/15269702/d488639a-1a07-11e6-97cc-c5b8fe8a4cba.png)

Also eventually I would like to add mode with a different tree (without stashes, separate lines, like in SourceTree + may be with ancestor order left-to-right). But that's a story for another day.

Anyway, because of consistency with git log current tree is also viable.

**Comment by vbjay** [comment]
Stash creates 3 commits Untracked files, the state of the staging area, and
a merge of those two commits.  Git extensions shows it correctly.

**Comment by Nochdarus** [comment]
I totally agree that GitExtensions shows it correctly.
However, my point is about timing, not about correctness.

As you said, Untracked files is a separate commit. And this commit doesn't have any parent. It only references a tree which references stashed untracked files.

Thus, when we click on stash in revision graph, it shows diff with also this "Commit of untracked", which results in showing _all_ tracked files in the repository (because the tree which is referenced by "Commit of untracked" simply doesn't have them) + stashed index + untracked stashed files.

On a big repository (~10K tracked files) it looked like GitExtensions just hangs, though actually it was loading ListView with those 10K files. Which took a while.

**Comment by vbjay** [comment]
I see.  Missed your point.  Thanks for the clarification.  Couple of ideas.


1.  LImit the number of items and do a paging system using virtual mode.
2.  Do more of that in a background thread.

**Comment by Nochdarus** [comment]
I think I'll try to use VirtualMode for that.

**Comment by Nochdarus** [comment]
The problem with virtual mode is that it is a bit tricky to have VirtualMode and Groups at the same time (however, possible).

By the way, this custom control works just fine http://objectlistview.sourceforge.net/cs/index.html

(Except that there grouping is kind of extension of sorting, since grouping is done on per-column basis)

If you already considered using it, may be I should just put it in?

On the other hand, if you dislike it by some reason, I can either try to have both groups and virtual mode as described here
http://www.codeproject.com/Articles/35197/Undocumented-List-View-Features#virtualgroups

or disregard groups all together (But I would rather not do that)

**Comment by Nochdarus** [comment]
Whatever I tried (either using standard VirtualMode or using custom control http://objectlistview.sourceforge.net/cs/index.html)
there is some flickering after all.

Any ideas?

**Comment by vbjay** [comment]
https://msdn.microsoft.com/en-us/library/system.windows.forms.listview.beginupdate(v=vs.110).aspx

**Comment by Nochdarus** [comment]
@vbjay Of course this is used. But with 1000+ changed files updating even once takes unacceptably long.

**Comment by vbjay** [comment]
With virtual mode, you only load enough for the current window.   You load
more when needed.  You don't load the full set.

**Comment by Nochdarus** [comment]
Yeah, that's also clear. Sorry, I thought you mentioned BeginUpdate() irrespective of VirtualMode. 
But the problems which I observed while using VirtualMode are different from speed problem (which is only natural, since, as you said, only current window is loaded).
These problems are:
1) Flickering when scrolling (especially if you have an entry selected).
2) It is somewhat ugly code to add support for groups in VirtualMode (but it is not the topic now)

**Comment by vbjay** [comment]
Generate the listview items in a background thread. Once generated.  Load all items in the listview inside of beginupdate/endupdate call.  Show an ajax spinner over listview when generating items.

**Comment by vbjay** [comment]
http://www.ajaxload.info/

**Comment by jbialobr** [comment]
Perhaps it is enough to only show the diff with the first parent for a merge commit that the stash points to. The other diffs don't provide any additional information that couldn't' be read from the commit for "untracked".

**Comment by Nochdarus** [comment]
In fact the speed is acceptable even in case of several thousand files now. Current master works quite okay. From my point of view it can be closed.

**Comment by GintasS** [comment]
I would close this one too, but if someone could check the speed, would be nice, but @Do-do-new says that it's alright now.
