### ISSUE TITLE
Flags don't stand for languages

### ISSUE THREAD

**Issue by tueena** [gitextensions/gitextensions#3243]
Don't use flags to identify languages. Flags are symbols of nations. Nations have often more than one official language. Many languages are the official language in more than one country. People maybe don't know the flags of other countries (that should symbolize their preferred language) or just dislike them (maybe because of the history of colonization) - maybe they dislike flags at all (because they stand for the system of nations, identification with nations (nationalism), governments, borders and so on). But anyway: They do not represent languages, they cannot even be mapped to languages in many cases.

**Comment by IDisposable** [comment]
:100:

**Comment by KindDragon** [comment]
What then show instead?

**Comment by ghanique** [comment]
I searched Google images for "choose language". I see *many* screens that
show flags. I'd just keep the flags. Especially is the language is below
the flag in text I don't see the problem.

**Comment by tueena** [comment]
> What then show instead?

There are no icons for languages. I would just use text.

> I searched Google images for "choose language". I see *many* screens that show flags.

Many, many bad ideas and concepts are very, very common. Why not make it better, where it's so easy?

> I don't see the problem.

What about my arguments? Can you please make concrete, why they are irrelevant.

**Comment by vbjay** [comment]
Makes it a lot easier to find. As he said, the names are below the flags.

**Comment by tueena** [comment]
> Flags ≠ Languages
> 
> Flags must be used with great caution, if at all. For example, what flag should be used to represent Spanish? Or, for that matter, English? And what language would users expect if they clicked on the flag of Switzerland—a country with four official languages?
> 
> There are geopolitical issues related to flags to be aware of as well. Companies that offer websites for China and Taiwan have found the Taiwanese flag can be offensive to Chinese nationals who feel that Taiwan is not a country in its own right. Dell, for example, removed its Taiwanese flag nine years ago. It continues to use flags on all other country websites. And Dell is not alone; many other companies have since followed suit.

http://uxmag.com/articles/select-country-select-language

I don't think nationalist claims to power are a good reason, but it is an example, that illustrates the problem. Why should a guy from Venezuela click on a Spanish flag, to choose his language? I understand the argument, that an icon helps finding the things better. But is it worth that? I for example have the German nationality. But I don't identify myself with this or any other nation. I have never signed an agreement to be ruled by anybody. There are very few anarchist in the world at these times, so maybe our (reasonable) rejection of nations have no relevance to you, but thats only one of many reasons, people don't like fags or having to choose (other nations) flags. Flags are symbols of ideologies.

> Iconography for translations: best practice for communicating availability of translated content

http://www.flagsarenotlanguages.com/blog/iconography-for-translations-best-practice-for-communicating-availability-of-translated-content/

**Comment by ghanique** [comment]
I live in the Netherlands. Our food comes from the Netherlands, Belgium,
France, Germany and sometimes from Scandinavian countries. Many of those
products have instructions and ingredients in different languages where
each language is preceded by, you guessed it, a flag.

Let's spend time fixing bugs and keeping the product up to date and not
waste effort because a Mexican guy doesn't want to click the Spanish flag.
(Then click the text "Spanish" for god's sake). Git Extensions is a tool
for developing software. What does politics have to do with it? Focus!

If someone can come up with a better solution than using flags then let him
build it. IMHO a solution where I have to read all the texts instead of
graphical representations is not a better solution.

You know what? I don't really care after all. You have to select a language
only once.

**Comment by tueena** [comment]
> What does politics have to do with it?

Yeah. Thats what I'm talking about! What have politics have to do with it. Throw it out!

> You know what? I don't really care after all. You have to select a language only once.

Yes, so why keeping those politics in, if its just a selection, you do once.

**Comment by tueena** [comment]
> What does politics have to do with it?

Yeah. Thats what I'm talking about! What have politics have to do with it. Throw it out! The flag makes it political.

> You know what? I don't really care after all. You have to select a language only once.

Yes, so why keeping those politics in, if its just a selection, you do once.

**Comment by ghanique** [comment]
Fine. Then let's change it.

And while we're at it let's change some other windows as well. The commit
window seems to have a cross because it's divided in four sections; that
cross is religious. I mean, where does it end?

But as I said, I only have to select the language once, so why bother.
Create yourself a pull request.
