### ISSUE TITLE
ConEmu can't open vim

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#3268]
Running this command:
`git rebase  -i --no-autosquash "refs/heads/master"`

results with this:

![2016_07_18_13_16_39_gitextensions_jb_testrebase_git_extensions_debug_](https://cloud.githubusercontent.com/assets/1003909/16913364/173f1d72-4cea-11e6-9bac-ed960693fccb.png)

**Comment by hypersw** [comment]
That's not exactly true, for generally ConEmu is able to run `vi`, separately or as a part of the `git` command which would open an editor (if editor is configured to be `vi` in gitext settings).

Does it fail always, or would it sometimes succeed? What happens if you do a gitext GUI command which causes an editor to be shown in the process?
Why the Chinese letters, does it have something to do with locale or other system settings?

**Comment by jbialobr** [comment]
Here is how it looks when run inside the GitExt. It runs and responds to commands, but displays mojibakes. My locale is pl_PL.
![2016-07-15 12_34_46-gitextensions master - git extensions -_ debug _-](https://cloud.githubusercontent.com/assets/1003909/16928672/2b6af556-4d34-11e6-92d1-0934a3a910a1.png)

**Comment by hypersw** [comment]
@Maximus5, any ideas?

**Comment by Maximus5** [comment]
That looks like console app tries to output using UTF-8 encoding, but `chcp 65001` was not called before.
Also, that may depends on `LANG` environment variable. Anyway, that's must happen outside of ConEmu, if environment variable sets are the same in both windows.

**Comment by jbialobr** [comment]
It seems to be a msysgit problem. When I installed the latest version (2.9.0.windows.1) it works perfectly.

**Comment by hypersw** [comment]
Were it msysgit 1.x?

**Comment by jbialobr** [comment]
Yes, it was 1.9.4-preview20140929

**Comment by hypersw** [comment]
Have never tested against <2.0, that was too long ago, and 2.0 is dramatically better.
