### ISSUE TITLE
Are GitExtensions dead?

### ISSUE THREAD

**Issue by TonyAntonucci** [gitextensions/gitextensions#3326]
It's been over a year since an update. I use GitExtensions daily, and feel its the best GUI for git on Windows. So, I hope it's not dead, but if it is.....what is the next best GUI?

**Comment by vbjay** [comment]
Look at the commit history.

**Comment by miparnisari** [comment]
No it's not dead. In fact it seems like there will be a new release soon: https://github.com/gitextensions/gitextensions/milestone/16.

**Comment by leak** [comment]
It does indeed feel dead or the priorities are very intransparent.

Two of the issues on that milestone are ancient and pull requests are stacking up (never a good sign).

**Comment by miparnisari** [comment]
![image](https://cloud.githubusercontent.com/assets/5374887/18820603/6402d74a-8375-11e6-91e4-129f008a4968.png)

=)

**Comment by pmiossec** [comment]
>It does indeed feel dead or the priorities are very intransparent.
>Two of the issues on that milestone are ancient and pull requests are stacking up (never a good sign).

I really don't understand such a comments :(

GitExtensions is an opensource project so feel free to help if you want to see the things move (faster).

If you are here, that's because you think that some things should change, feature added or bug fixed otherwise if it's already perfect, you don't care if it's dead because it already suits you and you could use it as is!!!

If that's the case, there is a lot you could do to help (instead of whining).

You could at least open issues (or contribute to an existing one) to report problems.
Even better, make a code review of a pull request to help merge the pull request fixed and merged quicker. Or test these pull requests to report problems or if it works well for you, that help the mainteners to know the interest given to a feature and free some of there time to fix other bugs... 

And you could also help to translate: #3333

I also think that GitExtensions is not released enough often ( I prefered a 2 or 3 months release period) but instead of complaining, I have taken the time to fix 2 or 3 bugs blocking the release.

You could also contribute. Do not hesitate!!! Every help is welcomed.

**Comment by leak** [comment]
> I really don't understand such a comments :(

I don't understand your comment either since it has literally nothing to do with the original question. ;)

But since you quoted me directly, I try to clarify some things for you.
1) It appears you misread some sort of accusation into the original question and my comment. It is a plain and simple question based on 3 facts (time since last release, tickets on the next milestone and open pull requests)

2) Nobody asked for an open source contribution speech. Personally i worked on various OSS projects but you can't be a contribute on every single one, for some you are just a user which I am in this case.

3) Accusing people of "whining" when clearly there is none is kind of condescending, I'd be a bit more careful with that.

As @miparnisari pointed out the milestone milestone actually was completed. Apparently there have been  other issues added to the milestone since the completion which dropped it below 100% again, but needless to say there is a soonish release pending.

Also I agree with you about the release cycle, having a release no matter how small every couple of month or so might not also get features/fixes to the users faster, it might also help avoid confusion about the projects health and avoid tickets like this one.

**Comment by brcaswell** [comment]
this isn't a forum for general discussions.  put that in a blog or something.

(though the fact that this comment hasn't been closed in 23 days does indicate there is an issue.. but not in the context of this repository)

**Comment by phillijw** [comment]
2.49 is basically ready to be released. There's just one last issue waiting to be looked at. To me, it's an issue that can be handled later though...

**Comment by KindDragon** [comment]
[2.49RC1](https://github.com/gitextensions/gitextensions/releases/tag/v2.49RC1) released 👍

**Comment by KindDragon** [comment]
[2.49RC2](https://github.com/gitextensions/gitextensions/releases/tag/v2.49RC2) released

**Comment by KindDragon** [comment]
[2.49](https://github.com/gitextensions/gitextensions/releases/tag/v2.49) released

**Comment by pmiossec** [comment]
Well done! :fireworks:

**Comment by thorade** [comment]
For projects hosted on github, in addition to looking at the commit history, one can look at the "pulse" page:
https://github.com/gitextensions/gitextensions/pulse
https://github.com/gitextensions/gitextensions/pulse/monthly
