### ISSUE TITLE
Improve usability of stash dialog

### ISSUE THREAD

**Issue by phillijw** [gitextensions/gitextensions#3401]
In other git gui's you can name your stashes for later use. While looking into this, I think the whole stash window/functionality could use an overhaul at this point as it isn't very friendly. Anyone have any ideas for new concept designs?

**Comment by vbjay** [comment]
You can.

**Comment by phillijw** [comment]
...How? I've tried several things with no success.

**Comment by vbjay** [comment]
![image](https://cloud.githubusercontent.com/assets/3629489/19988869/274b77ba-a1f9-11e6-9fe1-ebd776422722.png)

**Comment by phillijw** [comment]
Ah, neat. I always try to type in the box at the top expecting it to do something.

**Comment by marazt** [comment]
Now, when I have to use more stashes that normally on a project (>5) , I came with similar idea - what about to have a stash message instead of stash{N}. I have prepared the change, so if there will be interest, I can create a pull request.

![stash-sample](https://cloud.githubusercontent.com/assets/323018/20769397/05bafc34-b742-11e6-972b-208c30b17561.png)

**Comment by gerhardol** [comment]
In 3.4 or so the naming of stashes was changed to just add the message by editing.
