### ISSUE TITLE
Commit Window Position

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#3462]
If the main window is near top left corner then the commit window can be positioned so that part of the window is cut off.  
![image](https://cloud.githubusercontent.com/assets/3629489/21296412/0a9c6012-c539-11e6-9f20-736dfd480236.png)

![image](https://cloud.githubusercontent.com/assets/3629489/21296416/1beecaa8-c539-11e6-84b3-40c32376080f.png)
![image](https://cloud.githubusercontent.com/assets/3629489/21296421/47747c7c-c539-11e6-8b0a-3d5197d6e34d.png)

**Comment by slvr9** [comment]
Version 2.50.01 - this drawback is present.

This causes inconvenience when working in multi monitor systems. When the main window on one monitor and a "commit window" I want to place on another. 

Sorry for my English robot translation.

**Comment by RussKie** [comment]
> When the main window on one monitor and a "commit window" I want to place on another.

The app remembers positions of its window, so if you had the commit dialog opened on one monitor, then moved to another and then closed - it will open up again where you closed it. Whether you moved the main window to another monitor is immaterial.

An argument can be present from both sides - to open a modal dialog on the monitor where the parent is; or open it where the user has moved it to.

**Comment by KvanTTT** [comment]
> An argument can be present from both sides - to open a modal dialog on the monitor where the parent is; or open it where the user has moved it to.

Can GitExtension supports both with setting? But I like the last one.

**Comment by RussKie** [comment]
The last option is fraught with own sets of problems in multi display
environment - windows get lost or opened outside visible areas....

**Comment by KvanTTT** [comment]
For me, it's contrary not a problem. That is what I'm needed in.

**Comment by mstv** [comment]
Usually, the previous window position is restored.
@RussKie has added an algorithm which moves the window (only) if too much of the title bar is invisible. So one should always be able to drag the window.

<kbd>Alt</kbd>+<kbd>Space</kbd> opens the window menu. I see no difference to the main window. `Maximize` should always work.

**Comment by apar945** [comment]
I have also experienced this issue when plugging in a different monitor, as opposed my original set of monitors. This happens when I work from home. As a workaround, I use the keyboard shortcuts to move the commit modal window to my current monitor.

Follow these steps:
1. Click on the "Commit" button in git extensions main window.
2. Hold down the ALT key.
3. Press SPACEBAR.
4. Press M (Move).
5. A 4-headed arrow should appear but you can't see as it is not on the current set of monitors connected. Use your arrow keys to move the outline of the window.
6. When you are happy with its position, press ENTER.

Note: This only works if the modal window is not maximised. If it is maximised, then you would need to first try "R" to restore to non maximised state. Then follow the above steps.

**Comment by RussKie** [comment]
Which version?

**Comment by apar945** [comment]
> Which version?

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.30.0.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4360.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Please update to 3.5.1
