### ISSUE TITLE
GitCredentialWinStore missing

### ISSUE THREAD

**Issue by flip111** [gitextensions/gitextensions#3511]
Hi, i just installed the latest GitExtensions-2.49-SetupComplete.msi i'm getting an error that in the credential store is not there. I checked that the directory `GitCredentialWinStore` is missing from `C:\Program Files (x86)\GitExtensions`. I also searched the documentation for `GitCredentialWinStore` and `credential store` but no results. Where can i get this missing functionality?

**Comment by u-abramchuk** [comment]
Hi, the same here. Also tried to install it separately, but git just doesn't see them.

**Comment by flip111** [comment]
I think i solved this problem after removing both git and git extensions from my pc and then reinstall both .. but it's still a strange situation to occur without any information about what's going on so i will leave the issue open

**Comment by u-abramchuk** [comment]
Thank you for the advice. I tried that as well, but only reverting back to GitExt v. 2.48.05 allowed me to use git as it used to be. Still struggling with 2.49.

**Comment by KindDragon** [comment]
GitCredentialWinStore removed from installer, because it now included in Git installer. So just update to latest Git https://git-scm.com/

**Comment by u-abramchuk** [comment]
Not sure about the reason but after a few re-installs and restarts 2.49 started to work as expected.

**Comment by flip111** [comment]
I leave this issue open because i think it's worth to have GitCredentials warn about git version being too old (missing GitCredentialWinStore) and not supplying own GitCredentialWinStore.

**Comment by RussKie** [comment]
instead of GitCredentialWinStore I use the following:

```
[credential]
	helper = manager
```

and 

```
[credential]
	helper = wincred
```

perhaps the source may need to be updated to no longer use GitCredentialWinStore since it is obsolete

**Comment by pmme** [comment]
I don't see another post with a clear explanation of the problem and a way to fix it, so here goes:

Historically GitExtensions' installer included the credential helper git-credentials-winstore.exe and it set the git global configuration entry `credential.helper` to the path to its file.

Move along to GitExtensions 2.49 and git-credentials-winstore is no longer distributed in the GitExtensions installer and it no longer tries to set the git variable `credential.helper`. The current versions of git for Windows include a credential helper for windows called "wincred".
However, your git configuration still contains that entry to use git-credentials-winstore, a credential helper that's now missing from your computer.

If you update git it doesn't change the setting. As far as git is concerned you have chosen to use that credential helper so it shouldn't change it.
If you uninstall and reinstall git then it appears to fix the problem (according to flip111's comment above) and this would most likely be because it removes your old git configuration and recreates it.

You can remove the old setting with the following command: 
`git config --global --unset credential.helper`. 
After this you will need to enter your username and password when pushing.

You can switch to using git's wincred with the following command: 
`git config --global credential.helper wincred`.

You could download the successor to git-credentials-winstore: [Git-Credential-Manager-for-Windows](https://github.com/Microsoft/Git-Credential-Manager-for-Windows). You will still need to change the `credential.helper` setting with a command similar to that above, unless their installer does that for you.

You can read about credential helpers here: https://github.com/Microsoft/Git-Credential-Manager-for-Windows

**Comment by RussKie** [comment]
Good stuff!

**Comment by RoLYroLLs** [comment]
For completeness (an explain it a way a newbie might understand, maybe?), and anyone who likes/prefers to manually update their `.gitconfig` file (I'm a noob and I like to manually update so I know exactly what is happening so I learn) and wants to use the credentials helper installed by Git, do like @RussKie shows:

1. open your `.gitconfig` file
2. look for `[credential]`

it should look like this (if you've never made changes)
```
[credential]
	helper = !\"C:\\Program Files (x86)\\GitExtensions\\GitCredentialWinStore\\git-credential-winstore.exe\"
```
and make it look like this:
```
[credential]
	helper = wincred
```

**Comment by pmme** [comment]
@vbjay that was exactly my suggestion in issue #4179

**Comment by vbjay** [comment]
Great minds think alike :D.

**Comment by RussKie** [comment]
PRs are welcome ;)

**Comment by RussKie** [comment]
Please have a look at #5132.

**Comment by borgogelli** [comment]
So what are the differences between the "wincred" and the "manager" helper ?

**Comment by RussKie** [comment]
I think they are essentially the same thing (for Windows)
https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage

**Comment by vbjay** [comment]
Yes but manager is the better one. It supports more and we obsoleted the
non manager one for a reason.

**Comment by gerhardol** [comment]
wincred (git-credential-winstore) was previously included with Git (that GE set some defaults for previously).
manager [Git-Credential-Manager](https://github.com/Microsoft/Git-Credential-Manager-for-Windows) has replaced wincred in the Git distribution, but still remains in some documentation. There may even be some migration support within git-for-windows, unless the paths are set.
