### ISSUE TITLE
Column resizing does not work as expected

### ISSUE THREAD

**Issue by iinnkkyy** [gitextensions/gitextensions#3580]
--- GitExtensions2.49, Git 2.10.1.windows.1, Microsoft Windows NT 6.1.7601 Service Pack 1

Column resizing does not work for me as expected in GitExtensions main window.

I had an issue that the right-most column in the grid (the one which lists the commit date) was too narrow, partially obscuring the end of the date. 

I tried to resize the column normally: hover the mouse pointer over the column divider until I see ⬄ ("left right white arrow") symbol appear, press mouse button, hold, and move the symbol towards the left. This did not resize the date column, but unexpectedly had an effect a column to the left of it (commit author column): it's left border moved towards the right, making the column narrower. 

I experimented with this a bit. 
Attempts to move the left divider of commit date column to the right: instead of making date column narrower, makes the commit author column wider by moving it's left divider to the left. 
Attempts to move left divider of commit author column: no effect regardless of direction.
Attempts to move right divider of date column to the right (yes, I can get ⬄ on it even though it's at the right edge of the window) : no effect
Attempts to move right divider to the left: date column gets narrower. 

No matter what I try, I cannot make date column wider.

**Comment by EbenZhang** [comment]
>Attempts to move the left divider of commit date column to the right: instead of making date column narrower, makes the commit author column wider by moving it's left divider to the left.

the `left divider of commit date column` is in fact the `right divider of the author column`

> Attempts to move left divider of commit author column: no effect regardless of direction.

the `left divider of commit author column` is the `right divider of the commit message column`, we have set the commit message column to fill the datagridview thus not resizable unless we have another column set to fill, e.g. Build Server Integration.

> Attempts to move right divider of date column to the right (yes, I can get ⬄ on it even though it's at the right edge of the window) : no effect

This is natural for the last column, because the mouse is out of the view. Not sure if there is a workaround without affecting the horizontal scrollbar.

> No matter what I try, I cannot make date column wider.

Yes, you can only narrow it. A workaround is to show the SHA, right click any commit, select the view menu item, select `show SHA1`. By adding the SHA1 column, the date column becomes 2nd last column hence resizable.


The column should have enough space to display the date. Do you have a special setting for date format? How does it look on your system? Maybe we just need to fix the format or make it a bit wider.

**Comment by iinnkkyy** [comment]
@EbenZhang, thanks for the prompt answer! 

Your work-around (show SHA) works. Thanks!

I think the reason for my issue is that I played with fonts and font sizes (I think "Application Font" is relevant for this problem) when I tried to get GitExtensions to look better on my 4K external monitor. 
Currently I have Application Font set to Segoe UI, 10.

When I start GitExtensions regularly, I see most of the date, in most cases only "M" in "AM" or "PM" is obscured (although for times with double-digit hour like "12/23/2016 12:46:25 AM", the whole "AM" is obstructed). 

When I try to start GitExtensions with "Disable display scaling on high DPI settings" compatibility setting, I get nice and sharp fonts, but about 2/3 of the date column is obstructed. (This mode has other issues, but this date thing was the only show-stopper for me).

Please let me know if you have other questions, I will be happy to help in any way I can! :)

**Comment by hhogi** [comment]
In my case the SHA1 column accidentally got narrowed to 4 digits, with could not be reverted, because there is nothing to the right of the SHA1 column.

The work-around for me was to re-install GitExtensions.

**Comment by RussKie** [comment]
dup of #3447 #3603

**Comment by RussKie** [comment]
Can you please verify if it is still an issue in the latest version?

**Comment by iinnkkyy** [comment]
Yes, this is still a problem
