### ISSUE TITLE
Revision details on the right

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#3676]
The latest master now forces the revision details to the right by default
<img width="700" alt="screen shot 2017-04-26 at 10 54 00 pm" src="https://cloud.githubusercontent.com/assets/4403806/25435499/8ce4bea2-2ad3-11e7-88c9-fd52220ac540.png">

It was introduced by https://github.com/gitextensions/gitextensions/commit/180121324d8cc41173cf848c03e6b34874aa9471#diff-fe399207d4534c21f67a65c9ec715343R320

It should be set to `false` so users opt in rather then forcing them to opt out.

Also the setting controlling the behavior is hard to find, without looking through the commit history it could find the necessary setting to return. So it is something that needs improvement.

@jbialobr FYI

**Comment by pmiossec** [comment]
I quite like that feature in my personal wide screen.
But I'm pretty sure that it will not display very well on our small 4:3 screen at work :( (I can't test until released due to security reasons).


Even if I think that it's good to have it by default, an item in the `View` menu should have been interesting.

**Comment by RussKie** [comment]
I wasn't suggesting the feature wasn't useful. It shouldn't be forced on
users, that's all.

**Comment by pmiossec** [comment]
>I wasn't suggesting the feature wasn't useful.

I never said that you suggested it ;-) I presented my point of view. But I think I was not as clear as I wanted. 

>It shouldn't be forced on users, that's all.

Most of the users never configure their tools (for a lot of reasons : interest, time,...).
So, if we agree with that, I think that the better thing we should do as a developer is to make the default settings the better we can.

One advantage is that all the current users that will update will discover this feature. It won't be hidden in settings that they never look at... 

And if they don't like it (I hope less than 50% of the users) , I think they will search how to revert to the previous design. 

And that's here that we could improve by making the revert easy:

* displaying clearly in the release notes how to do it 
* as I tell in my previous message, put the option in the view menu
* perhaps even adding a link towards the settings page directly in the dashboard called "you don't like the new display? Revert to the previous one..." (a new idea for your dashboard redesign ;-) where their could be a place where we display links toward some useful settings. I see 'revision links', 'configuration of start page', 'configuration of build server integration',...)

**Comment by RussKie** [comment]
I think this may alienate users.

Perhaps a better way to introduction of a new feature could involve the following:
- check whether the setting is already configured 
- if not, present the user with a dialog/prompt describing the feature and offering to configure it - "_Hey, we have a new cool feature. Would you like to turn it on? You could have it on the * left * right * original place. Please select_
NB: you could always change your settings at /setthings/browse/setting name"
- remember user's choice and render the UI accodringly

**Comment by mortb** [comment]
Dockable GUI FTW? 
I think that if GE had a dockable GUI it would be easier to customize and achieve this.
Maybe the revision details could default be docked to the right hand side of the main window?

**Comment by vcpp** [comment]
> Most of the users never configure their tools (for a lot of reasons : interest, time,...).
> So, if we agree with that, I think that the better thing we should do as a developer is to make the default settings the better we can.

I see logic trap here. We should do everything as _good_ as we can, it's a trivial statement which is always true, but may be interpreted different ways depending on point of view to what is considered _good_. So, I'd like to say it more specifically. Since most of the users keep defaults, initial settings should provide maximum compatibility. It's about minimizing inconvenience. Having suitable defaults and ability to tune the settings will irritate less than having inappropriate defaults and necessity to fix the settings.

Screenshot from the first message on this thread looks awful. Its resolution is 1828×870 px, most probably it was taken on FullHD display having small dimensions (15" laptop?). I doubt that many developers still use 4:3 displays, but they also certainly exist. Someone with huge widescreen will decide to split it and have two windows on the left and the right halfs. I don't know which usage environment is the most common, but conventional layout seems the most compromise. Personally I have two wide monitors, but there is no empty space on the right side of the GE window due to a bunch of branch lines which take space on the left, and CI build results on the right. Remaining space in the middle is just enough to fill branch names (local, remote, superpoject branches for submodule, tags) and text info (commit msg, author, date). Your mileage may vary.

**Comment by RussKie** [comment]
Thank you.

A little correction - the screenshot wasn't taken fullscreen, at the size I
normally run GE. But even full screen it didn't look convenient or usable.

On 08/05/2017 5:33 AM, "Airat Salikhov" <notifications@github.com> wrote:

Most of the users never configure their tools (for a lot of reasons :
interest, time,...).
So, if we agree with that, I think that the better thing we should do as a
developer is to make the default settings the better we can.

I see logic trap here. We should do everything as *good* as we can, it's a
trivial statement which is always true, but may be interpreted different
ways depending on point of view to what is considered *good*. So, I'd like
to say it more specifically. Since most of the users keep defaults, initial
settings should provide maximum compatibility. It's about minimizing
inconvenience. Having suitable defaults and ability to tune the settings
will irritate less than having inappropriate defaults and necessity to fix
the settings.

Screenshot from the first message on this thread looks awful. Its
resolution is 1828×870 px, most probably it was taken on FullHD display
having small dimensions (15" laptop?). I doubt that many developers still
use 4:3 displays, but they also certainly exist. Someone with huge
widescreen will decide to split it and have two windows on the left and the
right halfs. I don't know which usage environment is the most common, but
conventional layout seems the most compromise. Personally I have two wide
monitors, but there is no empty space on the right side of the GE window
due to a bunch of branch lines which take space on the left, and CI build
results on the right. Remaining space in the middle is just enough to fill
branch names (local, remote, superpoject branches for submodule, tags) and
text info (commit msg, author, date). Your mileage may vary.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gitextensions/gitextensions/issues/3676#issuecomment-299728933>,
or mute the thread

**Comment by RussKie** [comment]
Thank you

**Comment by ltrzesniewski** [comment]
Wow, I was looking for something like this, and I found it only thanks to this discussion.

I had to look at the commit to find the setting in the options, it's waaaay too hidden.
