### ISSUE TITLE
System.ArgumentException: Illegal characters in path

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [gitextensions/gitextensions#3721]
This is a bug, caused by incorrect user configuration.

Current behavior:
If the configuration variable core.editor is not set, doing a git commit results in an exception dialog.

Steps to reproduce:
git config --unset --system core.editor
git config --unset --global core.editor
git config --unset core.editor
echo "" > somefile.txt
git add somfile.txt
git commit

Expected behavior:
Some useful hint what's really going wrong. "Illegal characters in path" is not helpful.
Perhaps check the content of the core.editor configuration and provide a hint that one has to set this.

Affected versions:
Git 2.11.0.windows.3
Windows 10.0.14393
.NET 4.0.30319.42000
I don't know if earlier versions worked.

Stack trace:
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at GitExtensions.Program.GetWorkingDir(String[] args)
   at GitExtensions.Program.Main()

**Comment by thomasw-mitutoyo-ctl** [comment]
This is closed without an associated commit. Does this indicate a "won't fix"?

**Comment by pmiossec** [comment]
@thomasw-mitutoyo-ctl This is a pragmatic action because no one found it enough preoccupying to take the time to fix it (even with the label 'up for grabs') 

So it makes little sense to keep it open during years.

This is the type of edge case bug waiting for a fix by an external contributor encountering it.

The project is an open-source one so live with contributions. The very small development team could not handle every cases and have features and fixes with higher priority to do first....
