### ISSUE TITLE
"Remote branch not specified" dialog truncates display of suggested branch

### ISSUE THREAD

**Issue by RrnR** [gitextensions/gitextensions#3773]
**Do you want to request a *feature* or report a *bug*?**

Report a bug/Request a Feature - both really.  More a suggested improvement

**What is the current behavior?**

When pulling from a remote repo and a remote branch is not specified, the following dialog is offered:

![dialog](https://www.dropbox.com/s/3c777c7blc6jsla/GitEx.jpg?raw=1)

Now I may be confused as a Git newbie, but my assumption is that the first choice "Pull from..." has suggested a branch from the remote repo, but it can't display it because the URL of the repo is too long and renders "..." at the end of the URL instead.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

As above.

**What is the expected behavior?**

Either the dialog be changed to that the entire pull URL be shown, or a mouse hover show a hint with the entire URL.

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**

Probably all.

**Comment by JurjenBiewenga** [comment]
I've been looking into this, unfortunately this does not seem possible with the current API of the TaskDialog as it is not possible to set the flag `TDF_SIZE_TO_CONTENT` in any way. (see [here](http://pinvoke.net/default.aspx/comctl32/TaskDialogIndirect.html) for the options, and [here](https://github.com/contre/Windows-API-Code-Pack-1.1/blob/master/source/WindowsAPICodePack/Core/Interop/TaskDialogs/TaskDialogNativeMethods.cs#L121) for the available flags).

We could change the text from `Pull from {uri/branchname}` to `Pull from {branchname}`, would that be an acceptable fix? @RussKie

**Comment by gerhardol** [comment]
The actual problem is mostly handled in #8517

**Comment by RussKie** [comment]
I'd say there are few issues here.

One issue is the chosen UI is probably not the best for the use case. Instead of trying to guess it should warn the user and then fall back to the pull dialog.
Windows Forms in .NET 5.0 added a support for the Task Dialog, and it provides [support for TDF_SIZE_TO_CONTENT](https://docs.microsoft.com/dotnet/api/system.windows.forms.taskdialogpage.sizetocontent?view=net-5.0#System_Windows_Forms_TaskDialogPage_SizeToContent), but we're still some time away from fully [moving to .NET 5.0](https://github.com/gitextensions/gitextensions/pull/8522).

In lieu of .NET 5.0 you could perhaps try to break down the string "Pull from xxvssadfasdfasdf" to "Pull from" and "asvadsfgasdfgas" as a 2nd parameter to `TaskDialogCommandLink` overload that takes 3 parameters: `TaskDialogCommandLink(string name, string text, string instruction)`.

Given this is rather niche use case, I wouldn't spend too much effort here.

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion.
