### ISSUE TITLE
After upgrading to 2.5 I get error trying to commit, switch branch, etc

### ISSUE THREAD

**Issue by thoward333** [gitextensions/gitextensions#3823]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
Getting error on doing any git command:
"C:\Program Files (x86)\Git\bin\git.exe" pull --rebase --progress "origin"error: Unable to create 'c:/path/to/repo/.git/index.lock': File exists.Another git process seems to be running in this repository, e.g.an editor opened by 'git commit'. Please make sure all processes are terminated then try again. If it still fails, a git process may have crashed in this repository earlier:remove the file manually to continue.Updating 0760adde..55e0ffa0Done

There is no other process that would be touching this repo, since it was freshly cloned. Tried manually deleting the lock and now getting segmentation fault on 'git status'

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Clone repo
2. Checkout a different branch

**What is the expected behavior?**
Switch to other branch

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**
Never got this error in previous versions. Only seeing error since upgrading to 2.5

**Comment by jbialobr** [comment]
What is your git version?

**Comment by thoward333** [comment]
It was the version that came bundled with Git Extensions 2.5. I don't
remember specific version and have since downgraded when I re-installed Git
Extensions 2.49.03

**Comment by jbialobr** [comment]
Perhaps it is the same issue as #3804. It was solved by installing the latest git.

**Comment by thoward333** [comment]
Yep, looks like a duplicate of that. I'll follow those instructions.
Thanks, Janusz.

**Comment by jbialobr** [comment]
Duplicates #3804

**Comment by glen-nicol** [comment]
I still run into this occasionally even with the updated GE & git for windows. Just recently I tried to hard reset a branch through GE and it failed with this error 5 times in a row. I copied the command to command line it ran first try. So it may not be just a git issue. I have noticed it seems to happen more often with repositories with submodules. I posted this here because I do not get the seg fault error as described on #3804

GE: 2.50.02
git version 2.14.2.windows.1
Windows 7 professional 64bit

**Comment by RussKie** [comment]
* What errors do you get?
* What does git command log show? (It is available in one of the last
menues on the right)

**Comment by glen-nicol** [comment]
This is the same error for a different command (commit instead of reset)

> "C:\Program Files\Git\bin\git.exe" commit --amend -F "D:\path\to\repo\\.git\COMMITMESSAGE"
> fatal: Unable to create 'D:/path/to/repo/.git/index.lock': File exists.
> 
> Another git process seems to be running in this repository, e.g.
> an editor opened by 'git commit'. Please make sure all processes
> are terminated then try again. If it still fails, a git process
> may have crashed in this repository earlier:
> remove the file manually to continue.

I have 1 GE running and a couple cygwin consoles open to various places in the repo but not running anything.

As for the git command log, Is there an easy way to export all that to text? There is some paths I need to clean up before posting and doing it line by line sounds exhausting. And I also don't see anything related to the commit failing. Lots of the following though
* diff
* rev-list
* rev-parse
* status

**Comment by vbjay** [comment]
Git is the king of his castle.  2+ kings in 1 castle = a fight.  If you
have GE running and another tool runs git, this will happen.  Git uses an
index.lock file to handle this.  You can clear the index.lock file but only
do so after you know no git processes are running.

**Comment by glen-nicol** [comment]
As far as I know nothing else is running though. Like I said the consoles have the directory open but they aren't running anything. 

I did just get the same error on the command line. With that evidence it must be a problem with my git for windows version or something in my environment and not necessarily GE. I do have the periodic background fetch turned on. So I may try disabling that but as that is once per hour that seems unlikely to be causing my problems as often as they are occurring.

Thanks for the tips though!

**Comment by RussKie** [comment]
You aren't using VS Code by any chance, are you?
VS Code runs its own git process which collides with GE.

Maybe you need to run ProcMon and ProcExp and check whether there are any
other gits running...

**Comment by glen-nicol** [comment]
Yes, I am! But I have had this problem since before I started using VS Code on this computer. I also don't have any repos folders open in VS Code. I use it mostly as a Notepad++ replacement to open misc files.

**Comment by vbjay** [comment]
Visual studio also has its git provider.  

![image](https://user-images.githubusercontent.com/3629489/34849583-d758ada6-f6f0-11e7-83ad-ffe9917f487e.png)

**Comment by glen-nicol** [comment]
I ended up using procmon to try and analyze git.exe during the commit dialog's operation since that is the most common time I see this error. Looks like the commit button becomes enabled after the status query(git status -porcelain=2) of the repo has been completed. But then it seems to kick off another set of status queries after a file is staged and maybe it isn't syncrhonized with the commit button click so GE may be stepping on itself? I haven't looked at the code enough to know if GE has things in place to synchronize its own access to a repo.

But I think the main reason I am running into this is the repo I am working on has >100 recursive submodules! It just takes too long for anything to do any normal operation which is causing the collisions(either internally in GE or with external tools too).

**Comment by vbjay** [comment]
What are you doing, writing windows?  :O  

This brings up the idea of a git status service.  Sort of an idea of GE hosting a git service for itself.  What the service does is provide results of git status calls.  If a call to git status is needed after a change, the service is told and all git status calls are canceled and a new one is called.  If one is already running then piggyback on its result.  Think of using RX Extensions and using observable<T>.  T being some result object that contains git status results.  This would stop GE from stomping on its own toes.  I wish RX extensions would implement the switch operator in the .net version.  http://reactivex.io/documentation/operators/switch.html

**Comment by gerhardol** [comment]
> This brings up the idea of a git status service

There is an embryo to to this in master (#4209), some enhancements in #4327 #4328 
The checks at changes will be done much less often with #4327 Those PRs need reviews to be merged

**Comment by gerhardol** [comment]
This problem will be smaller if the "background" git calls do not lock git internals.
The negative is that when interactive commands run, the data is not cached and it takes more time, as well as the next background check.

https://git-scm.com/docs/git-status#_background_refresh
https://git-scm.com/docs/git#git---no-optional-locks
