### ISSUE TITLE
Japanese does not appear in the language options

### ISSUE THREAD

**Issue by kunimitaiyoh** [gitextensions/gitextensions#3851]
**Do you want to request a *feature* or report a *bug*?**

*Bug*.

**What is the current behavior?**

Japanese does not appear as an option for languages in "Choose language" dialog.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Open "Choose language" dialog at *Settings*.

**What is the expected behavior?**

Japanese appears and is selectable in "Choose language" dialog.

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**

This problem occurs in version `2.50.x` while the dialog works properly in version `2.49.03` or earlier.

### Version 2.50.01
![version 2 50 01](https://user-images.githubusercontent.com/3128211/28199594-cfbcfbe8-68a1-11e7-9a00-484bf8218322.png)

### Version 2.49.03
![version 2 49 03](https://user-images.githubusercontent.com/3128211/28199592-cc65d28a-68a1-11e7-9b52-2d371566ca5d.png)

**Comment by RussKie** [comment]
The immediate reason that you probably don't have Japanese translation in C:\Program Files (x86)\GitExtensions\Translation\ folder.

The main reason that it was commented out in 8870c444d5a73490a66343ec3eb5acca81ff48bb allegedly because the current translation does not provide sufficient coverage.

The best way to get the translation back is to get involved and help with missing translations.

**Comment by kunimitaiyoh** [comment]
I see. Thank you.
