### ISSUE TITLE
kdiff3 three-way comparison in the history of the file

### ISSUE THREAD

**Issue by Dumsik** [gitextensions/gitextensions#3994]
**What is the issue kind?**

- feature request

**What is the current behavior?**
In the history of the file when selecting three versions of the file does not work comparison  through kdiff3.

**What is the expected behavior?**

 I want to be able to compare with the help of kdiff3 three arbitrary versions from the history of the file.

**Environment you encounter the issue:**
- GitExtensions version: 2.50.01

**Comment by gerhardol** [comment]
This would be tricky to do in the GUI. GE 3 allows selecting many versions. It could be a diff option if at least three revisions are selected and use the first as base, the current diff revision as remote and last clicked "selected" as local (if current revision is last selected, use second selected as local). 

Related to this is #4154 to show differences to the base

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion.

**Comment by gerhardol** [comment]
Since 3.5 it is also possible to see the range-diff, comparing the commits in the branches

A full support would require configuration of the difftool, to mark support there. It would then only be supported for the "builtin" tools.
(Related is the directory diff feature, also just supported by some tools)
