### ISSUE TITLE
Issue Template Not working

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#4001]
**What is the issue kind?**
- feature request
- bug report
 vs

- [x] bug report
- [ ] feature request

**What is the current behavior?**
Users are messing up with the issue template.  Why I set up the checkboxes.  I don't know why the change was made to remove them

![image](https://user-images.githubusercontent.com/3629489/30502280-92e5c006-9a33-11e7-9269-3bda61c6d962.png)

See the difference in the "What is the issue kind?" section
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Users to pick one or the other type.

**Comment by KindDragon** [comment]
https://github.com/gitextensions/gitextensions/pull/3976#issuecomment-328340798

**Comment by RussKie** [comment]
I did update few of the existing issues, but I didn't modify the template.

On 16 Sep. 2017 10:51 am, "Arkady Shapkin" <notifications@github.com> wrote:

#3976 (comment)
<https://github.com/gitextensions/gitextensions/pull/3976#issuecomment-328340798>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/gitextensions/gitextensions/issues/4001#issuecomment-329933422>,
or mute the thread

**Comment by jbialobr** [comment]
> I don't know why the change was made to remove them

Because Checkboxes are for checklists. We can rollback to the previous template `Do you want to request a feature or report a bug?` which seemed to work.

**Comment by RussKie** [comment]
Can we close this?

**Comment by vbjay** [comment]
It's fine. Closedxml project uses the checkboxes. . It makes it so simple.
