### ISSUE TITLE
i am getting attached issue while checkin the code for truehub project. Please suggest.

### ISSUE THREAD

**Issue by dimriruchi** [gitextensions/gitextensions#4038]
![giterror](https://user-images.githubusercontent.com/32477510/31113489-2d2c3206-a837-11e7-8eff-8401b04bf648.png)

**Comment by RussKie** [comment]
As per your screenshot the jira issue you're referencing does not exist

**Comment by dimriruchi** [comment]
All of my team member using the same jira number to check in there code. They are able to do it.

**Comment by RussKie** [comment]
Then check and compare yours and theirs settings.

Do the push from the command line and see if it works any differently


On Oct 3, 2017 6:12 PM, "dimriruchi" <notifications@github.com> wrote:

All of my team member using the same jira number to check in there code.
They are able to do it.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/gitextensions/gitextensions/issues/4038#issuecomment-333759469>,
or mute the thread

**Comment by dimriruchi** [comment]
settings are exactly same.  
from where can i get the command to push the code using command line?

**Comment by RussKie** [comment]
From your screenshot

**Comment by dimriruchi** [comment]
Screen shot only tells about error. not about any command line.

**Comment by RussKie** [comment]
Yes, it does

![image](https://user-images.githubusercontent.com/4403806/31126515-c3e9598e-a897-11e7-9f29-7d1db09ed0aa.png)

**Comment by dimriruchi** [comment]
Hi Russkie, any solution for this issue plz.

**Comment by RussKie** [comment]
Have you run it from the command line?

**Comment by dimriruchi** [comment]
yes i did.. it is showing same issue
.

**Comment by RussKie** [comment]
Then it is nothing to do with git extensions

**Comment by dimriruchi** [comment]
ok thanks
