### ISSUE TITLE
VS2017 extension availability

### ISSUE THREAD

**Issue by huangyoum** [gitextensions/gitextensions#4050]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Environment you encounter the issue:**

- GitExtensions version:
- GIT version: 
- OS version: 

**Did this work in previous version of GitExtensions (which)?**

**Comment by vbjay** [comment]
Try searching issues next time.

**Comment by RussKie** [comment]
@vbjay we actually don't have any open discussions for VS 2017 apart from https://github.com/gitextensions/gitextensions/issues/3722, and that discusses the installation of the extension more than the extension availablity.

@huangyoum we have stalled on the extension due to number of reasons, including the change of how VS2017 installs extensions.
Having said that, there is a VS2017 compatible extension available and it is shipped with the installer but it is only accessible if VS2015 is present. And it isn't bug-free (https://github.com/gitextensions/gitextensions/pull/3439#issuecomment-334464279).
There are also unofficially built extensions floating around (e.g.  https://github.com/gitextensions/gitextensions/pull/3439#issuecomment-333587872) but we do not support them.

**Comment by RussKie** [comment]
You are now able to get a VSIX for VS 2017 from the VS Market Place https://marketplace.visualstudio.com/items?itemName=HenkWesthuis.GitExtensions
Thanks to @spdr870 for publishing
