### ISSUE TITLE
[feature] split vertically tree view

### ISSUE THREAD

**Issue by nicomeunier** [gitextensions/gitextensions#4183]
**Do you want to request a *feature* or report a *bug*?**  
feature

**Description:**  
Should be really great if we could split the tree view in 2 tree view. That could simplify some comparisons between branches before merge/rebase and so on. Nothing else to add.

- GitExtensions version: 2.50.02
- GIT version: 2.7.4
- OS version: win 10

**Comment by RussKie** [comment]
Could you please elaborate how you envisage this

**Comment by gerhardol** [comment]
Open a second instance?

**Comment by pmme** [comment]
I believe I understand the proposal correctly: you would like the option to split the tree view into two separate chunks of the tree so that it is simpler to select two different commits when those commits are far enough apart such that they do not fit within the vertical height of the tree view on your display. 

I believe you would want to select these two commits to show the total difference between them in the Diff pane at the bottom of GitExtensions.

Assuming that I am correct, there is a feature in GitExtensions that you may find useful: you can independently select two commits as a Base and as a comparison and GitExtensions will display a floating Diff window showing the total difference between those two commits.
Right click on the first commit, choose Compare > "Select as BASE to compare", or press CTRL-L.
Scroll to find the second commit.
Right click on the second commit, choose Compare > "Compare to base", or press CTRL-R.
GitExtensions will display its difference window loaded for those two commits.

This method is not prone to easy mis-clicking and spoiling your selection of the two commits and additionally the difference is shown as a full floating window instead of being restricted to a pane across the bottom of the main window.

**Comment by RussKie** [comment]
Closing as it isn't something on our roadmap.
There are few suggestions which, whilst may not be perfect, are providing some options for your request.

**Comment by nicomeunier** [comment]
@pmme, thank you for showing me this other way to compare commits, I wasn't aware of that. That is perfect so.
