### ISSUE TITLE
Jenkins integration does not refresh "in progress" builds info.

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#4185]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

As in the title.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Push a commit.
2. The build status is always In Progress.

**What is the expected behavior?**

Build server integration should query for completion status.

**Environment you encounter the issue:**
- GitExtensions version: 11c8c59ed79c617602d528d94bc6a51ecac31f56

**Did this work in previous version of GitExtensions (which)?**
No.

**Comment by gerhardol** [comment]
Not sure it is due to this change, but I get exceptions for InProgress builds, maybe when they are completed. Cannot recreate it at home (no Jenkins setup).

System.OutOfMemoryException
   at System.Collections.Generic.List`1.set_Capacity(Int32 value)
   at System.Collections.Generic.List`1.EnsureCapacity(Int32 min)
   at System.Collections.Generic.List`1.Add(T item)
   at System.AggregateException.Flatten()
   at System.Threading.Tasks.TaskExceptionHolder.Finalize()
