### ISSUE TITLE
Option to use another source than gravtar.com for avatars

### ISSUE THREAD

**Issue by waschmittel** [gitextensions/gitextensions#4226]
At our company, we have out own service that implements the gravatar API.

This is for example supported by the whole Atlassian stack, too.

This would be very nice for us and other users that made their own Gravatar server. All that is needed to make this work would be to make the Gravatar URL configurable.

**Comment by gerhardol** [comment]
Note: Fior GitHub "fake" email addresses (like <gerhardol@users.noreply.github.com>) then GitHub is queried, otherwise Gravatar. The gravatar service also have the default service that gravatar uses to generate images if a user is not on gravatar. The default service need to be a parameter in the url.

**Comment by vbjay** [comment]
Right click picturebox.

**Comment by drewnoakes** [comment]
> we have out own service that implements the gravatar API

We could make the base URI configurable without too much trouble.

@waschmittel is this still something you're interested in? If so, can you provide an example of a URL that your API accepts?

**Comment by gerhardol** [comment]
For BitBucket server:
https://docs.atlassian.com/bitbucket-server/rest/4.5.1/bitbucket-rest.html#idp2837072
Not sure if email->avatar can be done in one step for BB server.
Such lookups likely have to be hardcoded, it is already for GitHub. But for instance BitBucket Server could be added for corporate users.

The current hardcoded table looks like below, in GitUI\Avatars\AvatarDownloader.cs
This table could be configurable, inserting lines for corporate servers as well as other public services.

Matching email; url
@"^(\d+\+)?(?<username>[^@]+)@users\.noreply\.github\.com$"; GitHubEmailToAvatarUrl()
*, $"http://www.gravatar.com/avatar/{hash}?s={imageSize}&r=g&d={d}"

I do not want @drewnoakes to work on this though, he has submitted ideas for more interesting features!

**Comment by gerhardol** [comment]
> 
> 
> Should I implement that too or is the current version (only custom providers without authentication) good enough?

Are there any providers without authentication?
If so, that is a first step.

Can the auth be done in a generic  way?

> **Update**: I just found out that there is a bitbucket server plugin. Maybe we could reuse the credentials from there? I might give it a go later this week.

Yes, you can reuse the BitBucket plugin. Credential storage should be stored in the credential manager for the plugin, but that is another story, no need to do that twice.
I can do some testing at work.

**Comment by wischi-chr** [comment]
> Are there any providers without authentication?
Libravatar for example is a provider like gravatar that also doesn't require authentication _(more examples are listed in the PR, but most of them provided seeded random avatars like identicon, robots and such)_.

The way it's currently implemented _(also explained in detail in the PR)_ supports template and the user can use _(at the moment only without authentication)_ any provider they want even in-house providers.

> Can the auth be done in a generic way?

I guess if we limit the types of authentications.
The simplest one I guess most APIs would support would be Basic Auth (via TLS). Bitbucket for example supports that. But that would probably mean a different PR to improve/change they way avatar providers are configured not (see section _"Things that could still be improved"_ at the bottom of the PR description)

**Comment by gerhardol** [comment]
> For BitBucket server:
> https://docs.atlassian.com/bitbucket-server/rest/4.5.1/bitbucket-rest.html#idp2837072
> Not sure if email->avatar can be done in one step for BB server.

As usual, Atlassian BitBucket is quite annoying.
You do not have to authenticate to get an avatar, just a get:
https://bitbucket.example.com/users/{userSlug}/avatar.png

There are problems with this though:
* I see no way to get the userSlug (username) from the email. the request do not seem to allow the email or md5 or so. If you are logged in, you can retrieve all users for a repo and get the match: https://bitbucket.example.com/rest/api/1.0/projects/{project}/repos/{repo}/participants
If you add parameter ?avatarSize=8 you will see the avatar url too, see below.

* If no avatar is configured, you get the mystery silhouette. If you know the slug, you can find out about if an image is configured if you are logged in: https://bitbucket.example.com/rest/api/1.0/users/{userSlug}?avatarSize=8
(the actual value for the parameter seem to do not matter, but you will not see the image otherwise. if no avatar configured, the default image is returned: "https://bitbucket.example.com/s/-954693452/c4995b3/1/1.0/_/download/resources/com.atlassian.bitbucket.server.bitbucket-webpack-INTERNAL:avatar/avatar/default-avatar-16.png" )

So I can hardcode the image to myself or the mystery man but not show anything useful with what I have seen.
So BitBucket will require quite some extra steps (in addition to a login).

#8564 works fine
