### ISSUE TITLE
Settings messed up in Mono

### ISSUE THREAD

**Issue by CymricNPG** [gitextensions/gitextensions#4266]
I I open the Settings Dialog (also as first time user) it is completely messed up (see pictures), after this also the menu entries have changed.
The environment I use:

- Centos 7.3, mate as desktop
- Gitextensions: Any from 2.50 (also in 2.49)
- Mono: 5.4.0.201-0.xamarin.1.epel7
All running in a virtualbox 5.1.30.

**Did this work in previous version of GitExtensions (which)?**
I think this worked with centos 7.1 and an older mono version

Images:

![image](https://user-images.githubusercontent.com/5290177/34300333-d571eb70-e727-11e7-956a-fbfec294692b.png)
![image](https://user-images.githubusercontent.com/5290177/34300351-ea0743a0-e727-11e7-9659-e3ac7ce43d6c.png)
![image](https://user-images.githubusercontent.com/5290177/34300370-015a0560-e728-11e7-91b9-a7fea29aa6d8.png)

**Comment by RussKie** [comment]
This looks like something very wrong with linux+mono configuration. Maybe
some packages missing or not playing along nicely....

You are in the best position to get it fixed, mono isn't a top (or medium)
priority for us. Sorry.

On 23/12/2017 1:00 AM, "Roland Spatzenegger" <notifications@github.com>
wrote:

I I open the Settings Dialog (also as first time user) it is completely
messed up (see pictures), after this also the menu entries have changed.
The environment I use:

   - Centos 7.3, mate as desktop
   - Gitextensions: Any from 2.50 (also in 2.49)
   - Mono: 5.4.0.201-0.xamarin.1.epel7
   All running in a virtualbox 5.1.30.

*Did this work in previous version of GitExtensions (which)?*
I think this worked with centos 7.1 and an older mono version

Images:

[image: image]
<https://user-images.githubusercontent.com/5290177/34300333-d571eb70-e727-11e7-956a-fbfec294692b.png>
[image: image]
<https://user-images.githubusercontent.com/5290177/34300351-ea0743a0-e727-11e7-9659-e3ac7ce43d6c.png>
[image: image]
<https://user-images.githubusercontent.com/5290177/34300370-015a0560-e728-11e7-91b9-a7fea29aa6d8.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/gitextensions/gitextensions/issues/4266>, or mute the
thread

**Comment by RussKie** [comment]
This is how it looks on Ubuntu 17.04

![image](https://user-images.githubusercontent.com/4403806/34335212-235ac836-e9a1-11e7-8f52-eb48dcffb35d.png)
![image](https://user-images.githubusercontent.com/4403806/34335220-389c25a0-e9a1-11e7-9691-4c72a729c288.png)

**Comment by CymricNPG** [comment]
I made a complete new install and now it works. Cannot find what caused it.

**Comment by RussKie** [comment]
Good to know. Thank you
