### ISSUE TITLE
Support for Windows Subsystem for Linux (also known as Bash on Windows or Ubuntu on Windows)

### ISSUE THREAD

**Issue by dmtr81** [gitextensions/gitextensions#4307]
I tried to configure Git Extensions to work with WSL but did not manage to do that. I created a git.cmd file which actually runs git inside WSL bash. When trying to choose it in the Settings, it just hangs the Git Extension after apply.

Is there a way to configure Git Extensions to work with WSL? If it is not supported, than it would be a great new feature.

- GitExtensions version:
- GIT version: 2.50.02
- OS version: windows 10 professional

**Comment by gerhardol** [comment]
Do you want to use git.exe in WSL or both git and GE in WSL?
What is the benefit of using WSL git.exe?

**Comment by dmtr81** [comment]
I'm trying to use git and bash from WSL. And I don't want to use git.exe, because all my development environment is in WSL.
GE is installed as Windows application, it is not in WSL.

**Comment by gerhardol** [comment]
WSL-git only supports WSL filepaths like /mnt/c and not Windows style.
While there are not many direct "file references" between GE-core and git, there are enough to make this feasible, it might be impossible.

Windows git cannot be used, Windows applications should not modify WSL files.
I doubt that GE-mono in WSL will work

**Comment by dmtr81** [comment]
Thanks. I will try using mono. Just thought it can be solved without it. Anyway, if GE on Windows will ever support WSL directly, this would be great and much more user friendly.

**Comment by JamesB192** [comment]
I don't suppose you tried using windows GE and the WSL command-line to try working on a git repository outside the FHS say in /mnt/c/Users/${YOU}/git/${GITREPO}/ or some such. I have tried a similar tactic except for sticking it on the Desktop. 'ln -sv' can link the repositories shallowly under ~ if that floats your boat.

**Comment by dmtr81** [comment]
@JamesB192 sorry, I did not get your idea. Can you describe your setup in more details?

**Comment by JamesB192** [comment]
No, I'll draw a diagram instead. Run something not quite completely unlike this:

```bash
ln -sv /mnt/c/Users/${USER}/Desktop . # creates a symbolic link Desktop which links to windows desktop
cd ~/Desktop
git clone ${GITURL}
```

Then you have a git repository on your desktop that you can edit with WSL command line tools as well as GitExtensions/Notepad/whatever.

**Comment by dmtr81** [comment]
Still I can't understand how this solves the described problem. Thanks, anyway.

**Comment by GintasS** [comment]
Need to close this. Also the issue #6164.

**Comment by gerhardol** [comment]
WSL improvements since about 3.3, \\wsl$ can be used
Further improvements discussed in #8307

**Comment by ivan-danilov** [comment]
FWIW, I succeeded in setting up GitExtensions with WSL through `\\wsl$\` and even made it work from the WSL command line seamlessly, but it required some escaping black magic. Effectively, I needed to run `GitExtensions.exe commit`, using current `$(pwd)` as the target repo. Unfortunately, I cannot pass repo location through the command line, so I needed to translate `$(pwd)` to UNC format, and set the share location as the working directory for GitExtensions process.
And a final twist: I needed an alias for it so that my real command looks like `gitex commit` rather than typing all that nonsense every time.

So, I needed a string for the alias that will contain `PowerShell.exe` invocation, passing quoted UNC share + current directory as `WorkingDirectory` and passing the rest of the arguments to `ArgumentList`. I use zsh, and this line in `.zshrc` worked for me:
```sh
alias gitex='(){ powershell.exe -command '"'Start-Process -WorkingDirectory \"\\\\wsl.localhost\\Ubuntu'\$(pwd)'\" -FilePath \"c:\\Program Files (x86)\\GitExtensions\\GitExtensions.exe\" -ArgumentList \"'\$@' \"'; }"
```

All that escaping took me a good hour to make it right, so I'd be glad if someone could make it simpler.

P.S. There's a weird problem with PowerShell that it does not like empty string as ArgumentList, so the space after `$@` is important.

**Comment by ivan-danilov** [comment]
A slightly more readable version that works both from `/mnt/X/some/path/` and usual Linux paths like `/home/user1/repo` (in the former case, it launches GitExtensions in `X:\some\path\`, and in the latter -- in `\\wsl$\Ubuntu\home\user1\repo`):

```zsh
function _translate_to_windows_path() {
  if [[ "$1" =~ '^/mnt/[a-z]/' ]]; then
    print -r "$(print -r "$1" | sed -e 's|^/mnt/\([a-z]\)/\(.*\)$|\1:\\\2|i')"
  else
    print -r "\\\\wsl\$\\Ubuntu$1"
  fi
}

function _run_in_windows_in_current_dir() {
  local dir="$(_translate_to_windows_path $(pwd))"
  local cmd="$1"
  shift
  local args="$@"
  powershell.exe -command 'Start-Process -FilePath "'$cmd'" -WorkingDirectory "'$dir'" -ArgumentList "'$args' "'
}

alias -g gitex='_run_in_windows_in_current_dir "c:\\Program Files (x86)\\GitExtensions\\GitExtensions.exe" '
```

**Comment by mstv** [comment]
`wslpath -aw` converts WSL paths to Windows.

**Comment by gerhardol** [comment]
My Git alias from ~/.gitconfig
The path is translated in GE

[alias]
       ge = !sh -c \"\\\"/mnt/d/_tmp/GitExtensions/GitExtensions.exe\\\" browse $(git rev-parse --show-toplevel)\" &

A bash alias could be added with something like
alias ggg="/mnt/d/_tmp/GitExtensions/GitExtensions.exe browse $(git rev-parse --show-toplevel)&"
