### ISSUE TITLE
[Discussion] GitExtensions v3.0 proposal

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#4308]
I propose the next version of GitExtension to be v3.0. I would like to make this next version all about [user experience and usability](https://www.nngroup.com/articles/definition-user-experience/). The UI looks dated and can do with a fresh coat of paint, so to speak. Also there are multitude of hidden features and configurations which can make or break the experience. Even savvy users aren't always able finding a particular settings hidden behind some context menu or a toolstrip dropdown or buried away in settings.

First of all, I propose we stop supporting Mono.
Mono WinForms is and has been dead for almost a decade now - last commit to https://github.com/mono/winforms is made on Oct 22, 2009. In its current form it has a number of bugs and limitations which, being the lowest common denominator, limits our ability to innovate or provide exciting UX. Mono development, absent of UI designer and with limited debugging experience, is also extremely frustrating and time consuming.
If we use the number of issues per platform as a very coarse approximation (120/2664), then our non-Windows userbase is less than 5%, contribution from these users is close to 0%. I am not convinced that 95% of our users should be provided with a substandard experience because of this.
Versions 2.51 and below will still be available to our non-Windows users, however going forward Mono will no longer be our concern.

Dropping Mono support brings opportunities to rework the current UI and introduce controls like ribbon (instead of toolbars) and dock containers. 
We can also make free use of dynamically sizable controls with variable content.

I plan to resurrect my dashboard revamp (#3693) and replace the current experience with it. With that I plan to overhaul the whole repository history aspect (categories and anchors). I plan to break things too.

The branch tree view (#3038) is another candidate for the inclusion into the next release. It has been sitting forgotten in the queue for a few years now, which is pretty sad. We will work with @EbenZhang to try to integrate it into the main branch (though we will need to have it in reviewable state first).

I'm sure @gerhardol has 3,000 branches with exciting features of his own already primed to be pushed in too :)

I've gone through the (part of) backlog and picked a list of issues and features which seem to fit the theme - https://github.com/gitextensions/gitextensions/milestone/23. This list is by no means final and will probably change along the way.
Timeline-wise I would like to make the next release by July 2018. Again, it is not a date set in stone.

. . .

Before you ask or say it - we can't move to WFP, GTK+, Qt, Xamarin or any other fancy tech (#3026) there is out there, and are stuck on WinForms due to a number of architectural decisions and the current implementation (I'm not blaming anyone, stating the fact). It will take a significant refactor (rewrite?) before UI can be decoupled from business logic and we would be in a position to plug a different UI layer. 
It is doable, but requires a significant effort, which we currently can't afford.

Related: #4037

@spdr870 @KindDragon @jbialobr @gerhardol @EbenZhang @gpongelli @vbjay @pmiossec @mdonatas @Drake103 and everyone else for that matter - thoughts?

**Comment by gerhardol** [comment]
Fully supporting. Depreciate Mono is unfortunately the first step. I like the idea of multi platform (I did play with Mono when it was new), but in the end there are too many limitations and a "native" implementation is preferred. Most multiplatform applications seem to have considerable portions in native code. (I will not go into discussions about this, I am sure there are applications that are designed well on many platforms with minimal specifics too.)

But I would like to revise the "next version" target.
As a project with limited resources and no committed (more than intention) resources, I would like to have a realistic goal with next release. I would prefer a time based release schedule (every second month?) rather than about 2 releases every year. If the 3.0 target is too big it will take too long time for next release. The proposed milestone is quite big, I doubt that 6 months is sufficient. That is even without "ribbon" changes (I cannot really estimate the time for a complete UI touchup).

Maybe next release should be 2.60, just depreciating Mono and release whatever that is ready in six months.
The realistic goal is to beautify the UI, maybe start with a smaller form?
Should a changed GUI have the same form setup as now? (a lot of functionality is hidden now, I would like to see more of it in Browse).

@RussKie With comma as a decimal separator I have for sure 3,000 branches waiting to make PRs...

**Comment by Drake103** [comment]
It's okay to stop supporting Mono, not only because of little percentage of users, but also because current version of gitextensions is pretty sufficient (but not ideal). I use gitextensions everyday and I could use this version for a very long time (most of days my workflow is pretty simple). Also in case of decoupling of BL and UI, Mono support will have chance to be restored.

I think milestones should be smaller, maybe with one epic per milestone.

I hope UI updates will not hurt performance hard, things like startup time or smooth UI are critical for me. I would like to see vector or high-res icons and in general better support for high resultion.
Could be state decoupling of BL and UI as one of our goals, and disallow old approach in new commits? This would make easier to implement things like Quick Search which is very useful to find features.

**Comment by gpongelli** [comment]
Unfortunately I think that dropping Mono is a needed step. 
I would like to use GE on linux/mac, but mono/winform enchain instead of allow you reaching the goal.

I also agree to refresh the UI, those are interesting proposal to renew it.

Having a codebase for different OS is not only a matter of User Interface, it's also related to the low level interface (e.g. I think about directory content listener).

ps
Just to say, seems that monodevelop uses GTK.

**Comment by RussKie** [comment]
I am fully supportive of higher release cadence, especially for bug fixes.
Feature releases probably aren't feasible any more often than twice a year. Because no one is working full time on the app. A release is also a pretty involved process which requires a few number of moving parts dance in accord (e.g. translations).

No matter how much I think about it, I can't see how we can maintain multiple branches (release branches, bug fixes etc) using github flow.
If we use more traditional git flow, we'll have master (or develop) branch, release/2.x and release/3.x. Then we can have a faster turnaround with bug fixes on each branch and release features more often.
Thoughts?

> I hope UI updates will not hurt performance hard, things like startup time or smooth UI are critical for me.

This one of my goals - the app has to feel snappy. It must also be resource efficient.
That's the reason I am refactoring the code to untangle dependencies and separate state from behaviors.

**Comment by gerhardol** [comment]
> Feature releases probably aren't feasible any more often than twice a year

Can that be improved somehow?

> we'll have master (or develop) branch, release/2.x and release/3.x. 

Obviously, there will be a 2.x branch for bugfixes, maybe even mono. I expect this to be low activity.

However, I want to have as few "public" branches as possible. Many issues in features are found by other maintainers, so there should be few branches.
There could be some longer living feature branches though if several maintainers are working on a feature and the central repo is a better common repo than the developers.

> the app has to feel snappy

I do not think that GE is slow, but there are occasional slowdowns from git commands. A new GUI should of course not be slower, but optimizations are better in other areas.

**Comment by denismaster** [comment]
What about switching to .NET Core and using Avalonia as a GUI framework?

**Comment by pmiossec** [comment]
@denismaster

>Avalonia is now in alpha. This means that framework is now at a stage where you can have a play and hopefully create simple applications. There's still a lot missing, and you will find bugs, and the API will change

I let you do the first developments ;-)

To be realistic, we hardly find developers that have the time and wishes to fix the existing GUI. So, I find it unrealistic to restart from the beginning with a completely new framework...

**Comment by gerhardol** [comment]
> To be realistic, we hardly find developers that have the time and wishes to fix the existing GUI. So, I find it unrealistic to restart from the beginning with a completely new framework...

If someone finds it fun enough to spend 2000h (?) to the switch, I will happily use the results.
Until then polishing the current interface is good enough for me.
Stop supporting Mono now could improve the multiplatform support eventually by speeding up development.

**Comment by RussKie** [comment]
.NetCore is a server-side tech which has nothing to do with UI.

Avalonia is in alpha, so I wouldn't use it for anything beyond 'hello
world' app. And it is not using .NetCore.

**Comment by MattLichter** [comment]
Just a humble user here.  I love GE.  By far the best.  You guys are awesome.  Been using since 2012 and I have full muscle memory baked into my fingers ;)

I have *really* appreciated the Linux support in the past year.  Thank you so much for that.  It's *incredibly* useful to be able to switch over to a Linux VM and not have to use an alternative client.  Everything else just feels like I'm wearing mittens.  Even though I do 95% of my work on Windows, just wanted to say thank you for that extra effort.

All that said, I do concur with dropping Mono support if you feel like it's holding you back from bigger and better things.  I know the feeling all too well.  And make no mistake, 2.50.2 will remain a perfectly usable piece of software for a long time.

Just out of curiosity -- is .NET Core support in the realm of possibilities eventually?  I'm not talking right away, maybe another year or two down the road.  I simply don't know what supporting that would entail.  Is it a matter of using portable syntax/libraries, or is it the kind of thing that requires major overhaul of architecture, or lots of platform specific code?  I simply don't know because I haven't explored .NET Core much.

**Comment by vbjay** [comment]
Core is just that core.  It is a server based framework.  It doesn't have a
gui like winforms.  It does have mvc and web site gui.

**Comment by RussKie** [comment]
Thank you Matt.
Upcoming 2.51 should make GE a little bit more usable for the Mono users.

And as Jay already said - .NET Core isn't a viable tech for us.

**Comment by gerhardol** [comment]
Should we make a separate issue to link PRs for depreciation of Mono?
I suggest to separate Mono depreciation to specific commits if possible, not remove actively.
First to go is building, which should include Travis builds.

**Comment by RussKie** [comment]
Sounds like a sensible idea

**Comment by brunoais** [comment]
@RussKie 
> Mono WinForms is and has been dead for almost a decade now - last commit to https://github.com/mono/winforms is made on Oct 22, 2009
That commit is for the examples on how to use WinForms.
Their bugfixing is quite active: https://github.com/mono/mono/labels/area-BCL%3A%20System.Windows.Forms
Not as much as we would want but it is, indeed, active.
Did you try creating issues about the troubles we are encountering?
Although I don't like the removal of support in v3.0, I think telling that their code is frozen in time since 2009 is wrong and the truth should be given.

With that said, maybe we can remove support in v3.X and, if they fix their stuff, we can bring support back in 4.X.
Regardless, for them to fix, we first need to let them know that there's more stuff that needs fixing. Check their issues and our issues and then create the missing issues in their repository.

Am I missing anything?

**Comment by RussKie** [comment]
> Their bugfixing is quite active

I am afraid I can't agree with this statement. 8 open and 2 closed issues is not "active" for a 15+ years old platform.

> I think telling that their code is frozen in time since 2009 is wrong and the truth should be given.

It is frozen. There has been no innovation or any serious development.

Along with other members of the team I have no interest or inclination to pursue Mono path. As I stated previously, in my opinion Mono support for WinForms is fundamentally broken and is incapable of providing UX comparable to what GE offers on Windows. Even [Migel suggested to look at other platforms](http://forums.dotnetfoundation.org/t/anyone-porting-winforms-mono-to-net-core/898/2). 
I have spent an unreasonable amount of time dealing Mono layout issues. There are more interesting and exciting things to do in this project which will benefit our users.

That said, if you feel inclined and have time and resources to raise all deficiencies with Mono to Microsoft and see them fixed - please go ahead. You will certainly have my greatest respect.
If one day Mono for Winforms becomes are viable platform again - we will certainly consider adding it back.

**Comment by RussKie** [comment]
Surprisingly Migel de Icaza is still tinkering with Mono Winforms
https://www.infoq.com/news/2018/02/mono-forms-carbon64

**Comment by brunoais** [comment]
Thanks @RussKie . I get it better now. I hope they can do advances so programming for WinForms in Mono is not as much of a pain.
I have no more arguments against this. It is an unfortunate requirement to be able to continue working with this.

**Comment by pmiossec** [comment]
I read something interesting on multiplateform support on .net today and let there:

https://www.hanselman.com/blog/CrossPlatformGUIsWithOpenSourceNETUsingEtoForms.aspx

If someone is interested and that could help...

**Comment by brunoais** [comment]
... and this may be what you need to know how to use Eto for a git Ext already using WinForms
https://github.com/picoe/Eto/wiki/Embedding-Eto.Forms-in-an-existing-application

**Comment by JohannesHoppe** [comment]
I work on a Mac and I love GitExtensions. That's why I have always Parallels Desktop running, which eats my battery within hours. 😢 

And I have to admit, I was never able to get the mono version up and running. So counting the active userbase is unfair. It does not work at all. You could also ask people about their preferred vehicle for travelling - next to a road! 😉

I would love to see Mac-support coming back in future!

**Comment by vbjay** [comment]
With .net core supporting GUI platforms later on, this may come back.


https://blogs.msdn.microsoft.com/dotnet/2018/05/07/net-core-3-and-support-for-windows-desktop-applications/

**Comment by JohannesHoppe** [comment]
Not that soon! 😪

> .NET Core 3 will still be cross platform, but WinForms and WPF remain "W is for Windows" - the runtime is swappable, but they still P/Invoke into the Windows APIs. 
> AnnouncingNETCore21RC1GoLiveANDNETCore30Futures.aspx

**Comment by RussKie** [comment]
> And I have to admit, I was never able to get the mono version up and running. So counting the active userbase is unfair. It does not work at all. You could also ask people about their preferred vehicle for travelling - next to a road! 😉

With all due respect, this is OSS - if you want it to work for Mac, get involved.

**Comment by mdonatas** [comment]
Awww, dude @RussKie from a number of podcasts and blog posts about managing OSS projects there is a recurring theme that this kind of attitude is damaging. This is close to telling someone to go F* themselves. And in this case Johannes had a valid point that there might've been few users because many failed to even launch the app; also told in a polite manner. Not that this changes anything regarding the 3.0 plan but we shouldn't dismiss people like that.
p.s. it sucks that Github doesn't have PMs. ¯\_(ツ)_/¯
p.p.s. please take this feedback kindly :)

**Comment by JohannesHoppe** [comment]
Everything ok here, from my side.  I would love to participate, but I'm already involved in countless OSS projects! 😉 

For 3.0 I totally agree that mono (especially for Mac) sucks and that it's unmaintainable. But I would still argue, that there might be a big potential userbase which was more or less excluded until today.

**Comment by gerhardol** [comment]
The comment should not be taken personally. The reality is that there has not been any developers for a long time that have really used GE in Mono. It is hard to maintain something like this without active interest. Russkie can say what he wants with the workload he puts in (he has done many improvements for Mono in 2.51 too, how many have hours to spare every day?).

**Comment by RussKie** [comment]
@mdonatas - thanks, appreciate your feedback

@JoanCharmant - I would love to have GE running on OSX, 2 out of 4 computers I use are MBPs (with Parallels). However we are stuck on WinForms for foreseeable future. 
Also over the years there has been relatively weak interest/participation from non-Windows users, and this means efforts in this direction amount to a waste and lost opportunities with our core userbase.

Incidentally today @KindDragon shared a tweet with me:
https://twitter.com/MalwareMinigun/status/996643440376008705

**Comment by bernhardberger** [comment]
Everyday GitExtensions user here on Linux. Had started using GitExt a few years ago as a VS plugin, but it very quickly became my go-to git GUI, nothing even comes close.

I think the reason most mono-users don't post issues is that we're all developers and basically no-one expects it to run smooth on Linux (at least this is my experience).

We are just more-than-happy that we CAN use GitExt even with all those mono-bugs and don't have to use alternative GUIs that are less than optimal (actually pretty trash in comparison to the minimalistic and exceptionally good approach of GitExt).

From my side a +1 tho for dropping mono support, will just have to use 2.5 forever then :) Just a big :+1: for your work on GitExt!

**Comment by gerhardol** [comment]
> I think the reason most mono-users don't post issues is that we're all developers and basically no-one expects it to run smooth on Linux (at least this is my experience).

One problem with GE and mono/Linux is that no developer was using mono and issues always came late as well as the quality of issue reports were low (i.e. users just testing GE). So it was impossible to maintain.
There were discussions without much mono users response about if anyone used mono seriously.
So do not be too quiet...

**Comment by RussKie** [comment]
Totally agree with @gerhardol. If Linux users made more noise it would be easier for us to gauge our user base and level of brokeness.
Besides I'm sure some of Linuxoids are good with C# and could help in getting the app better. Unfortunately it isn't something we observed over the years, so that led to the demise and deprecation of Mono support.

**Comment by jelical** [comment]
Avalonia is already 0.7 and can be used for relatively serious stuff.

**Comment by vbjay** [comment]
It is version 0. As in beta. I seriously doubt we would support beta
products in our codebase.

**Comment by brunoais** [comment]
Maybe Avalonia can be used to make GitExtensions 4.x in about 3 years.... Tools to try uniting development to multi-platform keep on popping up and improving...

**Comment by gerhardol** [comment]
To be fully multiplatform, GE will have to completely switch from WinForms. That is a lot of work. It will not happen unless someone is really serious about changing and has a lot of time to spend on the conversion.

**Comment by brunoais** [comment]
I disagree. Although WinForms indeed was made for windows, it is a high level API to build forms. Although much different markup/code design concept than HTML, WinForms is, according to my reading, at the same high level as HTML is.
That means, even though it is designed for windows, WinForms is easily universal, even though some names won't match to the actual components in MacOS, linux (X / Wayland), freebsd, etc...
In my opinion, the real problem is having a proper translators from WinForms into the intended targets where, so far, there seems to be only one (windows).
@gerhardol Did I get that wrong?

**Comment by RussKie** [comment]
> Did I get that wrong?

I am very much inclined to say that you did. 
WinForms is tightly coupled to WinAPI.
IIUIC, Mono WinForms implementation was an attempt to make WinForms x-plat by providing shims and proxies into Linux's UI layer (X11). It kind of worked, kind of didn't... Ultimately MWF was abandoned many years ago (Mono 5.14 brought some badly needed fixes and tweaks, but it is still nowhere near parity).

Like @gerhardol said, we are tightly coupled to WF. 
It would be a significant engineering effort for us to migrate to any other framework(s). It is probably not as difficult as time consuming - move all (business) logic from the UI layer into controllers/service layer; after that we can substitute the WF UI layer with another.

**Comment by RussKie** [comment]
There is another aspect to the x-plat story. 
Unlike web, you can't build a native app once and run it everywhere - an app designed for Windows would feel foreign on a Mac or Linux, and an app build for a Mac would look horrible on Windows... Each OS has a different set of usability principles and guidelines.

So for us to be truly x-plat we will need to migrate off WF. I hope one day it happens.

**Comment by RussKie** [comment]
I'm glad to hear it is :)
