### ISSUE TITLE
Push multiple branches: check all and uncheck all required feature

### ISSUE THREAD

**Issue by Calabonga** [gitextensions/gitextensions#4421]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
There are no way to check all and uncheck all branches for pushing (deleting and so on)

**What is the expected behavior?**
It's would be wonderful to have a possibility to check/uncheck all branches for all operation (push, pull, delete)

- GitExtensions version:
- GIT version:  2.50.02
- Windows version: 10

**Did this work in previous version of GitExtensions (which)?**
There are no mentions about this feature in previous version

**Comment by RussKie** [comment]
Could you please provide more information/screenshots for your request?
Thanks

**Comment by Calabonga** [comment]
![2018-02-02_1926](https://user-images.githubusercontent.com/346209/35733330-8de0396c-084f-11e8-8179-d6cd5fc758fe.png)

I think it's should looks something like in the screenshot

**Comment by RussKie** [comment]
Great, thanks

**Comment by johndog** [comment]
What boxes are checked by default?  I've never understood/trusted it, and it's never been close to the set of branches I want to push.  That's the main reason I've yearned for "uncheck all".

It would actually be a pretty nice step forward if it always came up with no boxes checked.  It'd be even better if it defaulted to the same boxes as last time (although that would add back some pressure for an uncheck-all option).

**Comment by gerhardol** [comment]
What is pushed by default is those with a remote already.

I would vote for a change where only the current branch is checked by default.
A workflow where all branches ticked is if you use this to create a backup. It is possible to add a script instead (git push --all), so I do not think it is a major loss for anyone (but a win to use the boxes).

It should be possible to select/unselect the checkboxes after shift-click, then select a checkbox.

**Comment by pmiossec** [comment]
>I would vote for a change where only the current branch is checked by default.

+1

The only time I wished to use this feature to push multiple branches, I didn't used it finally because too much branches was selected by default and that was too painful to unselect all 😢

**Comment by johndog** [comment]
> I would vote for a change where only the current branch is checked by default.

Ironically I'm usually using 'push multiple' in cases where I want to push branches _other_ than the one I'm in (because the one I'm in is a local-only temporary merge of the ones I want to push).  Still, I'd support this compromise.

> It should be possible to select/unselect the checkboxes after shift-click, then select a checkbox.

Agreed.  I tried this instinctively, and I also tried right-clicking on the column headers for a context menu supporting [un]check-all.  I think either of those would be relatively discoverable UI options.

A context menu has some advantages...  imagine being able to choose any of the following:

- check all
- uncheck all
- check all branches with upstream
- check all branches with same name on remote (I often have multiple branches with the same upstream)
- check all branches that can fast-forward remote
- check all branches requiring force-push
- etc

IOW, a context menu could scale to support a lot of scenarios without requiring a lot of UI design.

BTW, why does the column header say "Force Rewind"?  That's not a very common phrase.  Why not just say "Force Push"?

**Comment by gerhardol** [comment]
> >  I would vote for a change where only the current branch is checked by default.

> Ironically I'm usually using 'push multiple' in cases where I want to push branches other than the one I'm in (because the one I'm in is a local-only temporary merge of the ones I want to push). Still, I'd support this compromise.

No selection at all is fine for me

> >  It should be possible to select/unselect the checkboxes after shift-click, then select a checkbox.

> Agreed. I tried this instinctively, and I also tried right-clicking on the column headers for a context menu supporting [un]check-all. I think either of those would be relatively discoverable UI options.

There are many ways to select all. It would be good if there were some replacement to select all, but not required for me to vote on a change.

> BTW, why does the column header say "Force Rewind"? That's not a very common phrase. Why not just say "Force Push"?

Legacy, probably happen to get this header ten years ago, since the dialog obviously is not much used it has stayed.
Should be changed
