### ISSUE TITLE
Installer fails to re-launch explorer if aborted

### ISSUE THREAD

**Issue by tomlogic** [gitextensions/gitextensions#4451]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The installer asked to kill Explorer, but then balked when it saw the PuTTY Agent running.  Without a taskbar, I couldn't launch Task Manager to kill it, or bring up the "Run" dialog to launch taskmgr.exe.  After aborting the install, I was left without a task bar.  Luckily I had a shell window open that I could use to launch the task manager and re-launch explorer.exe.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
See above.

**What is the expected behavior?**
Installer should re-launch Explorer before exiting, regardless of what happened during the install.  It might be useful to identify the PuTTY issue before asking to quit Explorer, but that's less important.

**Environment you encounter the issue:**

- GitExtensions version: Installer for 2.51.0
- GIT version: n/a
- OS version: Windows 7SP1

**Did this work in previous version of GitExtensions (which)?**
Not that I know of.

**Comment by RussKie** [comment]
> Without a taskbar, I couldn't launch Task Manager to kill it

Ctrl+Shift+Esc should always work....

**Comment by vbjay** [comment]
Ctrl alt del has a start task manager option. Then start a new task and run
explorer.

**Comment by tomlogic** [comment]
Thanks for the tips -- after filing the bug report I thought of Ctrl-Alt-Del as another way to launch Task Manager.  And although I've used PCs since before Windows, and used Windows since 3.1, I'm not sure I ever knew the Ctrl-Shift-Esc shortcut.

Hopefully there's an easy way to update the installer to re-launch Explorer on an aborted install.

**Comment by jupsoleil** [comment]
This is a long-standing problem which still hasn't been solved.  Just encountered the problem again while upgrading to version 3.2 of git extensions.

**Comment by jupsoleil** [comment]
Apparently the problem appears only when running the installer in quiet mode.

**Comment by RussKie** [comment]
no, unfortunately not only in quiet mode.
I typically resort to running a PS script while running an installer:

Stop-Process -name explorer

**Comment by RussKie** [comment]
@Johno-ACSLive do you have any tricks up your sleeve for this?

**Comment by Johno-ACSLive** [comment]
In the last few updates, I tell the installer during upgrade not to automatically re-start processes. It never asks me to reboot and everything seems to work correctly (can't say I tested any of the explorer menu items but they do remain there).

Alternatively, if explorer does fail to start up then Ctrl + Alt + Del and then Task Manager will allow you to keep going.

These are the only quick ones i have at the moment.

I believe the issue lies in how the installer has been configured around the explorer integration. I'm not too sure of the actual cause (WiX issue or config issue) but once i start work on the Advanced Installer migration, definitely keen to test the results there.

**Comment by gerhardol** [comment]
As the shell integration has not changed for some time (other than icons in 3.0), it is not a problem to postpone the restart of explorer to next restart. The default could be changed.
