### ISSUE TITLE
First line always selected on "Resolve merge conflicts" dialog

### ISSUE THREAD

**Issue by yesgrey** [gitextensions/gitextensions#4478]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When the "Resolve merge conflicts" dialog is opened for the first time the first line is selected. If we then select another line to fix that conflict, after it has been solved the next file in the list gets selected, however, the first line also is selected. This is a problem because sometimes we might miss it and then apply the same solution to different files. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1) Open "Resolve merge conflicts" dialog with at least 3 conflicts.
2) Select the 2nd conflict on the list (when you do this the 1st line is deselected and only the second one shows as selected) and fix it. 
3) After fixing the conflict, the file that was on 3rd place on the list is now in second and selected, but the 1st line is selected also.

**What is the expected behavior?**
After fixing a conflict, only the line after that fix should be selected.

**Environment you encounter the issue:**

- GitExtensions version: 2.50.02, 2.51
- GIT version: does not matter
- OS version: Win7, Win10

**Did this work in previous version of GitExtensions (which)?**
Don't know.

**Comment by ignacioerrico** [comment]
The issue is reproducible in v 3.1.0.5877 too (build bb1687f6bd0450d0c1a2bae10a37c65493fc1294). The issue is presumably with the even-numbered items on the list (second, fourth, sixth, and so on), and not just with the second.

Additionally, the information :information_source: underneath the grid is not updated for the even-numbered items on the list. The text that was displayed for other items remains when selecting them instead.

**Example**.
- Select the third item &rarr; say you see :information_source: "changed both locally and remotely".
- Then select the fourth  &rarr; you see the same information, even if it should be "deleted locally and modified remotely".
- If you resolve the conflict in the fourth file, the first and fourth (provided there were at least five conflicts) are selected.

**Comment by MarkJ74** [comment]
I think this has been fixed and can be closed, I could reproduce this with GE 3.2 but I can't with 3.3.
