### ISSUE TITLE
Develop in VS2017 only

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#4479]
**Do you want to request a *feature* or report a *bug*?**
discussionfeature

**What is the current behavior?**
In 2.51, VS2015 was the default, changed to VS2017 in #4434
With #4475 VS2017 is required

Most developers should be able to use VS2017 Community. If there are significant number of users that cannot upgrade, dev still need to support VS2015
See #4475 for arguments

**Environment you encounter the issue:**

- GitExtensions version: master

**Comment by drewnoakes** [comment]
I tested adding the `Microsoft.Net.Compilers` package to a project that uses C# 7 language features and it does build until VS2015.

From the package's page on NuGet.org:

> Referencing this package will cause the project to be built using the specific version of the C# and Visual Basic compilers contained in the package, as opposed to any system installed version.
>
> This package can be used to compile code targeting any platform, but can only be run using the desktop .NET 4.6+ Full Framework.

Would you commit this package dependency to all projects?

---

Regardless, even before this PR I couldn't build the `JiraCommitHintPlugin` project under VS2017 due to compile errors in `JiraCommitHintPlugin.cs`:

> error CS0012: The type 'IEnumerable<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
error CS1061: 'Task' does not contain a definition for 'Result' and no extension method 'Result' accepting a first argument of type 'Task' could be found (are you missing a using directive or an assembly reference?)
error CS0012: The type 'IEnumerable<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
error CS0012: The type 'IEnumerable<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

Adding a reference to `Microsoft.Net.Compilers` doesn't help for this project.

**Comment by gerhardol** [comment]
> Would you commit this package dependency to all projects?

Yes, or at least publish a commit that can be cherry-picked

> Regardless, even before this PR I couldn't build the JiraCommitHintPlugin project under VS2017 due to compile errors in JiraCommitHintPlugin.cs

I assume you meant VS2015. 
The source file was modified before the default switch to VS2017, so it is a little strange. But things like this will slip unless we maintain and test with the oldest version, this is an argument to drop VS2015: There are more fun things to do ensure backwards compatibility.

Discussion continuing in #4475

**Comment by RussKie** [comment]
We are permanently switching to VS2017.
