### ISSUE TITLE
Commit index count dissapears on refresh

### ISSUE THREAD

**Issue by nsartor** [gitextensions/gitextensions#4483]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The new "Commit index" and "Current unstaged changes" file count disappears when you click the refresh button. (Or press F5)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Stage some files and close the commit dialog. Note the commit index has a file count next to the words Commit index. Click the fresh icon. Both the Commit index count and Current unstaged changes count dissapear.

**Workaround**
Reopen the commit dialog and close it (making no changes). The values appear again next to Commit index and Current unstaged changes. The commit file count on the commit button is always correct.

**What is the expected behavior?**
The values should not disappear.

**Environment you encounter the issue:**

- GitExtensions version: 2.51
- GIT version:  2.13.0.windows.1
- OS version:  Windows 10x64

**Comment by gerhardol** [comment]
This is due to the commits are loaded asynchronously and the update of the count is occasionally done before the commits are refreshed.
This has a lower probability to happen for a small repo than a big one.

Keep this as a known error, the effort to correct it is likely relative high. The "count supervision" need to be updated to improve performance too, this can maybe be done after that.
