### ISSUE TITLE
Wrong diff on "Current unstaged changes"

### ISSUE THREAD

**Issue by BUInvent** [gitextensions/gitextensions#4489]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When doing a diff by highlighting "Current unstaged changes" and any other commit, the diff shows the difference to local changes regardless of whether the changes are staged or not:
![image](https://user-images.githubusercontent.com/20247455/36282740-c2a69ac0-1267-11e8-924f-375ec9ce2dc0.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1: Make a local change to a file in the repo
2: Stage the change
3: Highlight any commit and the artificial commit made for the "Current unstaged changes"
4: You will see a diff of that commit and the "Current staged changes", not the "Current unstaged changes"

**What is the expected behavior?**
We could probably just avoid this problem entirely by changing the wording from "Current unstaged changes" to "Current uncommitted changes".

**Environment you encounter the issue:**

- GitExtensions version: 2.51
- GIT version: 2
- OS version: Windows 7

**Did this work in previous version of GitExtensions (which)?**
No because getting a diff by highlighting the current uncommitted changes was not possible until the latest release.

**Comment by gerhardol** [comment]
To get this behavior you must stage the file outside of GE.

This is intentional, the files in the Diff-list is not updated when there are changes outside GE.
Refresh all or select another commit to refresh.
If refreshed automatically selections and scroll is not preserved to full extent, that would be annoying.
The count for the commit is updated though.

"Current unstaged changes" has been used previously, "Working directory changes" is used in the commit form and just "unstaged" in the code. This does not include the indexed files so "uncommitted changes" would be incorrect. "Working dir" is slightly more according to Git documentation, but  I find "unstaged" clearer (and changing strings have some effect on translations).

**Comment by BUInvent** [comment]
I'm confused, even when I refresh GE, I still get the same problem. So the diff isn't accurate. Am I not right? Changing from "Current unstaged changes" to "Current uncommitted changes" is not necessarily the solution (and not really the important part) but I was hoping we could do something.

**Comment by gerhardol** [comment]
> when I refresh GE, I still get the same problem

What do you see?

**Comment by BUInvent** [comment]
> What do you see?
The same problem as mentioned above. When highlighting "Current unstaged changes" and the base commit. You see a diff even though there should be no diff.

**Comment by gerhardol** [comment]
But there is a diff: The file exists in "Working dir commit" but not the other commit you selected.
This is presented as a diff to /dev/null, the standard way for Git to present new files
