### ISSUE TITLE
Slow commit reading when using 2.51 with .Net 4.7.1 runtime

### ISSUE THREAD

**Issue by yesgrey** [gitextensions/gitextensions#4543]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
After installing .Net 4.7.1 runtime the commits reading got very slow. When we click on a different commit, it takes several seconds for its information to be shown.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Click on a commit different from the one it's currently selected. It will take several seconds for its information to show up.
**What is the expected behavior?**
The information of the new commit should be visible very fast.
**Environment you encounter the issue:**

- GitExtensions version: 2.51
- GIT version: 2.16.1
- OS version: Win 7 SP1 (32bit) with .Net 4.7.1 runtime

**Did this work in previous version of GitExtensions (which)?**
2.50.02 worked fine in the exact same environment

**Comment by malys** [comment]
Hi,
Same issue with:
* GitExtensions version: 2.51
* GIT version: 2.16.2.windows.1
* Windows 10 .NET   4.7.02556

Since the update to 2.51 ,GExt takes several seconds to open commit window.

**Comment by vmuriart** [comment]
Same issue on 2 systems both running win10 and GitExtensions 2.51 and 2.51.01.

**Comment by RussKie** [comment]
Can you please provide some tangible information?

**Comment by malys** [comment]
Hi,
installation of 2.51.1 has solved mi problem.  gitex is fast again. THX for developping thé best git client

**Comment by vmuriart** [comment]
@RussKie I'm trying to figure out how to best provide a good example. Currently what I am seeing is a lag (1-5 seconds) on the UI when clicking between different commits, or when doing commits. 

I've noticed this on multiple machines, on both 2.51 and 2.51.01 with various git versions as well. 
Downgrading to 2.50.02 seems to have made the issue go away.
I've seen this occur on various/different repositories 

The best I can think I can provide to demo the issue is a couple gif-screen captures showing the behavior. I doubt that will be enough. Are there logs that I can enable to help provide better information ?

**Comment by RussKie** [comment]
you can try capturing and comparing 
* git log timings in GE - Tools > Gitcommand log
* processes and I/O in [ProcMon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon)

**Comment by enzy** [comment]
Still experiencing noticeable slowness with 2.51.01

**Comment by vmuriart** [comment]
@RussKie I am withdrawing my earlier statements for now. In my case, the slowness is being caused by changes pushed to my systems from IT

**Comment by RussKie** [comment]
Thank you for the update. 
Ah the joy of corporate IT assets... it is all too familiar

**Comment by RussKie** [comment]
Please try [RC2](https://github.com/gitextensions/gitextensions/releases/tag/v3.00.00-rc2) and see if it is any better

**Comment by GintasS** [comment]
Abandoning this because of the age and lack of discussion.
