### ISSUE TITLE
Crash on opening repository in Recent list.

### ISSUE THREAD

**Issue by trevorloflin** [gitextensions/gitextensions#4549]
**Do you want to request a *feature* or report a *bug*?**
Bug report

**What is the current behavior?**
Sometimes when opening a repository, I'll get a crash with this exception:

```
The process cannot access the file 'C:\Users\[me]\AppData\Roaming\GitExtensions\GitExtensions\Recent\[my repository].gitext' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at GitUI.CommandsDialogs.FormBrowse.UpdateJumplist(Boolean validWorkingDir)
   at GitUI.CommandsDialogs.FormBrowse.InternalInitialize(Boolean hard)
   at GitUI.CommandsDialogs.FormBrowse.RefreshRevisions()
   at GitUI.GitUIExtensions.<>c__DisplayClass15_0.<InvokeAsync>b__0(Object s)
```

This is intermittent and difficult to reproduce. Here's what I know:
- The file is actually being locked, by the System process. It can't be deleted in Explorer without a reboot. I also can't delete the handle in Process Explorer (it gives an "Invalid Handle" error).
- The lock isn't temporary, it remains until I reboot the computer.
- I've never had a crash the first time I run GitExtensions after rebooting.

This leads me to believe that GitExtensions is not closing its handles on the file properly. E.g. when I close GitExtensions, it's got an orphan handle on the file, which System inherits. Then when I next open GitExtensions, it tries to access the file but is prevented by the remaining handle from the previous run.

**What is the expected behavior?**
GitExtensions shouldn't cause the file to lock, or barring that should handle a locked "Recent" file gracefully.

**Environment you encounter the issue:**
Windows 10 Pro x64

- GitExtensions version:
- GIT version: 2.51
- OS version: 10.0.16299 Build 16299

**Did this work in previous version of GitExtensions (which)?**
I've only encountered it recently, but I can't be sure it's not something specific to my current setup.

**Comment by pmiossec** [comment]
I have this behavior on my personal computer (win10) but not on my work computer (win7). I don't know if it's linked...

**Comment by RussKie** [comment]
This may be intermittent.
I haven't experienced this at all.

**Comment by kpetrianakis** [comment]
I have exactly the same issue on exactly the same environment. Any workaround? It is really annoying having to restart frequently

**Comment by RussKie** [comment]
Please provide more tangible info.

You can always clear the jumplist....

**Comment by kpetrianakis** [comment]
Clearing it and then opening the repository from File Open still makes Git Extensions Crash with the following error

The process cannot access the file 'C:\Users\[UserName]\AppData\Roaming\GitExtensions\GitExtensions\Recent\[Repo].gitext' because it is being used by another process.

The file is being held open by System.

**Comment by RussKie** [comment]
Hmm... what antivirus are you running?

Maybe worth running Process Monitor and see what's going on...

**Comment by kpetrianakis** [comment]
No Antivirus. Only what comes with Windows (Defender)

Here is what procmon shows
![image](https://user-images.githubusercontent.com/283247/40649953-c3fa4236-633a-11e8-8e39-2fa8d7e5f0fc.png)

**Comment by RussKie** [comment]
Thank you. Running out of ideas....

I suppose we could put a try..catch around the offending code to avoid a
fatal crash but it doesn't feel like a proper solution.

**Comment by afabre** [comment]
One of my computer started having the same issue a while ago, and I've tried to narrow down the issue.

A build with a tweak in the method UpdateJumpList, with all lines from [838](https://github.com/gitextensions/gitextensions/blob/46117b34afec58055251ce68c9f15eb733a18c3b/GitUI/CommandsDialogs/FormBrowse.cs#L838) to [846](https://github.com/gitextensions/gitextensions/blob/46117b34afec58055251ce68c9f15eb733a18c3b/GitUI/CommandsDialogs/FormBrowse.cs#L846) commented out almost never hit the issue (I spent at least 1, probably 2 months without hitting the issue once... but it crashed again last week).

So, keep writing the recent file, just as before, but skip the jumplist update so that it uses it helps. It hints at the logic to update jump list that somehow triggers System to keep an open handle to the recent file. There's nothing JumpList class that looks suspicious, it merely forward calls to the win32 API, and, on top of that, it hasn't changed for a while.

Combining that, with the fact that several people started to have the issue at about the same time (trevorloflin has the issue on Windows 10.0.16299 Build 16299, aka [Falls Creator Update](https://en.wikipedia.org/wiki/Windows_10_version_history), released back in April, I would suspect a regression in there.

Not sure what we can do there, except hiding the error under the carpet with a try/catch, as suggested 🤕

**Comment by kpetrianakis** [comment]
I agree, it looks like it has to do with a recent windows update...
I vote for the ugly try/catch suppress solution, unfortunately ….

**Comment by RussKie** [comment]
Could you please test and confirm the fix
https://ci.appveyor.com/api/buildjobs/qvgj6a6l23gig46c/artifacts/GitExtensions-2.51.01.2685-Mono.zip

**Comment by kpetrianakis** [comment]
It works for me, thank  you very much
