### ISSUE TITLE
Wrong diff for initial commit

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#4580]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
![gitext05](https://user-images.githubusercontent.com/1003909/37031162-065f3f9e-213e-11e8-9f81-12a1a0175fe8.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Checkout 458ef9d6f76f0d6278c218717b7ce48750124e3d (from jbialobr fork)
2. Open file history for the SearchWindow.cs file
3. Go to the initial commit and see the diff tab.

**What is the expected behavior?**
![gitext](https://user-images.githubusercontent.com/1003909/37031144-f7462400-213d-11e8-8c07-b00594eb9712.png)

**Environment you encounter the issue:**

- GitExtensions version: 2.51
- GIT version: 2.15.1 
- OS version: win10

**Did this work in previous version of GitExtensions (which)?**

Yes: 2.50

**Comment by RussKie** [comment]
It is disappointing we can't get this behaviour correctly...

**Comment by gerhardol** [comment]
Suggested headline: Diff for initial commit is compared to working directory

This is what I see in 2.50:
![image](https://user-images.githubusercontent.com/6248932/37058299-612e522e-218a-11e8-9a2b-e772b6c25d72.png)

The problem is that we cannot see the difference between comparing selected revision and working directory and this situation where we compare selected revision and there is no parent. If the file does not exist the output is as expected in the issue.
In 2.50, the working directory could only be compared to commit index, so it was not a problem here.

This should be solved with separating working directory and parent/child not existing. This is probably not possible for a 2.51 release.

I suggest the handling I see in 2.51 is reintroduced, as seen in my screenshot: If there is no parent, show the complete file (similar to how the Commit shows the diff also in 2.51).

> It is disappointing we can't get this behaviour correctly...

Considering that there was not even a standard if the diff arguments should be as in diff or the opposite and there were several ways to find what the parent/selected is, this is unfortunately not so strange. With #4569 the handling is at least consistent. But there are still such corner cases where the excellent GE feature with artificial commits clashes with Git functionality.

**Comment by RussKie** [comment]
A patch to 2.51 is still pending...
