### ISSUE TITLE
Changed the Reset file or directory changes hotkey

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#4666]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

The hotkey for `Reset file or directory changes` is set to `S`
I have not changed any hotkey settings, just pulled the master branch and compiled GE.
I wanted to stage a file but got a confirmation popup asking me if I want to reset the file:)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

N/A

**What is the expected behavior?**

The hotkey for `Reset file or directory changes` is set to `R`

**Environment you encounter the issue:**

- GitExtensions version: ddb9bd169d5fd643fab7ac1be501919a501367b2

**Did this work in previous version of GitExtensions (which)?**
Yes: 2.51

**Comment by RussKie** [comment]
A silly bug... I guess @mdonatas doesn't likes "5" :) And I didn't spot it during the review.

Are these persisted somehow? Do we need to write some tests to ensure the order?

**Comment by mdonatas** [comment]
Oh crap! I've double checked the digits before committing but somehow this still slipped through.
These are persisted in a settings file under the user folder. I've added explicit values because for not the first time I've inserted a new enum value where it makes sense logically and broke half of the keybindings as they got shifted when loaded from settings file.

**Comment by jbialobr** [comment]
I am not sure if we need to tag it with 3.0 milestone as this bug was never a part of any release.

**Comment by RussKie** [comment]
Yes, you're right, makes little sense. Thanks for keeping me in check :)
