### ISSUE TITLE
Drag and Drop Exception

### ISSUE THREAD

**Issue by jonathanmcelroy** [gitextensions/gitextensions#4861]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Occasionally, if you drag and drop from the file tree in one instance of GitExtensions into the file tree of another instance of GitExtensions, it throws this exeption:

![gitextensionsexception](https://user-images.githubusercontent.com/5642506/39000827-89f88a6a-43ba-11e8-80c1-544ccdf6b826.PNG)

I came upon this accidentally when I was dragging the file from the tree into my editor and the mouse ran over another instance of GitExtensions.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Open an instance of GitExtensions, open a repository, and view its file tree.
2. Open another instance of GitExtensions, open a repositry and view its file tree.
3. Try to drag one of the file elements from one instance to the other.

**What is the expected behavior?**
The drag will not throw an exeption.

**Environment you encounter the issue:**

- GitExtensions version: 2.50.02
- GIT version: 
- OS version: Windows 10 Pro

**Did this work in previous version of GitExtensions (which)?**

**Comment by gerhardol** [comment]
This occurs in the FileStatus panel where the file is dropped. The workaround is just to click OK, GE do not crash.

The error is that the assumption is that only text is dropped in in the area, it should occur also for other drag and drops.
https://github.com/KindDragon/ICSharpCode.TextEditor/blob/master/Project/Src/Gui/TextAreaDragDropHandler.cs#L62

**Comment by lhiginbotham** [comment]
@gerhardol @RussKie 
I'm taking a look at this at the moment and found a work around that avoids this exception.  During my investigations, I found that when dragging and dropping file[s] into an editable field, we can either ignore the drag-over and the drop or we can insert the path[s]/name[s] of the file[s] that were selected and dragged into the text editor.

Would you prefer drag and drops of files to be a no-operation gesture, or to place the paths of the selected files into the text editor?

**Comment by gerhardol** [comment]
Edit extends functionality but I do see that as expected. If only the path is transferred without revision then the correct file is not opened anyway.

**Comment by lhiginbotham** [comment]
@gerhardol 

Seeing as files can be brought in from Windows Explorer (with no associated revision) or from GitExtensions opened in a different repo (where it would not make sense to reference the revision in the text editor's Git repo), it might not be worth pursuing this additional functionality.  I think I will just opt for blocking the drag-drop of files rather than supporting it.

Is this okay with you?

**Comment by pmiossec** [comment]
@lhiginbotham 

> Seeing as files can be brought in from Windows Explorer (with no associated revision) or from GitExtensions opened in a different repo (where it would not make sense to reference the revision in the text editor's Git repo), it might not be worth pursuing this additional functionality. I think I will just opt for blocking the drag-drop of files rather than supporting it.

I'm not sure to understand. 

Do you propose to disable all the drag and drop support in Gitextensions? 

Because I use it sometimes, to easily get the history of a file by drag and dropping from visual Studio, vscode,... 

I won't be very pleased if this feature is removed.

**Comment by RussKie** [comment]
> Would you prefer drag and drops of files to be a no-operation gesture, or to place the paths of the selected files into the text editor?

I like placing the text DnD'ing it to a textbox 👍 
Could you please indicate which textboxes were you thinking to enhance?

**Comment by gerhardol** [comment]
@pmiossec 
How do you drag files to open the File History?

**Comment by pmiossec** [comment]
@gerhardol 
https://github.com/gitextensions/gitextensions/pull/6249#issuecomment-464031574 to select the file in the filtree and then key pressed 'H' or 'B'

**Comment by gerhardol** [comment]
I have tried drag&drop before and not seen it working...
There should maybe be some feedback if a path cannot be found.
But I expect this specific issue to be solved due to other changes (like #6249).
Close this and if someone bothers, an issue for improving the feedback?

**Comment by lhiginbotham** [comment]
@gerhardol @RussKie @pmiossec 

I think you guys might be mistaken as to what I am proposing.  This issue is in regard to the diff viewer (which is used in many situations in GE) and the "edit file" editor, which both use the ICSharpCode.TextEditor.TextAreaDragDropHandler class.  

Diff viewer:
![image](https://user-images.githubusercontent.com/14078392/67910859-bb544000-fb5a-11e9-9a36-4631d6e0fa75.png)

Edit file editor:
![image](https://user-images.githubusercontent.com/14078392/67910903-e50d6700-fb5a-11e9-8144-d489cefc6f4e.png)
or...
![image](https://user-images.githubusercontent.com/14078392/67910949-0d956100-fb5b-11e9-9bde-f1cec1e0064d.png)
which opens...
![image](https://user-images.githubusercontent.com/14078392/67910978-26057b80-fb5b-11e9-80dc-5ad9bb4f1a7b.png)


From my knowledge, the diff viewer is read-only, so no benefit will be gained here.  As for the "edit file" editor, this is not read-only.  This is the area that I am referring to when I ask whether it would be worth adding the functionality to.  As of right now, if you drag and drop ANYTHING from one GE process to another GE process and place it in the diff viewer or the text editor, then you will get the exception that is reported by this issue.  Curious enough, drag and drop of files from Visual Studio into the text editor will paste the path of the file into the text editor.  In addition, if you drag a file from Windows Explorer into the editor, then you will get NO perceivable reaction from GE, other than your cursor turning into an "invalid drag and drop" icon.  Finally, drag-and-drop of files within a single GE process will not result in any cast exception.

Maybe there is some (uncastable) COM wrapper put around the files when dragging between different GE processes?  I found that switching the GetDataPresent(typeof(string)) to check for DataFormats.FileDrop, DataFormats.UnicodeText, and DataFormats.Text all result in a non-exception-throwing operation.

I think for now the best thing to do would be to prevent the exception from occurring (without extending current functionality).

**Comment by lhiginbotham** [comment]
Also, @pmiossec, you taught me something cool with that drag-drop of files to get to the history in GE, thanks 😄👍 Maybe I should read GE's docs and see what else I am missing...

**Comment by RussKie** [comment]
@lhiginbotham thank you for clarifying. Indeed I was thinking of something entirely different.
Please update the issue's description explaining the proposal in details. Screenshots, animated gifs etc would help as well.

**Comment by gerhardol** [comment]
> Maybe I should read GE's docs and see what else I am missing...

Many features that are missing there. The doc need to be updated...
(I hoped that Dark Theme would be ready first so we do not have to change it again soon.)

**Comment by gerhardol** [comment]
The reason I see to drop something in the DiffFiles (list or viewer) or the File tree for that matter would be to select the file for that revision. That is what pmiossec implemented by dropping on the revision grid.
The revision the file is dropped on could have been selected too.
Note that if an artificial commit is currently selected, an exception with System.ArgumentOutOfRangeException is raised - really a separate issue.
