### ISSUE TITLE
Commit dialog should remember its panels sizes

### ISSUE THREAD

**Issue by evil-shrike** [gitextensions/gitextensions#4863]
Please makes Commit dialog to remember its panels sizes and positions. Currently on dialog resizing its whole sizes (w/h) are remembered but not panels' positions and sizes inside.

**Comment by kgrammer** [comment]
+1 to both of the above comments.

**Comment by vbjay** [comment]
Already fixed.  If you search for issues first...  Closed and open.

**Comment by vbjay** [comment]
Ok.  That was the browse and not commit window.  Similar issue though.

**Comment by kgrammer** [comment]
Well, it doesn't appear to be fixed in 2.51.02 which is the release I'm running.  If I resize and/or move a window (main, commit, etc.), the size and position is not remembered.  When I exit and restart the default small window returns.

Is there a setting someone that needs to be checked to have it remember?

**Comment by vbjay** [comment]
See #5021

**Comment by kgrammer** [comment]
Cool.  Thanks.  I searched for "size" and other words but that one didn't pop up.

I look forward to getting that feature back in 2.51.03... :)

**Comment by vbjay** [comment]
(y)  Go ahead and close this issue since it is already resolved.
