### ISSUE TITLE
Artificial GUID for Staged was set to the same as for CombinedDiff

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#5015]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
regression from #4988  (still great PR)
The GUID for Staged commit was changed from 1111... to 2222... which is the same as for CombinedDiff.
Checks for Combined Diff failed, for instance RevisionDiff difftool was not allowed for WorkingDir

**Environment you encounter the issue:**

- GitExtensions version: master

**Did this work in previous version of GitExtensions (which)?**
yes

**Comment by RussKie** [comment]
Damn, I noticed that change but forgot to ask why it was changed...

**Comment by drewnoakes** [comment]
`IndexGuid` was changed from 1's to 2's because `UnstagedGuid` was changed from 0's to 1's.

The motivation here was to avoid having a special value be equal to the default, uninitialised data value of an `ObjectId`.

This was required when I experimented with having `ObjectId` be a `struct`. It's a `class` now, but I still think 0's shouldn't have a special meaning.

Apologies for missing `CombinedDiffGuid`. Consolidating them all in one place is a good improvement 👍

**Comment by gerhardol** [comment]
> Damn, I noticed that change but forgot to ask why it was changed...

I did not have time to review the big change in #4988. The PR is still great, things like this will happen.

I considered consolidating the artificial guids when updating FileStatusList some time ago. Previously a text string was used but RussKie commented on that so I changed to a 'proper' string but kept the handling (mostly) private in FileStatusList. Drew would have seen the change without my change or with a consolidated change... PR updates at least.
