### ISSUE TITLE
Feature request: show local branches only

### ISSUE THREAD

**Issue by kasal** [gitextensions/gitextensions#5078]
Feature request: show local branches only

I'd like to have a view that displays less than "all local and remote branches" but more than "current branch only."

Situation: "show all branches" presents a nice overview of all my work and related remote work
But if there is a recent remote branch with many commits, it occupies lot of space.
I would like to get rid of these.

The view shall contain all local branches, perhaps also their upstream remote branches, but not all remote branches.

Alternatively, remote branches would simplified, represented by their tip commits only.

Note: Actually, I expected this behaviour when I uncheck "Show remote branches;" would it be reasonable to change it?

Perhaps the option "Show remote branches" shall be renamed to "Show remote branch references" (corresponds with "Show reflog references")

**Comment by gerhardol** [comment]
Not what you asked for, but gives overview also with current branch only:
GE v3 has a left-panel that lists branches so you have a quick overview of both local and remote branches

![image](https://user-images.githubusercontent.com/6248932/41432766-3a068c26-7017-11e8-86dc-deb4298da45c.png)

**Comment by MattLichter** [comment]
+1

This is actually what I expect when I de-select View->Show remote branches.  Removing just the labels in the graph doesn't really add much value for me.  I'd like to see their commits removed from the graph as well.

I'm dealing with a really messy git repo that I don't have control over.  Dozens of long-running branches, with lots of merges between non-master branches.  Of all these branches, I may only be interested in three of them.  It would be **really nice** to checkout the three branches, then disable "Show remote branches", and have all the other branches *and their commits* disappear from the graph.

My workaround so far is to use the advanced filter, but this doesn't persist between gitext sessions, so I have to re-type it every time.  That's tedious, especially when the branch names are really long and awkward (which of course they are in my case :).

If someone wanted to point me in the general direction to implement this, I'd be happy to take a crack at it.  I have only skimmed the gitext source code, but it looks like the straightforward winforms code that I work with every week.

**Comment by vbjay** [comment]
You are asking for a mountain.  Think of git commits like a paperclip chain.  Branches are just a labeled pointer to an end commit or paperclip or HEAD.  This is why the remote branches just removes the labels on the commits.  This is why the filtering is done somewhere else.  You can right click a commit and tell it to show only that branch.  

![image](https://user-images.githubusercontent.com/3629489/46217504-2ad07e00-c310-11e8-8cb8-610bf2ca02ca.png)

**Comment by vbjay** [comment]
One thought is you could ask for a persistence of the filtered branch names so that you could just select show only filtered branches each time the application starts.   I bet you could even create a pull request to do so.  Don't remember the filtering just what the filter value is.

**Comment by MattLichter** [comment]
@vbjay Thanks, I'll look into your suggestion regarding filter string persistence.  If I can't manage make a pull request, I'll add it as a feature request.

**Comment by brianjlacy** [comment]
+1 I think I understand the OP's conundrum; I've also got a project with thousands of commits by various folks which makes it really hard to see what's going on.

I find the "Branches" filter control in the toolbar very useful for narrowing things down to the commits that are most relevant to a specific branch; but might it be possible to change that to a "checklist" to be able to show a combined view of only those branches I choose from that list?

So, from:
![git-extensions-branches-filters-20180318](https://user-images.githubusercontent.com/19938700/77013437-b0e1e980-6935-11ea-9ac2-06e3c8f64a17.gif)

To (e.g.):
![git-extensions-branches-filters-checked-20180318](https://user-images.githubusercontent.com/19938700/77013802-7b89cb80-6936-11ea-9d26-17a5163542c9.gif)

Feasible??

**Comment by RussKie** [comment]
> Feasible??

Maybe? ¯\_(ツ)_/¯
What git commands do we need to run? Or do we need to get the full history and parse it dynamically?

**Comment by ruffin--** [comment]
Would love to reopen this request in large part because I often use it in projects with too many coders, [exactly as @brianjlacy describes](https://github.com/gitextensions/gitextensions/issues/5078#issuecomment-600893326). If I'm just worried about, say, two or three devs' work on a specific topic, I ensure I only have their most recent branches pulled down locally and compare their work without any of the noise of ten other branches.

I'm trying Fork out now. I _love_ the ability to swap order of branches when I diff ("Reverse Commits"), but I'm lamenting losing the ability to cut out all the remote branch noise.

Which brings me to... I also really want it because SourceTree has had the feature for years -- I should know; I still prefer [a version from 2015](https://community.atlassian.com/t5/Sourcetree-discussions/I-m-still-using-SouceTree-1-7-b-c-I-prefer-well-everything-about/td-p/762618). I've come to rely on the ability to reduce branch noise like that as part of my workflow.

![Screengrab of SourceTree's Source Remote Branches checkbox](https://user-images.githubusercontent.com/5659878/196717386-c3feb23f-2d5e-4cd2-adfe-16de24f747f3.png)

That doesn't make adding the feature any easier, of course, but it does make me wonder if there's an easy way to do it that we're missing.

For instance, I think you can just grab the latest local date of a branch and ignore commits with dates past that in the UI. That's at least reasonably straightforward. Though I'm suspicious there's a git native way too.

**Comment by MattLichter** [comment]
@ruffin-- The latest version of GitExtensions lets you deactivate remotes:
![image](https://user-images.githubusercontent.com/8321199/196721339-c3a5dd29-d4f2-4281-8b76-0e2c9de16a0f.png)

This effectively hides all remote tracking branches for that remote.  Does this meet your needs?

BTW Huge thanks to the GE team for implementing this feature!

**Comment by ruffin--** [comment]
@MattLichter  Mac only maybe?

![image](https://user-images.githubusercontent.com/5659878/196743091-d26c8301-4faf-4542-a11e-fe6d285f1a73.png)

That's from 1.78.1.0 on Windows. The [versioning does look different, Mac vs. Windows](https://git-fork.com/releasenotes), so that might be it.

Not quite as discoverable, but I'll be on the lookout. If that does the same (though perhaps on a remote-by-remote basis), that would work!

**Comment by gerhardol** [comment]
Since many years:

![image](https://user-images.githubusercontent.com/6248932/196767778-fd4f9cb6-16ad-424a-be25-d6c025018297.png)

Hide all remotes in grid (from 4.0 beta, same in master)

![image](https://user-images.githubusercontent.com/6248932/196767247-1ac4e986-11b5-44a8-9df7-641fb0c28906.png)

Special in 4.0 to hide certain branches (not documented yet)

![image](https://user-images.githubusercontent.com/6248932/196767515-c2090261-fca5-416d-9eec-61b1c6277d69.png)

**Comment by vbjay** [comment]
Reread the readme and what versions are xplat.

**Comment by pmiossec** [comment]
I think that @ruffin--  noticed that he asked a feature for another git GUI than gitextensions that's why he has deleted its messages...

**Comment by RussKie** [comment]
This is the reason I proposed to lock closed issues, like we do in dotnet/*
repos, to stop random chat like this and "me too" posts.
