### ISSUE TITLE
Not seeing which is the Mac install version

### ISSUE THREAD

**Issue by skyvondave** [gitextensions/gitextensions#5123]
**Do you want to request a *feature* or report a *bug*?**

Bug from https://github.com/gitextensions/gitextensions/releases/tag/v2.51.02

**What is the current behavior?**

The Getting Started instructions for Mac say "Now download Git Extensions latest version from https://github.com/gitextensions/gitextensions/releases/latest. Remember to select the appropriate package otherwise you could have problems.", however, the link doesn't seem to have any Mac install or program files and doesn't even specify anything about Mac.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Search for Git Extensions Mac, find that releases help page above, get stuck.

**What is the expected behavior?**

Have a downloadable Mac file to install the program with (I do have Mono installed already).

**Environment you encounter the issue:**

Mac OS

- GitExtensions version: 2.51.03
- GIT version:  2.14.3
- OS version: 10.12.6
- .NET version: Mono 5.10.1.47

**Did this work in previous version of GitExtensions (which)?**

Can't install

**Comment by vbjay** [comment]
We don't support mono anymore.

**Comment by vbjay** [comment]
Well on master we don't.  On 2.5 you can look at the releases.  I'm sure you can figure out which one would be the one you need.

**Comment by vbjay** [comment]
https://github.com/gitextensions/gitextensions/releases/latest

**Comment by vbjay** [comment]
On the readme:

![image](https://user-images.githubusercontent.com/3629489/42053546-cf36be38-7adf-11e8-8798-41eba782cd5e.png)

**Comment by RussKie** [comment]
Portable or Mono.zip is what you want.

A word of caution, GE on Mac is not particularly great experience....
There are a number of tweaks you may likely need to do, check #4090.


On Jun 29, 2018 5:35 AM, "Gerhard Olsson" <notifications@github.com> wrote:

Linux/MacOs hints
https://github.com/gitextensions/gitextensions/wiki/How-To%3A-run-Git-Extensions-on-Linux

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/gitextensions/gitextensions/issues/5123#issuecomment-401148553>,
or mute the thread

**Comment by skyvondave** [comment]
This maybe looks overly-complicated or issue-prone... can someone recommend the next best alternative to Git Extensions for Mac?

I'm trying out SourceTree and it's basically a pain in the butt compared to Git Extensions (for Windows).

**Comment by RussKie** [comment]
Run Windows in Parallels and use Git Extensions 🎉
