### ISSUE TITLE
Crash in Master

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#5242]
**Do you want to request a *feature* or report a *bug*?**
🐛 
**What is the current behavior?**
![image](https://user-images.githubusercontent.com/3629489/43358613-7fabd566-9262-11e8-888f-e04c03f8cd2b.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
No crash
**Environment you encounter the issue:**

- GitExtensions version:Master
- GIT version: 2.18
- OS version: Microsoft Windows [Version 10.0.17134.191]
- .NET version: 4.7

**Did this work in previous version of GitExtensions (which)?**

**Comment by RussKie** [comment]
It would be great if next time you could post the stack trace as text as well.

**Comment by vbjay** [comment]
Sure.

**Comment by RussKie** [comment]
It is not happening for me. Do you have a reliable way to reproduce?

**Comment by vbjay** [comment]
Not really. Just noticed it. I'll keep an eye out.

**Comment by drewnoakes** [comment]
There's not enough information in that stack trace to reveal the issue here. Whatever state is causing the problem does not appear to be on the stack.

https://github.com/gitextensions/gitextensions/blob/85d0072839034f5c8b162b65b36db9e9bbcbc88f/GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs#L552-L570

The call to `NotifyProvidersVisibleRowRangeChanged` here is the hand off to the UI thread, where this code runs.

Do you remember what you were doing at the time?

**Comment by vbjay** [comment]
No. Sorry.

**Comment by RussKie** [comment]
I'm going to close it, let's reopen it if it comes back.

**Comment by vbjay** [comment]
Sure.
