### ISSUE TITLE
Build configurations

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#5270]
**Do you want to request a *feature* or report a *bug*?**

Discussion.

The solution currently has two solution platforms:

- Mixed Platforms
- Any CPU

@sharwell points out in https://github.com/gitextensions/gitextensions/pull/5269#discussion_r206935731:

> We should delete one of Mixed Platforms or Any CPU unless both are useful. Not good having multiple configurations when some are invalid.

So, do we need both? 

We also have a build configuration `ReleaseTC` which doesn't seem to be used anywhere. Can that go too?

**Comment by pmme** [comment]
`ReleaseTC` was introduced in 32e8a7aadef6d5e8cad2778c8012d31edbf92ef0 (and in a parallel branch 622a6779ece4c4a57ff0ac5800703fea83b04e0a) for TeamCity.
TeamCity isn't something I use but I was curious about these build configurations so I thought I'd track them down.

**Comment by RussKie** [comment]
I think it should be safe to delete, we don't use TC as part of our CI pipeline

**Comment by pmme** [comment]
Mixed Platforms, x86 and x64 were removed in bd916ac44f306c4b11cb373f8963dd3e7da6afd4 
(and one more in a16e72c37e90a37b0398a39da07eb570a14cb83b, because the GitFlow project had the old configs)

Mixed Platforms was reintroduced in e381bfd31de367c21f30c5a2bad979d96a50935e, presumably by accident, during what appears to be an "evil merge".

**Comment by drewnoakes** [comment]
Thanks all for the research, I'll pop a PR together that removes these.

> "evil merge"

Gives me flashback of CVS and SVN 😱

**Comment by RussKie** [comment]
🤣
