### ISSUE TITLE
Show all stashes in the revision grid

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#5371]
**Do you want to request a *feature* or report a *bug*?**
enhancement (low prio, primarily logged as an issue if someone else stumbles on this, too)

**What is the current behavior?**
Multiple stashes (with identical names based on the same revision) are not shown separately in the Revision grid.
In general, Git Extensions shows only the latest stash in the Revision grid (see gerhardol's comment below)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
* checkout (the most recent) branch and modify a file
* stash the changes
![grafik](https://user-images.githubusercontent.com/36601201/44882136-5bda7600-acb2-11e8-81d5-15f4f673dd0b.png)
* modify a file and stash the changes
![grafik](https://user-images.githubusercontent.com/36601201/44882174-8298ac80-acb2-11e8-9cfa-1849973f81c7.png)
* open the stash manager and drop down the list of stashes
![grafik](https://user-images.githubusercontent.com/36601201/44882272-ecb15180-acb2-11e8-9a00-f2921c700182.png)

**What is the expected behavior?**
All stashed should be visible in the Revision grid.
gerhardol: A second enhancement could be to allow for manipulations of stashes in Revision grid.

**Environment you encounter the issue:**

- GitExtensions version: master **and** 2.51.02
- GIT version: 2.17.1.w.2-x64
- OS version: Windows 7
- .NET version: 4.7

**Did this work in previous version of GitExtensions (which)?**
no

**Comment by gerhardol** [comment]
GE shows one stash only, for the latest stash. Other stashes are not visible.
This behavior is not changed in 2.x vs master.
It is kindof a bug, it is shown due to the way Git shows stashes. But the short term fix would be to remove stash in Browse completely, which is not what I want.

So I suggest you change the description to an enhancement:
Show all stashes in the revision grid
(controlled in the same was as e.g. reflog branches)

A second enhancement could be to allow for manipulations of stashes in revision grid.

**Comment by eric-wieser** [comment]
It surprises me that even showing reflog references does not seem to make stashes appear

**Comment by gerhardol** [comment]
TCurrently, a single git-log command is used to get the commits in the revision grid.
It does not seem to be possible to get the stashes in the same command (when searching for it, I found a question from @jbialobr on StackOverflow so this has been attempted before). So stashes without reflog would require a separate command and that the grid is not drawn until the output is merged. So GE would be slower with this option.

Similar to add a label with reflog, that info is not available. However, it should be possible to add the label after like for subrepo labels.

**Comment by mdonatas** [comment]
I have this enabled in my custom build, can't say I feel any slowdown
https://github.com/mdonatas/gitextensions/commit/a91d1846cdb3a0525ad6893cea0c4bd494565276

**Comment by gerhardol** [comment]
> I have this enabled in my custom build, can't say I feel any slowdown [mdonatas@a91d184](https://github.com/mdonatas/gitextensions/commit/a91d1846cdb3a0525ad6893cea0c4bd494565276)

In a repo like gitextensions this adds 200 ms for me, which is 30% extra time (in master, init is heavily optimized there).
So not zero impact.

You can use reflog already, almost no performance impact (but you will see other commits too).

The stash commits probably need special "rectangles" in the grid too.

That said, I would probably toggle seeing stashes if this was available (as I use stash heavily) in situations when reflogs are overwhelming.

**Comment by gerhardol** [comment]
See also #5460 for stashes in the sidebar (this is a prerequisite).

The way the stash revisions are added is essential to how to identify stashes for operations.
The suggestion in https://github.com/gitextensions/gitextensions/issues/5371#issuecomment-1049570568 will require adding attributes to the revisions when adding them to the grid. () attributes will need to be new.
I merged #5785 to also add stash operations to the context menus. This issue also discusses ordering of stashes
https://github.com/gitextensions/gitextensions/issues/5785#issuecomment-450683212
If stashes are reordered to be placed with the commit, they need to be excluded in the "insert" when viewing reflog.

Suggestion:
* Run `git stash list  --pretty=format:"%H%P %s"` after (or parallel to) `git for-each-ref` to get the *main* stash commit and the first parent for where to insert. Create dictionaries for commit->stashes and stash->commit
* Further handling depends on the ordering
  * reflog requires no `git-stash` prior to *main* `git-log`, only add attributes
  * If git-order is preferred, the data is required prior to git-log runs and be added to the *main* `git-log`. Otherwise similar to reflog
  * If *stash close to commit* is preferred, `git-stash` commits are inserted when viewing similar to artificial commands. This will not work well with filtered views when the *main* commit is filtered in the grid and the commits need to be inserted afterwards
