### ISSUE TITLE
Pull in toolbar: "Set the next selection as default" stays checked

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#5374]
**Do you want to request a *feature* or report a *bug*?**
regression bug, code review

**What is the current behavior?**
The menu item `Set the next selection as default` is not automatically unchecked after a pull action has been selected.

The method `DoPullAction` is not used for all of the pull menu items -- looks like unfinished refactoring.
I started to finish it and found that AppSetting.DefaultPullAction affects how the pull dialog will behave.
This is a very unexpected behavior in my opinion.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- check `Set next selection as default`
- `Fetch`
- `Set next selection as default` is still checked

**What is the expected behavior?**
The menu item `Set the next selection as default` shall automatically be unchecked after a pull action has been selected.

AppSetting.DefaultPullAction shall only affect what will happen when the toolbar button is pushed.

**Environment you encounter the issue:**

- GitExtensions version: master
- GIT version: 2.17.1.w.2-x64
- OS version: Windows 7
- .NET version: 4.7

**Did this work in previous version of GitExtensions (which)?**
2.51

**Comment by RussKie** [comment]
I must have never paid attention because the first thing I'd do opening a new repo is to check "Set next selection as default" and then "Fetch all". From that point onwards I would always click the toolbar button and rarely, if ever, open the dropdown again....
However upon checking the existing (i.e. v2.5x branch) behaviour, it works as described - it resets the checkbox.

So it looks like I have unintentionally added a regression in #5324. @zvirja has come up with a fix as part of #5321, which I asked him to submit separately.

**Comment by vbjay** [comment]
Appsettings is how it is stored so why not keep it there?  We use
appsettings so that when we application exits the settings are saved.

**Comment by mstv** [comment]
`AppSetting.DefaultPullAction` shall only be set if `Set the next selection as default` is checked, not always.

But e.g. having
`AppSetting.DefaultPullAction = AppSettings.PullAction.FetchAll` and `AppSettings.SetNextPullActionAsDefault = false`,
then `Fetch` will run
`git.exe pull --progress "master"`
Instead it must be
`git.exe fetch --progress "master"`

**Comment by mdonatas** [comment]
I always found this `Set the next selection as default` behavior strange and not even sure if I ever saw it in any other application. Should we maybe change it into a submenu where one could select the default actions?
So instead of `Set the next selection as default`
it would be
`Set default action`
-- `Pull - merge`
-- `Pull - rebase`
-- `Fetch`
-- `Open pull dialog...`
-- `Fetch all`

This would not only be more clear but would also solve this spaghetti with checking and unchecking this checkbox. Ideas? :)

**Comment by RussKie** [comment]
I think this may work

**Comment by zvirja** [comment]
I do agree that nested menu with work much better! 👍  Great idea!

**Comment by mdonatas** [comment]
Just an FYI, I am working on a PR for this approach.

**Comment by gerhardol** [comment]
I still prefer to have this setting in the dialog, even if it is more difficult to find - more flexible

**Comment by zvirja** [comment]
Oh, thanks, for mentioning. Glad to hear that :relaxed:

**Comment by mdonatas** [comment]
Preview

![image](https://user-images.githubusercontent.com/483659/45124595-98571780-b173-11e8-843f-3e8c16ad53e7.png)

**Comment by RussKie** [comment]
The divider needs to go in the new menu

**Comment by EbenZhang** [comment]
much better @mdonatas

**Comment by vbjay** [comment]
If we added a tag to the menus that do the actions, we could just loop and
create menus in the sub menu that duplicate the menus and the setting could
be set by the value in the tag property of the source menu.  Then all we
need to do is add a new menu that does the new action and set the tag
property and the text properties could be copied.

**Comment by zvirja** [comment]
@mdonatas Also it makes sense to mark the currently selected option with bold. Functionally it changes nothing, but will look much nicer :relaxed:
