### ISSUE TITLE
reset all files to a revision?

### ISSUE THREAD

**Issue by hinstw** [gitextensions/gitextensions#5464]
In GitExtensions UI, currently it is possible to reset individual files to a specific revision, but not possible to reset all files to specific revision
I often need to reset all files, but i have to click all of them one by one to do that ((

![reset-all-files](https://user-images.githubusercontent.com/43474314/45885460-d3358e00-bdb6-11e8-8ff4-c8b44c913aee.png)

on screenshot: there are 6 folders in the repo root folder; need to click every one of them. I often have way more files than 6 files in the repo root dir

**Comment by vbjay** [comment]
Right click commit. Checkout revision. Then checkout branch and don't change in the dialog.

**Comment by vbjay** [comment]
We have an issue template for a reason.

**Comment by pmiossec** [comment]
If you want to reset **all** files to the state of a specific revision (even if I don't understand completely the need), you could :

1. reset hard to this revision.
2. reset soft to the previous commit.

Note: To be able to reset back to this initial commit, because their is a great chance it won't be visible anymore on e you did the first reset, you could either previously create a branch or use the "View" > "Show reflog references".

Done.

**Comment by vbjay** [comment]
That's the idea behind checkout revision instead of reset branch.

Checkout the commit you want.

Then check out branch dialog. Click don't change and pick branch. You now
have a working directory like the 1st commit and the right granch is
checked out.

**Comment by vbjay** [comment]
You can also hit Ctrl a in the file tree and hit reset context menu option.

**Comment by RussKie** [comment]
As suggested above there are a number of possible ways to reset files to the selected revision.

In the future, please make sure to fill the issue template, we have it for a reason.
