### ISSUE TITLE
Submodules dialog gets confused

### ISSUE THREAD

**Issue by ggnkua** [gitextensions/gitextensions#5466]
Hi,

I have a project in which a few submodules contain open and close parentheses in the path. This results into something like the following screenshot:

![image](https://user-images.githubusercontent.com/5121492/45913650-0e7b9f80-be3f-11e8-846f-8755c91d3ee3.png)

"Name" field should contain `ASM/Various/Sascha Springer (Anima)/chorensha`. So it seems something gets confused while parsing "Name" and encounters the opening parenthesis?

I've been witnessing this for a long time now up to current version (2.51.05) on Windows so it's not a new issue FWIW.

**Comment by vbjay** [comment]
We have an issue template for a reason.  



**Do you want to request a *feature* or report a *bug*?**
--->>>
**What is the current behavior?**
--->>>
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
--->>>
**What is the expected behavior?**
--->>>
**Environment you encounter the issue:**
--->>>
- GitExtensions version:
- GIT version: --->>>
- OS version: --->>>
- .NET version: --->>>

**Did this work in previous version of GitExtensions (which)?**
--->>>

**Comment by RussKie** [comment]
Please fill the report correctly, then we'll re-open it.
