### ISSUE TITLE
“Show console window” doesn't always work

### ISSUE THREAD

**Issue by IEVin** [gitextensions/gitextensions#5502]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When options *'Show console window when executing git'* and *'Use Console Emulator for console output in command dialogs'* are unchecked git console window appear but only for  fetch/pull/push commands.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Open Tools\Settings
1. In Git Extensions\General in block Behaviour uncheck *'Show console window when executing git'*
1. In Git Extensions\Advanced in block General uncheck *'Use Console Emulator for console output in command dialogs'*
1. Close settings
1. Run fetch (or push/remote/pull)

Git window will appear. If run any local command (like revert commit or rebase) git window will not appear.

**What is the expected behavior?**
Git window should be hidden.

**Environment you encounter the issue:**

- GitExtensions version: 3.00.00 beta
- GIT version: 2.18
- OS version: Windows 10 x64
- .NET version: 4.6+

**Did this work in previous version of GitExtensions (which)?**
In GE 2.51.01 doesn't work too.

**Comment by IEVin** [comment]
Problem in [this line](https://github.com/gitextensions/gitextensions/blob/96b7ed6ba385a698ce8547a0e62639a93a012910/GitUI/UserControls/EditboxBasedConsoleOutputControl.cs#L123)
When command use ssh, git console window is not hidden.

**Comment by IEVin** [comment]
GitCommandHelpers.UseSsh have no any another usages. Is this expected behaviour or just a legacy?

**Comment by gerhardol** [comment]
Console is needed if you have set a passphrase for the key or ssh  is not accepted (normal login often attempted).

**Comment by hypersw** [comment]
My changes, as far as I remember, were specifically for replacing a redirected stdout edit box with a real terminal emulator (implemented by ConEmu-inside). The main goals (besides displaying the real git output and progress messages) were (a) user input when prompted by git, say, for passphrase, or whatever else; (b) making git believe it's running in the interactive mode in the real terminal, otherwise it didn't even try to prompt for adding the host key on the first connection. The latter was the main reason. Passphrases aren't used too much, but you can't skip past asking for the host key on the first connection, and that were unsolvable without the terminal because at some version git started checking whether it's running in an interactive terminal.

I tried to keep the old non-ConEmu behavior as it were. Maybe that were related to the passphrase. I vaguely remember the editbox code had attempts to intercept passphrase questions and handle them somehow.

**Comment by IEVin** [comment]
> @IEVin is it causing problems to end users or more an inconvenience?
No, this is just unexpected behavior and sometimes obstructs progress dialog with real output.

**Comment by RussKie** [comment]
> obstructs progress dialog with real output.

Does it go away on its own?

**Comment by IEVin** [comment]
>Does it go away on its own?

Yes, when the operation ends the console window closes and user can read log. Or just move console window when operation in progress.

**Comment by RussKie** [comment]
At this stage we'll call it by design.

**Comment by TomasChmelik** [comment]
What about now? I know I have the remote configured so the console will never prompt me for anything, yet it still obstructs command window. Would it be possible to at least open the console minimised if `AppSettings.ShowGitCommandLine` is false?
