### ISSUE TITLE
Need to Fetch Before "Pushing with Lease" When Local Branch History Changed

### ISSUE THREAD

**Issue by artina** [gitextensions/gitextensions#5536]
**Do you want to request a *feature* or report a *bug*?**
A bug ( or maybe intended behavior).

**What is the current behavior?**
Every time the local branch history has been changed (e.g., reset, rebase, etc), you have to fetch from remote before you can **push with lease**. If you **push with lease** directly without fetching, it will fail.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
To reproduce, try following steps:
1. check out a remote branch to local;
2. add two commits locally and push to remote;
3. reset local branch to the commit just before the two new commits (**mixed mode**);
4. commit uncommited changes locally (essentially merge two commits into one);
5. try to **push with lease**, it will fail;
6. fetch and **push with lease** again, it will success.

**What is the expected behavior?**
No need to fetch.

**Environment you encounter the issue:**

- GitExtensions version: **2.50.01**
- GIT version: **2.6.3.windows.1**
- OS version: Windows 7 Enterprise SP1
- .NET version: 4.0.30319

**Did this work in previous version of GitExtensions (which)?**
No.

**Comment by vbjay** [comment]
That's the whole point.

**Comment by vbjay** [comment]
https://developer.atlassian.com/blog/2015/04/force-with-lease/

**Comment by pmiossec** [comment]
@artina with the example you gave, we can't be sure if you miss something (most probable) or if you've got a bug in git (not in GitExtensions!)

With the steps to reproduce you gave, if you are the only one to push to the remote, "force with lease" should not fail.

But if someone else pushed to the remote when you are occupied to do the step 3. and 4., that's normal that "force with lease" failed. That's a security to not loose other developers commits that you didn't saw (that's why you need to fetch first that way you are aware that they exist and you "loose" consciously). 

I'm pretty sure that by doing step 6., you didn't understood that you loose the work of your co-developers...

And, like @vbjay told you, this control to verify that you don't loose work is the main goal of "force with lease" over just a "force push"...

If you are the only one pushing to this remote, there is perhaps a bug in your version of git (and you should perhaps update your git version)

PS: the option is called "force with lease" (and not "push with lease")

**Comment by RussKie** [comment]
I trust the above answers address your issue.
