### ISSUE TITLE
Clone dialog doesn't pick up destination

### ISSUE THREAD

**Issue by asherber** [gitextensions/gitextensions#5590]
**Do you want to request a *feature* or report a *bug*?**  Bug

**What is the current behavior?**  Right-clicking in a folder and choosing GitExt Clone does not populate the Destination field

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**  Right-click in or on a folder and choose GitExt Clone.

**What is the expected behavior?**  Destination field should be populated with the name of the current folder.

**Environment you encounter the issue:**

- GitExtensions version: 3.00.00 beta1
- GIT version: 2.17.1.windows.2
- OS version: Windows 10
- .NET version: 4.7.2

**Did this work in previous version of GitExtensions (which)?**  2.5.x

**Comment by mstv** [comment]
Encountered this, too. It worked in the v3 master branch at least two month ago.

**Comment by lhiginbotham** [comment]
I can probably give this a look.  As I am new to this project, can anyone give me any tips on debugging the code responsible for Windows Context Menu functionality, such as what files contain the code?

**Comment by RussKie** [comment]
> Encountered this, too. It worked in the v3 master branch at least two month ago.

Yes, I think we regressed somewhere.


> I can probably give this a look

Awesome 👍 

Debugging this particular one is a bit tricky. 
What I've done in the past trying to fix this bug was to:
* rename/backup the official installation `C:\Program Files (x86)\GitExtensions` folder
* add `Debugger.Launch()` somewhere here:
https://github.com/gitextensions/gitextensions/blob/99e3c0f52da5cd79598d3ae4e8718390914dae01/GitUI/CommandsDialogs/FormClone.cs#L62-L67
* build the app
* copy the debug build into `C:\Program Files (x86)\GitExtensions`
* attempt to clone
* attach the debugger and debug
* once it is fixed, restore the official GE version

**Comment by RussKie** [comment]
Thank you for the heads up.
RL comes first, so don't stress about it. This isn't a showstopper bug, we
can fix it in subsequent releases.
