### ISSUE TITLE
Make commit dialog modeless

### ISSUE THREAD

**Issue by andygarcia** [gitextensions/gitextensions#564]
A modal commit dialog is not intuitive, especially when minimized.

**Comment by drewnoakes** [comment]
Another nuisance of the modal commit dialog is that it brings the main window forward with it when focused.

For example, if you dock the main window left, then open the commit dialog and dock it right, then you open an IDE docked left and focus the commit dialog, the main window obscured the IDE. You end up having to juggle the windows a bit to get it the way you want.

I realised recently that I basically only use the commit window, and I'd be happy to launch it standalone. I really like the ability to commit patches with the mouse (rather than interactively on the console), but all other git stuff feels more comfortable at the command line.

With this in mind, my answers to the three questions posed by @vcpp are:

1. Reuse the commit window on a repository basis (I would like to have multiple commit windows open for different projects).
2. Leave the commit window open
3. Committing in the child window notifies main window of new commit, so update occurs immediately

It seems that there is agreement between @NJAldwin, @jbialobr and myself (the three respondents) on everything except the second point, and that could be controlled by an option in this existing drop-down:

![image](https://cloud.githubusercontent.com/assets/350947/24107095/c4262b22-0d81-11e7-922f-f95183bacafd.png)

There's some interesting discussion at the UX Stack Exchange site:

http://ux.stackexchange.com/questions/39778/benefits-and-drawbacks-of-modal-windows

It seems to come down to whether you use the commit window for a short spell, or whether you leave it open. A tool like Git Extensions fits into the varied workflows developers. On this issue alone I feel like it was designed for someone with a workflow different to mine. Anecdotally, this view is shared by the other developers on my team.

**Comment by drewnoakes** [comment]
Recently, a console was added to the tab control in the lower pane of the main window. Why couldn't the commit window be added as a tab there too?

This seems like a great solution to me.

**Comment by drewnoakes** [comment]
Here's a mockup. The tab titles would need to change. Maybe the second "Commit" tab becomes "Changes".

![image](https://cloud.githubusercontent.com/assets/350947/24108075/7c608424-0d84-11e7-9cc5-0618ff6caf56.png)

You could still keep the existing commit window for users who have grown to like that. At least from a visual perspective, the control could be reused (minus the options about closing the dialog on commit, etc).

**Comment by jbialobr** [comment]
>This seems like a great solution to me.

It is indeed a great idea! Most of the time I switch to the Browse dialog only to open the Commit dialog.

**Comment by vbjay** [comment]
The only problem I would see with it is ui slowdown.  That is a lot of
functionality rolled into one form.  Maybe not update the control till the
tab is active.

**Comment by drewnoakes** [comment]
Loading the UI lazily seems reasonable (not familiar with the code though).

**Comment by KindDragon** [comment]
I think if we want to integrate FormCommit to main form, then we should move "Console",  "Commit..." tabs  on the full window

**Comment by drewnoakes** [comment]
@KindDragon that seems logically consistent as neither of those are dependent upon the selected commit in the graph.

Downsides are losing more vertical space, and increasing the amount of mouse moving and clicking required to navigate around the UI. Often a UI is more friendly/natural to the user even when it's less logical to the programmer.

If you were going to introduce tabs at the top, I'd personally prefer if they were for repositories so that I could track multiple repos in one window. That's not the focus of this issue, but it is worth considering alternative usages for a top-level tab control before doing so.

**Comment by drewnoakes** [comment]
One workflow that would be nicer if the commit form was beneath the graph is that of creating fixup commits. Everything you'd need would be visible on screen. I'm sure the two most looked-at UI elements are the graph and the commit window. Making commit modal makes it hard to use these two together. Putting them in tabs makes it easier, but having them both visible at the same time is (to my mind) the ultimate.

**Comment by KindDragon** [comment]
> If you were going to introduce tabs at the top, I'd personally prefer if they were for repositories so that I could track multiple repos in one window.

I thinking about tabs at the bottom.

**Comment by drewnoakes** [comment]
Moving between the tab bar at the bottom, the tabs in the middle, and the toolbar/menu at the top is a lot of mouse activity to navigate where you need to go. Having one bar at the top and one bar in the middle is better than having three bars, IMO. Tabs placed beneath their panes are not so common in UIs.

Maybe a column of tabs (Graph, Commit, Console) on the left side of the window, aligned to the top. That'd keep everything close together.

Consider using a docking framework so users can configure the layout to suit them. I don't think it's possible to please everyone with a single layout. Again, I like seeing the graph while I commit.

**Comment by RussKie** [comment]
I actually don't like the proposal... For me it would mean constantly resizing panels (the splitters).

Perhaps a better UX could be achieved with docked windows like in the VS (refer to https://github.com/gitextensions/gitextensions/issues/3679). 
But (there always has to be one) it won't work for non-windows users....

**Comment by mortb** [comment]
Maybe a "poor mans" docking solution where the user could select a layout from a predefined set of docked or undocked layouts would be possible? Finding a framework that will support docking for everyone might be hard?

**Comment by gerhardol** [comment]
I added some related issues:
#4033 
#4031 

Suggestions in #4031 that should related to the "modeless commit" similar to mockup by @drewnoakes
I agree to some extent with @RussKie and believe basic commit should be modeless, but "full" commit could be done in the popup


 *  Commit tab is currently hidden. Should have similar info as the commit tab for HEAD, except that there is no commit hash and that commit message is "current WIP" (what has been preliminary added).

 *  Enhancement: Editable commit text. Even if it only is possible to commit from popup dialog, it will simplify writing the commit message.

 *  Enhancement: Commit buttons similar to Commit popup

 *  Diff tab, file view context menu to stage/unstage and reset files
  - Should double-click a file work as in Browse (File History) or stage/unstage as in Commit?

 *  Enhancement: Separate tab so Commit/Diff can be seen simultaneously
  - Sufficient with moving the commit window?

**Comment by mdonatas** [comment]
What do you think of an idea to have commit dialog "dockable" at the bottom of commit graph (like @drewnoakes mockup) and dock/undock keyboard shortcut could be the same (or configurable) as opening the dialog in the first place.
So say you open the full-blown dialog with ctrl+space but want it smaller, ctrl+space again and it's docked. And the reverse if the last dialog state was docked.

@drewnoakes do you have a working prototype? I'd love to start using this TODAY :D

**Comment by gerhardol** [comment]
I started to implement using the CommitInfo tab in the beginning of the year, but it basically duplicated all code in FormCommit so that solution would not be fun from maintenance perspective and I dropped it.

**Comment by mdonatas** [comment]
Any thoughts on leaving this dialog as a modal but with an option to dock/undock it?

**Comment by vbjay** [comment]
Never used it.  It is MIT licensed.  https://github.com/dockpanelsuite/dockpanelsuite

**Comment by RussKie** [comment]
Closing this in favour of #5535.

**Comment by gluttony38** [comment]
In my personal opinion, it would have been better to implement this, anyway, there is a workaround, at least under Windows, that is to open folder in file explorer, right click and select "GitExt Commit...", this will open the commit dialog independently to any other Git Extensions window opened.
