### ISSUE TITLE
Avoid running "git.exe tag --contains ..."

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#5741]
**Do you want to request a *feature* or report a *bug*?**
performance issue, discussion

**What is the current behavior?**
GE runs "git.exe tag --contains _hash_" in order to fill the commit info.
This command can consume more RAM than GE!
Several instances can continue to run in the background when different rows are selected in GE.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- open a huge repo, e.g. Linux
- click several commits

**What is the expected behavior?**
- GE shall be responsive
- git.exe shall not allocate all the RAM

Proposal: retrieve the information on branches and tags from the RevisionGraph instead running git.exe

**Environment you encounter the issue:**
- Git Extensions 3.00.a1
- 2fcf603670dddbd6e3ed572f6838e7cf0c15210c 
- Git 2.19.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0

**Did this work in previous version of GitExtensions (which)?**
I guess no, does not in 2.51.05

**Comment by spdr870** [comment]
The revision graph has all the info, so it is possible. However, the graph is accessible for other controls. I think we could move the graph to GitModule. Other problem is that the graph can be filtered. The 'contains' will not return the truth when the graph is filtered. Options like 'first parent' and 'decorate' make things even harder.

I investigated the problem for the contains command a while ago. There is an issue reported on git for this issue. Git will walk the entire log per ref. So if you have many branches (or tags in your example), the contains command will walk the entire log many times.

Personally I always keep these options turned off, because it performs badly in my repo's. I added a script that I can start manually. It takes over a minute for the git command to run.

Microsoft is working on performance improvements for git. It should help a lot for this issue:
https://blogs.msdn.microsoft.com/devops/2018/06/25/supercharging-the-git-commit-graph/
This table (taken from the blog) shows that the performance for contains is a lot better. I think we should wait for this to be turned on by default in git. It is already merged into git 1.19, but you have to run some commands to activate it.

Command | Before | After | Change
-- | -- | -- | --
git merge-base master topic | 0.52 | 0.06 | -88%
git branch --contains | 76.20 | 0.04 | -99%
git tag --contains | 5.30 | 0.03 | -99%
git tag --merged | 6.30 | 1.50 | -76%
git log --graph -10 | 5.90 | 0.74 | -87%

**Comment by mstv** [comment]
I fully agree, I didn't have in mind that the graph could be filtered etc. Thank you for the explanation.

This is very good news. After I had run _both_ commands, it became very responsive even for the oldest loaded commits of the Linux repo.

**Comment by RussKie** [comment]
> I think we could move the graph to GitModule.

NOOOOOOOOOOoooooooooooo.... `GitModule` is abomination and must be broken down into manageably SOLID objects, not added to.
But there is no reason the graph data can't shared.

**Comment by RussKie** [comment]
I ran it on GE repo:

Setting \ Command | log --graph --oneline -1000 | log --graph --oneline -100000
-- | --  | --
core.commitGraph=false | real    0m0.410s / sys     0m0.031s | real    0m0.516s / sys     0m0.077s
core.commitGraph=true | real    0m0.290s / sys     0m0.062s | real    0m0.463s / sys     0m0.046s

Peculiarly, sys call with the graph takes twice as long for the 1000 commits...

**Comment by TaoK** [comment]
@spdr870 says:

> Personally I always keep these options turned off, because it performs badly in my repo's.

But I was unable to find any UI to do so... eventually I tracked down the `CommitInfoShowContainedInTags` setting considered in CommitInfo.cs, and its retrieval from the key `commitinfoshowcontainedintags` in AppSettings.cs`.

Bottom line, if you come across this issue, and in your repo `git.exe tag --contains ...` *simply doesn't work*, you might want to add the following section to your `C:\Users\USERNAME\AppData\Roaming\GitExtensions\GitExtensions\GitExtensions.settings` (or equivalent) file:

```
  <item>
    <key>
      <string>commitinfoshowcontainedintags</string>
    </key>
    <value>
      <string>false</string>
    </value>
  </item>
```

With this, I can *finally* use Git Extensions on my multi-GB many-hundreds-of-thousands-of-commits repo without it creating lots of multi-GB CPU-pegging git processes.

**Comment by RussKie** [comment]
You can access the setting via a context menu on the commit info tab:
![image](https://user-images.githubusercontent.com/4403806/70527497-310eeb00-1ba0-11ea-925e-d741f7f925b2.png)

**Comment by TaoK** [comment]
Another note - I *had* enabled the `core.commitGraph` option, and `git.exe tag --contains ...` was *still* taking forever - this turns out to have been because my repo includes "replace" objects, and their presence disables the use of the commit graph.

So - the `commitinfoshowcontainedintags` setting should hopefully only be critical for those of us who need grafts and/or replace objects, and cannot "bake them in" with git-filter-branch for whatever reason.

**Comment by TaoK** [comment]
Thanks @RussKie! Amusingly I had tried to find such a context menu, but *clicked too low*. The context menu only appears if you right-click on/above the last lines of text in this area. Clicking in the whitespace below the "parent" line or below the last "contained in" line won't get you anything :(
