### ISSUE TITLE
Revision grid context menu improvements

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#5786]
**Do you want to request a *feature* or report a *bug*?**

UX improvement.

**What is the current behavior?**

Revision grid context menu looks like this:

![image](https://user-images.githubusercontent.com/350947/48618136-51b24480-e990-11e8-976d-f8b6d2a7dedd.png)

**What is the expected behavior?**

A few proposed changes with the goal of making actions clearer to the user.

| Before | After |
|----|----|
| Create new branch | Create new branch **here...** |
| Create new tag | Create new tag **here...** |
| Checkout revision | Checkout **this commit...** |
| Revert commit | Revert **this** commit... |
| Cherry pick commit | Cherry pick **this** commit... |
| Archive revision | Archive **this commit...** |

Use of _this_ removes any potential ambiguity.

Use of ... (ellipsis) is a UI standard for actions that open a dialog, as opposed to carrying out the action immediately.

This also removes use of 'revision', standardising on 'commit' instead. If we like this idea, we should apply it generally.

Also:

- [ ] Move _Create new branch here_ and _Create new tag_ next to one another

**Environment you encounter the issue:**

- Git Extensions 3.00.00.03-RC2
- 8cbcd2b25223c73fbe9f7dad08e498cf82734bfa  (Dirty)
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3190.0
- DPI X:150.00% Y:150.00%

**Did this work in previous version of GitExtensions (which)?**

Don't think so.

**Comment by crypto-rsa** [comment]
As for moving the branch/tag creation commands next to each other: we should consider the case where there is both a branch head and a tag on the selected commit. In that case, the menu looks like this:
![obrazek](https://user-images.githubusercontent.com/11479798/48620687-40256880-e9a1-11e8-86f1-2a5d1616b6e9.png)
But it probably makes sense to move the _Compare_ submenu elsewhere so that it doesn't separate the two groups.

**Comment by RussKie** [comment]
Good pick, I agree with the re-order suggestion
