### ISSUE TITLE
Author's avatar settings are not working correctly in Version 3.00.00 RC2

### ISSUE THREAD

**Issue by Gyokur0** [gitextensions/gitextensions#5828]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Under Settings -> GitExtensions -> Appearance -> Author images 
"No Image Service" is set to "None" and the checkbox "Show author's avatar in the commit info view" ticked off.
But the avatar images get fetched (in wireshark I see GET requests to gravatar.com)
Also the clear cache button seem not properly working.
From some users like Janusz I see his image in every settings combination

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Set the settings as described above and open a repo (for example the gitextensions repo).

**What is the expected behavior?**
If the checkbox "Show author's avatar ..." is not set and Image service is set to none I expect no avatar image (and no outgoing network requests) at all.
In V3 I also find the labeling of the UI problematic, gravatar is not named anymore and the drop down labeled "No Image Service" is kinda confusing.

**Environment you encounter the issue:**
- GitExtensions version: 3.00 RC2
- GIT version: 2.19.2.windows.1
- OS version: Win 10 Pro 64 
- .NET version: 4.7.3190

I use the portable version (GitExtensions.exe.config => IsPortable: True) with GitExtensions.settings in the app folder

**Did this work in previous version of GitExtensions (which)?**
2.51.05

**Comment by gerhardol** [comment]
The avatar can also be displayed in the revision grid.
In 2.x you could toggle the layout, in 3.x this is a column (enabled by default)

![image](https://user-images.githubusercontent.com/6248932/50665437-fd4f3c80-0fb0-11e9-83fd-d73151248bcd.png)

This setting is separate from the CommitInfo, the avatar can be shown there separately.
The remaining settings are used for all avatars. (The Show avatar should be moved to Browse repository for clarity).

![image](https://user-images.githubusercontent.com/6248932/50666626-e8c17300-0fb5-11e9-96f2-5e8bb1feafd6.png)

If any avatar is to be shown, GH is always queried for GH email addresses (as the <user>@users.noreply.github.com address is not available on Gravatar), otherwise Gravatar is used with the provided service that is used to generate avatars if no image at gravatar. I do not have a better name than "No image service", maybe a tooltip too.

Documentation should be updated too. But I do not see any functionality change needed.
Please verify that changing the setting resolves the actual problem

**Comment by RussKie** [comment]
I think it is a good idea to consolidate the settings. Now, when you
described it, the feel disjointed.

**Comment by hanswolff** [comment]
It is still broken as of version 3.0.2.5232. If I select "None" as image service I would expect no outgoing connections to any image service being made.

This is my current setting
![image](https://user-images.githubusercontent.com/1478348/53017869-45d39400-3451-11e9-9d6f-3b055ee38a4c.png)

**Comment by RussKie** [comment]
Please test this build
https://ci.appveyor.com/api/buildjobs/y2kbbneph9f7578m/artifacts/Setup%2FGitExtensions-Portable-3.1.0.5328.zip

**Comment by gerhardol** [comment]
@hanswolff 
> It is still broken as of version 3.0.2.5232. If I select "None" as image service I would expect no outgoing connections to any image service being made.

See my explanation above, 'None' means that no _backup_ service is used.
At least the column has to be hidden too, maybe something else.

My suggestion:
 * Add a setting in Appearance to Show Avatars
 * Move "Commit info view" to Browse

**Comment by RussKie** [comment]
Please test this build
https://ci.appveyor.com/api/buildjobs/xp86a42kbgc51oxq/artifacts/Setup%2FGitExtensions-Portable-3.1.0.5347.zip

**Comment by RussKie** [comment]
Added a tooltip:
![image](https://user-images.githubusercontent.com/4403806/53298615-a1a08180-3884-11e9-8193-99c6f610114c.png)
