### ISSUE TITLE
Add functions to create branches to branch list and/or branch dropdown

### ISSUE THREAD

**Issue by mika76** [gitextensions/gitextensions#5831]
**Do you want to request a *feature* or report a *bug*?**
FEATURE

**What is the current behavior?**
Currently you have to select the Repository menu and click `Create branch`

**What is the expected behavior?**
I would love if I had a right click menu item on a branch in the left hand panel (v3) to create branch from selected branch (kind of like in VS)

Also an option in the checkout list on the toolbar.

They both seem like logical places to look for creating a new branch, but I always get confused and first try both those and then remember and click in the Repository menu and click Create Branch.

**Comment by vbjay** [comment]
It's in the context menu of the grid.

**Comment by mika76** [comment]
@vbjay do you mean the commit log grid? Yes it's true, but not exactly logical to me. If I would like to create a branch from a branch first place I think of is the branch list or branch drop down...

**Comment by vbjay** [comment]
A branch is just a pointer to a commit.  You create branches off of commits.  So click desired branch in left panel.  Right click selected commit in grid which will now be the correct commit.  You can also double click a branch in left panel.  


Double clicked on remote branch.
![image](https://user-images.githubusercontent.com/3629489/49250198-43324700-f3ec-11e8-9c0d-f971372ecf5c.png)


remote branches

![image](https://user-images.githubusercontent.com/3629489/49250311-81c80180-f3ec-11e8-80f3-cbd479193b44.png)


Local branches
![image](https://user-images.githubusercontent.com/3629489/49250357-9f956680-f3ec-11e8-888c-122e6481096e.png)


So I can see adding a create new branch on local branches but remote branches already have a check out option which does this work.

**Comment by mika76** [comment]
All I'm saying is it's quite common to create a branch off a branch (especially coming from VS since they do it that way) and it's the first place my mind says to go to. 

Think of it as me asking for a shortcut 😊

**Comment by vbjay** [comment]
Right. Like I said. Remote branches already let you do this. Local branches could have a new menu to create a branch off of that ref. Here is the thing. It's better to click on that branch and see where that branch points to and create a branch in the grid. Because now you see where you are basing the branch from.

**Comment by vbjay** [comment]
I did say we could add a create branch menu did I not?  Yes I did. My point was that remote branches ALREADY have it. I also pointed out the better way because hmm. Maybe my local branch is behind the remote tracking. If you click the local branch, you would see this because remote/branch would not also be pointing to that commit.

**Comment by mika76** [comment]
Ah I apologise, I guess I misunderstood. 

You're right about the branch being behind I guess but I don't see that as a showstopper - that mistake you can make anyway (from GUI or from command line)

I would actually say that most of the things you can do with a branch on right-click of a commit should also be in the right-click of the branch menu. 

![screen shot 2018-11-30 at 07 45 36](https://user-images.githubusercontent.com/229311/49273078-1cb7ee80-f474-11e8-854b-d009bb501ac8.png)

**Comment by vbjay** [comment]
Frankly, I think it should stay on the grid.  The actual work is done on commits.  The grid gives you information like what commit the branch is actually pointing to.  The left panel does give you a list but not what commit that new branch will be created on.  

![highlight branch](https://user-images.githubusercontent.com/3629489/49306623-c1502580-f4a0-11e8-847a-f22ccd659700.gif)

Right click on the commit you want to do the action.  That way you are sure you are creating a branch or other action on the commit you really want to.  I think blindly using the branch name is goofy.  The grid gives you the context (hence context menu) to work with.  I can see working with the branch and doing branch specific actions.  I just think piling too many actions on a local branch node without the context is silly.  Would you blindly rebase a local branch just by the name instead of wanting to rebase by looking at the commits?

**Comment by mika76** [comment]
Seems silly to me to do the thing you want to do by clicking on the branch on the left, just so you can find the line on the right, right click on that and only then get context ... of the branch (which you had already selected on the left).

But hey - we're going around in circles here. I mean I'm obviously not the only person who feels this belongs here, since other git GUI's have added these actions to their context menus on branches...

Fork...
![screen shot 2018-11-30 at 21 39 30](https://user-images.githubusercontent.com/229311/49313868-ee282b00-f4e8-11e8-8561-4bd307b68a34.png)

Sublime Merge...
![screen shot 2018-11-30 at 21 39 13](https://user-images.githubusercontent.com/229311/49313865-eb2d3a80-f4e8-11e8-823c-a03a192664ac.png)

Visual Studio...
![screen shot 2018-11-30 at 21 40 55](https://user-images.githubusercontent.com/229311/49313862-e8324a00-f4e8-11e8-84ab-d5d49b4a10ef.png)

**Comment by drewnoakes** [comment]
For 3.0.1 I think it would be great to do a review of the ROT context menus and see where we can add more commands. This seems like a good candidate to me.

**Comment by gerhardol** [comment]
I agree to add more commands (as well as submodules maybe repos too).
But that will likely happen after 3.00.01

**Comment by RussKie** [comment]
I believe this is done in the latest master
https://ci.appveyor.com/project/gitextensions/gitextensions/branch/master/artifacts

![image](https://user-images.githubusercontent.com/4403806/56205925-74a36a80-608e-11e9-9e81-16fc4fc3cbe6.png)
