### ISSUE TITLE
Clipping of the search text box in the branches panel

### ISSUE THREAD

**Issue by ulrichb** [gitextensions/gitextensions#5866]
**Do you want to request a *feature* or report a *bug*?** 
Bug (Cosmetics)

**What is the current behavior?**

The search text box in the in the left branches panel is clipped when the the panel width is below a certain limit:

![image](https://user-images.githubusercontent.com/388796/49675788-6bb6e280-fa77-11e8-8bc0-b96ac314ed79.png)

This is the minimum width so that the clipping doesn't appear anymore:

![image](https://user-images.githubusercontent.com/388796/49675794-73768700-fa77-11e8-8165-3dcc7e642ed8.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
See screens

Note that I saw on another device that this doesn't seem to happen with 96 dpi.

**What is the expected behavior?**
No clipping

**Environment you encounter the issue:**

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.19.2.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3190.0
- **DPI 120dpi (125% scaling)**

**Did this work in previous version of GitExtensions (which)?**
n/a

**Comment by vbjay** [comment]
Please use the issue template we have. We have it for a reason.

**Comment by vbjay** [comment]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Environment you encounter the issue:**


- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version: 

**Did this work in previous version of GitExtensions (which)?**

**Comment by ulrichb** [comment]
@vbjay Fixed that
