### ISSUE TITLE
Cannot select file in Diff tab

### ISSUE THREAD

**Issue by SkinKo** [gitextensions/gitextensions#6034]
- GitExtensions version: 3.00.00.4433
- GIT version: 2.17.1.windows.2
- OS version: Windows NT 10.0.17134.0
- .NET version: 4.7.3260.0

**Did this work in previous version of GitExtensions (which)?**
2.xxxxxxx

The files in Diff tab are not selected on click by mouse. Can select using keyboard Up/Down keys or  hold the left mouse-button and drag over the needed file - selects it.

**Comment by drewnoakes** [comment]
Can you also include a screenshot?

**Comment by masterjedi-mj** [comment]
I have the same problem.
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.17.1.windows.2
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.7.3221.0
- DPI 96dpi (no scaling)
For any commit in the diff tab, you can not select a file with a mouse click. In the screenshot it makes no sense, because it is impossible to show that the file in the commit is not selected by click. For verification, I created a new locally test repository and everything is fine with it, but with all the existing such problem is observed.

**Comment by gerhardol** [comment]
Screenshot is still helpful, shows style etc

**Comment by RussKie** [comment]
You can record an animation using something like [Screen2Gif](https://www.screentogif.com/) and post it here.

**Comment by masterjedi-mj** [comment]
Hello! My problem disappeared after restarting the application, I apologize for disturbing

**Comment by DmitryZhelnin** [comment]
I've ran into this issue too. Didn't do anything unusual only changed repository via main toolbar.
I have a laptop with 2 display connected (laptop is closed and its display is not used), GitExtensions was on the primary display.
![diff](https://user-images.githubusercontent.com/4993430/51057307-49742f80-15f6-11e9-9dfa-dbeab1b4b4da.gif)
The second gif shows the behavor @SkinKo described. And it is recorded with external displays disconnected.
![diff_selection](https://user-images.githubusercontent.com/4993430/51057445-ac65c680-15f6-11e9-8963-634cb0f72181.gif)

- Git Extensions 3.00.00.4805
- Build 500e3cb71ee70a5153c6d6cfde4262122e989f45 (Dirty)
- Git 2.20.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3221.0
- DPI 120dpi (125% scaling)

**Comment by vbjay** [comment]
Just curious.  

- Is the laptop screen not at 125%?
- Does it still happen at 100% dpi?

**Comment by DmitryZhelnin** [comment]
The laptop screen is 125% dpi also.
