### ISSUE TITLE
Debounce navigating the list of branches

### ISSUE THREAD

**Issue by chris-findlay** [gitextensions/gitextensions#6072]
## Current behaviour
In a large repo, navigating the list of branches using the keyboard is painful as every selection change selects the branch in the main view, so if I'm down-arrowing a few lines to get to what I want, and pass a branch that's way back in the history things get very slow.

## Expected behaviour
It'd be nice if the main view waits for the branch selection to come to rest (e.g. 0.5 or 1s delay) before updating the main view.

## Steps to reproduce
Navigate the tree of branches on a large repo, in particular where tree-adjacent items are far apart in history.

## Did this work in previous version of GitExtensions
N/A

## Environment
- Git Extensions 3.00.00.4433
- Build fca7cf2
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Is this for 3.0.0?
Is it in the side panel you are navigating?

**Comment by RussKie** [comment]
@chris-findlay  could you please confirm that you saw a template when created this issue? We recently reconfigured our templates and I'm concerned people aren't seeing issue templates.

If you did see it and ignored it, please complete it.

**Comment by drewnoakes** [comment]
Agree that debouncing makes sense, likely only on keyboard navigation. Clicking should apply immediately.

It'd also be good to see if we can move the work of scrolling far back in the history off the UI thread to keep things responsive. Might consider cancellation here too.

**Comment by chris-findlay** [comment]
I didn't see a template, but here's the info that I'd normally put in it:
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Comment by chris-findlay** [comment]
I just tried the new-issue button now, and got the menu of templates to start with, and both seem to work, so whatever it was that meant I didn't see a template seems to be fixed now.  (c:

**Comment by chris-findlay** [comment]
@RussKie I can't decide if this is a bug or a feature-request...

**Comment by drewnoakes** [comment]
This is a usability bug.

**Comment by amaiorano** [comment]
I quickly put together a solution for this on my fork here: https://github.com/amaiorano/gitextensions/tree/amaiorano/left-panel-arrow-keys-dont-select-node

Instead of auto-selecting after some delay, I followed the Explorer approach: arrow keys move the selection, but don't perform the OnSelected action; instead, you press Space to do that. Mouse clicks still work as before. This is, in my opinion, a better approach, and also much easier to implement (creating/stopping timers that run on the UI thread is finicky business).

There may still be bugs, but can @drewnoakes or @RussKie give it a try? I would package it up for @chris-findlay, but until we can package the latest dependencies, it likely won't work for non-devs, right?

**Comment by amaiorano** [comment]
Alright, now that we can package up our builds again, I've rebased and have zipped up a release build with my changes:
[amaiorano_GitExtensions_left_panel_arrow_keys_like_explorer.zip](https://github.com/gitextensions/gitextensions/files/2836454/amaiorano_GitExtensions_left_panel_arrow_keys_like_explorer.zip)

As I wrote above:

> Instead of auto-selecting after some delay, I followed the Explorer approach: arrow keys move the selection, but don't perform the OnSelected action; instead, you press Space to do that. Mouse clicks still work as before. This is, in my opinion, a better approach, and also much easier to implement (creating/stopping timers that run on the UI thread is finicky business).

Also, like explorer, if you move your cursor to a node with the arrow keys, then click on the selected node with the mouse, it will perform the selection action.

@chris-findlay Can you give this a try?

**Comment by chris-findlay** [comment]
I will give it a go shortly.

**Comment by chris-findlay** [comment]
Works well for arrows + space to select, but enter doesn't select the node - neither the main nor the keypad one.

**Comment by amaiorano** [comment]
> Works well for arrows + space to select, but enter doesn't select the node - neither the main nor the keypad one.

Yes, that's true. Enter is already used to perform a "go to next search hit", like F3. We could probably change Enter to behave like space here. I suspect it was done this way because you'd type in the search bar and hit Enter to start searching, so hitting Enter again would go to next match. But I doubt many people rely on this behaviour.

**Comment by amaiorano** [comment]
So I'll make it Enter behave like Space, and open a PR tonight.

**Comment by RussKie** [comment]
@chris-findlay please try this build
https://ci.appveyor.com/api/buildjobs/6qt05jcwq7n5xuvg/artifacts/Setup%2FGitExtensions-Portable-3.1.0.5183.zip

**Comment by chris-findlay** [comment]
That works well (c:
