### ISSUE TITLE
Git Fork Repos should have the Sync button to sync with upstream repos

### ISSUE THREAD

**Issue by rmsmani** [gitextensions/gitextensions#6084]
Git Fork Repos should have the Sync button to sync with upstream repos.

This will be useful for developers to to Sync the Forked repos with the upstream repos in regular frequency.

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.0.windows.1
- Microsoft Windows NT 6.3.9600.0
- .NET Framework 4.7.3260.0

**Comment by TamaHobbit** [comment]
What do you mean? 
What is a "Git Fork Repo"? 
What should the sync button do? 
How will GitExtensions know what the "upstream repo" should be?

**Comment by vbjay** [comment]
That's what fetching/pulling is for.  

My remote pointing to my fork.
![image](https://user-images.githubusercontent.com/3629489/50966484-0ce3ef00-14a3-11e9-81f3-05a184003c85.png)

gitextensions/gitextesions copy of the repo.
![image](https://user-images.githubusercontent.com/3629489/50966517-29802700-14a3-11e9-84c6-25fd1eeb8041.png)

So you can see my local master and my copy on github are pointing to a specific commit.  It is behind upstream.

![image](https://user-images.githubusercontent.com/3629489/50966859-5123bf00-14a4-11e9-889d-27faa3561881.png)

I will do a pull  
![image](https://user-images.githubusercontent.com/3629489/50966903-7284ab00-14a4-11e9-8c18-2828c8382b4a.png)

See how it did nothing because master is set to pull on origin.  I want to pull changes if I push changes from another clone.  I don't want to pull from upstream. I could do this. 
![image](https://user-images.githubusercontent.com/3629489/50967060-035b8680-14a5-11e9-91f8-d08911a52c91.png)
![image](https://user-images.githubusercontent.com/3629489/50967093-225a1880-14a5-11e9-9408-2d5e24f36399.png)


 I handle that process in a different way.  It makes it so I can keep submodules and master current at the same time and push the changes to my fork.

![image](https://user-images.githubusercontent.com/3629489/50967203-69480e00-14a5-11e9-9cfc-c16ef4933410.png)
![image](https://user-images.githubusercontent.com/3629489/50967292-b4fab780-14a5-11e9-848b-3c51fe38c956.png)
```
sh -c "git submodule foreach git checkout master &&git submodule foreach git pull upstream master && git submodule foreach git push origin master && git checkout master && git pull upstream master && git push origin master && git submodule update --init --recursive"
Entering 'Externals/Git.hub'
Already on 'master'
Your branch is up to date with 'origin/master'.
Entering 'Externals/ICSharpCode.TextEditor'
Your branch is up to date with 'upstream/master'.
Already on 'master'
Entering 'Externals/NBug'
Already on 'master'
Your branch is up to date with 'origin/master'.
Entering 'Externals/conemu-inside'
Your branch is up to date with 'origin/master'.
Already on 'master'
Entering 'GitExtensionsDoc'
Your branch is up to date with 'origin/master'.
Previous HEAD position was 4f9e9cd doc 3.00 (#88)
Switched to branch 'master'
Entering 'Externals/Git.hub'
From https://github.com/gitextensions/Git.hub
 * branch            master     -> FETCH_HEAD
Already up to date.
Entering 'Externals/ICSharpCode.TextEditor'
From https://github.com/gitextensions/ICSharpCode.TextEditor
 * branch            master     -> FETCH_HEAD
Already up to date.
Entering 'Externals/NBug'
From https://github.com/gitextensions/NBug
 * branch            master     -> FETCH_HEAD
Already up to date.
Entering 'Externals/conemu-inside'
From https://github.com/gitextensions/conemu-inside
 * branch            master     -> FETCH_HEAD
Already up to date.
Entering 'GitExtensionsDoc'
From https://github.com/gitextensions/GitExtensionsDoc
 * branch            master     -> FETCH_HEAD
Already up to date.
Entering 'Externals/Git.hub'
Everything up-to-date
Entering 'Externals/ICSharpCode.TextEditor'
Everything up-to-date
Entering 'Externals/NBug'
Everything up-to-date
Entering 'Externals/conemu-inside'
Everything up-to-date
Entering 'GitExtensionsDoc'
Everything up-to-date
M	GitExtensionsDoc
Your branch is up to date with 'origin/master'.
Already on 'master'
From https://github.com/gitextensions/gitextensions
 * branch                master     -> FETCH_HEAD
Updating 5fa57a943..f7e97be0c
Fast-forward
 GitExtUtils/GitUI/ControlHotkeyExtensions.cs       |  64 ++++++---
 .../RepoObjectsTree.ContextActions.cs              |  24 +---
 .../RepoObjectsTree.Nodes.Remotes.cs               |  87 ++++++------
 .../BrowseDialog/GitStatusMonitor.cs               |  16 ++-
 .../GitWorkingDirectoryStatusEventArgs.cs          |   6 +-
 GitUI/CommandsDialogs/FormBrowse.Designer.cs       |   7 +-
 GitUI/CommandsDialogs/FormBrowse.cs                | 147 +++++++++++----------
 .../Pages/GeneralSettingsPage.Designer.cs          |   4 +-
 .../Pages/RevisionLinksSettingsPage.Designer.cs    |  15 ++-
 GitUI/CommitInfo/CommitInfo.cs                     |   2 +
 GitUI/CommitInfo/CommitInfoHeader.cs               |   5 +
 GitUI/Editor/RichTextBoxXhtmlSupportExtension.cs   |   6 +-
 GitUI/Properties/Images.Designer.cs                |  10 ++
 GitUI/Properties/Images.resx                       |   5 +-
 GitUI/Resources/Icons/RepoStateUnknown.png         | Bin 0 -> 293 bytes
 ...ntrackedOnly.png => RepoStateUntrackedOnly.png} | Bin
 GitUI/Translation/English.xlf                      |   4 +-
 GitUI/UserControls/RepoStateVisualiser.cs          |  36 +++--
 .../RevisionGrid/RevisionGridControl.cs            |   2 +-
 .../UserControls/RepoStateVisualiserTests.cs       |  20 ++-
 20 files changed, 263 insertions(+), 197 deletions(-)
 create mode 100644 GitUI/Resources/Icons/RepoStateUnknown.png
To github.com:vbjay/gitextensions.git
   5fa57a943..f7e97be0c  master -> master
Submodule path 'GitExtensionsDoc': checked out '4f9e9cd59cd13360bccb4dac707036a600442fe9'


Done
```
This is how I created that get current menu

![image](https://user-images.githubusercontent.com/3629489/50967353-ea9fa080-14a5-11e9-9595-925b5d6dc637.png)

```bash
-c "git submodule foreach git checkout master &&git submodule foreach git pull upstream master && git submodule foreach git push origin master && git checkout master && git pull upstream master && git push origin master && git submodule update --init --recursive"
```

That script will fail if your working directory is not clean ( no changes that are not committed) which is a good thing.

**Comment by drewnoakes** [comment]
Doesn't this button do what you want?

![image](https://user-images.githubusercontent.com/350947/50967577-66164780-14d0-11e9-9422-4d80f05fc182.png)

**Comment by vbjay** [comment]
http://www.vogella.com/tutorials/Git/article.html

**Comment by rmsmani** [comment]
@vbjay
It worked as per the steps given by you. Thanks.

@drewnoakes,
Thanks
