### ISSUE TITLE
Revision grid: bad behaviour when resizing of commit message column

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#6117]
## Current behaviour

* In the revision grid, when:

1. reducing the width of the commit message column, it reduce the size of the second to last column
2. reducing again the width of the commit message column, it reduce the size of the third to last column
3. reducing again the width of the commit message column, it reduce the size of the fourth to last column
4. until the commit message column become not resizeable
5. You have to select another line (sometimes retry more than once) to be able to resize the column again (this one perhaps linked to #5753)

Same behaviour when increasing the size.

## Expected behaviour

* When reducing the width of the message column, it change the size of the last column.
(Or at least having a deterministic behaviour)

## Screenshots

![gitextensions_column_problem](https://user-images.githubusercontent.com/460196/51252922-58176980-199d-11e9-8db9-58555b0bfcb2.gif)

## Did this work in previous version of GitExtensions

v3 changed the way to handle the column resizing. So, yes and no ;)

## Environment

- Git Extensions 3.01.00.0
- Build 6d9a0fc5dda34479fd11b58a17ec9a8f35c15ecc
- Git 2.20.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 192dpi (200% scaling)

**Comment by pmiossec** [comment]
There are other strange behaviours around colmun resizing but I don't really understand the how it behave.
I hope we will see much clearer when we will try solve this one...

**Comment by mstv** [comment]
The changes in #5811 set the resizeable state of the wrong columns step by step, because the last visible and resizeable column is made non-resizeable and hence not found anymore.
I think that `_lastVisibleResizableColumn` must be a field again. Though it must updated when the visibilty of columns is toggled. Note: Before searching the victim column again, the resize settings of the old victim column must be restored.
I can reproduce the issue #5753. It might be caused by the code in `Refresh()` not yet executed.

I'll prepare a PR.

Unfortunately, I cannot reproduce the strange resizing shown in the video in #5811 (using a build of that PR's parent commit aebb024).

**Comment by pmiossec** [comment]
>I'll prepare a PR.

Thanks! I will be happy to test it.
