### ISSUE TITLE
Full install for 3.0 release ?

### ISSUE THREAD

**Issue by boxerab** [gitextensions/gitextensions#6171]
2.5 had a complete setup including git and kdiff, but this doesn't seem to be the case for 3.0.

**Comment by vbjay** [comment]
That is on purpose. Please search issues and pull requests next time.

**Comment by RussKie** [comment]
We have decided to exclude dependencies such as git and kdiff3 from our installer due to a number of reasons. One of the main reasons that our release cadence is significantly slower of our dependencies, and thus we may be providing a disservice to our users by shipping outdated (and possibly insecure) 3rd party software.

If you desire to automate you installation story please consider using Chocolatey package manager:
https://chocolatey.org/packages/gitextensions

**Comment by boxerab** [comment]
Thanks for the update.
