### ISSUE TITLE
How to add shell extension in portable version?

### ISSUE THREAD

**Issue by crosslife** [gitextensions/gitextensions#6182]
## Current behaviour

I found this link but can't find GitExtensionsShellEx64.dll

## Environment

- GitExtensions version:3.0
- GIT version: 2.20.1
- OS version: Windows 10 latest
- .NET version:

**Comment by crosslife** [comment]
https://github.com/gitextensions/gitextensions/issues/1821

**Comment by RussKie** [comment]
We do not currently ship shell extensions in the portable version.
Primarily because these can't be easily installed, and the portable version, as the name suggests, isn't a permanent installation.

However the suggestion in #1821 is reasonable and may be a good addition.

Would you like to have a go at implementing it?
