### ISSUE TITLE
Frozen once staging 1000 files with CRLF line break and core.autocrlf = input

### ISSUE THREAD

**Issue by Denitz** [gitextensions/gitextensions#6225]
## Current behaviour

Updated repo, there are 1000 updated files, trying to stage all, program is frozen and can be terminated only.

## Expected behaviour

Just stage all 1000 files.

## Steps to reproduce

Try to stage 1000 files with CRLF line break while you have core.autocrlf = input

## Did this work in previous version of GitExtensions

Yes, before 3.0

## Environment

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

**Comment by steeintw** [comment]
I have the same problem while staging about 400+ files using "Stage All" in "Commit" dialog.
My core.autocrlf =true.
Staging one file at a time works fine.
Use "Git Extensions -> Add Files" from Windows Explorer context menu also works fine.

**Comment by RussKie** [comment]
Do you have a repro repo to share?

**Comment by mast-eu** [comment]
I observed this issue as well. But I believe the key is not only the sheer number of files.
At least in my case, I rather think it's the fact that I copied a bunch of files from a Linux system (LF line endings) to a Windows system (CRLF line endings) and made GitExtensions substitute the line endings during staging.

I think I can make this reproducible and provide an example repo.

**Comment by mast-eu** [comment]
### Reproduction repository
https://github.com/mast-eu/GitExtensions.issue6225.git

### Reproduction steps
1. Make sure you have set "Checkout as-is, commit as-is" for line endings.
![lineendings](https://user-images.githubusercontent.com/46861028/53016044-d8256900-344c-11e9-9bcb-fc1507c85c90.png)
2. Clone the repo given above and open it in GitExtensions.
It contains 3 folders `files_with_CR`, `files_with_CRLF` or `files_with_LF`, each one containing 1024 files with the respective line ending.
3. In Windows Explorer, copy one of the folders, in order to make them appear as 1024 new files for git. For example:
![lineendings2](https://user-images.githubusercontent.com/46861028/53016045-d8256900-344c-11e9-9ad0-bcb57f1408b0.png)
4. Open the commit dialog and click on `Stage all`. It works, if you did no yet change the setting for line endings.
5. Play around with the setting for line endings (core.autocrlf). Depending on the setting you can observe GitExtensions hang when trying to stage the 1024 files with a certain line ending.

Here's the error matrix I found:

| Line endings  | Stage copy of `files_with_CR` | Stage copy of `files_with_LF` | Stage copy of `files_with_CRLF`
| --- | :---: | :---: | :---: 
| Checkout Windows-style, commit Unix-style (`core.autocrlf=true`) | ok | FAIL | ok
| Checkout as-is, commit Unix-style (`core.autocrlf=input`) | ok | ok | FAIL 
| Checkout as-is, commit as-is (`core.autocrlf=false`) | ok | ok | ok 

@Denitz , @steeintw : Could you please check it's the same issue that you had?

**Comment by fgc0109** [comment]
I have same problem, but i didn't set line-ending 
![qq 20190224203012](https://user-images.githubusercontent.com/13477904/53299347-955ff880-3873-11e9-96a2-366992c1b644.png)
![qq 20190224203310](https://user-images.githubusercontent.com/13477904/53299352-a6a90500-3873-11e9-91a2-e9e84554da30.png)
but when i commit little files to tepo it still replace CR LF with LF ,when i try to commit more it crashed
![qq 20190224203411](https://user-images.githubusercontent.com/13477904/53299387-2505a700-3874-11e9-9aaa-8ac2cfd9c6ac.png)

**Comment by gerhardol** [comment]
> but when i commit little files to tepo it still replace CR LF with LF ,when i try to commit more it crashed

Set core.autocrlf to false (not sure what the default is here).
Check your .gitattributes too

You can get something similar like this if you for instance rename GitUI directory and stage files. Update is occasionally slow, regardless of core.autocrlf. The debugger reports that GitModule::UpdateIndex() (preparing filenames for git-update-index) is running, but no user code executes. Sometimes it is quick.

**Comment by steeintw** [comment]
> se check it's the same issue that you had?

@mast-eu Yes, this is exactly the same issue I had, thank you for clarifying.

**Comment by mast-eu** [comment]
As a workaround you can stage the files in chunks of ~100 at a time.
The exact limit on my system is 482 files at once, but this probably depends on your system configuration.

**Comment by RussKie** [comment]
@mast-eu are you in a position to debug it?
Perhaps run it, pause the debugger while staging and inspect threads in Parallels Stacks (_Debug > Windows > Parallel Stacks_)

**Comment by mast-eu** [comment]
Ok, I (mostly) understood the problem.
Now we need a solution ;-)

First of all, it is not a threading issue. I was thinking of #6319 too, but this is **not related**.

### Analysis
The problem is how GE interacts with the underlying git process. It starts here:
https://github.com/gitextensions/gitextensions/blob/d0ba1a57823f12cc1caec12026586bb9353d2771/GitCommands/Git/GitModule.cs#L1748-L1761

Which runs:
https://github.com/gitextensions/gitextensions/blob/d0ba1a57823f12cc1caec12026586bb9353d2771/GitCommands/Git/ExecutableExtensions.cs#L276-L289

So, GE runs `git update-index --add --stdin`, writes all file names in single lines to `process.StandardInput` and afterwards checks `process.StandardError` for eventual error messages. In other words, GE wants to do:
```
$ git update-index --add --stdin
"file_with_LF_0001.txt"
"file_with_LF_0002.txt"
[...]
"file_with_LF_1024.txt"

[read process.StandardOutput]
[read process.StandardError]
```

However, git responds with a message to `process.StandardError` **after each file name**. You can verify this by running the same command from console:
```
$ git update-index --add --stdin
"file_with_LF_0001.txt"
warning: LF will be replaced by CRLF in file_with_LF_0001.txt.
The file will have its original line endings in your working directory
"file_with_LF_0002.txt"
warning: LF will be replaced by CRLF in file_with_LF_0002.txt.
The file will have its original line endings in your working directory
[...]
"file_with_LF_1024.txt"
warning: LF will be replaced by CRLF in file_with_LF_1024.txt.
The file will have its original line endings in your working directory
```

Normally these error messages are shown all together once the staging is completed:
![stagedetails](https://user-images.githubusercontent.com/46861028/53957328-5d13b200-40de-11e9-8bda-4b5414eecdc5.png)

This works well with a low number of files, but for some reason hangs when staging a lot of files.

### Cross check
Git has a [flag to disable the warning](https://git-scm.com/docs/git-config#git-config-coresafecrlf).
Set `git config --local core.safecrlf false` and GE can stage 1024 files without hanging. You will obviously not see the "warning: LF will be replaced by CRLF" messages, but the files get staged.
Set the flag back to it's default `git config --local core.safecrlf warn` and GE will hang again.

### Possible solutions (to be discussed)
1) Force `core.safecrlf` to `false`
-> Technically would do the trick, but the "warning: LF will be replaced by CRLF" messages are valuable feedback for the user. I wouldn't like to loose them.
2) Read and reset `process.StandardError` and `process.StandardOutput` after having written n files to `process.StandardInput` 
-> Might work, but probably decrease performance.
3) Make `writeInput(process.StandardInput)` async as suggested in comment 
-> Don't know whether this would help.
4) ...

I got the feeling that any fix requires a deeper understanding of GE's internals than I currently have. Therefore, I will gladly help, test and provide further feedback if needed. But I will provide a PR on my own, since the risk of breaking something is too high.

**Comment by gerhardol** [comment]
For me, it seem to be stuck in 
private static void UpdateIndex(StreamWriter inputWriter, string filename)

> Set git config --local core.safecrlf false

This can be set on this command with git -c and could be activated when AppSettings.ShowErrorsWhenStagingFiles is false
But this is a hack
(async should not improve)

**Comment by mast-eu** [comment]
> When the problem occurs for me, it seem to be stuck in
> 
> ```
> private static void UpdateIndex(StreamWriter inputWriter, string filename)
> ...
> inputWriter.BaseStream.Write(bytes, 0, bytes.Length);
> ```

Yes, that's the exact point indicated when you pause the debugger. From there, I inspected the call stack.

`UpdateIndex()` is called from:
```
     inputWriter => 
     { 
         foreach (var file in nonDeletedFiles) 
         { 
             UpdateIndex(inputWriter, file.Name); 
         }
```

Which is called from:
```
     if (writeInput != null) 
     { 
         // TODO do we want to make this async? 
         writeInput(process.StandardInput);  //<- this hangs
         process.StandardInput.Close(); 
     } 
```
However, I think the problem is not (or at east not directly) the `inputWriter` because the situation changes when the git messages to `StandardError` are bypassed.

**Comment by mast-eu** [comment]
> > Set git config --local core.safecrlf false

> This can be set on this command with git -c and could be activated when AppSettings.ShowErrorsWhenStagingFiles is false
But this is a hack

I wouldn't consider this a hack. When I set `AppSettings.ShowErrorsWhenStagingFiles` to false I don't want to see the messages. Using `git - c` to enforce core.safecrlf=false would make git not even produce them in first place, instead of dropping them later in GE.

Obviously that wouldn't change anything when `AppSettings.ShowErrorsWhenStagingFiles` is true, which is the default setting.

**Comment by gerhardol** [comment]
This problem seem to be related to #6357. If I try to stage quickly after refreshing, I can occasionally recreate also if no file ending changes with show errors and safecrlf both true.
If at least one of them is false, I have not seen the problem I this scenario. That does not prove anything though.

**Comment by Hemaolle** [comment]
Is it possible that the `StandardError` stream has a limited size buffer that gets full resulting in a deadlock when the git process tries to write the next error message there?
