### ISSUE TITLE
Support cross-platform app

### ISSUE THREAD

**Issue by safield** [gitextensions/gitextensions#6239]
I would love to see Linux support reintroduced as a priority.

I was looking for a similar feature request, to upvote it, but I couldn't find it.

**Comment by vbjay** [comment]
Search our issues for mono.

**Comment by kekekeks** [comment]
If you consider switching from winforms, you might want to investigate Avalonia as your next target platform. It works on top of .NET Core across all desktop platforms and uses the same concepts as WPF/UWP.

**Comment by RussKie** [comment]
We've discussed Avalonia and other frameworks in https://github.com/gitextensions/gitextensions/issues/4972, https://github.com/gitextensions/gitextensions/issues/4308 has also reasons why we it isn't easily achievable

**Comment by t00** [comment]
Hi @RussKie, I have been GitExtensions users for many years, thanks for the most to-the-point git client out there - none can handle submodules so well as GitExtensions.

Anyway, I use Linux daily as well as Windows and GitExtensions 2.51 on Linux are obviously still somewhat buggy due to WinForms on Mono crashes among other things, not even getting into looks.

Having extensive WPF experience, and now fresh hands on experience with Avalonia building cross platform app, I can confidently say moving to Avalonia is not just possible - it can be relatively easy - with all advantages it can bring - fresh, themable UI with responsive looks.

First of all, it is clear that GitExtensions codebase at which I had a quick look is tightly coupled with WinForms workflow but not too heavily to modernize forms one by one by embedding Avalonia windows inside GitExtensions at first using this control: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Windows/Avalonia.Win32.Interop/WinForms/WinFormsAvaloniaControlHost.cs (Avalonia.Win32.Interop package)

I would not go to redoing whole UI in ReactiveUI as that would be too much work yet by implementing a simple AsyncCommand, many WinForms actions can be done without extensive changes.

Once forms conversion is complete, whole app can be restructured to create native Avalonia dotnet 3 binary which will obviously work on multiple platforms while looking good. Some operations can be improved on the way, i.e. instead of "ok" dialogs GitExtensions can present automatically disappearing notifications  (NotificationManager).

I also would discourage from using any MVVM framework, the barebones dependency injection for ViewModels would make it much simpler to pass on dependencies and improve GE codebase along the way.

A summary of steps:
1. Add Avalonia dependencies
2. Add bootstrap code - IServiceProvider for dependency injection, identifying Views and ViewModels by reflection (rename ViewModel to View, check if type exists, create instance). It is important to decide how dependency injection scope will be used, probably main view scope -> action scope based on main view scope -> subaction scope based on action scope etc.
3. Identify all platform dependent code (Windows) and interface it so it can be reimplemented when needed - change existing code just refactor it, maybe this step is optional.
4. Identify most self-contained forms and create Avalonia counterparts having all functionality moved, while adding dependencies to boostrap code along the way (registering classes, handlers, git functions). Also styles need to be created along the way, less the better for easier theming support.
5. Repeat 4 for all forms, make releases in between and make sure default theming matches current GE visuals so users won't complain too much about different looks of some GE parts.
6. When all forms are moved, implement native avalonia navigation between them by dropping WinForms completely. Present them in navigation main view using ContentControl for a start, any time parent actions can be somehow made peekable to see i.e. list of commits when currently viewing git commit details view.
7. Convert project to avalonia with all target platforms available making sure all final bits like installer, explorer extension etc are compatible

What are your thoughts?

**Comment by RussKie** [comment]
Awesome write up, appreciate your thoughts, and the proposal on the way
forward.

Perhaps the biggest concern is the revision graph portability, but if one
engineer built it, another can rebuild it. 😎

Currently in the pipeline we have a migration to SDK-style projects, then
to .NET Core 3.1, then we can possibly start toying with the port.

Nikita Tsukanov (one of the Avalonia maintainers) suggested starting with
the FormCommit.

...and we will certainly look forward to the community contributions 😉

**Comment by meyertime** [comment]
Just want to say that this is sorely needed.  I wish I had time to help.  I've switched to Linux over the last couple years and had used GitExtensions on Windows ever since SourceTree got bloated and slow.  I've tried practically every git GUI for Linux now, and none compare to GitExtensions.  I really miss simple things like clearly seeing the branch structure and staging, committing, and pushing graphically, or even seeing the change history for a file.  You'd think one of the many Linux clients could get these things right.  The only ones that come close are not free for commercial use.

Ok, I'll get off my soapbox now ha.

Thanks for maintaining the most awesome git GUI out there!

**Comment by safield** [comment]
My story is the same. I have looked so hard for a good Linux git GUI, but they all really suck compared to Git Extensions. I am currently using Sublime Merge, and it is 10% the git client that git extensions is.

I am hoping and waiting patiently for the day that Git Extensions has first class Linux support again!

**Comment by kekekeks** [comment]
@RussKie 

Weather update from Avalonia. We've almost finished [our HwndHost counterpart](https://github.com/AvaloniaUI/Avalonia/pull/3473), so it would be possible to embed Winforms/WPF content to Avalonia apps. So you could mix and match controls, which should help greatly with the porting process.

**Comment by RussKie** [comment]
@meyertime @safield sadly without contributions from someone working on Linux there is little we can do... 

@kekekeks that's awesome!
I'm working on getting us to .NET Core as soon as practically possible. Then I can start looking at a POC. 
Unless, of course, someone else will start with that sooner

**Comment by meyertime** [comment]
Since I use Linux and git at work, I could possibly try things out and work on fixes, but I would not have time to invest in the refactoring being talked about here... :/

In order to tide over us Linux users, how hard would it be to fork version 2 and fix scaling?

**Comment by gerhardol** [comment]
> In order to tide over us Linux users, how hard would it be to fork version 2 and fix scaling?

GE v2.x is a fork already. Patches are accepted.
Scaling in Mono is supposedly hard though.

**Comment by safield** [comment]
Can you link to the fork?

**Comment by pmiossec** [comment]
That's not really a fork. 
The code is in the 'release/2.51' branch of the repository. 

https://github.com/gitextensions/gitextensions/tree/release/2.51

**Comment by meyertime** [comment]
OK, I don't want to derail this thread too much, but I'm trying to get version 2 workable for now. Some things scale and some things don't, but even when I disable scaling in the settings, it still doesn't render right. If at least that could be fixed, I could use a workaround like https://github.com/kaueraal/run_scaled. It won't look pretty, but at least it will work. Would it be OK to open an issue against version 2 to discuss and get pointed in the right direction?

**Comment by RussKie** [comment]
Absolutely, please do!

**Comment by NN---** [comment]
@RussKie

> Weather update from Avalonia. We've almost finished [our HwndHost counterpart](https://github.com/AvaloniaUI/Avalonia/pull/3473), so it would be possible to embed Winforms/WPF content to Avalonia apps. So you could mix and match controls, which should help greatly with the porting process.

I see this is merged. Does it mean that Avalonia can be used now in GitExtensions ?

**Comment by gerhardol** [comment]
> I see this is merged. Does it mean that Avalonia can be used now in GitExtensions ?

This should mean that someone with the time and interest can start playing around with Avalonia.
To get something fully working in Linux I expect that a large part of the application need to be updated.
(I do not think this is news to you, but others reading the thread may get too high hopes.)

See also GE in wine discussions in #6051

**Comment by SoerenDaenekas** [comment]
Linux and iOS support can be actively considered using .NET MAUI. 

The only downside is that with all other solutions a rewrite of the UI code is required.

https://github.com/dotnet/maui

See https://devblogs.microsoft.com/dotnet/introducing-net-multi-platform-app-ui/

**Comment by kekekeks** [comment]
@SoerenDaenekas have you actually tried writing complex desktop apps with Xamarin.Forms (which is what maui is)? Blindly following the hype train isn't a healthy thing.

**Comment by t00** [comment]
@SoerenDaenekas @kekekeks Indeed MAUI looks promising as a get out of jail card for Xamarin apps but trusting MS (again) to keep the platform under active development is a bit of gamble. Only real advantage of MAUI is using native controls and close to metal mobile platform support, both not that important for GitExtensions in my humble opinion.

**Comment by RussKie** [comment]
.NET MAUI is XAML-based, and with XAML it is the same answer as to the following questions - "Why not use WPF?", "Why not use WinUI?", "Why not use Avalonia?", etc.
Because XAML-based UI frameworks use completely different development paradigms such as MVVM, MVU, etc., that are not compatible with Windows Forms dev style. It is not necessarily better or worse, it is what it is, and it has its pros and cons. 

The development of the app has started back in 2008, when Windows Forms was about 7 years old and still popular, and WPF had just got out of its nappies. Building on WinForms has allowed the team to offer the app on Linux, however Mono WinForms had lost the steam, and hamstrung any further innovation, thus we cut it.

**Comment by PeshekhonovK** [comment]
And what about DotNet 5 when it comes out? It is going to just include WinForms, so probably it would be much easier task?

**Comment by miterosan** [comment]
WinForms is Windows only
It does not matte which .net version.

**Comment by RussKie** [comment]
Windows Forms remains Windows only (hence the name) as it is closely tied to Windows API.

**Comment by rstm-sf** [comment]
> Because XAML-based UI frameworks use completely different development paradigms such as MVVM, MVU, etc., that are not compatible with Windows Forms dev style.

Sorry, but winforms suit all of these approaches, for example [MVVM](https://github.com/oxyplot/oxyplot/tree/develop/Source/Examples/WindowsForms/ExampleBrowser) :)

Even more, it is possible to create combined approaches like MVPVM

**Comment by RussKie** [comment]
I didn't say it was impossible. But Windows Forms apps don't generally use these patterns. I've been involved in development of a Windows Forms app that use MVP pattern. To say it was complex - is not to say anything.

And for the argument sake we consider MVVM or MVPVM - are you offering your services to rewrite the app? :)

**Comment by rstm-sf** [comment]
> I didn't say it was impossible

Sorry for misunderstanding

In fact, I am interested in making this application cross-platform and understand that it will take a long time to rewrite it.

Seems to me that it is better to start thinking after the migrate to the .net core occurs and it looks like you started doing it all over again, but already on .net 5 #8522. It would be really interesting to start 🙂

Speaking about UI, we can remember that a [ControlGallery](https://github.com/modern-forms/Modern.Forms/tree/master/samples/ControlGallery) for Modern.Forms has appeared and it looks cool. But I don't like the fact that the Avalonia backend was taked by copy-paste, it would be more interesting to find another way to take the source code (maybe somehow through a submodule?), since keeping track of the changes in bug fixes is hard work, besides, the sources change slightly under csharp 8

**Comment by RussKie** [comment]
Thank you for the link to Modern.Forms, a (yet another) interesting x-plat attempt of Windows Forms.

We had few quick chats with @kekekeks (one of Avalonia maintainers). An idea was floated attempting to convert (or rather create a clone of) `FormCommit` to Avalonia to make it x-plat.

Right now I'd like to move off .NET Framework for a number of reasons, including but not limited to getting new API and perf benefits of .NET, the ability to debug and enhance Windows Forms code, and simplify our packaging and deployment stories. After we have migrated to .NET, I think should be in a better position to contemplate x-plat.

**Comment by rgl** [comment]
@RussKie care to share why you closed this issue? Is cross-platform done or abandoned?

**Comment by RussKie** [comment]
I closed it because I haven't seen anyone sufficiently interested in this. Saying "I want this done" is not enough.

**Comment by t00** [comment]
@RussKie I avoided switching to SmartGit with hope that cross platform GitExtensions will eventually be on the horizon. I was determined to support the project (similarily like I did with KeepassXC WebDAV feature) and help with dev once some plan materializes. Other times I sat quiet and liked some posts above.

Now GitExtensions can be considered a legacy software/abandonware - that's how it looks from 3rd person perspective at least. Windows is used less and less by devs, some prefer Mac others Linux but this is the reality - web dev is not limited to Windows and that is a majority of dev in 2021. Also dotnet roadmap and framework transformation seems to confirm this trend.

Dotnet 5 migration will help with making it cross platform but a goal of doing it (closing this issue) is not there.

It is fine if you lost interest in moving GE forward - it is still the most fully-featured Windows Git client and thanks for making it so.

**Comment by MCOfficer** [comment]
Labeling something abandonware because one (1) feature you want isn't actively developed is beyond just a stretch. They said they don't want to move GE forward *in this direction*, not that they're not moving it at all.

**Comment by t00** [comment]
@MCOfficer You're right, it was an unnecessary overstatement. One sure thing is that WinForms is a legacy GUI and it is holding back GE from not only being cross-platform but also from making use of better UI rendering techniques, styling among others. I remember the pain of rendering custom WinForms UI controls, sending messages to HWND, overriding WM_PAINT and other decades old methods of UI rendering. Not that is was not efficient, it was just hardly extensible with minimal separation of visual presentation and logic.

**Comment by gerhardol** [comment]
Git Extensions is a community project, the features added are basically what those that contribute want to have themselves. 
If a contributor wants cross platform enough, it could happen, but the effort is to big for any current contributor to start this. 
So the porting will not start automatically.

The .NET5 conversion (currently in review) is a step.
