### ISSUE TITLE
Commit message not stored after reverting a commit

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#6244]
## Current behaviour

A manually adapted commit message is not stored during an unfinished merge.

I know that there are reasons and test cases which ensure this behavior. Though there are valid use cases where this does not make very much sense.

## Steps to reproduce

- `Revert this commit...` with `Automatically create a commit` unchecked
- optional: modify the restored code
- enter an adapted commit message in the Commit dialog
- close the (modal!) Commit dialog (e.g. to lookup something in another commit)
- reopen the Commit dialog
- --> frustration

Even worse:
- try to revert a commit of a different branch
- no changes
- but the commit message 'Revert "..."' is sticky

## Expected behaviour

A manually entered commit message must not be discarded.

## Did this work in previous version of GitExtensions

No.

## Environment

- Git Extensions 3.1.0
- Build 4ebb916d67f24b09e4d8cc2213bae9be8b2cecfd
- Git 2.20.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
Thoughts?

**Comment by illfated** [comment]
When I manage to mess up a PR to Github and have to close it and then reset my local source back to before the first PR attempt to rebuild the PR content, I usually have to copy the PR commit text from Github back into GE (in particular if I spent some time to compose the commit text with required information) to recreate the PR with working content before pushing it to Github again. In that scenario, I would love to see GE being able to hold on to the previous commit message so I could apply it again, only making minor changes to the content for my next PR. Not sure if this is something I could have changed in the GE settings or if this is expected behaviour.

**Comment by mstv** [comment]
> When I manage to mess up a PR to Github and have to close it and then reset my local source back to before the first PR attempt to rebuild the PR content, I usually have to copy the PR commit text from Github back into GE (in particular if I spent some time to compose the commit text with required information) to recreate the PR with working content before pushing it to Github again. In that scenario, I would love to see GE being able to hold on to the previous commit message so I could apply it again, only making minor changes to the content for my next PR. Not sure if this is something I could have changed in the GE settings or if this is expected behaviour.

Which dialog(s) do you use for the use case you described, @illfated?
This issue deals with GE's Commit dialog, which provides the previous commit messages for re-use.
![grafik](https://user-images.githubusercontent.com/36601201/57028137-98de7a00-6c3e-11e9-91a7-8e6f0a5a01fb.png)

**Comment by illfated** [comment]
Hmm, I guess I based my experience on 2.5x versions, I haven't made as many PRs with long or complicated commit texts on 3.x.
Please ignore my input as such, it may be a lot better in 3.x than before.
