### ISSUE TITLE
vcxproj.filters highlighting

### ISSUE THREAD

**Issue by NN---** [gitextensions/gitextensions#6471]
## Feature description

Add XML highlighting for vcxproj.filter files.

## Environment

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.3745.0
- DPI 120dpi (125% scaling)

**Comment by gerhardol** [comment]
Please describe the desired rules

**Comment by NN---** [comment]
This is a regular XML file.

**Comment by kbilsted** [comment]
@gerhardol  How do I make changes to ``Project/Resources/SyntaxModes.xml` in the `ICSHarpCode` module? Is it some git-fu I still need to learn about?

 I was thinking we simply need to insert a `.vcxproj.filters;` into said file

**Comment by pmiossec** [comment]
>How do I make changes to ``Project/Resources/SyntaxModes.xmlin theICSHarpCode` module? Is it some git-fu I still need to learn about?

That's a submodule. So, you have to commit it first.

But I have already made the fix for this issue...I just have to push it.

>I was thinking we simply need to insert a .vcxproj.filters; into said file

No, that is not enough because of the way we find the highlighter with the extension

https://github.com/gitextensions/ICSharpCode.TextEditor/blob/master/Project/Src/Document/HighlightingStrategy/HighlightingManager.cs#L135

`Path.GetExtension(fileName)` will return `filters` and, so, will never find `.vcxproj.filters`

**Comment by pmiossec** [comment]
@kbilsted https://github.com/gitextensions/ICSharpCode.TextEditor/pull/12

**Comment by kbilsted** [comment]
@pmiossec  thanks for the quick reply. I did not have access to push there. Maybe  I need to first fork it on github...

**Comment by pmiossec** [comment]
Yes. Fork and PR like the main repository.
