### ISSUE TITLE
Request more information via NBug submission form

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#6607]
## Feature description

The uplift of NBug submission mechanism seems to be quick successful - we are now getting more reports about issues.
However most users fail to provide all required information that causes a) a lot of duplicates and b) a lot of requests from the Team for more information.

The NBug sumission form must be enhanced to request more information before a submission can be made.

The following information is required:
- Current behaviour
- Expected behaviour
- Steps to reproduce

Also advise users if their git version is below recommended.

**Comment by pmiossec** [comment]
It will be much more complicated but I was wondering if it's possible to search for duplicate before asking for the informations and opening the existing issue instead of creating one...

**Comment by RussKie** [comment]
#6608 :wink:

**Comment by pmiossec** [comment]
yes, I just saw it 😉

**Comment by gerhardol** [comment]
For 3.1.1, should we just add a comment in the default text asking the user to provide information or the issue will be closed?

**Comment by RussKie** [comment]
For 3.1.1 may be easier to spin up a duplicate check bot as discussed in #6608?

**Comment by gerhardol** [comment]
> For 3.1.1 may be easier to spin up a duplicate check bot as discussed in #6608?

Duplicates and improve information are separate.
We may choose to ignore this in 3.1.1 though.
I just suggest we do something like the following in 3.1.1. Could be new text boxes too in NBug, but this should be clear enough.

## Current behaviour

Replace this text with the current behavior.
Issues without information will be closed.

## Expected behaviour

## Steps to reproduce

Take some time to try and reproduce the issue, then explain how to do so here.

**Comment by RussKie** [comment]
How about the following dialog which appears when a user clicks on "Send and Quit" button?

![image](https://user-images.githubusercontent.com/4403806/58365342-5723b500-7f06-11e9-8f22-2c6ea94e7883.png)

or

![image](https://user-images.githubusercontent.com/4403806/58365502-d2866600-7f08-11e9-9358-550ae60610c6.png)

**Comment by gerhardol** [comment]
A popup is good. There is still some value in empty issues to get statistics so I would like to change the wording. 
A default text in the issue can be used by a bot and explain for other users why issues at just closed. 

On mobile now but can write a proposal tonight if no-one else does that.

**Comment by gerhardol** [comment]
Second popup:
Without this information your issue will be closed (but the information can be together with other issues).

Default text - or something the bot can use?
See above.

**Comment by RussKie** [comment]
Apologies Gerhard, but your last message eludes me.
Could you please post a full text of the popup as you see it

**Comment by gerhardol** [comment]
@RussKie 
Your second popup proposal, change (addition) to your second to last sentence:
Without this information your issue will be closed (but the information can be together with other issues).

In the issue default text - see my proposal above (or something the bot can use?)
https://github.com/gitextensions/gitextensions/issues/6607#issuecomment-494683221

**Comment by RussKie** [comment]
I'm afraid I'm finding `(but the information can be together with other issues)` bit unclear. 🤔 

Are you able to perhaps reword it?

**Comment by gerhardol** [comment]
I rather have the issues autoclosed than discouraging the users from submitting. The info can be used to get a bigger picture.

```
Without this information your issue will be closed (but can be used to gather statistics for issues).
```

**Comment by pmiossec** [comment]
I don't think the user understands what that means to be used for
statistics. What he want and expect when he reports an issue is that's to
be fixed.

I would prefer something like (in good English) :

Give as much as information to help the developers solve this issue
otherwise your issue will be closed without being fixed.

For that, please fill carefully all the fields.

Some fields are not filled but do you want to send the report anyway?

**Comment by RussKie** [comment]
Right, I think I get it now.

We'll have a message as discussed above:

```
Please give as much as information as possible to help the developers solve this issue
otherwise your issue will be closed without being fixed.
For that, please fill carefully all the fields in the report template.

Do you wish to proceed?
```

I am also working on a bot copied from https://github.com/Bartozzz/potential-duplicates-bot. The bot is looking at issues' titles and decides whether a new issue is a duplicate of existing issues. 
This should work nicely with our NBug integration flow.

I got the bot working when it is running locally (e.g. https://github.com/RussKie/Playpen/issues/25), but I'm struggling to have the bot deployed... 😒

**Comment by gerhardol** [comment]
_Closed without being fixed_ is incorrect. The issue may help still or already be fixed.

I am not persisting.

**Comment by pmiossec** [comment]
You're right, we could better use:

... may be/could be / would be closed without being fixed.

>
>

**Comment by illfated** [comment]
Suggestion:
```
Please give as much as information as possible to help the developers solve this issue.
Otherwise, your issue may be closed without any follow-up from the developers.
Because of this, please make sure to fill in all the fields in the report template.

Do you wish to proceed?
```

**Comment by RussKie** [comment]
I like that, Trond 👍 

@gerhardol @pmiossec: any objections to the Trond's wording?

**Comment by illfated** [comment]
BTW, some people see "issue" as meaning the same as "problem", meaning a solution is needed to fix something in the repository, I can suggest "issue ticket" as well, in case that is specific enough:
```
Otherwise, your issue ticket may be closed without any follow-up from the developers.
```

**Comment by gerhardol** [comment]
I can live with the suggestion

**Comment by RussKie** [comment]
![image](https://user-images.githubusercontent.com/4403806/58474427-66b52f00-818e-11e9-8d3a-f6a4350d3782.png)

**Comment by illfated** [comment]
The message looks good to me. Wishing you the best of luck with the rest of the source. 👍 
(The only nit-pick I have left is that I prefer "provide" instead of "give" in the first sentence, but with the caveat that it could look less understandable for less IT savvy users.)

**Comment by mstv** [comment]
I am quite late with this: Though when I used this message in a NBug report, I noticed that it uses "please" at the begin of the sentence (twice). I learned this has the meaning of a command/request. What do the (almost) native English speakers think about it?

I try to see it from the user's perspective: GE has crashed and instead of an apologize they might be demanded. (Of course, we need to force them to provide STR etc.; and OSS lives from contribution.)

**Comment by illfated** [comment]
From that point of view, it looks like the second "please" could be omitted. It is not strictly necessary, even though it could (from the developers' point of view) be seen as mildening the request for information to be filled in. Fair point, you can choose to remove that second "please" in the message, since it may not be clear enough to the end users that it is imperative to fill in all the fields.

Maybe I misunderstood your description, I have not tried to replicate a scenario to trigger the message.
> [ ... ] I noticed that it uses "please" at the begin of the sentence (twice). [ ... ]

Do you mean that it shows up more than one time in the text "Please give as much as information as possible to help the developers solve this issue.", or are you just referring to the same message as shown in RussKie's comment https://github.com/gitextensions/gitextensions/issues/6607#issuecomment-496474600, that it is used once at the very beginning, then once more in "Because of this, please make sure to fill in all the fields in the report template."? If the screenshot from RussKie shows the same message as you are referring to, my first paragraph in this comment box is my intended reply.

**Comment by mstv** [comment]
> Maybe I misunderstood your description.
> Do you mean that it shows up more than one time in the text ...

That's not my point. I had not noticed the emphasized imperative when I followed this thread -- until I used the text to comment an issue with an unfilled template.

My question is: Should we move the "please" to the end of the sentences - in order to ask more politely?

**Comment by RussKie** [comment]
Michael, could you please post the full message as you see it?
May be easier to discuss it

**Comment by gerhardol** [comment]
Take this discussion in the PR instead:
https://github.com/gitextensions/NBug/pull/18

**Comment by RussKie** [comment]
FYI I've started working on this. More to come.
