### ISSUE TITLE
Git credential-manager error when requires admin elevation

### ISSUE THREAD

**Issue by mdsmark** [gitextensions/gitextensions#6694]
## Current behaviour

An error appears while trying to launch git credential-manager command on operations like: pull or push. The bug started after an upgrade of company policies that limited access to the windows credential manager. Starting GitExtensions with admin privileges does not resolve.
Settings compatibility "admin privileges" to executable C:\Program Files (x86)\GitExtensions\ConEmu\ConEmu.exe sometimes resolve, sometimes not.
The error appears 2 times. After which the pull/push operation is still performed successfully.

## Expected behaviour

GitExtensions should hide this message box, since the pull/push operation works.
Otherwise should try to request admin elevation and retry the operation.

## Steps to reproduce

Prerequisites: Change windows credential manager access policy (only to administrators group)

1. Open GitExtensions
2. Open a repository from GitExtensions
3. Try pull operation
4. See the error

What I've tried:
- Set the compatibility settings (always start as administrator) to GitExtensions executable
- Set the compatibility settings (always start as administrator) to git executable
- Set the compatibility settings (always start as administrator) to ConEmu executable

Some combinations of settings above, cause other errors when starting GitExtensions

## Screenshots

![image](https://user-images.githubusercontent.com/49102769/58557914-d0314e00-821f-11e9-8817-0f8c896cf98b.png)

## Did this work in previous version of GitExtensions

Yes the version is not changed: Git Extensions 3.1.0.5877

## Environment

- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3416.0
- DPI 120dpi (125% scaling)

**Comment by RussKie** [comment]
Try disabling the ConEmu
https://git-extensions-documentation.readthedocs.io/en/latest/settings.html?highlight=emulator#git-extensions-advanced-general-use-console-emulator-for-console-output-in-command-dialogs

**Comment by mdsmark** [comment]
Thank you. Disabling the ConEmu the annoying message box is gone away.
But I don't know if these messages are still bugs
![gitcredentialmanager-elevation](https://user-images.githubusercontent.com/49102769/58554760-1da9bd00-8218-11e9-9dd5-874e7811b885.PNG)

I investigated that:
- Running GitExtensions as normal user: use git and ConEmu (if enabled) as normal user = OK
- Set the admin compat to ComEmu executable: need git to be launched as admin = OK
- Set the admin compat to git executable: GitExtensions crash as normal or admin user = KO
- Running GitExtensions as Admin: use git and ConEmu (if enabled) as normal user instead of elevated user = KO

So I think that the last point is an error because GitExtension should propagate its elevation to git and or other tools, when the user launch it as administrator.

**Comment by RussKie** [comment]
How is you credential helper configured?
Please run the following:
```
$ git config credential.helper
```

**Comment by mdsmark** [comment]
This is my configuration
```
[credential]
	helper = manager
```

I confirm that restarting GitExtensions without ConEmu but as Administrator resolves all errors.
![image](https://user-images.githubusercontent.com/49102769/58557661-35d10a80-821f-11e9-965a-098d76a9c583.png)

So all the previous errors depend on ConEmu/git elevations but only when ConEmu is enabled.

**Comment by KurzedMetal** [comment]
I'm having the same issue in a corporate environment, any recommendation to make this work without running stuff as Admin?

**Comment by RussKie** [comment]
@KurzedMetal what version of git/Git Extensions/OS/.NET are you running? What are your local and global (i.e. system-wide) git `crededntial.helper` settings?
The errors you're getting are (Conemu aside) are related to git configurations and not specific to Git Extensions.

**Comment by KurzedMetal** [comment]
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0

Repo config `credential.helper` = `manager`
Global config `credential.helper` is not set (empty)

Can you explain why do you think this is a config issue? May it can help me to troubleshoot this. I personally think it is not a config issue because it's the same repo and the same config but it doesn't work in Git Extension and it does work on console when using a user that can elevate, and works on both when running as Administrator. If it was a config issue, it would never work.

BTW, I also tried setting Global config `credential.helper` to `manager` to both my normal user and running a console with Administrator (so both users have set it globally) and I still get the error.

If you have any other idea or want any other info, feel free to poke me again.

**Comment by KurzedMetal** [comment]
May this be related to something like https://github.com/tmux/tmux/issues/1007 ?

**Comment by RussKie** [comment]
> Can you explain why do you think this is a config issue?

I don't believe it is a GE-specific issue because there are other reports of the problem for other systems. 
I punt that it is a config or an environment specific issue because only few users report the issue. So the likelihood of something broken in our app (whilst possible) is low. 
In a nutshell GE is a UI layer on top of git, there is no magic.

I'm not quite sure how to debug the issue empirically - this is a complex issue which may be a combination of many things - OS, group policies, acl configs, git, Git Extensions, etc etc etc...
You could pull down the source, attach a debugger, run a procmon. If that doesn't help, maybe do a dump and use a WinDebug to trace the issue...
