### ISSUE TITLE
Improve graph view when content/commit filtering is enabled

### ISSUE THREAD

**Issue by johndog** [gitextensions/gitextensions#6804]
## Feature description

GitEx has a strange way of breaking up the graph when filtering is enabled.  It only connects commits that are immediately related to each other, all other commits, whether they are reachable by another branch or not, show up as if they are unreachable.

In the picture below, a filter is applied.  The graph shows clearly which commit is "origin/master".  The selected commit is displayed as if it is a separate graph, since it's drawn with a line in column two.  However, the commit information below shows that this commit is clearly "Contained in branch" origin/master.  So the first three commits are all reachable from origin/master.  If I move three commits down, I find a commit "contained in no branches", but it is drawn in exactly the same way as other commits that are in origin/master.

My suggestion here is to not draw reachable commits as if they are different heads...  Draw them as if they are actually connected, even though the connections between are missing.  Ideally a graphical feature could show that links in the chain are omitted, but this isn't required.

This would make it much easier to reason about the part of the history that contributed to the version in the current branch, and the part of the history that's contributing to other branches.  Right now it's impossible to do just visually, you have to inspect each commit.

![image](https://user-images.githubusercontent.com/22213780/59538532-f8bb7800-8eae-11e9-9ab6-1116433d6c9b.png)

## Environment

- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.20.1.vfs.1.1.104.g2ab7360
- Microsoft Windows NT 10.0.18917.0
- .NET Framework 4.8.3752.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
@spdr870 could you please have a look.
Thanks

**Comment by spdr870** [comment]
There are actually 2 problems here.

1) The graph is incomplete but GitExtensions will still attempt to draw a line to its parent. If the parent is not in the graph, it will render a line from the commit to the bottom of the graph. I checked what git.exe returns from git log --graph --grep="test" and it will render fragments of the graph. I like this better.

2) All (or most if the current commit is visible) commits are rendered as unreachable. Also because there is not enough information to determine if the commit is a descendant of the current commit.

We could attempt to fix 1 by not rendering lines if the parent is not in the graph. This should only be done when filtering, but it is probably not too difficult. Issue 2 cannot be fixed as long as we let git handle the filtering. We could just render everything as reachable, but that's also incorrect.

Another option is to hide the entire graph when a filter is active. In some cases this might be better, but when filtering on branches of committers this might be worse.

**Comment by RussKie** [comment]
Thanks Henk.

> I would suggest to hide the entire graph when there is a filter active and always render all commits as being reachable. The behavior should differ per filter. A branch filter doesn't break the graph, so the graph can then be visible. A 'text' filter breaks the graph and then the graph should be hidden. All filters break the 'reachable' flag.

Any way you could create some visuals to help in understanding options?

**Comment by pmiossec** [comment]
@spdr870 An idea I got, but that could only solve just a small part (the display) of this difficult problem, could be to introduce a new type of "virtual commit" that could be used to link 2 far ancestors commits.

It will be used to show that there are normally, some commits between.

This commit would have the following characteristics:
- is made up by GitExtensions with the sha1 of a commit as child and the sha1 of a distant ancestor as parent
- could be displayed like that (dirty draft): ![image](https://user-images.githubusercontent.com/460196/60017347-d5e84b00-9688-11e9-9d84-fda9c5a63a49.png)
- will probably be unselectable.

If this idea could help for the thinking...

**Comment by spdr870** [comment]
@pmiossec I tried this before, but its not trivial to implement. It would make the graph cleaner. The hard thing is to figure out when the blue line should move to the right to use the extra available space.

**Comment by gerhardol** [comment]
Since GE 4.0 the parents are rewritten in more situations so the next visible parent is the displayed commit. There is no visible cue to this (will need a separate Git call, currently done per commit where needed in e.g. rebase and blame). Such a cue would be expensive.
Closing this, as the core issue is handled.
