### ISSUE TITLE
Blame view - use hash instead of timestamp

### ISSUE THREAD

**Issue by gpongelli** [gitextensions/gitextensions#6832]
## Feature description
File History form (opened with Blame command) shows the short hash in upper view.
Looking at the lower left window, where there is the list of commit's authors, the timestamp is displayed.

It's difficult to match the information from the upper tree view (that contains hashes and time distance) to the lower informations (that contains only timestamp).
I think changing the timestamp with the short hash on the lower left view can be useful to understand which commit (from above view) changes the highligted lines (on the lower right view).

![immagine](https://user-images.githubusercontent.com/842026/59904774-b17c3c80-9404-11e9-98c1-8c221706c07c.png)

## Environment

- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by drewnoakes** [comment]
/instead/as well as/

**Comment by pmiossec** [comment]
I worked some times on the blame form recently and never feel the need of such a feature because a hash is not really human friendly. But why not...

It's not very difficult to achieve to *add* an option to display Sha1. 

Perhaps you could do it by looking at my last changes on this form and do a pull request?

As a workaround, I imagine that you know that you could get the Sha1 of a line by hovering the line in left panel. It's displayed in the tool tip that is shown.

**Comment by gpongelli** [comment]
I didn't know about the hover feature on left panel, but I see the hash there is 10 chars long and on the upper panel is 7 chars long.

**Comment by pmiossec** [comment]
A hash is 40 chars long but most of the times, 6 or 7 are enough to find a commit.
So 7 are displayed be default in the revision grid because that's enough for humans, but you could resize the column to see all if you really want.
 
But for your comparison, 7 are enough.

For UX, I admit that we should harmonize but you have all you need to find your commits.

**Comment by pmiossec** [comment]
And also, double clicking in the left panel will select the commit, so that's probably more efficient than comparing the hashs.

**Comment by gpongelli** [comment]
> And also, double clicking in the left panel will select the commit, so that's probably more efficient than comparing the hashs.

I didn't know about this feature, I use blame feature too few.

From my point of view, with your explanation about hover and double click, there is no more need of the improvement, you can close this issue.

Thanks,

**Comment by gerhardol** [comment]
Closed as suggested by the author
