### ISSUE TITLE
Error in push or pull - ConEmu

### ISSUE THREAD

**Issue by marcieldeg** [gitextensions/gitextensions#6878]
A message error appear, but the operation occur successfully.

version: 3.1.1.6049

Message:

Exception 0xC0000005 (Read x02C7A000) was occurred (conemu.exe, PID=5348)

ConEmu build 190310 

Memory dump was saved to

C:\Users\Marciel\Desktop\ConEmuTrap\Trap-190310-5348.dmp

Please Zip it and send to developer (via DropBox etc.)

https://conemu.github.io/en/Issues.html

![error](https://user-images.githubusercontent.com/14255958/60341802-15af7b00-9986-11e9-8c33-383f82c7943a.jpg)

**Comment by hoppities** [comment]
I'm seeing this, too.

**Comment by JeremyMattingly** [comment]
I am also seeing this.

**Comment by pmiossec** [comment]
Perhaps you should report the error to the link provided.

And if you want to work around the issue, disable conemu in the settings.

**Comment by Zenilogix-Carl** [comment]
> Perhaps you should report the error to the link provided.
> 
> And if you want to work around the issue, disable conemu in the settings.

Just to confirm... is this the setting that will disable conemu?

![image](https://user-images.githubusercontent.com/13467127/60440398-be5a1680-9be2-11e9-9abe-4aa3c7220e1c.png)

**Comment by pmiossec** [comment]
@Zenilogix-Carl yes

**Comment by PedroLamas** [comment]
I've been having the same issue reported here, disabling the "console emulator" using the referred option seems to have fixed it completely!

**Comment by heinzdmx** [comment]
It appears that issues has already been created there https://github.com/Maximus5/ConEmu/issues/1926 https://github.com/Maximus5/ConEmu/issues/1934

They note that 190310 (10 Mar) which is the version that Git Extensions 3.1.1.6049 ships, is out of date. 
The newest one is 190623 (23 June).

**Comment by gerhardol** [comment]
In 3.0 we used a release from beginning of 2018, it was updated to 2019-03-10 to see if the issues decreased after recommendation from Maximus5. My feeling is that there are more issues in 3.1 after the update. I have tested with 2019-05-10 gitextensions/conemu-inside#16 butsee no improvement of the problems I see: background/foreground issues. I find nothing in the release notes since 190310 indicating that stability issues are addressed. 

The only "solution" right now is to disable ConEmu. I would prefer to not do that, I like the functions (even if I am annoyed by the foreground/background behavior) and do not have the crashes.
If this continues I would like to disable ConEmu by default though.

**Comment by dictoon** [comment]
Also seeing this when rebasing a branch.

**Comment by CookiePLMonster** [comment]
FWIW I'm also seeing this most often on rebase.

**Comment by programcsharp** [comment]
Seeing this pretty frequently on push.

**Comment by catonice** [comment]
Having this issue as well:
`- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)
`

**Comment by catonice** [comment]
![image](https://user-images.githubusercontent.com/13959541/64261183-674b2780-cf2c-11e9-9ee7-fe5252d1f94f.png)

**Comment by jimbo1qaz** [comment]
According to the ConEmu developer (https://github.com/Maximus5/ConEmu/issues/1934#issuecomment-506705063)...

> 190310 is rather old build, BTW

Would updating the ConEmu bundled with Git Extensions help fix this bug?

**Comment by RussKie** [comment]
We have been updating, maybe not as regularly, but we have.
The problem has been happening to our users for many years....
Since we uplifted the bug reporting capabilities we are now getting reports
more often, hence the quantity.

**Comment by jimbo1qaz** [comment]
Since disabling ConEmu to avoid this crash, I noticed that with "automatically close dialog" checked, Git operations on small repositories finish much faster than before, and the dialog closes almost instantaneously. So ConEmu was slowing the program down... Is this worth reporting as a separate bug?

**Comment by RussKie** [comment]
I think it is; at least for the tracking purposes.

**Comment by gerhardol** [comment]
Have not seen this the latest years, ConEmu updated several times since this was reported
