### ISSUE TITLE
Commit message  incorrect height at 150% scale factor

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#6898]
## Current behaviour

A regression (probably caused by me) in calculation of the commit message box in a scaled environment:
❗️ **This is only happening at 150% scale factor!**
![image](https://user-images.githubusercontent.com/4403806/60768585-e678d680-a108-11e9-98a6-12f37d120d47.png)

## Expected behaviour

Commit message must look the same at 150% scale factor.

## Steps to reproduce

Set Windows to 150% and run the app.

## Screenshots

I have tested all other scale factors available to me:

* 100%
![image](https://user-images.githubusercontent.com/4403806/60768576-c8ab7180-a108-11e9-8749-e3dab5b465ef.png)

* 125%
![image](https://user-images.githubusercontent.com/4403806/60768559-a285d180-a108-11e9-9dc4-c6d1ff8d9558.png)

* 175%
![image](https://user-images.githubusercontent.com/4403806/60768539-7f5b2200-a108-11e9-8b0c-0a30504e98c3.png)

* 200%
![image](https://user-images.githubusercontent.com/4403806/60768528-605c9000-a108-11e9-9ea9-5739729d21e7.png)

* 225%
![image](https://user-images.githubusercontent.com/4403806/60768507-34d9a580-a108-11e9-9bba-b3bdf80cd8e9.png)

* 250%
![image](https://user-images.githubusercontent.com/4403806/60768489-0360da00-a108-11e9-8c60-51c9a6b2719c.png)

## Did this work in previous version of GitExtensions

Yes, because the commit message had a newline appended that caused an additional margin at the bottom.

**Comment by RussKie** [comment]
@NikolayXHD any help?
Apart from adding a hardcoded check for 150% scale factor...

**Comment by NikolayXHD** [comment]
> @NikolayXHD any help?
> Apart from adding a hardcoded check for 150% scale factor...

I suspect this is caused by inconsistency of text measuring with actual text rendering due to rounding taking place somewhere, either in actual `RichTextBox` rendering or `TextRenderer.MeasureText` we use to calculate the size.

I can see following paths to exlore this hypothesis
- see `TextRenderer.MeasureText` although I suspect it ends up with Win32 API call without disclosing actual implementation
- try change `graphics` parameters related to antialiasing to see if it changes the result of `TextRenderer.MeasureText(graphics, ...)`

**Comment by RussKie** [comment]
I've done further testing on an 4K monitor with a SF 300% and 350% - everything renders as expected.
So it is just SF 150%.... 😱
