### ISSUE TITLE
Apply stash to some files

### ISSUE THREAD

**Issue by kaesaecracker** [gitextensions/gitextensions#6902]
## Feature description

From the stash window, I want to apply only one of the diffs.
For example I might have the files `foo.x` and `bar.x` in the stash. I expected the right-click menu of `foo.x` to have an option to apply the diff to `foo.x` without touching `bar.x`.

In the command line this is pretty easy to do, in the example it would be `git checkout stash@{0} -- foo.x`

## Environment

- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3801.0
- DPI 120dpi (125% scaling)

**Comment by pmiossec** [comment]
>From the stash window, I want to apply only one of the diffs.

 &

>In the command line this is pretty easy to do, in the example it would be git checkout stash@{0} -- foo.x

Correct me if I am wrong but the command you describe in the 2nd comment is not doing what you asking as new feature...

The command is not applying the stash for only one file but overwriting the content of the file with the one of the stash (loosing the changes done in the file since the stash has been made).

Because applying one file could be done, not very user friendly I admit, by:

* Opening "Manage stashes..."
* Select the file in the stash
* In the diff view, select all the text and right click and select "Cherry pick selected lines"

You could also do what you want but only for the last stash because that's the only one displayed in the revision grid with the option "Cherry pick file's change" or "reset file to" (depending to what you really want) .

**Comment by gerhardol** [comment]
There is no direct way to apply partial stashes. In addition to the workaround @pmiossec explained you could apply the stash and the reset you changes you do not want.
It is possible to see all stashes in the revision grid too (reflog).

I see no direct way to do this (and find the workaround simple enough), but if someone has a better idea and make a good implementation, it could be accepted.

**Comment by pmiossec** [comment]
>I see no direct way to do this (and find the workaround simple enough), but if someone has a better idea and make a good implementation, it could be accepted.

There are 2 ways that could be implemented not so difficultly. In the context menu of the diff view (there is already "Cherry pick selected lines" like I said).

Or in the context menu of the file list of a stash.

But indeed, someone has to do it.....
