### ISSUE TITLE
Keyboard Layout change to US Layout when changing branch name

### ISSUE THREAD

**Issue by VerzCar** [gitextensions/gitextensions#6962]
When the branch name get changed by the user and the user has a European layout, in my case German, the keyboard layout change to US layout. The layout is changed to US Layout in the whole system not only in git extension. 

Reproduce the issue:
- click the desired branch you want to change the name
- right click and select "Rename branch.."

When the dialog of the renaming appears, the keyboard layout is changed.

Used Version:

![extension-info](https://user-images.githubusercontent.com/41541298/62030737-0706ee80-b1e6-11e9-8640-6b723d2bf1ab.png)

**Comment by lhiginbotham** [comment]
@VerzCar 
I am unable to reproduce this issue using the version shown in the screenshot:
![image](https://user-images.githubusercontent.com/14078392/67136641-0a16e700-f1f7-11e9-9438-5c059a770594.png)

Can you please install the latest version of GitExtensions and try to reproduce this issue?  It is possible that it has been resolved since you submitted this issue.
