### ISSUE TITLE
Support basic git-svn commands

### ISSUE THREAD

**Issue by KindDragon** [gitextensions/gitextensions#713]
Basic Git-SVN Operation:
- [ ] SVN DCommit Command
- [ ] "SVN Rebase" command 
- [ ] "SVN Fetch" command 
- [ ] Support Git svn-clone at clone dialog.

P.S. Offer "DCommit" instead of "Push" when working as SVN client

**Comment by fareloz** [comment]
It would be awesome to have svn rebase\fetch instead of pull on pushing pull button when working with git-svn repository

**Comment by RussKie** [comment]
I don't know if any of the core team members use svn... 
So unless someone, who really needs the svn support, is willing to contribute - this isn't going to happen....

**Comment by gerhardol** [comment]
The support in GE is very limited. Is anyone using SVN at all in GE?
Is SVN really a use case with GE, why not use a separate client?
"Full" SVN support in GE will not happen unless someone with that interest put work into it.

SVN is not a major blocker for development, but it is still something I would like to remove rather than enhance.
