### ISSUE TITLE
Enable support also for older gerrit plugin versions

### ISSUE THREAD

**Issue by thimmy687** [gitextensions/gitextensions#7200]
## Current behaviour
After the last update it is possible to switch between shown options

![image](https://user-images.githubusercontent.com/7715216/65664325-642ded80-e039-11e9-8fa7-0fe39e4a02ae.png)

## Expected behaviour

since we not use the latest version of gerrit it would be nice to have a choice to select which version of gerrit-plugin we can use to have the possibility to use older features

## Environment

- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.20.0.windows.1 (recommended: 2.22.0 or later)
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3460.0
- DPI 96dpi (no scaling)

**Comment by thimmy687** [comment]
I know it is possible to just replace the plugin .dll, but it would be nice to have this as option to be able to switch easy between both

**Comment by pmiossec** [comment]
As far as I know, there is no one in the GitExtensions maintainers that use Gerrit.
So we are unable to understand and do that.
The solution can only come from you, the community!

Perhaps you could have a look at #7198 and give your point of view.
And perhaps you should include @lekhmanrus in this conversation.

>I know it is possible to just replace the plugin .dll

Indeed, most of the times it will work but it is, as you said, a perfect solution because that won't work if plugin api change.

>since we not use the latest version of gerrit

For the discussion, it would be good that you say what is your version, what is the one supported by the plugin at the moment and what is the last version of Gerrit to see if that everything make sense (because, as I said, there is no maintainer for this plugin).

The best is also that you do the development but if you can't, tell us as much as possible what are the changes that must be done...

**Comment by RussKie** [comment]
I would suggest to look into moving the current plugin out of this repo and converting it to a community plugin.
Then you will have a full control over the Gerrit integrations, multiple versions etc.

@maraf and @mast-eu have been pioneering the Plugin Manager for Git Extensions (and have done an impressive thing), and it is getting significantly easier to develop and install community plugins for Git Extensions.

* https://github.com/gitextensions/gitextensions.plugintemplate
* https://github.com/gitextensions/gitextensions.pluginmanager

Please let us know if you're interested and up for the challenge, I'm sure @maraf and @mast-eu would gladly help you in this journey.

**Comment by gerhardol** [comment]
One way is to add the old version as a separate plugin.

**Comment by RussKie** [comment]
> One way is to add the old version as a separate plugin.

We are not doing this in this repo.

**Comment by lekhmanrus** [comment]
I think we can do request to `{gerrit_host}/config/server/version` and based on version we can show different fields and process them in the needed different way.
We can read Gerrit host from `.gitreview` file. In this case we won't need to separate this plugin and maintain two or more different plugins.

Also it would be good improvements to read and set some default values from `.gitreview` (or even `GitExtensions.settings`), like Reviewer(s), CC, Publish Type etc. It might be useful.

**Comment by gerhardol** [comment]
@thimmy687 (as well as other Gerrit users
Please review and test the build in #7216
