### ISSUE TITLE
[Feature Req] Show branch name column

### ISSUE THREAD

**Issue by savioret** [gitextensions/gitextensions#7201]
It would be great to add an option inside the "View" contextual submenu to enable/disable something like "**Show branch name column**" so that every changeset shows its branch name.

![image](https://user-images.githubusercontent.com/5497332/65674799-774ab880-e04d-11e9-9545-c44a8c93cdc5.png)

I find this very helpful in the mercurial workbench:

![image](https://user-images.githubusercontent.com/5497332/65674713-53877280-e04d-11e9-81f5-32e42da3db1b.png)

Thanks you.

**Comment by pmiossec** [comment]
This feature that makes perfect sense in Mercurial (where a commit belong to a unique branch i.e. the branch is contained in the commit metadata) has no sense in git :(

Branches in git are pointers towards commits which are linked together forming a graph.

So, a git commit could belong to multiple branches (and the list could be huge, so difficult to display, and very time consuming to build).

If, for example, I take the first commit of the repository, it belongs to **all** the branches.

![image](https://user-images.githubusercontent.com/460196/65678661-fe029400-e053-11e9-87c4-f92f0a4a41e9.png)

Note: and also note that you already have this information if you select a commit, in the commit detail panel

To conclude, I don't think it would be made because, as I said, it makes no sense in git.

**Comment by savioret** [comment]
It makes sense, thanks.
However, in my case the first commit belongs only to _master_

![image](https://user-images.githubusercontent.com/5497332/65685606-a881b380-e062-11e9-8f84-b9ce3b35c083.png)

**Comment by pmiossec** [comment]
>However, in my case the first commit belongs only to master

I would like to say the **first made in the repository**, so the oldest one (the last one when you scroll down) not the newest, so the first displayed 😉.

Because the history is displayed the newest first.

**Comment by pmiossec** [comment]
Sorry, misunderstanding of your answer.

In fact, that's because you only have one branch, `master`. Create a new one and you will see.

**Comment by gerhardol** [comment]
You see the branch HEAD in the revision graph.
The request could be interpreted as "display all branches this commit is part of" as seen in the Commit info and the tool tip.
This is not very useful, as in practical solutions there will be an overflow due to many branches (and you often use longer branchnames in Git than Hg) and it will slow down (finding the info is a little expensive).

I suggest the request is rejected.

**Comment by RussKie** [comment]
@savioret few existing options you may find useful

1. "Show current branch only" - this will hide everything but the currently checked out branch
2. "Show filtered branches" 
3. "Highlight selected branch" - it highlights all parents of a chosen commit

All of these options are available under the View menu.
