### ISSUE TITLE
Provide Info on Suggested Commandline Needs for Mergeand Difftools

### ISSUE THREAD

**Issue by asjones987** [gitextensions/gitextensions#7397]
## Current behaviour

I wanted to setup UltraCompare as the Mergetool and Difftool for Gitextensions however I was not sure what parameters would be best for GitExtensions

What command line needs are suggested? When one pick different tools different commandline options set set. I know options will vary from one program to another. However "types" of things work betst for GitExtensions and can those items be shared here and added as some sort of reminder on the Config page for the Merge and diff option?

**Comment by RussKie** [comment]
GE is a UI over git cli, so whatever parameters UltraCompare expects should be configured to pass to it.
You can do it:
* via git cli, see: https://git-scm.com/docs/git-mergetool and https://git-scm.com/docs/git-difftool; or
* via GE interface:
![image](https://user-images.githubusercontent.com/4403806/68538680-b732e880-03cc-11ea-8201-8181b22e284b.png)

Because UltraCompare isn't preconfigured in GE, you'll need to type the necessary information in.

I had a quick search, and possibly these are parameters you need to configure ([source](https://community.atlassian.com/t5/Sourcetree-questions/Re-Configuring-SourceTree-for-Windows-to-use-Ultracompare/qaq-p/1009927/comment-id/31787#M31787)):
> difftool:
> file: uc.exe
> args: _-B -b -t "$REMOTE" "$LOCAL"_
> mergetool
> file: uc.exe
> args: _-B -b -t "$REMOTE" "$LOCAL" -rom "$MERGED"_

However if these don't work, please consult with UltraCompare.
