### ISSUE TITLE
Select-all in commit pane can freezes application for large repo

### ISSUE THREAD

**Issue by diaconesq** [gitextensions/gitextensions#7469]
## Current behaviour
On a large repo (3+ years of work for 30+ full time contributors), hitting Ctrl-A in the main pane, then changing the viewing mode, freezes and hangs the app (killed it after 3 minutes)
See repro steps for details.

## Expected behaviour
The app should not freeze.

## Steps to reproduce

View current branch: click main pane, Ctrl-Shift-U
Select all: Ctrl-A
View all commits: Ctrl-Shift-A

=> hang

## Did this work in previous version of GitExtensions

Probably not

## Environment

- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
It appears to hang on <kbd>CTRL</kbd>+<kbd>A</kbd>

**Comment by pmiossec** [comment]
> It appears to hang on <kbd>CTRL</kbd>+<kbd>A</kbd>

Real question:  what purpose selecting all commits is useful for? I never used it in years... 

Shouldn't we remove this shortcut?

**Comment by RussKie** [comment]
I think what may be happening once <kbd>CTRL</kbd>+<kbd>A</kbd> is pressed, the app is trying to generate a diff between all of the selected commits. 




> Shouldn't we remove this shortcut?

I'm not sure we will be addressing the underlying issue. Instead of <kbd>CTRL</kbd>+<kbd>A</kbd> a user could select a significant number of commits using a keyboard/mouse, and get to the same state (that's if my hypothesis is correct).

Perhaps a different question could be - should we restrict a number of commits for a multi-commit doff?

**Comment by gerhardol** [comment]
> Shouldn't we remove this shortcut?

Yes, that serves no purpose

> Perhaps a different question could be - should we restrict a number of commits for a multi-commit diff?

Yes, many commits can be selected by accident using Shift-Click instead of Ctrl-Click.

I use this to compare "a couple" of commits but too many are not useful anyway.
This alternative could simply just calculate first-selected (including merge and combined) by default and let the user expand.
A quick fix is to just ignore over a limit, like other than first, second, third to selected (last).

**Comment by gerhardol** [comment]
Slightly OT but related to what we may want to see in Diff tab.
See also #4154 for base compare. (That could be automatic for two selected commits, whare base is not any of the selected.)

**Comment by gerhardol** [comment]
Suggest a simple fix: Limit to diff to two diffs (and maybe combined and base compare in addition).
Compare selected (last clicked) to first and second to last selected.

**Comment by mstv** [comment]
Though the context submenu `Copy to clipboard` makes meaningful use of multi-select.
We could ask for confirmation once if more than e.g. 100 commits are being selected.

**Comment by pmiossec** [comment]
Or just don't do the processing that slow down GE when more than 2 commits selected to only keep the possibility to copy to clipboard.

**Comment by gerhardol** [comment]
> Or just don't do the processing that slow down GE when more than 2 commits selected to only keep the possibility to copy to clipboard.

I was only referring to the diff tab.
