### ISSUE TITLE
View History Not working

### ISSUE THREAD

**Issue by FreezeBirth** [gitextensions/gitextensions#7503]
Results of "View History" option is exactly same as git commit history <log>.

**Comment by FreezeBirth** [comment]
On pressing View History: Exact change history of the file is not listed.

**Comment by pmiossec** [comment]
Could you follow the issue template and give more information because, like that, your issue don't help us understand the problem.

Could you explain what is the exact problem except just "Gitextensions don' t do the job and should do it"? Provide screenshots of expected and actual results? Which version of git and gitextensions? 

Even better, could you provide a public repository with the problem?
