### ISSUE TITLE
Remove 2-way merge resolve

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#7550]
## Feature description

Removing 2-way merge is the functionality change, needed to clean up some messy code and to support #5919.

GE sets the path and cmd for mergetool and difftool in settings, similar to what will be done with git-config without any manipulation.

GE always call git-difftool without manipulation of arguments.

GE has two ways to invoke mergetool form FormResolveConflicts:
![image](https://user-images.githubusercontent.com/6248932/71326708-33a60480-24ff-11ea-984a-0bce818968fe.png)

 a. "Open in <tool>", context menues etc will get git config arguments and manipulate them
 b. "Start mergetool" will call git-mergetool

a. Used to have a lot of special handling, especially involving kdiff3 that was distributed with GE in 2.x. Most of the special handling was removed in #7009 (3.3), a few special cases that could not be understood was removed in #7044. The only that remains that I see is special handling for 2-way merge manipulation, hardcoded for kdiff3 and diffmerge (as well as for beyondcompare3, araxis, tortoisemerge, toolnames no longer used in GE 4). There are a few GitHub issues when applying the 2-way fixes, at least beyond compare seem to work better without this fix #1844.

The 2-way merge could be fixed by hardcoding for the tools where this is relevant (and possibly make this configurable but I would like to avoid that). However, I propose the explicit 2-way merge is removed together with all explicit handling of .cmd, .path.

As arguments can be changed in GE GUI (they could always be changed from the commandline), it is riskier to allow this command now, manipulations may fail.

## Environment

- GitExtensions version: 4.0
- GIT version: all
- OS version: n/a
- .NET version: n/a

**Comment by LightCC** [comment]
A case where the resolve window and launching from "Open in" appears to be providing some strange behavior.

## Specific to this suggestion

I currently am using VS Code for my diff and mergetool, and GE will launch the diffs fine, but for merging, it causes code to open an extra editor window that is empty, but called "code":
<img width="498" alt="image" src="https://user-images.githubusercontent.com/19731713/145498925-7c10acc0-f88b-4ce2-991b-95f50087a97c.png">

My `.gitconfig` relevant section is:
```
[mergetool "vscode"]
	cmd = code -n --wait $MERGED
	path = d:/apps/vscode/Code.exe
```

which, again, the path statement is only here because Git Ext forces me to have it there even to open up this window (see next section).

## Issues opening the resolve window in the first place

Just to open the resolve window, an early change in the 3.x series started checking for proper Git configuration of a merge tool **to even let you open the window**. This is bogus because there is plenty of functionality in the resolution window that doesn't need a merge tool configured at all - for example, you can right-click and resolve conflicts by choosing ours or theirs completely without launching a merge tool.

But, more insidious, the check is bad - it requires me to have a "path" statement and to provide the full path to the executable, even if the executable is on the system path and will be launched correctly. i.e. I can launch successfully from the command-line with gitconfig, but GE still says I'm misconfigured.

I get that you don't want the program to just plain crash if there is a misconfiguration, but can't you catch the exception and handle it if it fails rather than baby-sitting the user with code that just might not know exactly what has to be configured and how for all diff/merge tools and system setups?

Beyond that, can't you at least put that code on the actual button(s) that would cause the merge tool to launch, rather than on the entire resolution window?

I logged an enhancement issue on this and was told something about I was thinking about it wrong. Sounded like someone trying to defend the way the change was designed rather than answering the actual use case I presented, but maybe that was just me.

**Comment by gerhardol** [comment]
For the first part open a separate issue. 
(vsix uses the GE command line interface, maybe some quoting?)

> The `path =` statement is only here because Git Ext forces me to have it there even to open up the resolution window (see next section). Fine, I can fix my config to match what GE wants after spending an hour+ figuring out what it wants (but isn't needed), but then I need to get my entire team to update their .gitconfig files as well (many not very good with git...).
> ## Issues opening the resolve window in the first place
> 
> Just to open the resolve window, an early change in the 3.x series started checking for proper Git configuration of a merge tool **to even let you open the window**. This is bogus because there is plenty of functionality in the resolution window that doesn't need a merge tool configured at all - for example, you can right-click and resolve conflicts by choosing ours or theirs completely without launching a merge tool.
> 
> But, more insidious, the check is bad - it requires me to have a "path" statement and to provide the full path to the executable, even if the executable is on the system path and will be launched correctly. i.e. I can launch successfully from the command-line with gitconfig, but GE still says I'm misconfigured.
> 
> I get that you don't want the program to just plain crash if there is a misconfiguration, but can't you catch the exception and handle it if it fails rather than baby-sitting the user with code that just might not know exactly what has to be configured and how for all diff/merge tools and system setups?
> 
> Beyond that, can't you at least put that code on the actual button(s) that would cause the merge tool to launch, rather than on the entire resolution window?
> 
> I logged an enhancement issue on this and was told something about I was thinking about it wrong. Sounded like someone trying to defend the way the change was designed rather than answering the actual use case I presented, but maybe that was just me.

The handling of mergetools were changed in 3.5. You do get a popup if the mergetool is not set but can use other features.
If path is not set, you cannot use the special handling but fall back to Git default handling.
So this is handled what I see.

Closing the original issue as I believe this is handled reasonable now.
