### ISSUE TITLE
[NBug] The given path's format is not supported.

### ISSUE THREAD

**Issue by studentmain** [gitextensions/gitextensions#7660]
## Current behaviour

Program throw exception when viewing file name contain ':'

![图片](https://user-images.githubusercontent.com/17123090/72696988-2435cd80-3b36-11ea-8a64-89f45a9f33fa.png)

## Expected behaviour

Not throw exception, if possible, show diff.

## Steps to reproduce

1. commit a file name contains ':' (do it on Linux)
2. view it's diff (on Windows)

Here's an example repo
[test.tar.gz](https://github.com/gitextensions/gitextensions/files/4084334/test.tar.gz)

## Error Detail

```
System.NotSupportedException: 不支持给定路径的格式。
   在 System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   在 System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   在 GitUI.Editor.FileViewer.ViewItemAsync(String fileName, Func`1 getImage, Func`1 getFileText, Func`1 getSubmoduleText, Action openWithDifftool)
   在 GitUI.Editor.FileViewer.ViewGitItemAsync(String fileName, ObjectId objectId, Action openWithDifftool)
   在 GitUI.CommandsDialogs.RevisionDiffControl.<ShowSelectedFileDiffAsync>d__35.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 GitUI.CommandsDialogs.RevisionDiffControl.<DiffFiles_SelectedIndexChanged>d__36.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 Microsoft.VisualStudio.Threading.JoinableTaskFactory.SingleExecuteProtector.TryExecute()
```

## Additional information

Throw when file name contains ':', you can create such file under Linux.

git command works on such file. 

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.22.0.windows.1 (recommended: 2.23.0 or later)
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4075.0
- DPI 120dpi (125% scaling)

**Comment by gerhardol** [comment]
A file with : cannot be stored in a Windows filesystem, so GE could only possibly work with barebone repos. So not much functionality will work with files like this

This specific problem can be fixed, it tries to get the full path for a Git item for added items, it is OK to view items in file tree and I believe changed files are OK too.
FileViewer.cs:777 ViewItemAsync()
(This is also incorrect for submodules, I have added some TODO, removed submodules will not be viewed correctly too - minor issue.)

Adding a FullPathResolver.TryResolve() method could resolve this problem here, or just remove the file system check.
