### ISSUE TITLE
new UI option for Rebase window - "ignore-date"

### ISSUE THREAD

**Issue by itsho** [gitextensions/gitextensions#7708]
##  Feature description
1. add to the "rebase" window a new checkbox: "ignore-date"
2. add the same option to the context menu on a commit ("Rebase current branch on ...")

When checked/selected, it will apply "git rebase --ignore-date" which will change the dates of the rebased commits

also, take into account that this flag is incompatible with some other flags - [see here](https://git-scm.com/docs/git-rebase#_incompatible_options)
also, see [this question in StackOverflow](https://stackoverflow.com/questions/1579643/change-timestamps-while-rebasing-git-branch)

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.25.0.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.8.3928.0
- DPI 96dpi (no scaling)

**Comment by gtisdelle** [comment]
Hi. I'm currently working on this feature.

One complication with its incompatibility with both `--autosquash` and `--no-autosquash` is that the current argument builder explicitly disables autosquash using `-c rebase.autoSquash=false`. This means that whenever there is an interactive commit specified, either `--autosquash` or `--no-autosquash` is made part of the argument.

I can add this feature in a way that it only works when autosquash is not selected and have the `--no-autosquash` argument be implicit since it seems to be redundant. I can also disable the ignore date option for interactive commits entirely.

**Comment by itsho** [comment]
I'll be satisfied with whatever you see fit.
Thank you!

**Comment by pmiossec** [comment]
>I can also disable the ignore date option for interactive commits entirely.

I think it's the good way to handle it and also the opposite: disable interactive rebase when 'ignore date' is checked.

If you could also add a tooltip to explain what it does and  support `--committer-date-is-author-date` which is the opposite option, it will be perfect!

PS: You could do an early PR, even if your work is not finished to discuss about it. Just prefix the title with "WIP:" so that we know.

**Comment by mstv** [comment]
So this requires a second rebase: first interactive, then with `--ignore-date` in order to cleanup the commit dates. Have I got I right?

**Comment by gtisdelle** [comment]
@mstv Yes. That's the most common flow. More generally, it sets the author date to the committer date. Those dates most often come out of sync when a rebase (especially an interactive one) is performed which causes the committer date to update to the time of the rebase. But the committer dates can be changed independently of the author dates in other ways as well. A cherry-pick, for example.

Basically the way that this is used is:

do something that messes up committer times -> make the author times the committer times using `rebase --ignore-date`

**Comment by ADTC** [comment]
I found the wordings "Ignore date" and "Committer date is author date" to be confusing actually, but I understand that it reflects the wording used in the command line options. But the tooltips are confusing too, as they are merely opposing ideas without much clarity. I suggest that the tooltips should be as follows:

_"Ignore date" tooltip:_ "Original author dates are discarded. New author dates are set to be the same as commit dates (system date and time). Commits will appear fresh in history."

_"Committer date is author date" tooltip:_ "Commit dates are set to be the same as original author dates (instead of system date and time). Commits may appear back-dated in history."

**Comment by gerhardol** [comment]
> I found the wordings "Ignore date" and "Committer date is author date" to be confusing actually, but I understand that it reflects the wording used in the command line options. But the tooltips are confusing too, as they are merely opposing ideas without much clarity. I suggest that the tooltips should be as follows:

GE tries to use the same description as Git itself, to _not_ have to describe everything. Tooltips could be clarified.
Can you make a PR?
Adjusted the suggestions below, trying to shorten the description.

> _"Ignore date" tooltip:_ "Set the author date to the current date (same as commit date), ignoring the original author date."
> _"Committer date is author date" tooltip:_ "Commit date is set to the original author date (instead of current date)."
