### ISSUE TITLE
Some plugins are broken because they fails to load there dependencies

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#7735]
## Current behaviour

* Plugins with assemblies dependencies which are not in the main folder of GitExtensions are broken.
* A lot of `FileNotFoundException`
* Consequently all the plugins are slow to load and some plugins are broken (AppVeyor CI, Azure DevOps CI, GitHub, ....)

It seems that the assemblies are not loaded from the good folder.

## Expected behaviour

Plugins loading without problems

## Steps to reproduce

1. Delete the `artifacts` folder
2. Compile and Run
3. Open GitExtensions repository
4. CI integration with AppVeyor is not visible on commits (silent failed)
5. Copy `NewtonSoft` dll from a plugin subfolder and paste it next to `GitExtensions.exe`
6. Restart the application and see CI integration with AppVeyor displayed.

## Screenshots

GitHub plugin not working (it seems to be due to restsharp that failed to load):
![image](https://user-images.githubusercontent.com/460196/73938269-30b47700-48e7-11ea-8f15-3d52bbc932b5.png)

## Did this work in previous version of GitExtensions

It seems to be due to changes done with Arcade build

## Environment

- GitExtensions version: `master` branch

## Diagnostics

* Copying the`NewtonSoft` dll in Gitextensions folder fix some plugins (that only have this missing dependency). So it seems that the dependency is loaded from the wrong folder.
* **Recreating the old folder architecture (before Arcade build) by copying the content of each plugins directly in the `Plugin` folder fix all the plugins.** but that doesn't help for the debugging which is still broken...

**Comment by pmiossec** [comment]
Workaround :
In all the `Directory.Build.props` files in the  `Plugins` folder replace:
 `<BaseOutputPath>$([System.IO.Path]::GetFullPath('$(ArtifactsBinDir)GitExtensions\$(Configuration)\$(TargetFramework)\Plugins\$(OutDirName)'))</BaseOutputPath>`

By

`<BaseOutputPath>$([System.IO.Path]::GetFullPath('$(ArtifactsBinDir)GitExtensions\$(Configuration)\$(TargetFramework)\Plugins'))</BaseOutputPath>`

to recreate the same output folder architecture than before the arcade build.

**Comment by RussKie** [comment]
I think there are few issues:
- each plugin must specify binding redirect policy correctly. AppVeyor plugin doesn't specify it unlike few others. This is a minor issue at this stage; and
- the `AppDomain` must know where to probe for assemblies. Right now it is set to `Plugins` folder, and that's why it works if you copy all plugins there.

However it is problematic to use `Plugins` folder as it leads to file locks and race conditions during the build, as projects are build concurrently, and they use same references (e.g. Newtonsoft.Json.dll). These contentions leads to build failures.
Besides each plugin should live in its own dedicated folder, whether it is bundled with the app or installed via the Plugin Manager.

I'll work on it.
