### ISSUE TITLE
Microsoft Defender SmartScreen warning against GitExtensions MSI installer

### ISSUE THREAD

**Issue by vatsan-madhavan** [gitextensions/gitextensions#7738]
## Current behaviour

The GitExtensions MSI installer behaves as if it were unsigned, or as if it is being identified by Windows as an untrustworthy application. 

## Expected behaviour

The installer should download and launch seamlessly. 

## Steps to reproduce

- Launch GitExtensions 
  - Application suggests that an update is available. Accept to download
  - Launches default browser (=Edge 81.0.410.1 (Official build) dev (64-bit)) to download the latest MSI installer
  - Edge warns that the installer is blocked because _'it could harm your device'_
  - Override the warning (select _'Keep'_) and launch the MSI
  - Edge warns that ** Microsoft Defender SmartScreen** reports the installer as being _'not commonly downloaded or is not signed by its publisher'_

![image](https://user-images.githubusercontent.com/20246435/74054335-b0e3e680-4992-11ea-8ef2-0ac6fc1d1f2d.png)

![image](https://user-images.githubusercontent.com/20246435/74054412-e12b8500-4992-11ea-88ab-3f516a8ad272.png)

![image](https://user-images.githubusercontent.com/20246435/74054525-1637d780-4993-11ea-94b8-e86d6b6bce53.png)

This final warning can be overridden by selecting _'Show more'_ followed by _'Keep anyway'_

![image](https://user-images.githubusercontent.com/20246435/74054665-467f7600-4993-11ea-9bb0-3bd494e3283f.png)

After this, the MSI completes downloading. 

Here is a screenshot from **_edge://downloads_**. The first item shows the state before overcoming these warnings, the 2nd item shows the state after all the warnings have been overcome. 

![image](https://user-images.githubusercontent.com/20246435/74054786-847c9a00-4993-11ea-9429-2445b37fca91.png)

Launching the MSI that was successfully downloaded pops up yet another **Windows Defender SmartScreen** warning: 

![image](https://user-images.githubusercontent.com/20246435/74054847-a4ac5900-4993-11ea-9a87-c6ce52ecc7b0.png)

This too can be overcome by selecting _'More Info'_, followed by _'Run anyway'_. 

![image](https://user-images.githubusercontent.com/20246435/74054915-cb6a8f80-4993-11ea-849a-2cb82e1584b4.png)

![image](https://user-images.githubusercontent.com/20246435/74054937-da514200-4993-11ea-97ee-30238334b1c6.png)

I don't see anything obviously wrong with the [certificate](https://github.com/gitextensions/gitextensions/files/4172368/GitExtensions.cer.zip) used to sign the installer. 

[GitExtensions.cer.zip](https://github.com/gitextensions/gitextensions/files/4172368/GitExtensions.cer.zip)

## Did this work in previous version of GitExtensions

Not sure.

## Environment

- GitExtensions version: 
  - MSI (being downloaded): version GitExtensions-3.3.1.7897
  - Currently installed: 
    - Git Extensions 3.1.1.6049
    - Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
    - Git 2.25.0.windows.1
    - Microsoft Windows NT 10.0.19561.0
    - .NET Framework 4.8.4084.0
    - DPI 192dpi (200% scaling)

After typing this up I realized this is similar to #7705. I'm submitting it anyway since my report is a bit more detailed and outlines other problematic steps during installation.

**Comment by gerhardol** [comment]
The SmartScreen is based on trust, that has to be built before SmartScreen allows it. The previous certificate expired after a year, the new certificate (3 years this time) was new in 3.3 and it takes some time before the reputation is restored again. There is nothing much that can be done right now what I know. 

The GE certificates are provided by https://about.signpath.io/? for free (thanks), three years is the maximum they offer for open source projects. Longer time certificates will cost a lot.

**Comment by RussKie** [comment]
Having ~90K downloads I'd think we have the same order of magnitude of installs. So the app (and the cert) should be trusted by now.
This is a second report in a month, after months of no complaints.

@stefan-wenig do you have any thoughts on this?

**Comment by stefan-wenig** [comment]
There's nothing wrong with your certificate, that's how SmartScreen works. Here's some background: https://about.signpath.io/code-signing/windows-platform/#microsoft-smartscreen
Unfortunately that's all we have, as Microsoft is kind of secretive about it.

Are the 90K downloads with the new certificate already? That would be strange, but the algorithm/criteria is not published. It didn't take long with the previous certificate though. 

Just to make sure: has this warning ever *not* appeared for binaries signed with your new certificate? That would indicate that SmartScreen thinks there's something wrong with it, but "not signed or not commonly dowloaded" seems to indicate otherwise.

A few clarifications though:
* Your current certificate will expire in November. It was issued literally days before we managed to get 3 years certificates. 
* So you have a choice here: I can get you a new 3-year-certificate, but using this would start without the reputation your new certificate has already accumulated. You might be minutes away from getting rid of the warning, there's no way to tell. Or you keep it and have the same issue in November.
* @RussKie see our mail conversation around December 1.
* The recommended way to get rid of this is Extended Validation certificates. They are more expensive and not available to individuals. We hope to some day be able to provide these to high-reputation OSS projects and/or for renewed certificates. But unfortunately not yet.

**Comment by RussKie** [comment]
@vatsan-madhavan has reached out to the SmartScreen team (perks of working for MS 😏), and they confirmed the reputation has built up, and now it should be all good.
Thank you all involved!

Closing for now.

**Comment by AdminUser0** [comment]
Can anyone post some statistics about how many downloads you need in order to get "good" reputation?
