### ISSUE TITLE
Show branch name in recent repos drop down

### ISSUE THREAD

**Issue by joergpichler** [gitextensions/gitextensions#7882]
I am working on a big project and have the same repo multiple times on my developer machine. I am working on different branches in parallel. In order to make it easier to track in which repo which branch is current checked out it would make sense to (optionally) show the branch name in the recent repos drop down menu.

If you want to check it out I have a branch ready in my fork of gitextensions.

**Comment by gerhardol** [comment]
The current workflow is to Close Browse and go to Dashboard, so same number of clicks
But I would find this useful, some subrepos I work with are cloned in about 50 clones on my work computer and it is hard to remember which superrepo I worked on.
There may be objections if the menu is too cluttered though and GE already have too many options.

I suggest that you open a PR for this, to possibly get comments. A preliminary version not ready for a review to your own repo with a link here and more or less final to gitextensions with WIP in the title.

**Comment by vbjay** [comment]
Read up on worktrees.

**Comment by gerhardol** [comment]
> Read up on worktrees.

Still you want to know what worktree 'clone' that uses a specific branch
For the submodule in worktree scenario, the submodule is unfortunately always a separate repo

**Comment by joergpichler** [comment]
I created a PR here https://github.com/gitextensions/gitextensions/pull/7883

**Comment by gerhardol** [comment]
Closed with #7883, even if there are renewed discussions after the merge

**Comment by RussKie** [comment]
I just realised that we shouldn't have used "[ ]" because it is inconsistent with the existing formatting of branches. We based it off the submodules, but it is submodules that should have been fixed in the first place (because they came later).

We use "( )" in the following places:
* the title
  ![image](https://user-images.githubusercontent.com/4403806/78621626-63b6bf00-78c6-11ea-888d-5eeb5bd040a1.png)
* format "no branch" everywhere
  ![image](https://user-images.githubusercontent.com/4403806/78621724-9e205c00-78c6-11ea-8185-15f9dc895c53.png)
  ![image](https://user-images.githubusercontent.com/4403806/78621742-aa0c1e00-78c6-11ea-80f8-81cd5639dc45.png)
  ![image](https://user-images.githubusercontent.com/4403806/78621756-b3958600-78c6-11ea-82c8-c4140b7df5aa.png)


Secondly, we should also render "(no branch)" in the dropdown as well. Otherwise it looks very weird that some repos have branch information, and some don't.

**Comment by gerhardol** [comment]
I rather change the title, [no branch]

> Secondly, we should also render "(no branch)" in the dropdown as well. Otherwise it looks very weird that some repos have branch information, and some don't.

I am more confused by seeing this line, it is no point in seeing this information.

**Comment by RussKie** [comment]
> I am more confused by seeing this line, it is no point in seeing this information.

Disagree, it is very inconsistent and confusing - some entries have information, and some don't.
We show "(no branch)" in other parts of the UI too.

**Comment by gerhardol** [comment]
> We show "(no branch)" in other parts of the UI too.

I would rather remove "(no branch)"

If using () and displaying "(no branch)", how do a user see that "(no branch)" is not a branch?

**Comment by RussKie** [comment]
I have a PR incoming

**Comment by KvanTTT** [comment]
I guess it should be closed?

**Comment by vbjay** [comment]
Maybe headless?
