### ISSUE TITLE
"Cannot save settings" when closing multiple instances of GitExtensions

### ISSUE THREAD

**Issue by bansan85** [gitextensions/gitextensions#8006]
## Current behavior / Steps to reproduce

 * Open GitExtensions 10 times.
 * Close them all at the same time with "Close all windows" menu item from Windows taskbar.
 * Some instances will have "Cannot save settings" error message.

## Expected behavior

No error message.

## Screenshots

![Cannot_save_settings](https://user-images.githubusercontent.com/9248729/79642926-812a3980-81a0-11ea-8942-697597a481b1.png)

## Did this work in previous version of GitExtensions

I don't think so.

## Environment

- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.25.1.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4150.0
- DPI 96dpi (no scaling)

## Diagnostics

When Git Extensions closes, it saves his settings in a local file.
When there is multiple instances closed at the same time, one instance opens successfully the file and the others fail.

I suggest to had a small loop to retry after a small random time.
I already made a patch on my computer and this problem disappears. I can make a PR if you think it's a good solution.

It will not change the fact that only one instance of Git Extensions will have his settings saved, the settings of other instances will be override.

**Comment by gerhardol** [comment]
> It will not change the fact that only one instance of Git Extensions will have his settings saved, the settings of other instances will be override.

Maybe the popup should ask if the user wants to wait and overwrite or if prefer that changes are lost?

**Comment by bansan85** [comment]
@gerhardol 
The problem is that I have a project with lots of submodule (like boost.org). Every time I open one submodule, I open a new instance of Git Extensions. After an hour, I may have 20 instances of Git Extensions.
When I close them all together, I may have 15 MessageBox. This is really boring.

If I close Git Extensions instance one by one, only the settings of the last instance will be kept without any warning message. So I think asking a question will be more annoying than useful.

**Comment by gerhardol** [comment]
The answer could be remembered though (like other confirmations in GE), then you can set your behavior once.

**Comment by bansan85** [comment]
> The answer could be remembered though (like other confirmations in GE), then you can set your behavior once.

I don't really understand what you mean.

So you mean that GE should write only changed settings ? Instead of always writing all settings at every exit ?
Or do you mean the popup could have a button like "Ignore" then, with a single validation, all GE instances with this popup will close and not save settings ?

**Comment by gerhardol** [comment]
Like these confirmations

![image](https://user-images.githubusercontent.com/6248932/79667194-39161180-81b6-11ea-901f-5116c44b2099.png)

**Comment by bansan85** [comment]
Sure. I can make a try.

**Comment by RussKie** [comment]
Yes, we had been haunted with this problem for many years now.
The problem is that some settings are not saved immediately, and need to be saved upon save. To start with, I propose to review what changes are actually needed to be save upon exit.

Few days ago I discovered we have `SettingsPageBase` has a setting `IsInstantSavePage`, and some page are not instant save.
`AppSettings` should be persisted when they change too.

**Comment by gerhardol** [comment]
> AppSettings should be persisted when they change too.

This will still cause overwritten changes, as all settings are written to the file when saving so it depends on when the settings were read from storage (not only the global settings file).

**Comment by RussKie** [comment]
Equally AppSettings should be reloaded when it is detected config file has changed.

**Comment by mstv** [comment]
> When I think about this area, I have the following problems in mind:
> 1. Whenever the Settings dialog is opened it should read the latest settings available, so that when the dialog is closed with [OK] button the settings are up-to-date. 
This operation is the "best we can do", because if there is another instance of the app modifies the settings whilst the Settings dialog is opened in the current instance, the changes from another instance will be overwritten. This is a pure user-error scenario, and I don't believe we have to try to address it.

fully agree

> 2. Changes in the Settings dialog must be cancellable, i.e., if the dialog is dismissed (i.e., neither [OK] or [Apply] buttons clicked) then no changes should be written to the file.
I _believe_ this is the case now for all pages except for `ChecklistSettingsPage`:
https://github.com/gitextensions/gitextensions/blob/ad6671df6b114f49759e5dc17a69ffd4c54a8803/GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs#L153

agree, have not checked

> 3. Any other settings configurable outside of the Settings dialog (e.g., Show Current Branch) must be persisted immediately.
I _believe_ this is how the app is working now (though I haven't formally verified it).
https://github.com/gitextensions/gitextensions/blob/ad6671df6b114f49759e5dc17a69ffd4c54a8803/GitCommands/Settings/SettingsCache.cs#L119-L133

partially agree: There are temporary view settings which must not be applied to other running instances, e.g.
- DiffViewer: `Whitespace`, `Entire File`
- LeftPanel: display of categories like `Tags`, `Submodules`
- RevisionGrid: `Show current branch only` etc.

Most of those are stored on exit only - on purpose.

> 4. The config needs to be reloaded whenever the settings changed.

agree

This seems to work for (per-repo) revision links but not for user scripts.

> I _believe_ this is how the app is working now too, as least for some settings - if I apply "Show Current Branch" filter in one instance, and refresh another instance the filter is applied there too.

That's an example for unexpected UX, which should be avoided.

> I don't think we must persist settings on the app exit, and this IMO is the ultimate fix for https://github.com/gitextensions/gitextensions/issues/10016 and other related issues.
https://github.com/gitextensions/gitextensions/blob/ad6671df6b114f49759e5dc17a69ffd4c54a8803/GitUI/CommandsDialogs/FormBrowse.cs#L1435-L1438

Yes, the settings *is* a Pandora box.
Perhaps we must split the settings.
Alternatively, we could ignore the "view settings" on reload during runtime. Though then the last change of the view settings will be used on restart but not those from the last instance closed. Unexpected UX as well.

I prefer a set of default view settings for the DiffViewer and for the RevisionGrid. (Temporary) changes should not be stored. Rather store them on explicit request.

**Comment by RussKie** [comment]
Over the years I have made several attempts to refactor the appsettings, e.g. https://github.com/gitextensions/gitextensions/compare/master...RussKie:gitextensions:refactor_AppSettings. One of the things that always bothered me was/is the fact that AppSettings is a static type, meaning any changes affect the whole running app and all tests. This leads to issues where we open the "new" history window (based on the FormBrowse) and then "blame" settings is turned on affecting all other views....

Thinking about it, there are three types of settings contained in AppSettings types (this is obviously very rough and non-scientific gradation):
- system settings/configuration - those that the user has no control over - e.g., the app name, where it's located, etc.
- application settings - those are likely get configured once - e.g., git-related configs, diff/merge tools, etc.
- user/repo-specific settings - those that may get changed multiple times while the application is running.


(Thinking out loud) Perhaps, we should employ MEF/DI for these, e.g., no dialogs/types have direct access to AppSettings. Instead, to get read-only settings a type must request the service `ManagedExtensibility.GetExport<ISystemSettings>()`, `ManagedExtensibility.GetExport<IApplicationSettings>()`, etc. And to modify the settings request different "writer"-services `ManagedExtensibility.GetExport<IApplicationSettingsWriter>()`, etc. This way we'd have a more granular control over when and how the settings changed.

**Comment by mstv** [comment]
View settings are another category. They should apply to a single instance / view regardless of whether another one shows the same repo.
