### ISSUE TITLE
In the mergetool "Theirs" and "Mine" are swapped

### ISSUE THREAD

**Issue by vdboor** [gitextensions/gitextensions#82]
When a conflict occurs after a `stash pop` or `pull --rebase`, the "theirs" and "mine" views are swapped in the merge tool.

I'm using GitExtensions 1.93, msysgit 1.7.0.2 and TortoiseMerge from TortoiseGit.

**Comment by ensisnoctis** [comment]
How about creating a checkbox in Options that would swap the local and remote so that "mine (local)" would always mean "volatile code that truly is not pushed anywhere"?

I mean, it is VERY FRIGHTENING to see "delete theirs (remote)" prompt and be aware that ~50% of the times (depending on how often you use rebase vs other merge commands) these are MY (LOCAL) changes that I can accidentally get rid of. I understand GitExtensions is sticking to the _technically correct_ naming, but please think about creating an option for alternative, _user natural_ naming, so that I could get to trust the application!

**Comment by mstv** [comment]
(I guess it depends on the direction of the merge.)
One can avoid losing local changes easily: Just commit your changes into your local branch and then do the merge as a separate step. So you can restore everything you lost by mistake. And you can review/compare the merge result with both parents.

**Comment by illfated** [comment]
That is how I thought everyone does it when it comes to merging and pushing content. Commit locally, then push the new commit to the remote, then create a PR or update an existing PR.

**Comment by RussKie** [comment]
I hear you, it is somewhat unfortunate git has chosen/defined the lingo. And now we're stuck with it.

In theory we could re-define the terminology but by doing this we will put ourselves at odds with the git community (that includes git, users, diff tools, dev tools etc).

Let's consider a scenario where a user is doing a rebase or a merge and Git Extensions is showing a custom terminology. Next the user is launching a diff tool and the tool is showing "remote/base/local" terminology. 
Would you not think the user will have a mental overload and a massive confusion?

**Comment by gerhardol** [comment]
GE could present the branch names too, see #6582.
Not trivial though, requires some restructuring.

**Comment by RussKie** [comment]
I hear you, it is somewhat unfortunate git has chosen/defined the lingo.
And now we're stuck with it.

In theory we could re-define the terminology but by doing this we will put
ourselves at odds with the git community (that includes git, users, diff
tools, dev tools etc).

Let's consider a scenario where a user is doing a rebase or a merge and Git
Extensions is showing a custom terminology. Next the user is launching a
diff tool and the tool is showing "remote/base/local" terminology.
Would you not think the user will have a mental overload and a massive
confusion?
