### ISSUE TITLE
Commit dialog shows a "zero width no-break space" as non-printing character

### ISSUE THREAD

**Issue by AlexanderIljinUTS** [gitextensions/gitextensions#8317]
## Feature description
Sometimes files contain a "zero width no-break space" (0xFEFF). Usualy it is placed in the beginning of a file as BOM. Rarely it could be in the middle of the file, probably due of some errors.

Currently the commit dialog highlight any changed lines, even if changes are adding or removing of "zero width no-break space" only. But it is not obvious what the reason of the highligthing. It seams like removing and adding the same character.

"Show nonprinting characters" toggle also does not reveal this character.

As well as "Ignore changes in amount whitespace" toggle does not produce any effect on diff window.

So, I propose to show "zero width no-break space" as nontpinted character list, and adopt general functions of commit dialog for working with this new character.

## Environment

- Git Extensions 3.4.2.9737
- Build 082cfd97d09c47346638b1873f5c8cf6ed139382
- Git 2.22.0.windows.1 (recommended: 2.25.1 or later)
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4084.0
- DPI 96dpi (no scaling)

**Comment by ajilani** [comment]
I work with C# files in Visual Studio, which saves by default as UTF-BOM. I run into this issue whenever I remove the first line in a file (usually a `using` statement). Then the first line shows as deleted, but the second line also shows as changed. That behavior actually makes some sort of sense, because the second (now first) line did gain a BOM at the beginning. But I agree with this feature request, in that I think that the second line should show as unchanged in this case.
![image](https://user-images.githubusercontent.com/7442704/123146330-0755a600-d45e-11eb-8b6f-2b3fb0f403bf.png)

**Comment by gerhardol** [comment]
> I work with C# files in Visual Studio, which saves by default as UTF-BOM. I run into this issue whenever I remove the first line in a file (usually a `using` statement). Then the first line shows as deleted, but the second line also shows as changed. That behavior actually makes some sort of sense, because the second (now first) line did gain a BOM at the beginning. But I agree with this feature request, in that I think that the second line should show as unchanged in this case.

The diff is what git-diff supplies, GE tries to mark the changed part of the lines.
I do not think we want to manipulate the diff output.

The non-printed character could be displayed, but that would make copy and line patching more complex (when the character have to be removed again).

**Comment by vbjay** [comment]
Use the toolbar in diff.
