### ISSUE TITLE
Araxis does not show up in Mergetool/Difftool dropdown box

### ISSUE THREAD

**Issue by joncastillo** [gitextensions/gitextensions#8351]
## Current behaviour

Araxis is not an option in Mergetool / Difftool. It used to be there six months ago but I can't recall the gitextension version number.

## Expected behaviour
Araxis shows up in the mergetool/difftool dropdown boxes.

## Steps to reproduce

Git Extensions->tools->settings->Git->config->MergeTool
Git Extensions->tools->settings->Git->config->DiffTool

## Screenshots

![noaraxis](https://user-images.githubusercontent.com/9458979/88242693-4cfb7300-ccd1-11ea-924e-09f37c82da1b.PNG)

## Did this work in previous version of GitExtensions

Yes, i cannot recall the version #.

## Environment

- Git Extensions 3.4.2.9737
- Build 082cfd97d09c47346638b1873f5c8cf6ed139382
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

## Diagnostics

1. removal of gitextenision data in users/xx/appdata/local and users/xx/appdata/LocalRoaming
2. reinstallation of git extensions and araxis merge.

**Comment by gerhardol** [comment]
Araxis was predefined in 3.3 and earlier. However, the definition was obsolete (since 2010 or so) and there were no reports about it so the preconfiguration was dropped when the internal handling was redesigned.

You can add a diff/merge tool manually in the settings in 3.4 as well as add tools from the command line (as you had to do before).

**Comment by pmiossec** [comment]
I could add that it should be really easy to add back the support of Araxis.

You just have to add a file looking like that https://github.com/gitextensions/gitextensions/blob/master/GitCommands/DiffMergeTools/P4Merge.cs with the good options.

I highly encourage you to do it, **test it** and create a PR.

Eventually, you could provide the good information and we can do the PR for you...

**Comment by joncastillo** [comment]
Sorry for the late response. I haven't logged on to github for a while and didn't notice your replies.

The following settings used to work:
![image](https://user-images.githubusercontent.com/9458979/90097930-6ea0c500-dd7a-11ea-9f33-c927c1bb0db6.png)

Now I have to edit it this way, but it doesn't appear correct. More like a hack just to get it working:
![image](https://user-images.githubusercontent.com/9458979/90098144-ea9b0d00-dd7a-11ea-8e7f-04db5bd08a1e.png)

**Comment by gerhardol** [comment]
Araxis help mostly works:
https://www.araxis.com/merge/documentation-windows/integrating-with-other-applications.en#GitExtensions

Just type 'araxis' in the dropdown to configure the tool instead

The Mergetool command needs path too.

There is a minor benefit to type 'araxis' over other spellings, as this tool is known by Git and command is not needed. GE requires this info though, partly due to some extra processing, partly due to that there is no reliable way to get the supported parameters for a tool.

**Comment by joncastillo** [comment]
i have already tried these settings from araxis help. they don’t work with the current git extensions. The settings i was using were from stackoverflow.

but i haven’t tried typing ‘araxis’ in the dropdown box. will check that.

**Comment by hoborm** [comment]
This behaviour was changed in this commit: [36863f85d23606a2d2bca2adc9257011c9c28160 ](https://github.com/gitextensions/gitextensions/commit/36863f85d23606a2d2bca2adc9257011c9c28160). I'll try and fix this issue.
