### ISSUE TITLE
View history

### ISSUE THREAD

**Issue by raptoravis** [gitextensions/gitextensions#8354]
## Current behaviour
View history for any file, crash 

## Expected behaviour

to show the file log

## Steps to reproduce

1. select any file 
1. right mouse and select `View history`
1. crash

## Screenshots
![image](https://user-images.githubusercontent.com/4395022/88369390-7fd16400-cdc2-11ea-970f-d3d80e58c3b0.png)

## Did this work in previous version of GitExtensions

unclear, as I began using GE recently.

## Environment

- GitExtensions version:
- GIT version: 2.27
- OS version:  windows 10
- .NET version: 
4.6.1

**Comment by raptoravis** [comment]
sorry, it is my fault

**Comment by pmiossec** [comment]
>sorry, it is my fault

We are still interested by some explanation because a crash is not "normal" and that could help other users having the same behavior.
So please give us more information.

**Comment by pmiossec** [comment]
Oh and for the future, instead of creating the issue manually when you get the GitExtensions error report dialog, please, just click on the "Send and Quit" button that will fill all the datas and give us more information like the very useful complete stacktrace.

It's easier for you and better for us ;)
