### ISSUE TITLE
HTTP authentication support

### ISSUE THREAD

**Issue by occ** [gitextensions/gitextensions#85]
When I try to run a pull or fetch on a authentication-enabled http repository, the fetch dialog does not ask for username/password, and keeps waiting.

Also- it would be nice if Git Extensions could save the credentials.

**Comment by jetamartin** [comment]
Good God this bug has been around since 2010 and it's still not fixed????????? I just downloaded the latest version of Cygwin on Feb 7, 2015 and it's still a problem!

**Comment by kbilsted** [comment]
:+1:  please fix :-)

**Comment by KindDragon** [comment]
It's fixed. Git should display window to enter login/password.

**Comment by kbilsted** [comment]
@KindDragon  not when you are using 2-factor security. But it works when using `git-credential-winstore.exe` (on Windows). Perhaps the credential manager should come bundled with GitExtensions? It works out of the box with the Github desktop application (but I prefer GitExtensions due to all the shortcuts and proper display of the graph).

**Comment by KindDragon** [comment]
> But it works when using git-credential-winstore.exe (on Windows).
> 
> Perhaps the credential manager should come bundled with GitExtensions?

It's already bundled in Complete installer
