### ISSUE TITLE
Ability to rename a tag

### ISSUE THREAD

**Issue by francoas** [gitextensions/gitextensions#8579]
## Feature description

It would be convenient a command to rename (locally and remotely) a tag
At the moment it is possible to do it with a sequence of commands
- creating the new one (maybe as an alias of the old)
- deleting the old 
etc

Could be nice a command that implements all of it in the best way

For reference:

https://stackoverflow.com/questions/1028649/how-do-you-rename-a-git-tag

https://stackoverflow.com/questions/24244908/change-naming-convention-of-tags-inside-a-git-repository

**Comment by RussKie** [comment]
Use a script instead?
I can't really see this being a mainstream use case.

**Comment by francoas** [comment]
> Use a script instead? I can't really see this being a mainstream use case.

Never claimed it being a mainstream...
It said simply it would be a “convenient” contestual menu comand over the tag. Insert, delete, rename.

**Comment by vbjay** [comment]
Exactly what scripts are for.

**Comment by RussKie** [comment]
Adding a niche feature in reality means wasted effort and bloated code.
Please consider using a script.

**Comment by francoas** [comment]
Oook. So, be it a script. 
Anyway I wouldn’t consider it so “niche”
as you can see from the numerous results in a simple google “git rename tag”. 
Sometimes this little “efforts” are not a waste of time, but what make a software better and more user friendly than others and give the feeling of a better U/X.  
In my personal developments I always make efforts even to save a customer a single click. And it’s never “wasted” but always appreciated. It’s a matter of... details.

**Comment by pmiossec** [comment]
@francoas

I will give you another point of view that I think is also shared by @RussKie and could explain his answer...

A tag is something that is intended to be immutable and **not change** otherwise you must create and use a branch.
I think that's on purpose that git doesn't propose a built-in feature to update a tag.
Otherwise it will be as easy as a branch to change it and that's the opposite of the goal of using tags where you don't want to have it changed by error.

So the only way to do it with git is to delete the tag before (and already thank git to be able to do it for something that should be immutable 😉 ) and recreate it with the changes you want to do it.

Having said that, I'm not sure that's the job of GitExtensions to change this behavior and let the user do easily something that must not be done or very rarely... 

>Please consider using a script.

@RussKie 
One day, I think we should state on how we talk about "script"s.
Because even me I'm not sure what you are proposing 😢 

A "shell script" ? or a ["GitExtension script"](https://git-extensions-documentation.readthedocs.io/en/release-3.4/settings.html#git-extensions-scripts) ?

It could even been done or combined with creating a git alias...

**Comment by vbjay** [comment]
Git extensions script.   Wouldn't be hard to do so. @pmiossec  is right. That is exactly why git manages tags the way it does. Tags are more markers for versions and important points in the commit history.

**Comment by francoas** [comment]
I understand all your points of view! Thank you for taking time to share them. I agree also that tags are important points in istory. But that's also a reason why it could be possible to change them if they were mispelled (for instance "V.3.1" instead of "V3.1"). After all even for the commit (more important and immutable than a tag) there is an AMEND option. ;) 
Thank guys.

**Comment by RussKie** [comment]
Good point Philippe, thanks for raising it.

In a context of GE "scripts" refer to GE scripts. Their implementation is
up to a user.
