### ISSUE TITLE
Git Extensions cpu usage on big repo

### ISSUE THREAD

**Issue by bplatypus** [gitextensions/gitextensions#8582]
hi!
Git Extensions takes ~42% of CPU, !PERMANENTLY!, when I open specific repositories (pretty big projects... but I would not say huge. I mean we have ~20000 commits on the repos I'm talking about)

Opening smaller repos is not a problem, CPU is loaded and then drops down.

Can I do something to avoid this? (+ it's only on my computer... my colleagues don't have this issue opening the same repo)

Windows 10
GIT 2.28
Git Extensions 3.4.3.9999

btw, changing the 'Limit number of commits that will be loaded at startup' from 100000 to smaller amount (tested 5000), doesn't change anything

Thanks for any help!

**Comment by RussKie** [comment]
Do a memdump and see what's chewing the cpu.

**Comment by gerhardol** [comment]
First, look at Git Command Log to see what Git commands that requires resources.

git-log can require resources also with limited loading.

On a big repo, git-status requires significant resources. This is used for the commit count on the commit button and for the virtual commits. GE has limits for often the command is started in the background (triggered by filesystem changes so nothing at idle) so less problem after start.
Actually, running git-status once in the foreground (like open commit form) will speed up the background run.

**Comment by bplatypus** [comment]
Hi thanks for the replies. I did a git command log & git log, nothing special...

Then I did a memory dump and opened it with WinDbg but I have really not clue what to look at

**Comment by RussKie** [comment]
Look for threads spawned from the app directly. There may be some clues as
to whats going on.

In the past there had been reports of massive perf issues caused by video
drivers (!), and obviously antivirus is a usual suspect too.
If you have the same hardware, worth comparing your OS, AV, drivers
configurations... Do you both run the same version of git?

**Comment by pmiossec** [comment]
@bplatypus 

>Git Extensions takes ~42% of CPU, !PERMANENTLY!,

and 

>On a big repo, git-status requires significant resources. 

As @gerhardol told you, that's no more the number of commits that count than the number of files in your working directory and also the size of the files git has to check of they have changed.
If you have some huge files that never change or very rarely, perhaps you could have a look at the "Assume unchanged" feature.

@gerhardol I have a theory for reducing git status resources requirements. It needs to be verified but I wanted to share it with you...

When i see (from [git status doc](https://git-scm.com/docs/git-status#_background_refresh)

> status computes the values for itself, but writing them out is just to save subsequent programs from repeating our computation

and from [--no-optional-lock patch](https://public-inbox.org/git/20170921043214.pyhdsrpy4omy54rm@sigill.intra.peff.net/)

>The big downside is that any work done in refreshing the index for such a call is lost when the process exits. So a background process  may end up re-hashing a changed file multiple times until the user runs a command that does an index refresh themselves.

I wonder if we could just trigger in the background a `git status` without the `--no-optional-lock` options from time to time and that will have the effect to speed up the `git status --no-optional-lock` or use less resources.

I imagine that a good time to do it would be when the previous `git status --no-optional-lock` call discovered some changes over some summary changes that we could keep in memory. A simpler strategy could be to do it one time every x calls.

What do you think?

**Comment by gerhardol** [comment]
@pmiossec side discussion - should be a separate issue
So thrilled to make GitStatusMonitor more complicated again!
But once every time a repo is opened should be enough, after that the user is working with the repo and I see a minor risk that the index needs to be refreshed. A more complex suppression could be that if the user executes git-status (FormCommit), then the background call will not need to lock the indexes.

The problem is how to minimize the risk that the user is doing a change at the same time as the sync. Using file changed may well collide with user changes, but periodic is only done if there are no changes at all (then it has no big benefit anyway).
Maybe allowing lock the second time is good enough?

**Comment by gerhardol** [comment]
The load from GitStatusMonitor is reduced in 3.5.
(The sidediscussion about skipping --no-optional-locks the first update is in 3.5 too.)
