### ISSUE TITLE
It is not possible to resolve conflict

### ISSUE THREAD

**Issue by Yukooo** [gitextensions/gitextensions#8611]
When I try to resolve a conflict it says there are no files *.REMOTE, *.LOCAL, *.BASE, but in fact, they are there. I believe the issue is related to the "/" & "\" in the paths

![Capture](https://user-images.githubusercontent.com/4481418/98924841-9288b980-24d5-11eb-8a02-3186ad537e8f.JPG)

**Comment by RussKie** [comment]
I doubt it, but not totally ruling it out. Have you tried with "correct"
slashes?

You aren't hitting Windows path limits by any chance, are you?

**Comment by gerhardol** [comment]
The error message is from DiffMerge, not GE.

**Comment by vbjay** [comment]
Yep. Check your config to make sure it's passing values correctly.

**Comment by Yukooo** [comment]
Actually, I just click on the button "Open in diffmerge" and this pop-up appears, so I do not set any paths manually ... maybe it is also related to the Diffmerge ... I'll try to install another one

**Comment by gerhardol** [comment]
I can use DiffMerge both as diff and merge tools
The options look OK, maybe incorrect dashes?

However, the GE wizard to add the path is using the old executable name
(fixed in GE 3.2 cf6780981410c0a01d99374d1cfdfb04f6b852ac, regression in GE 3.4 36863f85d23606a2d2bca2adc9257011c9c28160)
Changed back in #8615
