### ISSUE TITLE
code highlight

### ISSUE THREAD

**Issue by lukaspupkalipinski** [gitextensions/gitextensions#8656]
Highlight the syntax if possible like in notpad++. See Example picture.
This is needed during reviewing an commit. see Problem picture.
It would also mean that the coloring need to be changed, so that the code highlight is visible.

Problem:
![image](https://user-images.githubusercontent.com/30108796/101030469-9e6a1780-3579-11eb-856f-156981f292b1.png)

Propose 1:
![image](https://user-images.githubusercontent.com/30108796/101029046-3a475380-3579-11eb-8993-65c9be058c43.png)

Propose 2:
![image](https://user-images.githubusercontent.com/30108796/101033155-657e7280-357a-11eb-9856-62d27cee6b73.png)

Propose 3:
![image](https://user-images.githubusercontent.com/30108796/101034232-b0988580-357a-11eb-9bee-7feb6af9308a.png)

**Comment by gerhardol** [comment]
Available (since 3.4?)
![image](https://user-images.githubusercontent.com/6248932/101050870-230e6300-3585-11eb-9b3c-e834c0ffa194.png)

Diff colors override other highlighting

**Comment by pmiossec** [comment]
Yes, but @lukaspupkalipinski is a little teasing ;)
Because he report the issue with a perl file, that is supported but show us what we have to fix with a c or cpp file, that is already supported.

So I would say it's more an issue with which file we support.

So @lukaspupkalipinski , feel free to contribute the perl syntax highlighting support (like this one: https://github.com/gitextensions/ICSharpCode.TextEditor/pull/11 )

**Comment by RussKie** [comment]
I don't like the 3 option, sorry.

**Comment by lukaspupkalipinski** [comment]
Thanks, Perfect. Didnt saw that button. I needed mainly for c and c#.
Case closed
