### ISSUE TITLE
Cygwin git, cygwin linux tools

### ISSUE THREAD

**Issue by EpsilonD3lta** [gitextensions/gitextensions#8702]
I tried to use my cygwin git in GE instead of windows git to be in sync, as I often use Cygwin terminal for git or other commands.
I set Settings->Git->Paths to C:\cygwin64\bin\git.exe for git and C:\cygwin64\bin\ for Linux tools and HOME folder to C:\cygwin64\home\myUserName and copied .gitconfig there (btw, when I only set git path and not Linux tools path, GE still uses windows git).

## Current behaviour
GE seems to work, except the built-in console. It opens home directory instead of repository directory. Also, the keybindings are wrong, e.g. hitting "backspaces" on keyboard types "space" instead. It is possible that this is a problem of the sh.exe that comes with cygwin and not a GE bug, but google found nothing.

## Expected behaviour
Console working without issues.

## Steps to reproduce
0. Have installed and fully functional GE with windows git version 2.26.0.windows.1
1. Install cygwin with git version 2.30.0 (also tried 2.29.0)
2. Set paths as described in the first paragraph
3. Try to type and run some commands in built-in console

## Did this work in previous version of GitExtensions
I don't know, but my best guess is that it didn't.

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.26.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4250.0
- DPI 96dpi (no scaling)

## Similar issues
- https://github.com/gitextensions/gitextensions/issues/3876

**Comment by gerhardol** [comment]
GE is primarily supported with Git-for-windows.
Cygwin Git may work but no active work is planned to make sure it works. Patches are accepted though.
ConEmu is also a Windows centric application.
So no direct response to your problem.

I used to use Cygwin Git in Windows (also GE) before Git-for-windows was up to date.
There were a number of minor issues with the various GE clients.
Since then I am using Git-for-windows in Cygwin instead. The home directories are separate, some aliases are shared by includes only. This works well for me.

**Comment by EpsilonD3lta** [comment]
Git-for-windows in Cygwin seems like a viable option, I will give it a try.
Thanks for the response.
