### ISSUE TITLE
Add alter texteditor

### ISSUE THREAD

**Issue by Pavia00** [gitextensions/gitextensions#8769]
I want use Notepad++ to edit text.  I dream that I have the function of opening a notepad by pressing the F4 key or the context menu. Please add new features in the next implementation.
I think GE can open the editor using git settings.

**Comment by Pavia00** [comment]
> Already there
> Settings - Git - Config - Editor

Don't work. Open GT Editor rather of Notepad++

[![GIF-18-01-2021-12-26-52.gif](https://i.postimg.cc/d1zN76bz/GIF-18-01-2021-12-26-52.gif)](https://postimg.cc/hz116LPr)

**Comment by RussKie** [comment]
You're welcome to send a PR.

**Comment by pmiossec** [comment]
@Pavia00 There is a misunderstanding...

You set notepad++ as the default editor for **Git**. So when git want to interact with you (during rebase, ...) it will open Notepad++.

Here the "Edit file in working directory" is a **GitExtension** feature and it always open the GitExtensions editor.

If you want to open the file with something else, that's a new feature that should be developed...
But we can't reuse the git setting because it contains special parameters...

So if it's what you want, please could you rewrite your feature request to be more explicit?

**Comment by Pavia00** [comment]
Ok.  I dream that I have the function of opening a notepad by pressing the F4 key or the context menu. Please add new features in the next implementation.
I think GE can open the editor using git settings to anyone

**Comment by pmiossec** [comment]
You have `Ctrl+O` to choose the editor:

![image](https://user-images.githubusercontent.com/460196/104900296-31211300-597c-11eb-9ce7-9ab4e1a3a852.png)

**Comment by RussKie** [comment]
> P.S. I never understood. Why so many questions? If you need to correct or add 1 line in the source code.

If you think it is easy - send a PR. Else - just stop, it won't take us far.

**Comment by Pavia00** [comment]
> If you think it is easy - send a PR. Else - just stop, it won't take us far.
I can't understand you. Please explain  the statement " send a PR. "?

**Comment by pmiossec** [comment]
> P.S. I never understood. Why so many questions? If you need to correct or add 1 line in the source code.

Once again, you seems to not understand the real behavior and that it is GitExtensions that asks all these questions but that is the Windows way to do.

>I can't understand you. Please explain the statement " send a PR. "?

It's difficult for us contributors that knows that things are often not easy to fix because you always have edge cases to handle that something is easy to fix because "you just have to do...". And also having to discuss a lot and explain all that to someone landing on the project. 

So, that's Why @RussKie is asking you, if you think it is just a one line fix to do it and create the pull request (PR) so that we just have to review and merge it.

Discussing on such feature requests without code changes is a waste of time for everyone...
