### ISSUE TITLE
Support "main" branch

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#8811]
## Feature description

A number of repos (including high profile like [Microsoft .NET org](https://github.com/dotnet/announcements/issues/172)) are renaming "master" branch into "main". We must update the code to include "main" alongside "master".

**Comment by pmiossec** [comment]
That indeed requires an audit to see where it is hardcoded but I don't know if there are a lot of places because most of the times, `master` is a branch like the others...

I don't know if you have something in mind.

One thing I see is letting the user specify the name of the branch in the clone form (because the setting `init.defaultBranch` should automatically supported by git).

**Comment by gerhardol** [comment]
See also #8741 
There are some hardcoding for master* for the branches in CommitInfo at least

**Comment by vbjay** [comment]
Default branch in pull requests.

**Comment by gerhardol** [comment]
CommitInfo.cs: Prioritize local and remote branches
BranchFinder.cs: Fallback?

If GE changes: References to PrivacyPolicy.md, ChangeLog.md

**Comment by RussKie** [comment]
> Default branch in pull requests.

Can you please provide more information?
