### ISSUE TITLE
[Theming] ToolStrip visual artifacts

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#8864]
## Current behaviour

| Default | Dark |
--|--
![image](https://user-images.githubusercontent.com/4403806/108448963-c9315580-72b6-11eb-90f1-970b38dd7180.png) | ![image](https://user-images.githubusercontent.com/4403806/108448997-d8b09e80-72b6-11eb-8a28-e0adf6471bbd.png)

In the default (system) theme the toolstrip is uniformly filled, and all borders are square. In the dark theme - the both ends show visual artifacts, that look like a rounded shadow.
![image](https://user-images.githubusercontent.com/4403806/108315941-45bd2900-7210-11eb-8ea0-acb05a93667b.png)

## Steps to reproduce

Checkout 983b0c3 (or the commit from #8849)

**Comment by RussKie** [comment]
@NikolayXHD would you be able to look into this? Or may be provide some pointers where to look... 
Thanks

**Comment by NikolayXHD** [comment]
@ivangrek is right, it's professional toolstrip renderer shadow.
If I use SystemToolStripRenderer instead, then it's ok

![image](https://user-images.githubusercontent.com/12046452/108641146-d1ec7c00-74ae-11eb-803b-3224c59727c3.png)

However, then we need to again, override how it paints, because

![image](https://user-images.githubusercontent.com/12046452/108641221-2e4f9b80-74af-11eb-8498-d4fc69bc1e55.png)

and who knows what else.

It feels to mee to little gain for the amount of work to be done.

**Comment by RussKie** [comment]
Thank you for the investigation.
Do you think we can paint over the offending corner in the current
implementation?

**Comment by drewnoakes** [comment]
Possibly related:

![image](https://user-images.githubusercontent.com/350947/108930745-98786400-769a-11eb-829d-c650327b89f9.png)

There's a phantom line below the toolbars, and a mysterious box to the right.

Dark theme. 150% display scaling.
