### ISSUE TITLE
Filter by file name not working

### ISSUE THREAD

**Issue by glebov21** [gitextensions/gitextensions#9069]
## Current behaviour

Filter by file name not working

## Steps to reproduce

1) Open commits list
2) Click Ctrl+F
3) In "File filter" input file name like: TextBox.cs
4) Result is empty

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.20.1.windows.1 (recommended: 2.25.1 or later)
- Microsoft Windows NT 6.3.9600.0
- .NET Framework 4.8.3928.0
- DPI 120dpi (125% scaling)

**Comment by adavila0703** [comment]
@glebov21 Were you searching for a file using its full path (including directory). For example "./TexBox/TextBox.cs" will find all instances of this file in that location, but if I search just "TextBox.cs" I will not get results, unless the file is located in the base directory.

**Comment by RussKie** [comment]
> 1. Open commits list

What's a "commits list"?

**Comment by glebov21** [comment]
> > 1. Open commits list
> 
> What's a "commits list"?

Main window in repository:
![image](https://user-images.githubusercontent.com/693132/126044126-4707f41d-4148-4409-b419-e751811043fa.png)

**Comment by glebov21** [comment]
> @glebov21 Were you searching for a file using its full path (including directory). 

Understandably. I was expected to search for all files named.

**Comment by gerhardol** [comment]
The arguments are the same as used by git-log https://git-scm.com/docs/git-log#Documentation/git-log.txt---ltpathgt82308203
You may use wildcards as "**/TextBox.cs" (use quotes with wildcards and spaces)

There are some discussions to use the advanced filter instead of the FileHistory, see https://github.com/gitextensions/gitextensions/issues/7598
(a few changes in master)

>>    What's a "commits list"?

> Main window in repository:

Normally called Revision grid in GE
