### ISSUE TITLE
Tags in dark theme are not really readable

### ISSUE THREAD

**Issue by MatthieuHernandez** [gitextensions/gitextensions#9190]
![image](https://user-images.githubusercontent.com/25429726/117647088-d0b51c00-b18c-11eb-8b3c-1b717c56b317.png)
[Color Contrast Checker 345454-292929](https://coolors.co/contrast-checker/345454-292929)

Maybe use #93BCBC
[Color Contrast Checker 93BCBC-292929](https://coolors.co/contrast-checker/93bcbc-292929)

Please be [WCAG AAA](https://webaim.org/resources/contrastchecker/?fcolor=93BCBC&bcolor=292929) compliant for all the texts in dark and light theme.

**Comment by gerhardol** [comment]
See also #9111 
Contributions are welcome

**Comment by LaughingJohn** [comment]
They're not very readable in the light theme either IMHO. I've gone back to 3.4.3 because of this and the side panel collapse state not being stored between restarts (also raised).

**Comment by mstv** [comment]
Have you tried 3.5.1? There have been fixes.
The theme files can be edited as well as inherited and overridden.

**Comment by gerhardol** [comment]
Tags were never changed in 3.5.0 only the colors and style of the labels.
The color (but not style or switch local-remote) was reverted in 3.5.1.

Someone with a good eye for colors, please help improving...

**Comment by LaughingJohn** [comment]
@mstv Yep I tried 3.5.1 - I think I must have still been using 3.4 and skipped 3.5.0. Thanks the info on the themes. I know it's subjective, but I personally prefer the graded colour of the tags in the old 3.4 theme as they stood out better. TBH I could probably live with the tags, but the fact the left hand pane wouldn't go away permanently was worse.
I'll give it another go at some point, but when you're busy any change can be a distraction, so I'm back on 3.4 and happy now! :)

**Comment by mstv** [comment]
3.5.1 restores the state of the Left Panel correctly (#9102). This was broken in 3.5.0.

**Comment by LaughingJohn** [comment]
> 
> 
> 3.5.1 restores the state of the Left Panel correctly (#9102). This was broken in 3.5.0.

Still broken in 3.5.1 for me unfortunately! Maybe the fix didn't get included?

**Comment by mstv** [comment]
The merge has not been reverted, of course.
It worked when I wrote the above reply and it works for me right now.
If multiple instances of GE are closed at the same time, it is indeterministic which instance "wins" writing the settings.
So please try it with a single instance.
The positions are stored in `%APPDATA%\Roaming\GitExtensions\GitExtensions\GitExtensions.settings`, the Left Panel state in `FormBrowse.MainSplitContainer_Panel1Collapsed` IIRC.

**Comment by LaughingJohn** [comment]
Thanks @mstv - I'll come back to it, I've reverted for now and unfortunately busy so don't have a lot of time to test at this moment. I did install/uninstall it twice, and I even deleted the settings folders just in case, but I guess it could be something on my side.

**Comment by h0lg** [comment]
I have a related issue: Since the whatever version changed the labels from filled to outline-only, I have more trouble distinguishing remote from local branches. Obviously, reading the `remote/` prefix that's still possible - it's just noticeably *harder* for me than it was before - when I could make that distinction by mere glancing.

Like many males, I have a red/green color impairment. Distinguishing between red and green with just a fine outline is hard for me. Considering the current demographic of programmers, you might also want to take this rather common impairment/blindness into consideration when choosing the color palette for your themes.

How about filling the labels of local branches and showing remotes as only an outline? That could solve the entire color question.

**Comment by gerhardol** [comment]
> Like many males, I have a red/green color impairment.

The themes have a setting to be better adopted for color blindness, try that.

Change outlining and switching the colors for local/remote was done to refresh the looks - these were much discussed (not my favorites, but a step to improve at least). That job is a little stalled, it would be good if an actual designer could make some contribution...

**Comment by RussKie** [comment]
![image](https://user-images.githubusercontent.com/4403806/128651384-e3918e2c-3e1b-4a66-bbf0-9f5c34103a32.png)
https://github.com/gitextensions/gitextensions/blob/d488e497cc6244483794abedb8e4779495ba861c/GitUI/Themes/README.md

PRs making dark themes WCAG 2.1 compliant are welcome.

**Comment by h0lg** [comment]
> The themes have a setting to be better adopted for color blindness, try that.

I did try that for both the bright and dark theme. It changes the color of the outlines which improves the contrast between them slightly - but doesn't restore it to how easy it was for me to **distinguish local from remote branches** before, when the labels were filled.

I'll fiddle with the custom theme described in the Readme that @RussKie pointend out to see if I can re-**fill the labels**.
But maybe that's something you'd want for the (local branches of the) dark theme or color-blind modes anyway - "inverted" label backgrounds: If I'm color-blind, my main visual key is **contrast**. So if the label background was filled with a dark color on the bright theme and vice versa, that would make them pop for me. Just food for thought. Thanks for the consideration, anyway. You're doing a great job with GitExtensions <3

**Comment by h0lg** [comment]
Speaking of color impairments, the label for `area: theming` above is impossible for me to read. The contrast is too low. I have to select the text in order to be able to read it.
![image](https://user-images.githubusercontent.com/680296/128684195-aaad5398-e871-4e16-aa08-60b3cdad5aeb.png)

But that's just me pointing out an interesting example while we're on the topic and not at all important to me.

**Comment by mstv** [comment]
> re-fill the labels

This is not supported because this was hard-coded in order to not increase the number of settings.

> How about filling the labels of local branches and showing remotes as only an outline?

So, I propose to add two settings `FillLocalLabels` and `FillRemoteLabels`.

**Comment by ZodmanPerth** [comment]
> So, I propose to add two settings `FillLocalLabels` and `FillRemoteLabels`.

Can we just have new filled colour tags in the theme css file?  Then we can set it however we want in any theme.

# Current

(excerpt)

```css
.Tag                     { color: #00008b; }
.Graph                   { color: #8b0000; }
.Branch                  { color: #008000; }
.RemoteBranch            { color: #8b0009; }
```

# Proposed

(excerpt)

NOTE: I used white because I don't know the actual colour.

```css
.Tag                     { color: #00008b; }
.Graph                   { color: #8b0000; }
.Branch                  { color: #008000; }
.RemoteBranch            { color: #8b0009; }
.TagFill                 { color: #ffffff; }
.GraphFill               { color: #ffffff; }
.BranchFill              { color: #ffffff; }
.RemoteBranchFill        { color: #ffffff; }

```

**Comment by pmiossec** [comment]
@ZodmanPerth I won't say that a development won't be done in the future to fix this issue, but just FYI the theme feature will be more likely removed from next release because no one was able to have it working with .net core / .net >= 5 :cry: 
So no more dark theme and no more problem until theme will be enabled again (if it will....)
