### ISSUE TITLE
Migrate theming from net461 to net50

### ISSUE THREAD

**Issue by NikolayXHD** [gitextensions/gitextensions#9191]
Beginning of discussion: https://github.com/gitextensions/gitextensions/pull/8522#issuecomment-836095772

**Comment by RussKie** [comment]
Have you seen https://github.com/Microsoft/Detours?

**Comment by RussKie** [comment]
...and https://github.com/citronneur/detours.net?

**Comment by NikolayXHD** [comment]
Thank you, will look at it the coming weekend

**Comment by NikolayXHD** [comment]
> @NikolayXHD if you run with the [Managed Debug Assistants](https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/diagnosing-errors-with-managed-debugging-assistants) turned on in VS, do they flag any kind of interop issues? It may be that a calling convention or argument marshalling is incorrectly specified, and that it worked under .NET Framework but fails under .NET Core.

Thank you, good to know it exists! Gave it a shot, unfortunately it no new information so far.
The program loads a bunch of DLLs, then `ExecutionEngineException`, nothing intercepted or outputted in between

![image](https://user-images.githubusercontent.com/12046452/120907366-66977600-c669-11eb-94ff-6ee41167fdf7.png)

**Comment by NikolayXHD** [comment]
> ...and https://github.com/citronneur/detours.net?

detours.net should be able to achieve what we need, not directly though.
```
.\DetoursNetRuntime myplugin.dll process_to_inject_hooks_into.exe
```
is not what we want. The goal would be to achieve hooking "from inside" a .net process by learning from detours.net codebase.

**Comment by sharwell** [comment]
is there a list of the APIs that are currently hooked for theming?

**Comment by NikolayXHD** [comment]
8 methods, see [Win32ThemeHooks.InstallHooks](https://github.com/gitextensions/gitextensions/blob/254cb4159df95e8e619c6b769a281d381ef686d2/GitUI/Theming/Win32ThemeHooks.cs#L54)

**Comment by KindDragon** [comment]
Related WinForms issue https://github.com/dotnet/winforms/issues/5166

**Comment by macsux** [comment]
I had success getting CoreHook to work with .net core as replacement for easyhook. https://github.com/unknownv2/CoreHook

**Comment by yenic** [comment]
CoreHook looks interesting but it does appear that WinForms theming is on the roadmap for .NET 8. https://github.com/dotnet/winforms/issues/5166#event-7167932536 

If they implement it, that will be November 2023. Unless someone volunteers to build in CoreHook and support it, we can probably count on 2024. I would just wait this one out, it's one year without dark theme in Git Extensions 4.0+.

**Comment by RussKie** [comment]
> Related WinForms issue [dotnet/winforms#5166](https://github.com/dotnet/winforms/issues/5166)

I wouldn't count on this in the foreseeable future (if at all). https://github.com/dotnet/winforms/issues/7641 is significantly more likely to occur, though I'd be surprised if it lands in .NET 8 timeframe.

**Comment by pmiossec** [comment]
> I had success getting CoreHook to work with .net core as replacement for easyhook. https://github.com/unknownv2/CoreHook

@macsux Do you have some more information on that? Documentation ? An example repository doing it? Or is it a drop-in replacement for EasyHook?

**Comment by macsux** [comment]
It's pretty much a drop in replacement from what I remember. Here's me using it in one of the projects: https://github.com/macsux/cf-buildpack-windows-services/blob/master/src/WindowsServicesBuildpack/ScimControllerInjector.cs

**Comment by spdr870** [comment]
It looked like a very simple replacement. Just replace LocalHook with CoreHook.LocalHook in Win32ThemeHooks. (after adding the nuget packages and the native dll's) Still, my attempt to replace EasyHook with CoreHook failed with this exception:
An unhandled exception of type 'System.ExecutionEngineException' occurred in Unknown Module.

**Comment by FenPhoenix** [comment]
> Still, my attempt to replace EasyHook with CoreHook failed with this exception:
An unhandled exception of type 'System.ExecutionEngineException' occurred in Unknown Module.

Hello, I'm the author of another app that uses hooking as part of WinForms theming, and I ran into this same ExecutionEngineException issue when trying to move from Framework 4.7.2 to .NET 7. I determined the exception comes from the GetSysColor() hook only, so I created an issue here: dotnet/runtime#78086

As you can see from the reply, it's apparently because GetSysColor() is set up with a \[SuppressGCTransition\] attribute in the newer .NETs, and that breaks the hook and causes the ExecutionEngineException. [Here's the code.](https://github.com/dotnet/runtime/blob/c2ec86b1c552ac8a1749f9f98e012f707e325660/src/libraries/Common/src/Interop/Windows/User32/Interop.GetSysColor.cs#L17) It looks like just a normal p/invoke setup that the runtime can call explicitly, so I'm not sure why putting the attribute on just that one definition would affect all calls to the native GetSysColor() function even from native controls, but it seems to. I'm no expert on how this sort of thing works so I dunno. I'm at a loss for any way to get around it, but at least I thought I'd save others the trouble I went through of trying to figure it out.

**Comment by yenic** [comment]
It sounds like EasyHook isn't going to work after reading that thread (https://github.com/dotnet/runtime/issues/78086). Seems like the best hope is https://github.com/dotnet/winforms/issues/7641 for this issue, as RussKie originally suggested.

**Comment by Eneong** [comment]
What if as a temporary solution before .net8 release you were to create a separate build with the dark theme? Something tells me that it shouldnt be too hard to implement

**Comment by RussKie** [comment]
Closing as it is currently technically not possible, see https://github.com/gitextensions/gitextensions/issues/9191#issuecomment-1312614913.

**Comment by Cyber1000** [comment]
Would this work? (Disclaimer: not tested by me)
- https://github.com/ryanbester/dotnet-darkmode (https://www.nuget.org/packages/DarkMode)
- would take windows-system-settings from win10 - if this works it would be a oneliner (and perhaps an additional flag in the settings)

**Comment by gerhardol** [comment]
Crossposting some suggestions: https://github.com/gitextensions/gitextensions/issues/10312#issuecomment-1468781985

**Comment by popara96** [comment]
Any news regarding this discussion, with the comment @gerhardol mentioned?

**Comment by gerhardol** [comment]
No workaround for the hooking found.
No support for theming that I have seen also in the upcoming.net8

**Comment by RussKie** [comment]
The theming support _may_ be coming in .NET 9 it seems: https://github.com/dotnet/winforms/pull/10985

**Comment by KlausLoeffelmann** [comment]
@RussKie: If that's all right, I'd ping you once I think, you could "try" it.

I would be very much interested in the experience to enable dark mode for whatever custom controls you guys have. For all the normal stuff, it should be easy to migrate. For now, you'd just use...

![image](https://github.com/gitextensions/gitextensions/assets/9663150/cb69dc8c-f37c-4dbd-a6f6-012f3efcdce5)

If you pick `Inherits`, then the System setting is applied wherever possible. (Problems are `TabControl` - not natively themable at all, and neither are `MonthCalendar` and therefore `DateTimePicker`). `Inherits` here is a "logical ambient" property, means, the idea is, that any control with that setting looks at its parent, a top-level control without a parent would look at `Application.DefaultDarkMode` and the Application using `Inherits` would look at the System.

So, for styling individual (custom) controls: If it's more than `ForeColor` and `BackColor` (and since I am working with Git Extensions, I know there is quite some coloring going on), the principal approach would be:

1. Test, if dark mode is in the current context available by using `[Contropl.]IsDarkModeEnabled`.
2. Access the Dark Mode/Current palette for the entire application, by using `Application.SystemColors.[SystemColorName]`.
3. Get the color from there and style the control with it. This way, the color assignment should then work both for dark- and light mode, since that palette reflects the current setting (and we also have then a hook for future extensions).

And, as usual, Igor and I do our usual "Naming and Convention Dance", so, API names might not be cast in stone quite yet.

Looking very much forward for feedback, but also keep in mind: The MVP Summit is coming up, so I'll be going dark (pun intended) for next 2 weeks.

**Comment by gerhardol** [comment]
@RussKie Is this ready to be tried for GE?

**Comment by RussKie** [comment]
> @RussKie Is this ready to be tried for GE?

¯\\_(ツ)\_/¯ I'm no longer part of the Windows Forms team, and I have a basic understanding of what the team is working on. 
That PR is still in draft, so the answer to your question is "no".

**Comment by gerhardol** [comment]
https://github.com/dotnet/winforms/pull/11857 has been merged, so there is some kind of dark mode expected in .NET9

**Comment by Bush-cat** [comment]
No available Light mode in Git Extensions has always bugged me, so I tried to fix it quickly by trying out this project
https://github.com/BlueMystical/Dark-Mode-Forms

![app](https://github.com/user-attachments/assets/ab78fdbc-963c-42b3-9702-5c96261f2a18)
![commit](https://github.com/user-attachments/assets/e67e01f3-4ab6-4ea1-bea6-b7ff0b1bcf9d)

I didn't spend a lot of time on it but I got this far already, I just lazyily implemented it where it seemed right, I didn't examine the code very much.

Some text became invisible and the Colors and Icons look washed out but are fixed when using the high contrast theme but the high contrast theme destroys other things
![app-hc](https://github.com/user-attachments/assets/7ecd8bb8-868b-4211-85f5-af1c6dcd3688)
![commit](https://github.com/user-attachments/assets/d5de340a-b30b-4dee-a4b2-1d36876f5db4)

Maybe when I have enough time I can fix all Issues and publish a fork or if we're lucky the devs implement it as this is more of a workaround.

**Comment by gerhardol** [comment]
> Maybe when I have enough time I can fix all Issues and publish a fork or if we're lucky the devs implement it as this is more of a workaround.

Coordinate with the changes in .NET9:  [dotnet/winforms#11857](https://github.com/dotnet/winforms/pull/11857)
A month or so before official.

**Comment by gerhardol** [comment]
There is a PR for dark mode: #12111 
There are quite some workaround to handle Winforms issues, some issues remain. GE application colors are tuned too.
The feature must be experimental in GE as Winforms could remove the experimental feature.
