### ISSUE TITLE
Release a new Linux version

### ISSUE THREAD

**Issue by anymor1024** [gitextensions/gitextensions#9238]
GitExtensions is super perfect tools, but unfortunately the last version for Linux is 2.51 with mono which is very old.

I would like to ask you to think about Linux as well and please include in the plans the preparation of the version for Linux and to come back again with the latest version.

**Thank you very much.**

Best regards,
anymor1024

**Comment by gerhardol** [comment]
The mono version was dropped due to mono being limited (no Mono/WinForms updates since about 2010) and that there were no active developer for GE on mono.
The GE 2.x mono branch still exists, there has not been many contributions since last release.
If there are any developers interested in maintaining the 2.x branch, there can of course be new releases. Mono/WinForms is still a limiting factor

There has been interests in making GE cross-platform in other ways, but that will require a lot of effort. Either "someone" ports WinForms to other platforms or the GE UI layer is rewritten using something else than WinForms.
GE master now uses .NET5, so that is cross-platform.
