### ISSUE TITLE
Missed default buttons in some dialogs

### ISSUE THREAD

**Issue by vpolozov** [gitextensions/gitextensions#9251]
## Current behaviour

Keyboard actions are more complicated in v3.5, than before.

1. Checkout dialog doesn't have default button.
2. Reset button in commit defaults to "Cancel"

## Expected behaviour

1. Expected, that "Checkout" button will be pressed on "Enter" in checkout dialog.
2. Expected to have some shortcut to reset selected changes. Or, at least, to have "Reset" button as default selection in reset dialog.

## Steps to reproduce
Checkout:
  1. Press checkout branch, e.g. "Ctrl+."
  2. Select branch, e.g. "master"
  3. Press "Enter" to checkout
  4. Nothing happens

Reset changes
  1. Enter "Commit" dialog. E.g. "Ctrl+Space"
  2. Navigate to changed file to revert
  3. Press "r" then "Enter"
  4. Nothing reverted

## Did this work in previous version of GitExtensions

It seems, that it was 3.4

## Environment

- GitExtensions version: 3.5.0.11713
- Build 0a5ef9ca6ce87754a510aa02c7a96d8b915714ac (Dirty)
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4341.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
Yep, we have regressed a little bit in single dialog windows. There is work in progress.

> 2. Reset button in commit defaults to "Cancel"

This has been changed on purpose because it is a dangerous operation.
But we have added the mnemonic "e" to the button at least in the English.xlf:
```
      <trans-unit id="btnReset.Text">
        <source>R&amp;eset</source>
        <target />
      </trans-unit>
``` 

Hint: In Windows' Accessibility Settings for the Keyboard, one can enable the permanent underlining of mnemonics.

**Comment by vpolozov** [comment]
> This has been changed on purpose because it is a dangerous operation.
> But we have added the mnemonic "e" to the button at least in the English.xlf:

Thanks, "Ctrl+Space, r, e" works!

**Comment by vpolozov** [comment]
Closed? What about checkout? It there some hidden shortcut?

**Comment by mstv** [comment]
The Form's default button is set correctly - but without affect. 🤔
```
            // 
            // FormCheckoutBranch
            // 
            this.AcceptButton = this.Ok;
```

**Comment by RussKie** [comment]
> The Form's default button is set correctly - but without affect. 🤔

https://github.com/gitextensions/gitextensions/blob/fa7fd3abba0dd953981a63383234853689427daf/GitUI/CommandsDialogs/FormCheckoutBranch.cs#L76-L77

But as I found later this is not enough, there has to be another statement added, like so:
https://github.com/gitextensions/gitextensions/blob/fa7fd3abba0dd953981a63383234853689427daf/GitUI/CommandsDialogs/FormCreateBranch.cs#L37-L39

**Comment by hultqvist** [comment]
Can I disagree on the reset being a dangerous operation in need of this level of protection.

In terms of accidental key presses I agree that double tapping `R` was a risk and was correctly fixed.

But the new `R, E` is more risky than the previous `R, Enter` because if you're looking at the keyboard `R` and `E` are next to each other making so that a single press by a finger could trigger the whole reset operation.

And `Enter` should confirm an dialog prompt, even a risky one.
