### ISSUE TITLE
FormCommit: `FileStatusList` not refreshed correctly

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#9283]
## Steps to reproduce

In FormCommit:
- Stage lines of a new file (or change it after staging a draft)

![grafik](https://user-images.githubusercontent.com/36601201/121774954-164a7780-cb85-11eb-9210-50476734a789.png)

- Unstage the file

### Current behaviour

File is shown as changed without contents.

![grafik](https://user-images.githubusercontent.com/36601201/121774860-ab00a580-cb84-11eb-84d2-befc2a14fc0a.png)

## Expected behaviour

File is shown as new file with contents (as after refresh):

![grafik](https://user-images.githubusercontent.com/36601201/121775083-bef8d700-cb85-11eb-8137-d4586d5a2f7c.png)

## Did this work in previous version of GitExtensions

?

## Environment

- Git Extensions 33.33.33
- Build eddb5e332bd8dc0cd483d2f17d874ecc1b4013a3 (current master)
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET 5.0.6
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
It is the same in 3.4 and 3.3 at least, so not new
(An alternative to refresh is to stage/unstage the complete file.)

The issue is that the status in the unstaged list is not refreshed if the item already exists in the unstaged list, in FormCommit.cs Unstage(). IsNew and IsTracked is therefore incorrect for the items. (Early return assumes that these properties are unchanged if the file already exists in the worktree list.)
The staging of files has a completely different logic.
