### ISSUE TITLE
Git executable not found in Console

### ISSUE THREAD

**Issue by bvarnai** [gitextensions/gitextensions#9353]
## Current behaviour

After upgrading to 3.5.1, when I choose the Console tab and type `git --version`, no Git executable found. This was working in version 3.4.3

## Expected behaviour

Git executable should be available in Console (like in Git bash). IMHO without adding `git.exe` to the PATH explicitly.

## Steps to reproduce

Switch to Console and type `git --version`

## Screenshots

![image](https://user-images.githubusercontent.com/7565328/125047075-e36da380-e09e-11eb-9640-a9336732e9c4.png)

## Did this work in previous version of GitExtensions

Yes, in version 3.4.3. 

## Environment

- Git Extensions 3.5.1.12196
- Build 9099a1e76d01dbbd6896d6b026027db0b68fba96
- Git 2.32.0.windows.2
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4150.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
There had been issues with and fixes for the setting "Path to linux tools (sh)", which is `gitbindir` (old name) in the settings file `%AppData%\Roaming\GitExtensions\GitExtensions\GitExtensions.settings`.
That's why you might need to set this settings again.
Perhaps you had something like "C:\Program Files\Git\bin" and now "C:\Program Files\Git\usr\bin". The latter does not contain `git.exe` usually. The first one uses to contain `sh.exe`.

Only this directory is prepended to the `PATH` in the console (and for user scripts).
The setting "command used to run git"  is used internally only.

**Comment by bvarnai** [comment]
@mstv Thank you! I tried to set `gitbindir` manually but it always restored when the application is started. What did I miss?

**Comment by vbjay** [comment]
Should be usr\bin folder where git is installed.

**Comment by mstv** [comment]
Unfortunately, `git.exe` is located only in `C:\Program Files\Git\bin` not in `...\usr\bin`.

@bvarnai, I guess you have enabled `Check settings at startup`. Its label does not clearly state that it tries to automatically choose the correct paths on every start of GE. 
Since 8eb7f615230cf847860175158bede84204265dc0 (cherry-picked from #9064), `Git\usr\bin` is preferred over `Git\bin` because the first one contains all the tools.

(BTW: I do not configure a global username on purpose.)

![image](https://user-images.githubusercontent.com/36601201/125349977-7425d700-e35e-11eb-8841-c85818c11ea5.png)

**Comment by vbjay** [comment]
Right. You go to that settings page and place the full path to git in top
text box. Then in second one the where git is installed\usr\bin folder.

**Comment by VsevolodGolovanov** [comment]
Same issue after updating to 3.5.1 on windows:
![image](https://user-images.githubusercontent.com/8070317/125796132-c2b50ab1-4100-460b-9771-697998f6e928.png)
Settings:
![image](https://user-images.githubusercontent.com/8070317/125796249-148f67a1-aa0c-46e4-a8a8-d26e3dff1016.png)
Command to run git is correct. I changed Path to linux tools, but it had no effect.

**Comment by mstv** [comment]
It worked for me because I tested with `cmd` as the default shell.
`bash` and `powershell` seem to ignore the `PATH` set by GE.

The `bash` sets its own `PATH` which looks like it would contain `Git\bin\`:
```
$ env|grep ^PATH=
PATH=/c/Users/M/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/bin:...
```
But it is the same as `Git\usr\bin\` - without the git executable.

**Comment by mstv** [comment]
Correction: It seems to work with `powershell`: The `$env:PATH` contains the `Path to linux tools` as the last entry - same as `cmd`.

Though the `git bash` tinkers the `PATH`. It removes `/c/Program Files/Git` from `PATH` entries.
So `/c/Program Files/Git/bin` is turned into just `/bin`, which seems to be redirected to  `/c/Program Files/Git/usr/bin`.
I do not see what GE could do here.

Does it really work with GE 3.4.3 and Git 2.32.0.windows.2?

You could try different Git releases and raise an issue in the Git project.

If I set the  `Path to linux tools` to `...\Git\bin\`, it starts a "MINGW64" `bash`. But with `...\Git\usr\bin\` it is a "MSYS" `bash` as in your screenshots.
Have the settings really been in effect?
![image](https://user-images.githubusercontent.com/36601201/126051824-1b3ac971-e89c-44bf-995b-0242c014a8a6.png)

**Comment by mstv** [comment]
BTW: Why do you hesitate to add `c:\Program Files\Git\cmd\` with just a few executabels to the `PATH`?

![image](https://user-images.githubusercontent.com/36601201/126051865-fa822044-af0f-49d0-b14f-cf08762d40b8.png)

**Comment by bvarnai** [comment]
Yes, adding `c:\Program Files\Git\cmd\` works. The only minor issue that this doesn't work out of the box which might be confusing to the some users. My assumption is that `Git bash` and GE's Console is interchangeable.

**Comment by fanfan-huang** [comment]
Having the same issue I don't I don't install git to be integrated into the command line path and I'm experiencing the same issue with git 2.32

**Comment by mstv** [comment]
The support for `git-bash.exe` was dropped in #8213 - by mistake IMO. #9416 restores this for the stand-alone shell.
