### ISSUE TITLE
After update to 3.5.1 OpenSSH keybased authentication broken

### ISSUE THREAD

**Issue by dopry** [gitextensions/gitextensions#9355]
## Current behaviour
I'm using the OpenSSH newly included in windows with KeepassXC as an SSH Agent. I can use git as expected from the command line, but git extensions fails to authenticate.  

I cannot set the SSH client to c:\Windows\System32\OpenSSH\ssh.exe because the open file dialog does not see the OpenSSH folder.  I've also set GIT_SSH to c:\Windows\System32\OpenSSH\ssh.exe, but git extensions doesn't seem to respect the environment variable. 

## Expected behaviour
1. Git Extensions can use c:\Windows\System32\OpenSSH\ssh.exe
2. Git Extensions will respect GIT_SSH

## Did this work in previous version of GitExtensions
It worked in 3.5.0

## Environment
Sorry I reverted since I need to work, but it was GE 3.5.1.12???

**Comment by mstv** [comment]
> I cannot set the SSH client to c:\Windows\System32\OpenSSH\ssh.exe because the open file dialog does not see the OpenSSH folder.

I can confirm that the FileOpenDialog does not see `c:\Windows\System32\OpenSSH\` - only for 3.5.1, works for .NET 5. Very weird!

Have you tried entering `c:\Windows\System32\OpenSSH\ssh.exe` directly without the `Browse` button?

**Comment by gerhardol** [comment]
The GE SSH settings is stored in the registry, to work with the installer and so the setting can be shared with multiple installations. (That should probably be changed, just using the GE settings but the installer is tricky.)
See the key HKEY_USERS\SOFTWARE\GitExtensions\gitssh

If the path ends with"plink.exe", PuTTY is assumed, and some special handling is done (starting PageAnt etc).
Otherwise there is no special handling. If the key is empty or the file does not exist, the setting in GE is presented as OpenSSH, otherwise Other. This is just a presentation, no different handling.
The GIT_SSH variable is always set also if the reg key empty. Git uses ssh.exe in the installation if the variable is not set. 
GE does not use GIT_SSH environment variable itself (only for Git), but sets the value to follow the settings (there were issues opened when GIT_SSH was not set). So part 2. should not be changed directly (see below first).
It should be possible to set GIT_SSH_COMMAND though.
https://git-scm.com/docs/git#Documentation/git.txt-codeGITSSHCOMMANDcode

Before 3.5.1, the SSH settings were lost in the upgrade. 
GIT_SSH was set regardless if the path existed or not.
Also, registry value was set also for OpenSSH, giving incorrect presentation in the settings (.
(The key was also set/read from the GIT_SSH env var.)
In 3.6, the reg key is migrated, the key is cleared if it is equal to the ssh.exe in the Git bin directory.

If you cannot set the SSH path in settings, try setting it directly in the registry.
Maybe GE cannot read the path in the gitssh key and uses an empty setting?
Can you set GIT_SSH_COMMAND?

**Comment by gerhardol** [comment]
Please try the test build (use portable) in #9369 https://ci.appveyor.com/project/gitextensions/gitextensions/builds/39964445/artifacts

**Comment by vittoso** [comment]
> > I cannot set the SSH client to c:\Windows\System32\OpenSSH\ssh.exe because the open file dialog does not see the OpenSSH folder.
> 
> I can confirm that the FileOpenDialog does not see `c:\Windows\System32\OpenSSH\` - only for 3.5.1, works for .NET 5. Very weird!


Could this be due to [32-bit app File System Redirector](https://docs.microsoft.com/en-us/windows/win32/winprog64/file-system-redirector?redirectedfrom=MSDN)?

**Comment by gerhardol** [comment]
> Could this be due to [32-bit app File System Redirector](https://docs.microsoft.com/en-us/windows/win32/winprog64/file-system-redirector?redirectedfrom=MSDN)?

Likely.
The proposal in #9369 worked in #9348, likely the same here.
The check in settings is similar to the removed check in #9369 (that was added in 3.5.1). Settings will not reflect the functionality.
GE does not use the value of GIT_SSH internally, so the non access does not matter.

**Comment by dopry** [comment]
@mstv 

in 3.5.1 I could not enter the path and it work.
in 3.5.3.12551 I can enter the path and it works, but the browse button still doesn't allow me to browse to the path.
