### ISSUE TITLE
[NBug] 同一のキーを含む項目が既に追加されています。

### ISSUE THREAD

**Issue by sxp200422** [gitextensions/gitextensions#9395]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentException: 同一のキーを含む項目が既に追加されています。
   場所 System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   場所 System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   場所 GitUI.CommandsDialogs.SettingsDialog.FormAvailableEncodings.ButtonOk_Click(Object sender, EventArgs e)
   場所 System.Windows.Forms.Control.OnClick(EventArgs e)
   場所 System.Windows.Forms.Button.OnClick(EventArgs e)
   場所 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   場所 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   場所 System.Windows.Forms.Control.WndProc(Message& m)
   場所 System.Windows.Forms.ButtonBase.WndProc(Message& m)
   場所 System.Windows.Forms.Button.WndProc(Message& m)
   場所 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   場所 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   場所 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
add encode shift-jis and jis

## Environment
- Git Extensions 3.5.1.12196
- Build 9099a1e76d01dbbd6896d6b026027db0b68fba96
- Git 2.18.0 (minimum: 2.19.0, please update!)
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
@sxp200422, I guess the available encodings on your PC do not have unique names - at least not the name used by GE internally.
Could you try the development build from https://ci.appveyor.com/project/gitextensions/gitextensions/builds/40053185/artifacts and report the message popping up, please?
Would you need to use both affected encodings?

**Comment by sxp200422** [comment]
@sxp200422, I guess the available encodings on your PC do not have unique names - at least not the name used by GE internally.
Could you try the development build from https://ci.appveyor.com/project/gitextensions/gitextensions/builds/40053185/artifacts and report the message popping up, please?
->
The message of popping up is :"'System.Text.DBCSCodePageEncoding'(日本語（シフトJIS）/shift_jis) has the same HeaderName'iso-2022-jp' as 'System.Text.ISO2022Encoding'(日本語（シフトJIS）/shift_jis) 

Would you need to use both affected encodings?
->
No. I want to use shift-jis only. But I don't know why it shows jis only in Selected(no shift-jis in Available). When I remove jis from Selected, shift-jis & jis both show in Available. And I try to add both of them, then this problem happened.

**Comment by mstv** [comment]
For the master branch (based on .NET 5.0), the encodings supported by the platform change anyway.
I propose to use the `EncodingName` instead of the [e-mail] `HeaderName` (without settings migration), i.e.
"System.Text.DBCSCodePageEncoding" and "System.Text.ISO2022Encoding" instead of "iso-2022-jp" in the settings file.
For display, use `ToString`, i.e. "(日本語（シフトJIS）/shift_jis".

Workaround for 3.5.2: Make the list of available encodings distinct regarding `HeaderName`.
But I will not create the `EqualityComparer` - needed for LINQ `Distinct` - without prior agreement.

---

> But I don't know why it shows jis only in Selected(no shift-jis in Available). When I remove jis from Selected, shift-jis & jis both show in Available.

`Available` contains only the not `Selected` encodings.

> And I try to add both of them, then this problem happened.

Does it work for you, if you add just one of these two to `Selected`, @sxp200422?
Does it matter which one? Can you distinguish these two?

**Comment by sxp200422** [comment]
> `Available` contains only the not `Selected` encodings.

I known it. But I first open Configure of Files content encoding, There is only jis shows in Selected(no shift-jis in Avaliable). When I remove jis in Selected and reopen Tools->Settings->Git->Configure of Files content encoding, both of jis and shift-jis show in Available.

> Does it work for you, if you add just one of these two to `Selected`, @sxp200422?

Work for me for now.

> Does it matter which one? Can you distinguish these two?

Yes, it matters to me. I need to use shift-jis(日本語（シフトJIS）) rather than jis, and I can distinguish these two.

**Comment by mstv** [comment]
I cannot distinguish these two in:
> The message of popping up is :"'System.Text.DBCSCodePageEncoding'(日本語（シフトJIS）/shift_jis) has the same HeaderName'iso-2022-jp' as 'System.Text.ISO2022Encoding'(日本語（シフトJIS）/shift_jis)

It might become clearer with screenshots pasted to the comments.

**Comment by sxp200422** [comment]
> I cannot distinguish these two in:
> 
> > The message of popping up is :"'System.Text.DBCSCodePageEncoding'(日本語（シフトJIS）/shift_jis) has the same HeaderName'iso-2022-jp' as 'System.Text.ISO2022Encoding'(日本語（シフトJIS）/shift_jis)
> 
> It might become clearer with screenshots pasted to the comments.

My project's files base on shift-jis, So there will be garbled code shown when use jis. See image below.
![useJISforCodeDiffPreview](https://user-images.githubusercontent.com/12292750/126494362-78eb5a81-1825-4017-add9-7b8ddf15a8e2.png)

In Settings:
![jis shift-jisbothShowinEncodingSetting](https://user-images.githubusercontent.com/12292750/126494490-f1f8d7b2-3d01-4ace-a1af-5a409de1fdd4.png)

---------------------------------------------------------------------------------------------------------------------------
Another problem, when I set shift-jis successfully, .gitconfig add contents below
[i18n]
filesEncoding = iso-2022-jp, 
and restart Git Extensions, the setting will restore to jis.
but what I expected is
[i18n]
filesEncoding = shift-jis.
shift-jis and iso-2022-jp are 2 different encodings.
Encoding list in Diff interface also have problems.

**Comment by mstv** [comment]
Since you got the MessageBox popup when adding both, it is very likely that the encoding with the `EncodingName` "System.Text.DBCSCodePageEncoding" and the `ToString` result "日本語（シフトJIS)" has the **wrong** [e-mail] `HeaderName` "iso-2022-jp".
GE uses the `HeaderName` as the identifier for the encodings, which therefore must be unique - but seem to be not on your system.

Have you tried entering "shift-jis" manually in the `.gitconfig`? Though I fear then there will be no matching encoding at all.

**Comment by sxp200422** [comment]
> Have you tried entering "shift-jis" manually in the .gitconfig? Though I fear then there will be no matching encoding at all.

I've tried before. After entering, Files content encoding can shows 日本語 (シフト JIS) correctly as I wish. No 日本語 (シフト JIS) shown in Selected, neither in Available. See image below.
![shift-jis in Files content encoding](https://user-images.githubusercontent.com/12292750/126593935-b909c3ea-109f-4268-bfa9-322817948414.png)
The content in Diff can be shown without garbled code. But encoding list in Diff is blank.
![image](https://user-images.githubusercontent.com/12292750/126594103-9d8cdf93-743b-4fae-a753-5d39a122e3b2.png)

**Comment by sxp200422** [comment]
I found a web ，but I don’t know if it’s useful for you.
![image](https://user-images.githubusercontent.com/12292750/126594483-cfa13058-3177-481e-a3e1-d1a02c5a9be7.png)
https://docs.microsoft.com/zh-TW/dotnet/api/system.text.encoding.headername?view=net-5.0

**Comment by mstv** [comment]
My .NET 5.0 installation has no inconsistent encodings - though only very few (7): UTF-*, us-ascii and iso-8859-1.
The .NET 4.8 encodings have the following conflicts / inconsistencies - perhaps on purpose:
`HeaderName` | `WebName` | `EncodingName`
-|-|-
iso-2022-jp | shift_jis | Japanisch (Shift-JIS)
iso-2022-jp | iso-2022-jp | Japanisch (JIS)
iso-2022-jp | iso-2022-jp | Japanisch (JIS, 1 Byte Kana erlaubt - SO/SI)
iso-2022-jp | csISO2022JP | Japanisch (JIS, 1 Byte Kana erlaubt)
euc-kr | iso-2022-kr | Koreanisch (ISO)
euc-kr | euc-kr | Koreanisch (EUC)

> After entering, Files content encoding can shows 日本語 (シフト JIS) correctly as I wish.

So I think we can replace all occurrences of `HeaderName` with `WebName` in order to support Japanese and Korean better.
(There will still be a conflict with the variants of "JIS, 1 Byte Kana enabled". This can be handled with a popup requesting to choose only one of these encodings.)

Any concerns, @gitextensions/git-extensions-source?

**Comment by gerhardol** [comment]
> My .NET 5.0 installation has no inconsistent encodings - though only very few (7): UTF-*, us-ascii and iso-8859-1.

Will .NET5 enforce UTF-8?

> Any concerns, @gitextensions/git-extensions-source?

OK for me

**Comment by RussKie** [comment]
UTF-7 is not supported in .NET.

No objections from me.

@sxp200422 if you think this representation/handling of header names is
incorrect, please raise it in *https://github.com/dotnet/runtime/
<https://github.com/dotnet/runtime/>.*
