### ISSUE TITLE
Freeze after exiting from commit diff view

### ISSUE THREAD

**Issue by Qrox** [gitextensions/gitextensions#9440]
## Current behaviour
If I double-click on a commit to bring up the commit diff view window, closing it causes GitExtensions to freeze. This happens for both small and large repos. The freeze may end after waiting for some time.

## Expected behaviour
It does not freeze.

## Steps to reproduce
1. Open a repository.
2. Double-click on a commit to open the diff view window.
3. Close the diff view window.
4. Freeze.

## Did this work in previous version of GitExtensions
Yes, but it was a very old version I updated from of which I no longer remember the version number.

## Environment

- Git Extensions 3.5.1.12196
- Build 9099a1e76d01dbbd6896d6b026027db0b68fba96
- Git 2.32.0.windows.2
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4390.0
- DPI 96dpi (no scaling)

## Diagnostics

After freeze ends, the command log contains this entry which takes a very long time:
```
File name:   *snip*\git.exe
Arguments:   difftool --tool-help
Working dir: *snip*
Process ID:  16568
Started at:  2021-08-05T00:56:33.0753398+08:00
UI Thread?:  False
Duration:    20424.33 ms
Exit code:   0
Call stack:  not captured
```

**Comment by mstv** [comment]
`git difftool --tool-help` takes 10-20 seconds. It runs in the background. Though after closing FormDiff, it seems to cause a temporary freeze - but only once.
It can be turned off here:
![image](https://user-images.githubusercontent.com/36601201/128245666-ad18fd50-3582-487c-ab20-186718b383b2.png)

**Comment by RussKie** [comment]
Are we failing to cancel a token?

**Comment by mstv** [comment]
> Are we failing to cancel a token?

`git difftool --tool-help` does not fully run in the background. Some operations can be blocked until it is finished.

Waits lilke the following are too unspecific:
```
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _asyncLoadCancellation.CancelCurrent();
                ThreadHelper.JoinPendingOperations(); // those run with FileAndForget
```

**Comment by AdamMadrzejewski** [comment]
I was experiencing the same freezing issue, in my case, it was taking forever and the program was not responding. I was about to report it because I was able to experience it every time I opened and closed diff windows. Anyway, just before I saw there was an update, so I updated and I'm not experiencing this issue anymore, so it seems like it was fixed:

It's not happening anymore on my updated version:

```
- Git Extensions 3.5.2.12435
- Build 77413699a9c25b160a6a622311529372b5d87f5b
- Git 2.26.2.windows.1 (recommended: 2.30.0 or later)
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4400.0
- DPI 96dpi (no scaling)
```

**Comment by gerhardol** [comment]
CustomDiffMergeToolCache.GetToolsAsync() makes a delay (10-15s) and run the Git command (5-30s) in FileAndForget() but does not have a cancellation token.
So forms using this will await the operation:
![image](https://user-images.githubusercontent.com/6248932/129449279-d7aa275a-ee16-4da6-81fa-697405c35424.png)

I assume that all callers will have to provide a token.

The workaround is to disable `AppSettings.ShowAvailableDiffTools`. (Merge still waits).
![image](https://user-images.githubusercontent.com/6248932/129449302-25249553-3079-4523-917f-4e4e0b7af681.png)

You will only see the primary difftool, not seen below. (You can disable the dropdown in menu too.)
![image](https://user-images.githubusercontent.com/6248932/129449497-637efbd8-9af3-4120-9868-6bedc95a239d.png)

**Comment by gerhardol** [comment]
The freeze due to CommitInfo was introduced in #9205.
There may be other ways to achieve that correction
The problem can be seen in other forms too though

This also requires some changes to the executable cancellation handling that I am not sure of how to do in the best way

I have pushed a branch with the changes I believe should be done to `feature/i9440-custom-difftools-token`
(Not submitting as draft yet, there are too many open PRs already).

**Comment by hyzcan** [comment]
Slightly modified repro steps and GitExtensions hangs 100% (on me) and never recovers itself:

1. Open a repository.
2. Ctrl+6 (or mouse click) to open built-in Git Console
3. Double-click on a commit to open the diff view window.
4. Close the diff view window.
5. Freeze.

Because of this, I reverted my installation to GitExtensions-3.4.3.9999 (which works pretty well).
