### ISSUE TITLE
Stash button no longer show the number of stashes

### ISSUE THREAD

**Issue by PhiLhoSoft** [gitextensions/gitextensions#9584]
## Current behaviour

When I stash the current code, I no longer see the current number of stashes next to the button. I have to click on the stash button and open the dropdown to see the number / if there is a stash.

## Expected behaviour

If I stash the current code, I would like to have the current number of stashes next to the button, as before.

## Steps to reproduce

Make a change, stash it.

## Screenshots

![image](https://user-images.githubusercontent.com/1087902/134197230-d329245e-4896-4eac-a44b-35f877824e6a.png)
![image](https://user-images.githubusercontent.com/1087902/134197313-6ed8c11f-4d70-4b8c-ac85-38cd053e8663.png)

BTW, the Write custom stash message button never worked for me (always deactivated).
Is there a way to enable it?

## Did this work in previous version of GitExtensions

Yes. One or two patch versions before.

## Environment

- Git Extensions 3.5.3.12551
- Build 00604a59a673142a3d34a22aa657466a922977f3
- Git 2.32.0.windows.2
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4340.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
Even with the setting checked?

![image](https://user-images.githubusercontent.com/460196/134198503-204e6dc7-2046-4bb1-84c7-5ef05c37fe14.png)

**Comment by gerhardol** [comment]
> Oups. I see, a new option… Maybe it should be active by default, as it is the behavior we are used to.

This option slows down the UI with up to some hundred ms every time the UI is (re)activated, so it should be off by default...

**Comment by PhiLhoSoft** [comment]
> BTW, the Write custom stash message button never worked for me (always deactivated).
> Is there a way to enable it?

See the second screenshot: the pen is always gray.
Is this a known bug / limitation / setting to activate?
Should I open a new issue for this one?
I ask here to avoid too much noise if the issue is just with myself… 😁

**Comment by pmiossec** [comment]
> BTW, the Write custom stash message button never worked for me (always deactivated).
> Is there a way to enable it?

It works well for me but I maybe you don't get what is the purpose of this button...

The goal is not to edit name of an existing stash (that's why it is disabled when you select an existing stash because I don't think we can modify an existing stash)
but to enter a message for the stash you want to create from this form.

So you will have to select the first row in the dropdown list named "Current working directory changes" to have the button enabled. Like in this screenshot

![image](https://user-images.githubusercontent.com/460196/134302203-1fa82a52-acef-472a-b966-131f6d8a9a33.png)

**Comment by gerhardol** [comment]
This is changed in master, pen is removed, just type to change the message
