### ISSUE TITLE
Git Extension : CPU load 100% - Disk space full - GIT.exe process increases

### ISSUE THREAD

**Issue by Newbies42** [gitextensions/gitextensions#9615]
## Current behaviour

I have different PC on Windows 10, with GIT and GIT Extension. One of them has a problem, when I open GIT Extension and the repository, GIT.ext process increases into the task manager. CPU Load is full after few minutes and disk space is also full after 20 or 30 minutes. PC cannot be used after several minutes due to the CPU Load. Into the task manager, after 20 minutes, I have more than 2000 process ! 

This process is called in loop : 
2021-09-10T12:29:27.4966054+02:00	1606	38644	UI	0	git	--no-optional-locks status --porcelain=2 -z --untracked-files --ignore-submodules=none	C:\HIL Applications\
2021-09-10T12:29:29.3576102+02:00	1607	64000	UI	0	git	--no-optional-locks status --porcelain=2 -z --untracked-files --ignore-submodules=none	C:\HIL Applications\

I read other issues on the same topic but I never found a answer to resolve my problem.
https://github.com/gitextensions/gitextensions/issues/6732
https://github.com/microsoft/vscode/issues/71085
https://github.com/git-for-windows/git/issues/3318
https://github.com/gitextensions/gitextensions/issues/230

I tried to uninstall my version of GIT and GIT Extension and install a old one... in case for this problem came from a regression, but I have still the same problem.

The setup is the same than other PC that I have, but only one PC have this behavior. Moreover, into the GIT Extension settings, I deactivate the "commit update" into the button. I though that this process is called to check which files have been changed into the branch. But nothing works...it's very boring. I don't know how can I resolve it. 

It seems that GIT process is launched by GIT Extension but is never killed automatically...and process increases indefinitely...
## Expected behaviour

Same than other PC. GIT Extension can be opened without any over load for the CPU after several minutes. Process GIT can be launched by GIT Extension but is killed after few seconds after.

## Steps to reproduce

Only on 1 PC, I don't know how to reproduce this behavior. 

## Screenshots

I didn't attach my task manager, but you can see GIT process many, many, many times !

## Did this work in previous version of GitExtensions

I tried different version, but always the same behavior.
GitExtensions-3.1.0.5877
GitExtensions-3.2.1.6628
GitExtensions-3.4.3.9999
GitExtensions-3.5.3.12551

Git-2.26.2-64-bit
git-2.26.3
Git-2.27.0-64-bit
Git-2.28.0-64-bit
Git-2.33.0.2-64-bit

## Environment

- GitExtensions version: See above.
- GIT version: See above.
- OS version: Windows 10 64bits
- .NET version:  ?

## Diagnostics

Thank you for your help !!

**Comment by gerhardol** [comment]
If you did not install LFS, git-status will be slow which is the trigger of both initiating the problem as well as eventually run with 100% cpu.

I have found one situation where a problem may occur: If you minimize/restore GE or open/close a modal dialog while a git-status command is running in the background, the running command is cancelled and a new command is started. The problem is that when the first command completes, it allows a new command to start.
So a few operations can cause several "chains" to run simultaneously, but I see no risk for "exploding".
If there is no trigger, i.e. no files changed in the repo or no restoring or modals, the "chains" will die.

For now, just deactivate the functionality as described above if it occurs again.
