### ISSUE TITLE
Expanded "Branches" folders do not survive restart of Git Extensions

### ISSUE THREAD

**Issue by fsinv** [gitextensions/gitextensions#9617]
## Current behaviour

Upon restarting Git Extensions all folder in "Branches" dropdown are collapsed.

## Expected behaviour

Expanded folders should also be expanded after restart like it was in previous versions.

## Steps to reproduce

Restart Git Extensions

## Did this work in previous version of Git Extensions

Yes, but I am not sure in which version. I think in the previous major release.

## Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.33.0.windows.2
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4400.0
- DPI 96dpi (no scaling)

**Comment by fsinv** [comment]
I can only conjecture why the issue is not affecting everyone. Maybe I am facing this issue because I do not have admin rights. Besides that I do not use any special config.

**Comment by pmiossec** [comment]
@RussKie I reproduce it ( with a custom version based on `3f4ed21998af4cb8bd5e105c5c93943d94ec4ca9` last commit before .net5 and also with last `master`).

From what I see with these version, the first level of `Branches`, `Remotes` and all levels of `Submodules` are opened when a repository is opened (but not `Tags`).

When I open a repo, I always end up in this state (all folders collapsed except the one of the currently checked out branch):

![image](https://user-images.githubusercontent.com/460196/140055483-e9f68493-6dc1-416a-8189-bdfc8cb75600.png)

So I think that @fsinv is right when he said that the whole sub-folders state is not restored (even if I don't know if it behaved differently in previous versions).

But I think that it is something done deliberately to start with a "cleaned" branch tree.

@RussKie Maybe you were talking about the `Branches` tree which has it's first level expanded at startup, right?

@fsinv Some screenshots could be a good idea to avoid misunderstandings because you are talking about `dropdown` where I think in fact you are more talking about the `Branches` tree in the left panel.

**Comment by RussKie** [comment]
We only expand top level nodes, and don't persist state of folders (this would be a massive overhead). This is by design.
