### ISSUE TITLE
Filter (only) sometimes show a commit preceding commit containing the search text

### ISSUE THREAD

**Issue by r0polach** [gitextensions/gitextensions#9618]
As attached screenshot shows, filtering commit messages in the main window
sometimes show two found commits instead of one. The second commit shown
(probably always the commit immediately preceding the first one) does not
contain searched text. I do not know why it behaves this way only sometimes
and sometimes not, but the screenshot show the wrong behavior described.

![screenshot](https://user-images.githubusercontent.com/1393254/136005487-e6e9182a-773a-4acc-b7c2-8fa44a83cfb1.png)

**Comment by r0polach** [comment]
After some experimenting, now I have idea, why sometimes it shows preceding commit and sometimes not.

First, it seems that filter support accented characters. If I use accented characters in the searched text, the
results show just the commits containing the searched text in the message. But if the searched text does NOT
contain accented characters, search results show also the preceding commit.

**Comment by RussKie** [comment]
You can see git commands being executed by pressing F12. You should be able
to replicate that from command line or create a standalone repro.

**Comment by r0polach** [comment]
There is a lot of things in log after pressing F12.
I cannot see searched text anywhere there.

**Comment by pmiossec** [comment]
> There is a lot of things in log after pressing F12. I cannot see searched text anywhere there.

First clear the view with a right click and "Clear".
Then launch you search and you will have to search for the ` git log` line looking like (here with 'test' search text):
` -c log.showSignature=false log -z master --pretty=format:"%H%T%P%n%at%n%ct%n%e%n%aN%n%aE%n%cN%n%cE%n%s%n%n%b1DEA7CC4-FB39-450A-8DDF-762FCEA28B05" --max-count=100000 --regexp-ignore-case --grep="test"  --`

With this command, run it from command line to see if it retrieves the 2 commits you're talking about....

**Comment by r0polach** [comment]
Thanks. I tried it.
When I search text without accents, I get a command like

`git	-c log.showSignature=false log -z --pretty=format:"%H%T%P%n%at%n%ct%n%e%n%aN%n%aE%n%cN%n%cE%n%s%n%n%b1DEA7CC4-FB39-450A-8DDF-762FCEA28B05" --all --boundary --not --glob=notes --not --max-count=100000 --regexp-ignore-case --grep=" na 75kPa"  --	X:\ProdRT\Source\`

but if I use some accents, the grep clause is completely missing from the command: 

`git	-c log.showSignature=false log -z --pretty=format:"%H%T%P%n%at%n%ct%n%e%n%aN%n%aE%n%cN%n%cE%n%s%n%n%b1DEA7CC4-FB39-450A-8DDF-762FCEA28B05" --all --boundary --not --glob=notes --not --max-count=100000 --regexp-ignore-case  --	X:\ProdRT\Source\`

There is no searched text in the command at all. Weird, because the results are commits that DO contain that text (in GitExtensions GUI, not in command line, of course).

Also, following commands `git branch`, `git tag`, `git describe` have different order. - I don't know if it is significant.

**Comment by pmiossec** [comment]
I think you hit the behavior described in this commit: https://github.com/gitextensions/gitextensions/commit/5e1352bbc306189af23165ecd0bdc3d6dc124aba

where the `--grep` option of `git log` is used when searching using ASCII strings
**but when the text to find contains non ASCII characters, the filtering is done by GitExtensions**.
And it seems to not behave the same...

This behavior has been removed by @RussKie in this PR #9580 (See especially this comment: https://github.com/gitextensions/gitextensions/pull/9580#issuecomment-922450346 ) and that will be released in next version (cc/ @gerhardol )

I highly recommend you to test the last development version (that you could find [here](https://github.com/gitextensions/gitextensions#downloads) to see if the behavior is better know or if it is worse.

If you still think it doesn't behave like expected, I think that it should not be too difficult for you to create a repro case with some dummy commits with commit messages containing these non ASCII characters so that we can debug it.

**Comment by r0polach** [comment]
The issue seems to be fixed in 4.0.0.
Thank you.

**Comment by RussKie** [comment]
Thank you for the confirmation.
