### ISSUE TITLE
Plugin menu in Dashboard

### ISSUE THREAD

**Issue by 011V32** [gitextensions/gitextensions#9642]
## Feature description

It would be great, to bring back the Plugins menu entry in dashboard.
I could not find out, why it was removed, but in #3693 the difference is shown.
If not available I had to create a branch before installing a plugin.
(I want to configure gerrit plugin for other users before creating a branch.)

## Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.33.0.windows.2
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 144dpi (150% scaling)

**Comment by 011V32** [comment]
Sorry, wrong wording. I want to configure the gerrit plugin before creating a repository.

**Comment by RussKie** [comment]
As I said earlier, plugins only work in a context of a git repo. The dashboard doesn't have that context, and hence the plugins aren't available.

**Comment by RussKie** [comment]
If you have further Gerrit related questions, please direct those to https://github.com/gitextensions/GitExtensions.GerritPlugin/.

**Comment by mstv** [comment]
Do we really need a repo context in order to open the plugin manager?

**Comment by RussKie** [comment]
No, the PLugin Manager shouldn't require the context, but the whole
implementation is currently structured that way.

Thinking out loud (as I don't remember all details) - to improve this, the
plugin definitions will need to be enhanced so that each plugin declares
whether it requires an active git repo context or not. Then the plugins
infra would interrogate the plugins for that declaration or display only
those that match the current context.

**Comment by mstv** [comment]
Thank you for the clarification.
