### ISSUE TITLE
Periodic Background Fetch is not doing anything at all

### ISSUE THREAD

**Issue by niikoo** [gitextensions/gitextensions#9643]
### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.33.0.windows.2
- Microsoft Windows NT 10.0.22000.0
- .NET Framework 4.8.4400.0
- DPI 96dpi (no scaling)

### Issue description

![Configuration](https://user-images.githubusercontent.com/16848460/136786559-a76dab9c-a17d-4bc0-b1dc-e71a1b502dbf.png)

![git call stack](https://user-images.githubusercontent.com/16848460/136786467-3dfb0338-ed08-468d-8385-36784e868bcd.png)

![Manual git fetch all works](https://user-images.githubusercontent.com/16848460/136786886-e79bc792-dafb-4151-b3b3-aa5c562c5364.png)

Note: I have minimum two GitExtensions windows open at any given time. 

[Similar issue !5971](https://github.com/gitextensions/gitextensions/issues/5971)

### Steps to reproduce

Enable periodic background fetch and wait the amount of seconds defined as interval. 

### Did this work in previous version of GitExtensions?

Yes, a few versions back. I don't remember exactly which one.

**Comment by RussKie** [comment]
Please follow [build instructions](https://github.com/gitextensions/gitextensions/wiki/How-To%3A-build-instructions#current-dev-branch) to get started. 
I believe you'd want to put breakpoints in this method:
https://github.com/gitextensions/gitextensions/blob/f70fd419fd39a67290229f11e76df5100d72646a/Plugins/BackgroundFetch/BackgroundFetchPlugin.cs#L65-L149

Holler if you get stuck or find something interesting.

**Comment by epikgit** [comment]
Hi guys.
Same problem here.
In my case I noticed the bug seems to stop after a while: when Git Extension starts the refresh works, after a while it doesn't work anymore. 
Can it be a problem with long work running sessions? 
My GE remains active for several days with no reboot and, in my case, system reboot/GE restart can't be the solution.

Thank you.

**Comment by RussKie** [comment]
To be honest I'm having difficulties understanding how restarting the app
may be unacceptable - it hardly contains any state that reversibility lost
upon restart. But this is beside the point.

Since this issue is affecting very few selected users, and you're one of
those unlucky ones, we'll look up to you to debug and propose a fix.

I use the plugin day in-day out on several workstations and haven't had any
issues...

**Comment by epikgit** [comment]
I told that system reboot/GE restart can't be a solution because the plugin can stop after a day or after an hour. I can't restart GE every time i want to check it because I don't know if the plugin is still active or not. It's easier to disable it completely and press the fetch button manually.

Do I have to debug GE? Executing the source? 
Isn't it more effective to introduce a strong log in the plugin code to understand what is happening in the lucky users PC? It seems a bit strange to ask a user to debug a program, doesn't it?

**Comment by pmiossec** [comment]
>  It seems a bit strange to ask a user to debug a program, doesn't it?

As it is an open source project that we all do on our free time (and so we should manage our own priorities how to fill our scarce available time), no... 

If you want to see it fixed (quickly), you should contribute...

**Comment by epikgit** [comment]
I analyzed the log for a while and now I have a more precise description for this bug.

The plugin launches the command "git fetch --all" regularly so my previous assertion wasn't true.

What is not working very well is the flag "Refresh view after fetch". 
If you don't open the log and don't force the refresh from the UI with F5 key, the only way to have a feedback that something changed in your source is exactly this option. I can't understand why but the automatic view refresh seems not to be in sync with the command fetch --all. 
What I expect is that every time the command is launched the view is refreshed or at least every time the command is launched and finds something changed, the view is refreshed.
This is not what happened. It seems that the view refreshes randomly or at least, as I told before, out of sync with the command.

I hope these new details can be helpful.

**Comment by mstv** [comment]
If there is running any `git.exe` (regardless for which repo), the plugin postpones the fetch for 5 seconds.
Though since `git fetch -all` appears in the Git Command Log, this is not blocking the updates.

> Is there a way to see somewhere if the Refresh command is actually executed by GE or not?

The same commands should appear in the Git Command Log as triggered by `F5`.

I could reproduce skipped updates with the large Linux repo.
Update requests are ignored while `RevisionGridControl.CanRefresh` is `false`, i.e. while the revisions are being loaded due to a previous update.
Then it just calls `Trace.WriteLine("Ignoring refresh as RefreshRevisions() is already running.");`

The fetch interval should be >= 1.5 * `execution time of the command "git -c log.showSignature=false log -z --pretty=format:..."`.

**Comment by RemiGaudin** [comment]
@mstv In my case, I can see the refresh command when I manually press F5 myself, but I never see any trace of this while the fetch command is run by the Periodic Background Fetch plugin. For exemple in the following logs you can see that:
- At 11:05:39.164: The Periodic Background Fetch is run without error but no Refresh seems to be run just after.
- At 11:06:21.430: I pressed F5 which successfully display the pending changes in my repo.
- At 11:06:39.185: A new Periodic Background Fetch is run again (because it is setup every 60s) but still no refresh afterward.

![image](https://user-images.githubusercontent.com/4699149/221537288-9393b00a-153a-4858-b426-4d2ac95d52eb.png)

Of course I have checked the "Refresh view after fetch" option.

![image](https://user-images.githubusercontent.com/4699149/221537340-0de465f1-e890-4c93-abe2-1deeabd24d48.png)

**Comment by mstv** [comment]
If nothing has been fetched because everything was up to date, no refresh is triggered.
There is a simple check whether the git output contains `"From"`.

Does the output contain "From" when you run
`git fetch --all --prune`
manually on the command line if there was something to fetch?

---

Is there a conflict in your settings or a display issue in the Settings dialog?
The screenshot shows just "fetch --all". Where does "--prune" come from?

**Comment by pmiossec** [comment]
> There is a simple check whether the git output contains `"From"`

I think git could be used in other languages than English. Do we set env Var to ensure the output is in English? Could it be the problem?

**Comment by RemiGaudin** [comment]
@mstv Yes if I run manually a fetch command using the command line I do have the "From" word in the output:

![image](https://user-images.githubusercontent.com/4699149/221803112-0111c924-ccd9-48bb-bb5c-9f6a72647972.png)

So about @pmiossec comment: yes maybe this check could not work when using another language than English, but it doesn't seem to be what's causing my issue here.

I looked at my GE logs again and I did spot a fetch command that I'm absolutely 100% sure it had actually fetch some new contents (because I pressed F5 around 45s after, and I saw the new content on my GE UI):

![image](https://user-images.githubusercontent.com/4699149/221804703-8d7ad13a-8157-4c27-9902-13226480f376.png)

Is it normal that we don't see the output (with the "From" word) inside GE logs? Or does it means my issue is here because GE doesn't receive the output for whatever reason?

**Comment by RemiGaudin** [comment]
> Is there a conflict in your settings or a display issue in the Settings dialog?
The screenshot shows just "fetch --all". Where does "--prune" come from?

Sorry, my logs and settings screenshot were coming from two different repos, that's why you see one using the "--prune" option and not the other. But I'm sure I don't have any settings conflict for any of my repos (all of them have the refresh option checked) and I have this "refresh not triggered" issue on all of my repos without exception.

By the way, if it may help, I'm French and using a French computer but always using English language setup (and indeed my git fetch command does output in English). And also some of my co-worker are experiencing the exact same issue, so it doesn't seem to be specific to my computer.

**Comment by vbjay** [comment]
Since you are seeing the problem, push to a repo and then run the command at a different clone. Post the output showing it updating. That way we can confirm.

**Comment by RemiGaudin** [comment]
@vbjay That's exactly what I did in this log screenshot I posted above:

![image](https://user-images.githubusercontent.com/4699149/222090126-5b077169-2b26-476d-b12d-f6e162a3c8d0.png)

I pushed some new contents from another computer, then at 09:53:.01.987 my GE did a `git fetch --all --prune` which I am absolutely sure it got the new contents because I pressed F5 around 45s later and saw the new content on my UI.

As you can see, between the fetch and my F5, GE did not trigger any refresh, we only see two commands `git status` triggered at 09:53:03.213 and 09:53:33.441.

**Comment by RemiGaudin** [comment]
@mstv I just realized something very interesting: Actually my GE is probably retrieving correctly the git output with the `From` word because after the `git fetch` I can see my refresh button turning red:

![image](https://user-images.githubusercontent.com/4699149/222092470-5614a1f8-ddab-4b66-8fcf-219cfdf2c12f.png)

So to me what does it means is the following:
- My Periodic Background Fetch is successfully running the `git fetch` command every 60s.
- My GE is successfully retrieving the git output with the `From` word because it's turning my refresh button in red just after.
- But it just doesn't trigger the Refresh action straight after for some reason, so I have to do it myself, despite the fact that the option is correctly checked on all of my repos settings.

![image](https://user-images.githubusercontent.com/4699149/222093729-92e6a69d-c124-469c-ae34-5401967c2280.png)

So to summarize: the issue seems really just that my GE doesn't take into account the refresh option for whatever reason, everything else is working fine (i.e. the fetch command and the new content detection). And as I said previously, this issue is occurring on all of my repos, also on my co-worker computers, and even on my own home computer (some computers are Windows 10, some other are Windows 11) and every of them have the very latest GE version: 

Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.13
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by mstv** [comment]
![image](https://user-images.githubusercontent.com/4699149/222092470-5614a1f8-ddab-4b66-8fcf-219cfdf2c12f.png) just means that the independent git status monitor has detected a change.

> My GE is successfully retrieving the git output with the From word because it's turning my refresh button in red just after.

This conclusion goes to far. It just means that the git has successfully fetched.

> But it just doesn't trigger the Refresh action straight after for some reason, so I have to do it myself, despite the fact that the option is correctly checked on all of my repos settings.

We might need to log the git output which is not done because it can be huge for some commands.

Could build an instrumented version of the plugin?
Just add

```
                                      MessageBox.Show(msg);
```
right before
```
                                      if (_autoRefresh.ValueOrDefault(Settings))
```
at line 137 of `Plugins\BackgroundFetch\BackgroundFetchPlugin.cs`.

**Comment by RemiGaudin** [comment]
@mstv Ok I just did what you asked, i.e.
- Adding `MessageBox.Show(msg);` right before `if (_autoRefresh.ValueOrDefault(Settings))` at line 137 of `BackgroundFetchPlugin.cs`.
- Start my modified GE on my sandbox repo.
- Modify the content of my sandbox repo using another GE from another computer.
- Wait for my modified Periodic Background Fetch to fetch for the new content and so to trigger the popup.

And the result I got is a blank popup:

![image](https://user-images.githubusercontent.com/4699149/223366071-adf14591-31f3-4ac7-ac99-29c5327e7f92.png)

You can notice that the refresh button did turn in red which confirms that the fetch command successfully retrieved the new content.

So looking at the code, it means to me that `msg` is empty so `_currentGitUiCommands.GitModule.GitExecutable.GetOutput(args);` is returning an empty string. So indeed it explains that the `_currentGitUiCommands.RepoChangedNotifier.Notify();` event was not raised and my GE did not automatically refresh.

So it doesn't seem a language issue (despite the fact that I'm on a French computer), but this is because GE doesn't retrieve the Git command output at all?

I am not familiar at all with the GE source code (first time I fork the repo), so what can I do to investigate the issue further?

**Comment by RemiGaudin** [comment]
@mstv I just debugged my modified GE a little bit further, down to the function `GitCommands.ExecutableExtensions.GetOutputAsync()`, and here is what I saw:

![image](https://user-images.githubusercontent.com/4699149/223372501-ef3a3d25-eb4f-40b6-b5f8-1a2453103df8.png)

So the `git fetch --all` command was successfully run but for whatever reason the output byte array remains empty...

**Comment by vbjay** [comment]
Do same experiment but use cli to run `git fetch --all` and `git --version` but redirect to two files like this 

`git fetch --all 2> error.txt > std.txt `

Post both files to this thread.

**Comment by RemiGaudin** [comment]
@vbjay Here you go:

[std.txt](https://github.com/gitextensions/gitextensions/files/10909433/std.txt)
[error.txt](https://github.com/gitextensions/gitextensions/files/10909434/error.txt)

There's no output written for `git fetch --all` in `std.txt` but there's indeed something in `error.txt` (doesn't look very helpful though).

So I guess this confirms this is a Git issue and not a GE one.

**Comment by vbjay** [comment]
That error text is exactly the output it is looking for. 

So the plugin needs to use the error output. Best bet is to just combine both error and output together. Instead of using getoutput we have other ways to get output with error. If you want to do a pull request fixing it .. go for it.

**Comment by vbjay** [comment]
That's because git writes it to that stream. It's not an error. It's a standard behaviour to output more detailed info to error stream. What happened is @mstv  and others altered output retrieval without verifying side effects of doing so and we keep finding oh that's actually in error stream.

**Comment by vbjay** [comment]
Don't change that. Look how we get both streams in other areas.

**Comment by RemiGaudin** [comment]
@vbjay The fix I just did is pretty simple and is working well under my testing:

![image](https://user-images.githubusercontent.com/4699149/223448397-6c9da289-70f0-49b0-8604-e5cac7161684.png)

Do you think there's another way better than that to fix it?

**Comment by vbjay** [comment]
Do not change that. They exclude error output on purpose with git output. 

Look at other methods in https://github.com/gitextensions/gitextensions/blob/master/GitCommands/Git/ExecutableExtensions.cs

Understand what to use when.

**Comment by vbjay** [comment]
https://github.com/gitextensions/gitextensions/pull/9562

Side effect from

**Comment by mstv** [comment]
I guess there seems to be a git configuration which makes git redirecting the fetch details to StandardError - but only for some users.

**Comment by mstv** [comment]
You can use `ExecutableExtensions.Execute(...).AllOutput`.

**Comment by RemiGaudin** [comment]
@mstv Great, thanks for the tip! I confirm that doing the following change in `BackgroundFetchPlugin.cs` is fixing the issue:

![image](https://user-images.githubusercontent.com/4699149/223667917-394d7197-2e48-416a-b4ff-286eb8b95714.png)

I'm going to do a pull request with this fix. Thanks everyone.

**Comment by gerhardol** [comment]
https://github.com/git/git/blob/b2f55717c7f9b335b7ac2e3358b0498116b94a5d/Documentation/git.txt#L712-L723
Is GIT_REDIRECT_STDOUT set?

**Comment by vbjay** [comment]
https://github.com/git/git/commit/96890f4c428ed62cf52c11aba5773d364a8d6234#diff-a8ad3d92e86b1622eb617b0a241f2622911f8e868e3816aebb998a0f3e3bcf95R479

They have been writing to err for a long time.  Nothing new.

**Comment by vbjay** [comment]
https://lore.kernel.org/git/CAH74SFS3hFzYzJ6eb2YenJh4-Pf_VBzVTo8axnEtHDyaJUB-jw@mail.gmail.com/

**Comment by vbjay** [comment]
Cause of the problem is the change that made error stream empty array without validating every output of every command was actually in std stream.

**Comment by RussKie** [comment]
Thank you @vbjay for taking the lead on this.

**Comment by gerhardol** [comment]
> In my case, GIT_REDIRECT_STDOUT doesn't seem to be set:

GIT_REDIRECT_STDOUT is an environment variable

@vbjay In this case the question was why this seem to be different in some setups.
There is for sure some data in stderr for for some commands and some in stdout that need to be handled.
Reading the combined output should be avoided, then you need to handle all situations.
Could be OK here.

**Comment by RemiGaudin** [comment]
> GIT_REDIRECT_STDOUT is an environment variable

I have no such environment variable as well.
All my computers having the issues all have a basic installation of Git for Windows, with the default setup suggested on the installation wizard, and no additional config tinkering afterward. Pretty standard installations, really!

**Comment by vbjay** [comment]
Yes the environment does have an effect, but I doubt that is playing a big part. I think the majority is that before the change we combined both output streams an we got the from or whatever. Then the error stream was zeroed out without understanding where git writes the output.

**Comment by gerhardol** [comment]
After reading this again: This is not a random change, the output has always been in stderr. 
The change was in #9488, where the use of stdout vs stderr was cleaned up.

**Comment by vbjay** [comment]
Correct. That is what I've been saying.
