### ISSUE TITLE
Hotkeys for navigate forward & backward don't work

### ISSUE THREAD

**Issue by crypto-rsa** [gitextensions/gitextensions#9845]
### Environment

- Git Extensions 33.33.33
- Build 995c9875e90f39d460ddfa899049c868bff73fcf
- Git 2.35.0.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 5.0.13
- DPI 96dpi (no scaling)

### Issue description

Hotkeys for navigating forward & backward (Alt + →, Alt + ←) no longer work when the revision grid is focused. Running the commands from the Navigate menu works, though.

### Steps to reproduce

- Select a few commits one by one in the revision grid using a mouse
- press Alt + left arrow to go back to the previous commit
- nothing happens

### Did this work in previous version of GitExtensions?

Yes, until now I have been using GE build 752a272f605ea26c1673bed224298f25efc12ae3 where I _think_ it worked correctly.

**Comment by gerhardol** [comment]
Maybe #9827 @mstv?

**Comment by mstv** [comment]
Yes, `Alt+←` & Alt+→` are consumed by the FileViewer now before these keys would reach the hardcoded handling in `RevisionGridControl.OnGridViewKeyDown`.
I will create regarding Hotkeys.

**Comment by gerhardol** [comment]
> I will create regarding Hotkeys.

Great.
Are you aware of any other keys that are  hardcoded and should have hotkeys?
`F5` is hardcoded in a few situations I believe.

**Comment by mstv** [comment]
I was already checking. The other hard-coded keys are "standard keys" like `F5`, `F2`, `Del`, `Enter`, `Esc`, `Ctrl+C`, `Ctrl+V` and few more.
With one exception: `FormCommit.OnKeyUp`. But this handler catches the keys before the Hotkeys. I will not change this one because multiple keys can be used for the same functionality there, which is not possible with the Hotkeys.
