### ISSUE TITLE
Amend Commit checkbox better leave checked and disabled (if been checked) while at the push execution

### ISSUE THREAD

**Issue by andry81** [gitextensions/gitextensions#9914]
### Feature description

Currently if press `Amend Commit` and press Push button (Commit dialog), the checkbox goes left unchecked after the  commit but before the push. Sometimes you thinks that you forget to check it and do interrupt the push. Better to leave it in checked state (may be disabled) along the whole operation.

### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.33.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.8.3761.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
>  Sometimes you thinks that you forget to check it and do interrupt the push. Better to leave it in checked state (may be disabled) along the whole operation.

I understand your point of view because it happens sometimes to me but I don't think that what you are proposing is a good solution.
The `Amend commit` checkbox makes sense only when you commit.
And it will raise the more difficult to solve question to when uncheck it:
When you push? But not everyone just push after an amend and it will increase the risk to amend also the next commit.
When you close the window? But there is an option to not close or not the window after each commit and when no more data to commit and in this case, the checkbox state is saved.

So I think that will introduce a lot of edge cases.

And there is the also the color of the "Commit & push" button that is a good reminder that your push will be done with the `--force-with-lease` flag.

![image](https://user-images.githubusercontent.com/460196/159936752-e1fbd2c3-fad4-40f3-be76-000a55b4a76b.png)

I don't know if a label "A commit has been amended" displayed until the commit form has been closed could be a better option....

**Comment by pmiossec** [comment]
> I don't see any coloring and option to set `--force-with-lease` before the button click.

It was an option and I didn't found it when writing my previous message.
![image](https://user-images.githubusercontent.com/460196/159953998-96a3ada4-9fbb-40be-816e-6c085a01ff8a.png)


> Better to use the wording Amend in the Push dialog before the push instead after the commit to avoid continue with the push in case of not amended or amended.

This request makes no sense in git terms because an amended commit is not different than other commits.
So you are requesting GitExtensions to keep a state of all the amended commits (to be able to display it in the push dialog) and set up a complex logic to handle this state (just as a reminder that maybe you did a mistake).

I don't think it will happened one day....

**Comment by andry81** [comment]
> This request makes no sense in git terms because an amended commit is not different than other commits.

It has sense if i press commit+push as a single action.
