### ISSUE TITLE
Refresh does not re-select the commit

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#9935]
### Environment

- Git Extensions 33.33.33
- Build bcd0c2617bdd4c842c9a707888f951af07c65ecd
- Git 2.35.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.3
- DPI 96dpi (no scaling)

### Issue description

Refresh does not re-select the commit

### Steps to reproduce

select an older commit, e.g. the initial one
hit `F5`
--> an arbitrary commit somewhere in the middle is selected but not scrolled to

### Did this work in previous version of GitExtensions?

3.5.4

**Comment by gerhardol** [comment]
For me it selects for instance the initial revision, but you have to scroll slighly manually to get GE to autoscroll.
The revision is in the revisionGraph but not yet in the gridView when revisions are loaded, so there has to be some further waiting.

**Comment by RussKie** [comment]
This is probably the biggest annoyance in the vNext for me atm...

**Comment by gerhardol** [comment]
> This is probably the biggest annoyance in the vNext for me atm...

Occurs for quite old commits only what I see, the gridView is normally loaded with the recent commits when grid has loaded.
This should not be much different from before I believe, grid is loading in a similar way.

**Comment by RussKie** [comment]
For me happening every time I rebase.

**Comment by gerhardol** [comment]
> For me happening every time I rebase.

That is a slightly different case than just a refresh.
The selected commit is cleared if HEAD changes, when switching repo or rebasing.
https://github.com/gitextensions/gitextensions/blob/master/GitUI/UserControls/RevisionGrid/RevisionGridControl.cs#L966
The 'repair' should select HEAD

**Comment by gerhardol** [comment]
A partial fix that always select something in a private branch.
What is needed is to force loading required Rows when all revisions are loaded.

**Comment by gerhardol** [comment]
Pushed an update that seem to work. (Removed more code than I added.)
However, if no HEAD is available and artificial commits are inserted, selection shifts. This is not a new problem though, but will look if that can be handled here.

**Comment by gerhardol** [comment]
I am preparing a PR for this
https://github.com/gerhardol/gitextensions/pull/new/feature/i9935-gridload-handling

The main change is to check if the grid rows that are expected are loaded when the revisions are loaded as that is running separately.
This should also improve the test failures, the checks were often done before the grid was loaded why the results were so flaky.
Some adjustments still to do it seems.

This should also fix the issue with selection changing after a reset. The check was done when revisions were loaded and since to selections were (possibly) done, the selections were changed.
Another issue occurred if all previous selections could not be reselected (for instance due to filtering), now at least the found revisions are shown.

**Comment by gerhardol** [comment]
@mstv can this be closed?
